- packages/xdl/CHANGELOG.md
- packages/xdl/package.json
- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/IosIPABuilder.js
- packages/xdl/src/detach/IosPodsTools.js
- packages/xdl/src/detach/IosShellApp.js
- packages/xdl/src/detach/IosWorkspace.js
- packages/xdl/src/detach/StandaloneContext.js
- packages/xdl/src/modules/Modules.js
- packages/xdl/src/modules/config.js
Fixes https://github.com/expo/universe/issues/3059 . The current latest version of `xdl` generates bad Podfiles on new detached projects because it includes unimodules that are not dependencies of `expo@29.0.0`.
Added a new `sdkVersions` field to module configs that is a semver range; when generating a Podfile, filter out the modules for which the `sdkVersion` of the project does not satisfy this range.
I filled out the `sdkVersions` of the current modules based on my knowledge, but @tsapeta or someone else should definitely double check them 😅 
Generated a new SDK 29 project, detached it, and successfully ran `pod install` 🎉
> [xdl] add sdkVersions to unimodules config

- packages/xdl/src/Credentials.js
credentialsExistForPlatformAsync always used to return true because `!!` was performed on the Promise itself
> [xdl] fix bug where credentialsExist always returns true

- packages/xdl/src/modules/config.js
- alphabetically sorted native modules (sorry @sjchmiela 🤷‍♂️)
- added missing modules: `expo-contacts`, `expo-ads-admob`, `expo-local-authentication`
> [xdl] update modules config

- packages/exp/src/commands/build.js
- packages/exp/src/commands/build/AndroidBuilder.js
- packages/exp/src/commands/build/BaseBuilder.js
- packages/exp/src/commands/build/IOSBuilder.js
- packages/exp/src/commands/unreleased/export.js
- packages/exp/src/commands/url.js
- packages/xdl/src/Exp.js
- packages/xdl/src/Project.js
- packages/xdl/src/ThirdParty.js
- packages/xdl/src/UrlUtils.js
- packages/xdl/src/xdl.js
We want a user to be able to host their own manifest, bundles, etc on their own servers. We also want them to be able to build a standalone binary with this url embedded in it. Instead of embedding the manifest and OTA updating from expo servers, we give the user the option to use their own server endpoints instead.
If a client submits a build request with a `publicUrl` parameter, we embed the manifest from `publicUrl` and pass in `publicUrl` to the shell app builders.
> [xdl] plumb publicUrl via build command to turtles

- packages/xdl/src/detach/AndroidIcons.js
- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/IosIcons.js
- packages/xdl/src/tools/ImageUtils.js
- packages/xdl/src/xdl.js
re-opening of https://github.com/expo/universe/pull/2868. This was not merged previously because it relies on `sips` when detached and therefore would fail when used on Windows or Linux. A solution was proposed to use `sharp` instead and install binary packages as optional dependencies of `xdl` (similar to ngrok), but I did not have time to get that working last cycle.
I think this is worth merging as it is now for turtle. (Turtle always uses `sharp` instead of `sips` anyway.) It's less important to resize icons for detached projects, as developers can easily modify the icons themselves before they make their build. However, there is no way for people to provide properly downsized icons for turtle builds, which means app icons can look ugly and pixelated in production.
This code is almost …
> [xdl] resize Android launcher and notification icons during build

- packages/xdl/src/Api.js
Currently, all XDL and powertools scripts that modify the versions endpoint are broken. Since all of these scripts (but one) read and modify the staging endpoint, but `Api` includes the prod session id with the request, the endpoint returns a 401.
Worse, because the `_versionCache` does not differentiate between staging and prod versions, this error is swallowed and a cached copy of versions is returned (likely from prod). This causes any previous changes on the staging endpoint to be overwritten. We ran into this multiple times while doing the SDK 30 release and had to resort to manually overwriting the entire endpoint whenever we wanted to make any change 😱
This PR explicitly sets the `Expo-Session` header to empty on Versions requests to avoid this problem. No auth is needed to read …
> [xdl] fix versions endpoint scripts

- packages/xdl/package.json
- packages/xdl/src/detach/installPackageAsync.js
- yarn.lock
If you run `expo init` and then eject to ExpoKit immediately, the current script installs the `expokit` npm package using npm by default (since `yarn.lock` doesn't exist). However, `npm` does something funky here and totally erases the `node_modules/react-native` folder (aside from its own `node_modules`). This makes both `expo start` and, in the ios directory, `pod install` fail. While this is fixable by simply reinstalling node_modules, the fix may not be obvious from the error message, and this extra step should not be necessary.
Using `yarn` as the default fixes this at least for people who have `yarn` installed.
I'm not tied to this PR, just wanted to suggest this in case it's worth it!
> [xdl] default to yarn when installing new packages, if it exists

- packages/xdl/src/detach/IosPodsTools.js
This makes two changes to the Podfile generator:
- The ENABLE_PACKAGER_CONNECTION flag on iOS is set to 0. We seem not to use it and to causes lots of log spam. Live reloads work without it.
- Sets the iOS target to 10+ since we are dropping 9.
We'll need a new version of XDL on npm so that the Expo repo can depend on this new code.
Tested by applying these changes to the Podfile directly and building the client.
> [ios] Generate Podfile with ENABLE_PACKAGER_CONNECTION=0 + target iOS 10+

- packages/xdl/caches/schema-30.0.0.json
If you try and use android intent filter with `autoVerify` you get the following error:
```
[11:08:04] Error: Problems validating fields in app.json. See https://docs.expo.io/versions/v30.0.0/guides/configuration.html.
[11:08:04]  • Field: android.intentFilters[0] - should NOT have additional property 'autoVerify'.
[11:08:04] Couldn't publish because errors were found. (See logs above.) Please fix the errors and try again.
```
The logic is all there in the code, it's just blocking you with the schema validation.
> Add missing android intentsFilters.autoVerify

- packages/xdl/src/detach/IosWorkspace.js
expo/expo#2380 moved all universal modules to `/packages`, but expo/expo#2425 is blocked until the conflict is resolved some way.
Are these paths safe to change?  Or is there a better approach?
> [xdl] '/modules' -> '/packages' in detached workspaces

- packages/xdl/src/detach/IosPodsTools.js
The "inspector" refers to the Nuclide inspector that RN tries to connect to on port 8082. This doesn't work with Expo CLI and causes errors when we load a published copy of dev Home from CloudFront and RN tries to connect to `<cloudfront>:8082/<inspector URL>`. This makes the Podfile configure the build so the inspector is disabled and we don't make network requests to unsupported endpoints that will fail.
> [podfile] Add RCT_ENABLE_INSPECTOR=0 to the generated Podfile

- packages/xdl/package.json
- packages/xdl/src/detach/AndroidShellApp.js
Missing block for https://github.com/expo/expo/pull/2330.
Removes obsolete SDK-specific code from `android-shell-app` upon its creation.
> Strip unneeded SDKs code from Android shell app

- packages/xdl/src/detach/AndroidShellApp.js
So far, we were running `generate-dynamic-macros-android.sh` twice. The first time when creating a Docker image for Android builders and the second time when building a user's standalone app. I verified that when we don't run it the second time, the standalone app works just fine.
> [xdl] remove generating dynamic macros for every build

- packages/xdl/src/detach/IosShellApp.js
As documented in [xcpretty's usage instructions](https://github.com/supermarin/xcpretty/tree/456604313faf4a1de6a4e687c2412eaf6097c4b0#usage), it doesn't exit with the same status code as the xcodebuild command.
This unblocks expo/expo#2425.
> [xdl] iOS shell app builds propagate xcodebuild errors

- packages/xdl/src/Project.js
This makes `expo start --offline` load a project properly while logged in. Currently it fails by throwing an error from here: https://github.com/expo/expo-cli/blob/1af1912114111072d93043f567671750c806ef55/packages/xdl/src/Exp.js#L261. This PR avoids this function call by treating signing the manifest the same way as if we were logged out.
I additionally had to treat `manifest.id` in the same way as initially the manifest was being generated without an id at all (which caused the clients to crash). This has some side effects, like the project being scoped as a different experience than when properly signed in and online.
I am not sure if this is the right way to fix offline mode -- there may be a better way to do this with fewer side effects, but wanted to open this PR as a first …
> [xdl] fix offline mode while logged in

- packages/xdl/src/detach/IosWorkspace.js
In order to fix apps hanging on the splash screen, we have to set `sdkVersions` and `detachedNativeVersions` properly in the `EXSDKVersions` file.
@sjchmiela knows more details and he says it shouldn't break anything.
I've published a canary version of `xdl` with these changes, built a shell app with `tools-public` having that canary release of`xdl` installed, deployed Turtle with the new shell app for SDK31 and built test app and verified it doesn't hang on the splash screen :tada:
> [xdl] fix unversioned shell apps

- packages/expo-cli/package.json
- packages/expo-cli/scripts/preversion.js
- yarn.lock
The `master` branch should be releasable at any time. It should be as straightforward as possible for Expo CLI maintainers to publish a new release. At the same time, we should make sure that when releasing new versions, we don't break the developer experience of Expo CLI users.
Offline development, logged-out development and ejecting has previously had many regressions, so these manual tests target those features specifically. To make releasing as smooth as possible, most of these manual tests should be automated in the future.
Added a `preversion` script to the `expo-cli` package, which Lerna will run before bumping the package version when we run `lerna publish`. The script shows instructions for manual tests to perform before publishing.
Run `lerna publish`. Answering "no" to the …
> [expo-cli] Add a few manual pre-release checks

- packages/xdl/src/modules/config.js
`Expo.Google` native features are spotty or inconsistent. This native module will replace the native parts of `Expo.Google` for legacy. `Expo.GoogleSignIn` only works in standalone.
[x-post](https://github.com/expo/expo/pull/2543)
> [Unimodule] `expo-google-sign-in`

- packages/expo-cli/src/commands/webhooks.js
`url.URL` doesn't exist in `node@6.9.1` and we have 
```
"engines": {
"node": ">=6.9.1"
},
```
in `package.json`.
@sjchmiela I tested it locally :P
> [expo-cli] use validator.isURL instead of url.URL

- packages/xdl/src/detach/IosNSBundle.js
Turtle apps from staging don't have `API_SERVER_ENDPOINT` set properly. I'm not 100% sure that something else isn't broken, but these changes should fix the problem.
> [xdl] set API_SERVER_ENDPOINT in EXBuildConstants properly

- packages/xdl/src/Project.js
- packages/xdl/src/UrlUtils.js
- packages/xdl/src/User.js
`util.promisify` doesn't work with `joi.validate` (with `joi@14.3.0`). There isn't any real benefit of making this "asynchronous", so I changed it to plain synchronous function calls.
> [xdl] don't use util.promisify for joi.validate

- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/Detach.js
`kernel.android.bundle` isn't used in standalone apps yet we include it in every ejected or standalone apps. x-ref: https://github.com/expo/expo/pull/2850
Pass `sdkVersion` around and remove the offending file from shell app if `sdkVersion > 32`.
I'll deploy staging Turtle with this XDL and see if an app built against this XDL works ok.
> Remove kernel.android.bundle in standalone apps in SDK32+

- packages/xdl/src/detach/AndroidShellApp.js
- fix path for APK copying according to https://github.com/expo/expo-cli/blob/eefd08b1b7269ba2608c7bca3ca41e7f2997fb7a/packages/xdl/src/detach/AndroidShellApp.js#L1019-L1021 for SDKs < 32
- add missing `jarsigner` step for SDKs < 32 https://github.com/expo/expo-cli/blob/eefd08b1b7269ba2608c7bca3ca41e7f2997fb7a/packages/xdl/src/detach/AndroidShellApp.js#L1025-L1046
> Fix XDL shell.apk paths, sign the APK properly on SDKs < 32

- packages/expo-cli/src/commands/fetch.js
In order to use universal links on Android the SHA-256 hash is needed (see https://docs.branch.io/pages/deep-linking/android-app-links/).
> feat: output SHA-256 hash for universal links

- packages/expo-cli/src/commands/build/auth.js
- packages/traveling-fastlane/Gemfile
- packages/traveling-fastlane/Gemfile.lock
- packages/traveling-fastlane/actions/validate_apple_credentials.rb
Fixes https://forums.expo.io/t/cant-build-ios/16684
TLDR: when a user has 2FA enabled, we should use the session produced by fastlane to make further requests to Apple servers.
> [expo-cli][traveling-fastlane] ask for 2fa code only once

- packages/xdl/src/modules/config.js
Will fix https://forums.expo.io/t/rejected-from-app-store-for-stripe-payments-integration-but-i-dont-use-stripe/16837, https://forums.expo.io/t/apple-app-transfer-rejected-passbook-integration-api/16908.
> [xdl] Remove expo-payments-stripe from default universal modules

- packages/xdl/src/detach/IosWorkspace.js
- packages/xdl/src/modules/Modules.js
- packages/xdl/src/modules/config.js
Related PR: https://github.com/expo/expo/pull/2338
It also fixes some problems on expo/expo CI with the shell app, as it was not including modules that were not released yet (like these one that has `sdkVersion: '>=32.0.0'`), however we need to include them to properly test new modules with unversioned shell apps.
> Add modules for background tasks

- packages/xdl/src/detach/AndroidShellApp.js
Added `android.permission.WRITE_CONTACTS` permission to the blacklist, so it can be removed by the user.
See also https://github.com/expo/expo/pull/3017
> [xdl] add android.permission.WRITE_CONTACTS permission to the blacklist

- packages/expo-cli/src/accounts.js
- packages/xdl/src/Project.js
Fixes #126.
Usage:
Set environment variable `EXPO_CLI_PASSWORD` to expo password.
```bash
expo login --non-interactive -u username
```
> Allow using EXPO_CLI_PASSWORD env var for expo password

- packages/xdl/package.json
- packages/xdl/src/detach/installPackagesAsync.js
- yarn.lock
Fixes `expo eject` crashing if Yarn is not installed.
Fixes #336. Closes #340.
> [xdl] Fix Yarn existence check throwing null

- packages/xdl/src/detach/AndroidShellApp.js
companion PR to https://github.com/expo/expo/pull/3386
> [xdl] flavorless Android builds for SDK 33+

- packages/expo-cli/src/commands/build/ios/IOSBuilder.js
- packages/expo-cli/src/commands/build/ios/appleApi/ensureAppExists.js
- packages/expo-cli/src/commands/build/ios/credentials/generate.js
If there are no new credentials that need to be created and added , do not check if the app exists in the Apple portal. This makes it possible to build an app with existing credentials or credentials you upload, without the Apple ID that the app is linked to.
*Test plan*
Built a brand new app with `expo build:ios`, choosing " Expo handles all credentials, you can still provide overrides", the App ID was ensured before creating the credentials:
```
✔ Ensured App ID exists on Apple Developer Portal!
[12:22:17] We're going to generate:
[12:22:17] - Apple Distribution Certificate
[12:22:17] - Apple Push Notifications service key
[12:22:17] - Apple Provisioning Profile
✔ Generated Apple Distribution Certificate
✔ Generated Apple Push Notifications service key
✔ Generated Apple Provisioning …
```
> [expo-cli] Only verify the app exists if credentials are created in expo build:ios

- packages/expo-cli/src/commands/build/AndroidBuilder.js
- packages/xdl/package.json
- packages/xdl/src/Android.js
- packages/xdl/src/detach/AndroidIcons.js
- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/IosIcons.js
- packages/xdl/src/tools/ImageUtils.js
- yarn.lock
It fixes messed up `resizeMode` on standalone Android apps.
Moreover when no `mdpi` to `xxxhdpi` image is provided it copies `splash.image` to `mdpi` directory as baseline resolution (was copied to `xxxhdpi` previously).
> [expo-xli][xdl][Android] Splash screen standalone app fixes

- packages/expo-cli/src/commands/init.js
- packages/expo-cli/src/exp.js
- packages/expo-cli/src/prompt.js
Allow all options to `init` to be passed as command line flags to enable using `init` in non-interactive mode. Fixes #332 and #342.
**Test plan**
Verified that mandatory arguments are checked in non-interactive mode:
Verified that `--ios-bundle-identifier` is validated:
Verified that `--android-package` is validated:
> Fix non-interactive init command

- packages/expo-cli/src/log.js
The timestamp is useful for CI, build scripts and such, but I don't see much point for it when using Expo CLI interactively in the console. It also takes a lot of precious screen real estate. Some output already doesn't show it, by using the `log.nested()` to log without a timestamp.
This PR removes the timestamp from Expo CLI output except when it's used with the `--non-interactive` flag or in a non-interactive terminal.
> [expo-cli] Remove timestamp from logs except in non-interactive mode

- packages/expo-cli/src/commands/init.js
We previously added a prompt to `expo init` that allowed choosing between the `managed` (a regular Expo project) and `advanced` (an ExpoKit project) workflows.
The `advanced` workflow was marked as experimental, but it seems that people sometimes choose it by mistake, which results in confusing problems: https://forums.expo.io/t/really-stuggling-to-run-in-simultor/18743/2, https://github.com/expo/expo-cli/issues/338. Also once the current work on [universal modules](https://blog.expo.io/expokit-2019-1e5cb02106f8) is done, the upcoming `custom` workflow will likely be a better option for many use cases than the current `advanced` workflow.
This PR removes the experimental `advanced` workflow prompt from `expo init`. However, you can still initialize a project using the advanced workflow, …
> [expo-cli] Remove the experimental workflow prompt from `expo init`

- packages/expo-cli/src/exp.js
exp (the predecessor of Expo CLI) had a command named `detach` that would eject your project to ExpoKit. In Expo CLI this functionality is a part of the `expo eject` (which lets you choose `ExpoKit` when ejecting).
This PR adds a more helpful error message when running the `detach` command that doesn't exist.
> Show a note about eject when running `detach`

- packages/traveling-fastlane/Rakefile
- packages/traveling-fastlane/actions/funcs.rb
- packages/traveling-fastlane/actions/manage_ad_hoc_provisioning_profile.rb
- packages/traveling-fastlane/publishing/darwin/index.js
- packages/traveling-fastlane/publishing/linux/index.js
- packages/traveling-fastlane/wrappers/manage_ad_hoc_provisioning_profile_wrapper.sh
- packages/xdl/src/detach/IosCodeSigning.js
- packages/xdl/src/detach/IosIPABuilder.js
- packages/xdl/src/detach/IosNSBundle.js
- packages/xdl/src/detach/IosShellApp.js
- packages/xdl/src/detach/IosWorkspace.js
- packages/xdl/src/detach/StandaloneBuildFlags.js
Adds support for configuring Expo Client shell app and signing it with an ad-hoc provisioning profile.
> [xdl] adjust configureAndCopyArchiveAsync to Expo Client builds

- packages/expo-cli/src/commands/publish.js
Closes https://github.com/expo/expo/pull/3551.
> [expo-cli] Do not warn about building a standalone app in ejected projects

- packages/expo-cli/src/commands/init.js
Was unable to using custom template:
`expo init App --template expo-template-reason`
due to the typo.
detail:
```
ikewat λ EXPO_DEBUG=true expo init App --template expo-template-reason
templaceSpec is not defined
ReferenceError: templaceSpec is not defined
at _callee$ (/expo-cli@2.11.6/src/commands/init.js:81:9)
...
...
...
```
After the fix, this script works fine.
> Fix typo templaceSpec->templateSpec

- packages/xdl/src/Api.js
- packages/xdl/src/Versions.js
- packages/xdl/src/project/Doctor.js
blocked by https://github.com/expo/universe/pull/3431
Move to new `versions/latest` endpoint that correctly conforms to the APIv2 protocol (response body should be wrapped in a root level object under a `data` key if there are no errors), and use APIv2 to fetch versions. The current endpoint does not conform to the protocol and cannot be used with the APIv2 client even though it has `api/v2` in the url.
> [xdl] switch to versions/latest and use ApiV2 client

- packages/dev-tools/TESTING.md
- packages/dev-tools/components/ProjectManager.js
- packages/dev-tools/components/ProjectManagerSidebarOptions.js
- packages/dev-tools/server/graphql/GraphQLSchema.js
- packages/expo-cli/README.md
- packages/expo-cli/src/askUser.js
- packages/expo-cli/src/commands/publish.js
- packages/expo-cli/src/commands/send.js
- packages/expo-cli/src/commands/start.js
- packages/expo-cli/src/commands/start/TerminalUI.js
- packages/expo-cli/src/printRunInstructionsAsync.js
This removes SMS from the UI for sending project development links. The server endpoint still behaves the same, but the UI now promotes email over SMS. Email is more reliable, much cheaper, and more customizable. We'll make a similar change on web as well.
Ran the CLI on a test project and verified that both the CLI and web UI showed just "email" without "SMS" for sending links.
Web:
CLI:
> Remove "SMS" from link-sending descriptions

- packages/expo-cli/src/commands/start.js
- packages/xdl/src/Project.js
- packages/xdl/src/Web.js
* Added `--web-only` flag to CLI to make usage in `react-native init` projects work better.
* Added a case where `webOnly` is enabled if `expo.platforms` only contains `web`
* Fixed bug when stopping webpack dev server
> expo start --web-only

- packages/webpack-config/webpack.config.js
- packages/xdl/src/Project.js
- packages/xdl/src/Web.js
Now you can create a `webpack.config.js` in your root project which reexports `@expo/webpack-config` without creating a stack overflow.
> Move root `webpack.config.js` check to XDL

- packages/webpack-config/webpack/createIndexHTMLFromAppJSON.js
- packages/webpack-config/webpack/utils/config.js
- packages/webpack-config/webpack/webpack.prod.js
Added options to the `app.json` for configuring the production compression in web projects.
* fixes #461
* `brotli` is disabled by default
* gzip can be configured from the app.json
* moved common tools to a central utils file in webpack
> Configuring the production compression

- packages/expo-cli/package.json
- packages/expo-cli/src/commands/build/ios/IOSBuilder.js
- packages/expo-cli/src/commands/build/ios/utils/image.js
- yarn.lock
Closes #414 
In order to verify whether a png doesn't have any transparency, we not only need to check whether the png doesn't have an alpha channel, but we also have to check every pixel and see if the value for the alpha channel is equal to 255.
> [expo-cli] fix icon validation

- packages/webpack-config/webpack/createBabelConfig.js
Thanks!
This one makes it possible to run `expo web` on Windows.
> Make `includeModulesThatContainPaths` OS indifferent

- packages/xdl/src/Project.js
This closes #460.
Problem is that `stopWebpackServerAsync` gets called (whether or not the webpack server is running) when `stopinternalasync` is called, and results in the logged message shown in the issue (through calling `getWebpackInstance`). I thought the simplest fix would be to check for web support before that call.
This way-> `getWebpackInstance` [here](https://github.com/expo/expo-cli/blob/229fc54e20a812aaa0b0422b035dc49ec56695bf/packages/xdl/src/Project.js#L1832 ) still works as originally intended if it is used somewhere else.
This all ties up with checking for websupport before the `startWebpackServerAsync` call because it results in more consistency and clarity (i.e: why should startwebpack function run and NOT start the webpack?)
Let me know if there's something more for me …
> add check for websupport

- packages/webpack-config/webpack/createBabelConfig.js
- packages/webpack-config/webpack/webpack.common.js
- packages/webpack-config/webpack/webpackLocations.js
This allows webpack to load (and babel to process) *.ts and *.tsx files.
This brings the Expo Web behavior inline with the normal Expo behavior.
> [web] Add webpack support for TypeScript files

- packages/expo-cli/src/commands/start.js
`rg isDetachexped` shows that there are no other references to this property, which looks like a typo for `isDetached`.
> Fix `isDetachexped` -> `isDetached` in command parser

- packages/xdl/src/Project.js
- packages/xdl/src/logs/PackagerLogsStream.js
- **Remove legacy filtering of React Native packager logs**
React Native packager doesn't exist anymore (it's Metro now) and we pass a custom logger to Metro, which makes all this faffing unnecessary.
Partially removing ANSI codes from the logs also messed up with Webpack logging because this code was processing all logs, Metro or not.
- **Remove the “Running application "main" with appParams” noise**
Instead of:
`Running application "main" with appParams”: { <lots of params> }`
every time you refresh the app, just show a short:
`Running application on Ville's iPhone.`
> Logging improvements

- packages/expo-cli/src/commands/client/createClientBuildRequest.js
- packages/expo-cli/src/commands/client/index.js
We previously didn't send the push key because it was not handled by the server end point in the beginning.
> Select and send a push key in the adhoc build request

- packages/xdl/src/Simulator.js
Problem booting simulator device if simulator is open but no devices booted.
To repro, have the simulator open, then close the simulator window (⌘W). The simulator doesn't quit, but has no windows. Then try to open an app on iOS simulator with Expo CLI: it hangs indefinitely, waiting for simulator to start.
Device ID is for iPhoneX, wasn't sure if that's an issue. There didn't seem to be any `simctl` args for default sim. If that poses a problem, might be easier to just call `_quitSimulatorAsync` and return false.
> Fix 'Opening iOS Sim' indefinite hang

- packages/expo-cli/src/commands/build/BaseBuilder.js
The simple spinner can cause issues in basic terminals (e.g. CI terminals), in which it will create a new line per spinning tick. By using a more advanced spinner, we keep the spinner but avoid issues with these terminals.
Another approach could be to detect CI terminals and to disable the loader, but I think the ora spinner is cool, so why not use it here as well?
> Don't use a simple spinner when waiting for the build

- packages/config/src/Config.js
- packages/webpack-config/web-default/index.html
- packages/webpack-pwa-manifest-plugin/src/icons.js
- packages/webpack-pwa-manifest-plugin/src/index.js
- packages/webpack-pwa-manifest-plugin/src/injector.js
- packages/webpack-pwa-manifest-plugin/src/validators/Apple.js
* Removed iOS splash screen prop from web PWA splash screen since the backgroundColor is used across both iOS and Android
* Changed default `apple-touch-icon` from 1024 to 180
* Removed all icon sizes `96, 128, 192, 256, 384, 512` in favor of browser optimized `192, 512`
* Removed unused template `apple-touch-icon` & `apple-touch-startup-image ` in favor of manifest plugin generated copies
* Fixed splash screen resize mode
* Fixed splash screen contain mode
* Parallelizing all icon generation for faster results
* Fixed splash screens meta tags not being generated
> Parallelizing PWA icon generation

- packages/webpack-pwa-manifest-plugin/src/validators/Apple.js
You cannot lock iOS PWA orientation, we should produce every splash screen.
> Removed orientation filter from splash screen generation

- packages/config/src/Config.js
If `platforms` key is missing in `app.json`, default is to provide it with all three (ios, android, & web). This results in the warning message - 
>Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v32.0.0/workflow/configuration/
• Field: platforms - should NOT have more than 2 items.
And also starts the webpack server. Proposing that by default just include ios and android in `platforms`
cc @brentvatne
> Remove `Web` from Default Platforms

- packages/expo-cli/src/commands/start.js
Right now, `logURL()` for web is called when web isn't supported, so the message 
>Expo Web is running at null
is displayed in logs.
Change was to check for web support before calling `logURL()`
Tested these changes locally
> Fix Logging of Expo Web server

- package.json
- scripts/publish.js
- yarn.lock
Because of lacking support for npm 2FA (https://github.com/lerna/lerna/issues/1091), our release script often fails and leaves behind a bad mess with tags to remove, working tree to clean and commits to reverse if you want to attempt again. This is kind of bad, if you need to make a release and you end up fighting the tools that are supposed to help with it, not make it more difficult.
This PR aims to fix some of the issues with the release script. Instead trying to use `lerna publish` for the whole process, we now call `lerna version` to determine which packages to publish, bump versions and tag them in git. Then the script loops over all packages and finds those with a version not found in the npm registry and simply runs `npm publish` to publish them, in topologically sorted order. …
> Fix release script

- packages/xdl/src/Project.js
- packages/xdl/src/UrlUtils.js
- packages/xdl/src/Versions.js
Start the React Native server with the assetPlugins CLI flag from https://github.com/react-native-community/cli/pull/318 and stop using a query parameter in the URL, as support for this regressed in Metro recentlyish and it's not an ideal way to inject this plugin anyhow.
> Add assetPlugins arg to React Native server start for SDK33+

- package.json
- packages/expo-cli/package.json
- packages/xdl/package.json
- yarn.lock
I released a new version of `@expo/spawn-async` which preserves async error stack traces. It will help with debuging users issues.
I updated `@expo/spawn-async` package to 1.4.2 in `expo-cli` and `xdl`.
I tested new xdl version with turtle running locally and finally, an error stack trace contained information about the origin of the error.
> [xdl][expo-cli] update @expo/spawn-async to 1.4.2

- packages/webpack-config/webpack/webpack.common.js
`.web.tsx` was missing from the extensions priority list, causing `.tsx` files to precede `.web.tsx` files. The same for `.web.jsx`.
> .web.tsx has higher priority than .tsx

- packages/xdl/src/detach/IosNSBundle.js
When adhoc builds are run, instead of having the text below the app icon show as `expo-home`, display `Expo` instead.
TODO(quin) test these changes
> [xdl] change app display name for adhoc builds

- packages/expo-cli/src/commands/client/index.js
Feedback from https://exponent-internal.slack.com/archives/CFSP4GXL6/p1553565327070500, added somewhat more verbose copy to this command to explain the steps of this flow in a bit more detail to users. Also noticed this command didn't have a description, so I added one.
> [expo-cli] update client:ios copy to be more verbose

- packages/expo-cli/src/commands/build/index.js
- packages/webpack-config/webpack/webpack.common.js
- packages/xdl/src/Webpack.js
with `expo build:web --no-pwa` you can prevent the bundling of PWA features which can save up to a minute of generation time.
> Added `--no-pwa` flag

- packages/xdl/src/Project.js
Webpack will only start if:
* platforms only contains web
* `--web-only` flag was passed
* `--web` flag was passed
* User presses `w` in the interactive prompt after running `expo start`
> Only start webpack if the user invokes web.

- packages/expo-cli/src/exp.js
Currently it's not very clear how to get information about a specific command and see what the options are. 
This PR fixes that by adding a message about it at the end of the `--help` output.
> Add how to get info about a specific command in --help output

- packages/dev-tools/server/dev-server.js
- packages/expo-cli/src/commands/start.js
- packages/expo-cli/src/commands/start/TerminalUI.js
- packages/xdl/src/Web.js
Currently, when using web and devtools you get a new tab each time. This exacerbates the annoying feeling of needing to restart the bundler. Using `react-dev-utils/openBrowser` wrapper for the `opn` module we can attempt to reuse tabs when possible.
> Reuse browser tabs

- packages/expo-cli/src/commands/eject/Eject.js
This PR addresses several errors related to building and running an ejected Expo app described below:
1. `react-native run-android` and `react-native run-ios` were both throwing the following error:
```
$ react-native run-ios
internal/modules/cjs/loader.js:651
throw err;
^
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
at Function.Module._load (internal/modules/cjs/loader.js:575:25)
at Module.require (internal/modules/cjs/loader.js:705:19)
at require (internal/modules/cjs/helpers.js:14:16)
at Object.<anonymous> (/Users/sergeichestakov/Documents/test-eject/node_modules/react-native/local-cli/cliEntry.js:11:41)
at Module._compile (internal/modules/cjs/loader.js:799:30)
at Module._compile …
```
> Fix problems with building/running an ejected Expo app

- packages/expo-cli/src/commands/client/selectDistributionCert.js
- packages/traveling-fastlane/actions/manage_dist_certs.rb
- packages/xdl/src/credentials/IosCredentials.js
The dist certs we have on file may have been revoked so we should check that they are ok to use before displaying it as an option to the user. Otherwise, we risk sending a revoked dist cert to turtle and having it fail/error down the line.
> [expo-cli] [xdl] [traveling-fastlane] check dist certs against apple servers

- packages/traveling-fastlane/actions/manage_ad_hoc_provisioning_profile.rb
right now, we choose provisioning profiles by selecting the first available profile associated with the app bundle id. this should change because:
- We potentially modify the profile (add udid). The user may have non-expo managed profile they dont want modified (especially as we support adhoc builds for apps other than expo-home). 
- The provisioning profile may not be associated with the correct development certificate that was uploaded to turtle
- prepend provisioning profile name with "*[expo]", and only modify profiles with this string
- choose the provisioning profile with the development certs we want. If none exist, we add the cert to the profile and update it on the apple servers
> [travelling-fastlane] change the way we choose provisioning profiles

- packages/expo-cli/src/commands/optimize.js
- packages/expo-cli/src/commands/publish.js
- packages/xdl/src/AssetUtils.js
This PR addresses a couple of issues brought up with the new `expo optimize` command in 2.17.0:
1. Allows for a non-interactive flag in both publish and optimize to stop the program from prompting the user (Resolves #578).
2. Ignores the `ios/` and `android/` directories when searching for assets to optimize as that becomes a problem for apps ejected with ExpoKit (Resolves #581).
> Fix breaking changes with optimize

- packages/expo-cli/src/commands/optimize.js
- packages/xdl/src/AssetUtils.js
- packages/xdl/src/Project.js
- packages/xdl/src/project/Convert.js
Allow a user to compress assets to a custom quality via `expo optimize --quality=[number]` where `number` is an integer from 1-100 inclusive.
> Add --quality flag to specify amount of compression

- packages/expo-cli/src/commands/client/selectDistributionCert.js
- packages/expo-cli/src/commands/client/selectPushKey.js
For the Adhoc build workflow, the most desirable options (in my opinion) is
1/ use existing certificate we have on our servers (least effort)
2/ create new one
3/ upload cert from user's filesystem (most effort)
in the terminal workflow, we should display the options from most desirable to least.
> [expo-cli] order options from most desirable to least

- packages/expo-cli/src/commands/client/clientBuildApi.js
- packages/expo-cli/src/commands/client/index.js
- packages/expo-cli/src/commands/client/selectDistributionCert.js
- packages/expo-cli/src/commands/client/selectPushKey.js
- packages/expo-cli/src/commands/client/selectUtils.js
Most users probably don't want to be bothered with manually selecting credentials unless absolutely neccessary. If we find valid credentials, we should autoselect it and just expose a confirmation (Y/n).
> [expo-cli] autoselect creds if they exist for adhoc builds

- packages/expo-cli/src/commands/generate-module/fetchTemplate.js
When I ran `expo generate-module`, several errors were being thrown with the following format:
```
ENOENT: no such file or directory, lstat '/Users/sergeichestakov/Documents/expo-cli/packages/expo-cli/bin/expo-test/android/src/main/java/expo/module/template'
```
It seemed to be relying on the latest version of the template, but was actually downloading `v2.0.1` which didn't have those files/directories, thus throwing an error when calling `fs` functions on them.
This PR fixes these bugs by downloading the latest expo-module-template from npm
> Use latest module template in generate-module

- packages/expo-cli/src/commands/client/index.js
- packages/expo-cli/src/commands/client/selectDistributionCert.js
- packages/expo-cli/src/commands/client/selectPushKey.js
- packages/expo-cli/src/commands/client/tagger.js
Update credentials from `expo-cli`, instead of on the server side when we are processing the adhoc build request.
- the server side updates credentials every single request. on the client side, we can properly detect which cases require updating.
- `expo build:ios` has a similar model of saving credentials: first the credentials are obtained on the client side, updated if needed, then a request is made to the build api
- we want to update credentials as early as possible in the workflow. during user testing, when ppl created dist certs and bailed before the request to the adhoc build api was made, they expected the certs to have been saved.
> [expo-cli] update credentials client side instead of server side

- packages/expo-cli/src/commands/install.js
Detect which type of project we're in.
- For `bare`, simply delegate to `yarn add` / `npm install`.
- For `managed`, read the correct package versions from `bundledNativeModules.json` and install them with `yarn add` / `npm install`.
> Make `expo install` work for both managed and bare projects

- packages/xdl/src/detach/IosPodsTools.js
Followup #601. It turned out there is also `HAVE_GOOGLE_MAPS_UTILS` flag that we should pass to the pods project.
> [xdl] add HAVE_GOOGLE_MAPS_UTILS=1 preprocessor definition

- packages/expo-cli/src/commands/client/clientBuildApi.js
- packages/expo-cli/src/commands/client/index.js
- packages/expo-cli/src/commands/client/selectPushKey.js
- we want to make it as easy as possible for people to make an adhoc build, and push credentials arent required to do this
- users who have already created the maximum apns (2) and don't have their apns to upload from their filesystem should be given the option to continue the build process. Otherwise they will have no choice but to exit the process.
> [expo-cli] make push keys optional

- packages/xdl/src/DevSession.js
- packages/xdl/src/Project.js
Building out the expo-cli side of  showing in-development sessions for web projects (for Expo for Web).
In xdl/src/DevSession.js, expo-cli will send individual updates for
'native' and 'web' projects.
In xdl/src/Project.js, expo-cli will spawn a 'web' server as well
as a 'native' server if all platforms are supported in app.json.
run apps/native-component-list with expo/expo running on branch @jkhales/display_app_platform
> [web-projects] Send platform information in updates

- packages/expo-cli/scripts/preversion.js
when i published the newest versions of expo-cli packages and followed the instructions to manually test that the newest changeset is good, the instruction to test an ejected android app seems outdated:
```
cd ../android
./run.sh
```
In the android directory, `run.sh` isnt there:
```
Quinlans-MacBook-Pro:android quin$ ls
android.iml		build.gradle		fastlane		gradle.properties	settings.gradle
app			debug.keystore		gradle			gradlew
```
So i changed it to what's in the expokit docs here: https://docs.expo.io/versions/v32.0.0/expokit/expokit/#4-android-build-and-run
> [expo-cli] update manual testing instructions

- packages/xdl/src/AssetUtils.js
Currently, if a user does not specify an `assetBundlePatterns` field in their `app.json` running `expo optimize` will cause it to crash. 
This PR fixes that bug by adding a default pattern and resolves #645.
> Provide default pattern if assetBundlePatterns is unspecified

- packages/xdl/CHANGELOG.md
- packages/xdl/src/detach/Detach.js
Instead of adding another field for `react-native-unimodules` (we need to install this package in some specific version when ejecting), let's extend the API this way!
> [xdl] Add support for packagesToInstallWhenEjecting dictionary in API

- packages/expo-cli/src/commands/client/clientBuildApi.js
- packages/expo-cli/src/commands/client/index.js
Prevent malicious users from spamming the turtle queues with redundant adhoc build jobs
- If a user is logged in, if there is an adhoc build currently in progress, disallow the user from creating another adhoc build request.
- If a user is not logged in (anonymous), if there are more than 5 anonymous builds with the same apple team id, disallow the user from creating another adhoc build request
https://github.com/expo/universe/pull/3549
> [expo-cli] limit builds inflight for adhoc builds

- packages/xdl/CHANGELOG.md
- packages/xdl/src/detach/AndroidShellApp.js
Related change — https://github.com/expo/expo/commit/efbded1b67917a3f5af5372355320621c225cb4f#diff-74aeda4cd5fc88b4be36cd1a3acefec6
> [xdl] Do not blindly overwrite settings.gradle for SDK>=33

- packages/xdl/src/modules/config.js
As per step one in [this guide](https://github.com/expo/expo/blob/master/guides/Creating%20Universal%20Modules.md#integrate-with-the-native-projects), it seems I have to add the IAP module to the xdl module config in order for it to show up as a dependency in my Podfile and be usable within Expo apps via the Expo client.
Not sure if these instructions are fully up to date (some of the Android ones were a little outdated), but figured this was still a necessary prerequisite. Also, if you guys have any suggestions for how I can get started developing IAP on iOS quickly please let me know. But as of now, it seems this is required for the module to even be exposed when importing the native module as such:
```
import { NativeModulesProxy } from '@unimodules/core';
export default …
```
> feat: add ExpoInAppPurchases module to xdl config

- packages/expo-cli/src/commands/optimize.js
- packages/expo-cli/src/commands/publish.js
- packages/xdl/src/AssetUtils.js
- packages/xdl/src/Project.js
- packages/xdl/src/project/Doctor.js
After some user feedback, I think it might be best to remove the prompts from the `expo optimize` workflow (including via `expo publish`) in favor of warnings.
The prompt in `expo optimize` was to let the user know that their assets were going to be overwritten and ask if they want to save.a backup. However, given that the images will most likely look the same this shouldn't be a problem. In the off chance that they don't and the quality is noticeably worse, they can always restore them using git since Expo projects are almost always git projects (unless the user deleted the .git folder which is unlikely). I think we should also discourage saving backups as that clutters the file system and is most likely unnecessary.
The prompt during `expo publish` was to let the user know about how to …
> Remove prompting from optimize workflow

- packages/xdl/src/createWebpackCompiler.js
Previously all error messages were printed twice on the screen.
This PR fixes that, so error messages only get printed once, after the "failed to compile" message.
> fix: error messages getting printed twice

- .github/.COMMIT_TEMPLATE
- CONTRIBUTING.md
New template follows the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) format. Also added a step in the `Setting up the repository for development` section of the `Contributing` readme to configure this template for your local repo, but maybe we can make this part of the `bootstrap` script so there aren't 2 separate scripts to run to set up the repo for development?
This is the first step towards an automated changelog. 
Second step- We already use `lerna publish` command in the `publish` script, adding the [--conventional-commits flag](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-commits) should automatically up our versions & generate/update changelog files (NOTE: I'm not familiar with Lerna so feel free to correct me if I'm …
> feat: added commit message template

- packages/expo-cli/CHANGELOG.md
- packages/expo-cli/src/commands/init.js
Adding `expo-template-blank-typescript` to the list of templates.
> [cli] add expo-template-blank-typescript as an option in init command

- packages/webpack-config/web-default/index.html
When set to `auto` the scrollbar will be hidden unless there is a need for it.
Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
> fix(webpack-config): set body overflow-y to "auto"

- packages/xdl/src/detach/IosPodsTools.js
In `use_unimodules` method, `expo-face-detector` and `expo-payments` should be excluded by default when ejecting an app.
> [xdl] exclude expo-face-detector and expo-payments from being used on ejected apps by default

- packages/expo-cli/src/PackageManager.js
- packages/expo-cli/src/commands/customize.js
- packages/webpack-config/template/webpack.config.js
- packages/xdl/src/Web.js
Make it easier to customize your expo web project. Easily extend the index.html, webpack.config.js, serve.json, and favicon. fixes #671 
Added a command `expo customize:web` with optional `--force` which enables you to overwrite existing files.
This command will prompt the user with files that will be copied over from expo/webpack-config. 
Run expo `customize:web` in any expo project.
> Added `expo customize:web`

- packages/xdl/src/detach/ExponentTools.js
I'm hoping this is what's causing crashes in our android builders.
The error message:
```
internal/streams/legacy.js:59
throw er; // Unhandled stream error in pipe.
^
Error: ETIMEDOUT
at Timeout._onTimeout (/app/turtle/node_modules/request/request.js:849:19)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
```
I could not find usages of request in turtle that does not handle the error event, but
of course it does use xdl.
Either way I think this line is worth changing.
> fix(xdl): saveUrlToPathAsync() handles request errors

- packages/config/src/Config.ts
- packages/webpack-config/webpack/webpack.common.js
- packages/webpack-pwa-manifest-plugin/src/createMetatagsFromConfig.js
Added `apple-mobile-web-app-capable` back. Exclude apple images from the service worker as they are only accessed when the device caches them during PWA generation.
> Fixed iOS PWA splash screens

- packages/xdl/package.json
- packages/xdl/src/Android.js
- packages/xdl/src/detach/AndroidShellApp.js
Resolves: https://github.com/expo/expo/issues/4494 and partially https://github.com/expo/expo/issues/3611
Deployed on staging and tested standalone android builds for all three android splash screen modes.
> [xdl] add 'native' mode for Android splash screen

- packages/expo-cli/src/commands/optimize.js
Users have been reporting the quality of some of their images is too low after they run `expo optimize`.
This increases the default compression from 60% of the original to 80%.
> Increase default optimize quality to 80

- packages/traveling-fastlane/actions/manage_ad_hoc_provisioning_profile.rb
Made a couple changes to the way adhoc device registration is done. '
- when the `manage_adhoc_proviisoning_profile.rb` script is run, we pass in an array of udids.  We first determine which of these UDIDs to register with Apple. 
- The udids we add should be determined with `udids_to_add = udids_we_pass_in - all_ios_profile_devices`
- `all_iphones` was changed to `all_ios_profile_devices` because we want to use the same fastlane device call we use in https://github.com/expo/expo-cli/pull/705 . Also we want to account for the usecase for installing the Expo client on other devices like iPads.
- originally, if a device is already registered but *disabled*, we will attempt to register it with Apple anyways (`all_iphones.select { |d| d.enabled? and udids.include?(d.udid) }`). This could be …
> improvement(traveling-fastlane) modify adhoc device registration

- packages/expo-cli/src/commands/client/index.js
- packages/traveling-fastlane/actions/list_devices.rb
this fixes the appletv bug that llamaluvr found
- You can't associate the UDID of an AppleTV to an ios provisioning profile 
- Currently, we compute the list of all UDID's on the client side (cli), and then send it off to turtle to register with apple
- This is bad because the list of UDID's could contain an AppleTV
- Instead of returning all UDIDs, we create support in the `list_devices.rb` script where you can pass in a flag to return only the devices that can be used for iOS profiles
> fix(traveling-fastlane) add flag for iOS device subsets

- packages/webpack-config/webpack.config.js
- packages/webpack-config/webpack/createDevServerConfigAsync.js
- packages/webpack-config/webpack/createIndexHTMLFromAppJSONAsync.js
- packages/webpack-config/webpack/loaders/createBabelLoaderAsync.js
- packages/webpack-config/webpack/utils/Diagnosis.js
- packages/webpack-config/webpack/utils/getConfigAsync.js
- packages/webpack-config/webpack/utils/getPathsAsync.js
- packages/webpack-config/webpack/webpack.common.js
- packages/webpack-config/webpack/webpack.config.unimodules.js
- packages/webpack-config/webpack/webpack.dev.js
- packages/webpack-config/webpack/webpack.prod.js
Properly reading the config files using `ConfigUtils` required that the entire webpack config be converted to an async method.
> [webpack-config] Converted to async

- packages/expo-cli/src/commands/build/index.js
Common practice seems to be for users to include this themselves based on their needs.
> Made polyfill disabled by default

- packages/xdl/src/detach/IosPlist.js
I've jumped into this part of code when working on https://github.com/expo/expo/pull/4591
I'm not fully sure why, but we used both `plutil` command line tool available on macOS and `plist` package from npm when running on Linux or Windows. I can only suspect it was caused by the different plist formatting used by Xcode and `plutil` (with opening `<dict>` being at the same level as `<plist>` and with tabs instead of spaces). However, `plist` package also supports such formatting through its options, so we can use one, cross-platform solution instead.
Question: does anybody know why we are creating these Info.plist backups? One backup in plist format and one in json 🙄 Seems like we don't need any of them.
> refactor(xdl): use `plist` npm package instead of `plutil`

- packages/expo-cli/package.json
- packages/xdl/src/detach/Detach.js
- packages/xdl/src/detach/IosPodsTools.js
- packages/xdl/src/detach/IosShellApp.js
- packages/xdl/src/detach/IosWorkspace.js
- yarn.lock
It turned out shell app for SDK33 was not using autolinking because it used an old version of xdl. Unfortunately, I found some issues with using them there - mostly related to the fact that shell app workspace doesn't look like a common project workspace.
- Replaced `shellAppWorkspaces/ios/default` with `shellAppWorkspaces/default/ios`
I suppose `default` was going to be some kind of a flavor, but having it inside `ios` folder makes the difference in paths when compared to a common projects (paths were different in shell app and when ejecting). 
- Added `UNIVERSAL_MODULES_PATH` to podfile substitutions so we know where to look for unimodules.
- Temporarily duplicated installing `packagesToInstallWhenEjecting` when creating iOS workspace. This is needed to install react-native-unimodules. …
> [xdl] Fix iOS shell app when using unimodules autolinking

- packages/expo-cli/src/commands/client/index.js
- packages/xdl/src/credentials/Credentials.js
- Push notifications don't work on adhoc builds. 
- This is because push credentials are fetched differently in apps that are identified to be an `Expo Client` vs a normal standalone app. 
- In a regular standalone app, there is a mapping from {bundleIdentifier, experienceName} -> push creds.  In an `Expo Client`, there is a mapping from {bundleIdentifier} -> push creds, and `experienceName` is disregarded
- In adhoc builds, we add an extra entry in the `AppCredentials` table with a bundleIdentifier and null experienceName. This is associated with the `UserCredentials` entry that has the proper push notification credentials.
- We modify the Redis caching to properly generate a cacheKey when experienceName is `null`
- In the `expo-cli`, there is an additional bug that doesn't create new …
> [expo-cli][xdl] fix credentials update + fetch bugs

- packages/expo-cli/src/commands/build/ios/appleApi/ensureAppExists.js
- packages/expo-cli/src/commands/client/index.js
- packages/traveling-fastlane/actions/ensure_app_exists.rb
- in order to make push notifications work for adhoc builds, you need to go into the Apple Development Portal into the `Identifiers` tab, and check the `Push Notifications` box in order to get push notifications working.
- this is very frustrating and not very intuitive at all, and we should enable it for Adhoc builds automatically for users. Maybe we should consider doing it for all standalone builds too (afaik we dont currently do this?)
> [expo-cli][traveling-fastlane] enable push notifs from apple portal

- packages/webpack-config/webpack/loaders/createBabelLoaderAsync.js
- packages/webpack-config/webpack/webpack.common.js
In the case of an example project, you may want to set the babel root to be `../` this will enable that functionality with `"expo.web.build.babel.root": "../"` in the `app.json`
> Ability to override babel project root

- packages/expo-cli/src/commands/start.js
Resolves https://github.com/expo/expo-cli/issues/599
I added checking the project's dependencies' versions when a user runs `expo start`.
I installed an incompatible version of `expo-camera` and ran `expo start`. I got this warning:
```
Some of your project's dependencies are not compatible with currently installed expo package version: 
- expo-camera - expected version range: ~5.0.1 - actual version installed: 4.0.0
Your project may not work correctly until you install the correct versions of the packages.
```
> feat(expo-cli): validate project's dependencies when running expo start

- packages/image-utils/index.ts
- packages/image-utils/src/index.ts
- packages/image-utils/src/sharp.ts
* fix `Cannot find module 'sharp'` (https://github.com/expo/expo-cli/issues/760)
* fix `NaN` inside the error message caused by a stray unary `+` (also from https://github.com/expo/expo-cli/issues/760)
* fix publishing `@expo/image-utils` with `npm` (https://github.com/expo/expo-cli/issues/767)
> fix: issues related to @expo/image-utils

- packages/xdl/src/Binaries.ts
- packages/xdl/src/Diagnostics.js
- packages/xdl/src/FileSystem.js
- packages/xdl/src/project/Doctor.js
This function has already been a no-up, unless running inside XDE (a former desktop app). Since XDE is long gone, this code is no longer necessary.
> BREAKING CHANGE(xdl): remove Binaries.sourceBashLoginScriptsAsync()

- packages/expo-cli/src/commands/build/utils.js
- packages/xdl/src/Versions.ts
- packages/xdl/src/tools/UpdateVersions.js
https://github.com/expo/universe/issues/3564
I changed `canTurtleBuildSdkVersion` function so it uses the new endpoint introduced here - https://github.com/expo/universe/pull/3593
> BREAKING CHANGE(xdl): use new endpoint to fetch SDK versions supported by Turtle

- packages/webpack-config/utils.js
- packages/webpack-config/webpack/webpack.common.js
Some libraries have too many side-effects to enable any kind of tree-shaking (like three.js). In this case we want to completely disable tree-shaking so you can push to prod.
Enable only in production mode:
```js
const createExpoWebpackConfig = require('@expo/webpack-config');
const { getMode } = require('@expo/webpack-config/utils');
module.exports = async function(env, argv) {
const mode = getMode(env);
const isProd = mode === 'production';
const config = await createExpoWebpackConfig(
{
...env,
removeUnusedImportExports: isProd,
},
argv);
return config;
};
```
> feat(webpack-config): add abiliity to disable deep scope

- .github/lock.yml
Once an issue has been closed, and is inactive for a certain period of time (in this case- 60 days, but we can change/update that), it should be locked. This results in less people commenting "I experience this bug, too" after the issue has been closed, and instead they will open up a new issue with more information and a repro
Main things to get feedback on-
- how long before we lock issues? I've chosen 60 days but that's pretty long
- adding the label outdated right now upon locking, any objections? Also see lock comment
Note: I've created a different config file for `expo/expo` repo and `expo/expo-cli` repo, but can always just extend one to the other. I just thought it might be nice to be able to customize each
> Implement Auto-Lock on Inactive & Closed Issues

- packages/expo-cli/src/commands/client/clientBuildApi.js
- packages/expo-cli/src/commands/client/index.js
- Google maps doesnt work on adhoc build clients
- Normally when a user makes a standalone build, they declare `ios.config.googleMapsApiKey` in their `app.json`. Regular Expo clients have the Expo googleMapsApiKey, but we are not going to use this since we are going to constrain it to the expo client bundleIdentifier soon.
- when a user runs `expo client:ios`, we try to find a valid `app.json` in their cwd or from a passed in `--config` flag. 
- we thread this through to turtle so it knows to use the custom ios configuration 
https://github.com/expo/expo-cli/pull/747
https://github.com/expo/expo/pull/4674
https://github.com/expo/universe/pull/3589
- custom adhoc build now works with Google Maps
> [expo-cli] adhoc builds: grab available app.json, improve disable services info text

- packages/webpack-config/package.json
- yarn.lock
Related https://github.com/expo/expo-cli/issues/614
Deep scope analysis was rewritten and only the patch version was bumped. I suspect this could be what broke web builds.
> fix: roll webpack-deep-scope-plugin back

- packages/expo-cli/bin/expo.js
We support Node.js maintenance LTS, active LTS and current release versions.
Previously the supported version range was defined as 8.x.x || >=10.0.0,
but this included the 11.x.x versions that reached end-of-life on June 1st 2019.
Update the supported versions to include the exact ranges we support and also
make the error message clearly tell which versions are supported.
Note: the version ranges purposefully use the normal forms such as '>=8.9.0 <9.0.0'
instead of '^8.9.0' to make them easy to understand even without knowledge of the
intricacies of semver.
> BREAKING CHANGE: make supported Node.js versions stricter

- packages/webpack-pwa-manifest-plugin/src/icons.js
https://twitter.com/Baconbrix/status/1138720833185075200?s=20
> fix: remove alpha from iOS PWA images when a background color is added

- packages/xdl/src/detach/AndroidShellApp.js
It turned out we don't remove Expo client's API keys from `AndroidManifest.xml` when corresponding keys are not provided by the user. With these changes, `xdl` will always delete Expo client's API keys from `AndroidManifest.xml`, especially when they are not provided by the user.
Fixes https://github.com/expo/expo/issues/4776
> [xdl] Remove Expo client's API keys from AndroidManifest when preparing a shell app

- packages/xdl/package.json
- packages/xdl/src/AssetUtils.ts
- packages/xdl/src/Project.js
- yarn.lock
Convert XDL AssetUtils module to TypeScript.
This is marked as a "breaking change" because removing `AssetUtils.toReadableValue` in favor of the `pretty-bytes` package causes a semver major version bump.
> BREAKING CHANGE: convert AssetUtils to TypeScript, drop AssetUtils.toReadableValue

- packages/webpack-config/package.json
- packages/webpack-config/webpack/webpack.common.js
- packages/webpack-config/webpack/webpack.prod.js
- packages/xdl/src/Webpack.js
- yarn.lock
- Explicitly prevent the generation of files with errors
- Run linter on project to throw build errors
- Log every error and warning
- Throw warnings as errors in CI
- Remove log about deleting the `web-build` folder
- Enable built-in Webpack performance warnings
- Fail faster when an error is found in a production build
> [web][webpack-config] Added linting errors to Webpack config

- packages/xdl/src/Project.js
This allows developers to provide fallback behavior for Expo client when they are running it against a bare app. Eg: you have `Map.js` that imports `react-native-mapbox-gl`, and `Map.expo.js` that imports `react-native-maps`. When you do a native build you'll want the react-native-mapbox-gl one, and when you run in the Expo client, in order for it not to crash due to a missing native module, you will want the react-native-maps one.
Note: this is not implemented for web in this PR. We may follow up with support for web, discussing internally.
> [xdl] Add .expo.* extension for projects running in Expo client

- packages/xdl/src/tools/ModuleVersion.ts
As part of checking for cli version updates, a request is made to the npm registry using the ["package-json" npm package](https://www.npmjs.com/package/package-json). That package doesn't respect proxy settings in any way, which means the request will time out if used behind a corporate proxy (which is my Expo use case). The standard timeout here is ~60 seconds.
Because this check is made every cli command if we don't have the data cached and because my environment fails to load the data, this is adding a minute of hang time before every cli command I make.
There is already a timeout applied to the other registry request in this same function, so I've decided to use the same pattern and timeout value (2 seconds) on this first check as well.
I'll still have an extra 2 seconds of time to …
> fix(xdl): Adding a timeout to a ModuleVersion request to the npm registry

- packages/expo-cli/src/commands/start.js
If a user installed some module from Github and that module happens to be defined in `expo/bundledNativeModules.json` then we don't handle this case properly (`expo start` fails). I fixed that by verifying whether the version in `package.json` is a valid semver (or range) and if it's not then we skip that module validation.
> [expo-cli] fix starting projects with modules installed from github

- packages/xdl/src/Simulator.ts
- packages/xdl/src/__integration_tests__/Simulator-test.js
(Redo of [PR 547](https://github.com/expo/expo-cli/pull/547))
Closes [536](https://github.com/expo/expo-cli/issues/536)
---
Follows the logic suggested in the issue. Additionally:
`_waitForSimulatorRunningAsync` was an extraneous function since `_waitForDeviceToBoot` is more specific. this way, we don't try to open the app url before the device is actually booted.
I also edited `_getFirstAvailableDeviceAsync` to only loop over iOS devices (since if there's no default, that's most likely what the user wants to test on), **and** it will start with the devices on the newest iOS software, which is also probably a good practice (faster boot-up time, as well)
@brentvatne I don't know if we should listen for the xcrun error codes and swallow them, because then we'd have to reroute and repeat the …
> fix: iOS Simulator booting device when booted

- packages/expo-cli/src/commands/build/ios/credentials/prompt/index.js
- packages/expo-cli/src/commands/build/ios/credentials/prompt/promptForCredentials.js
- packages/expo-cli/src/commands/build/ios/credentials/prompt/promptForOverrides.js
- packages/expo-cli/src/commands/client/selectDistributionCert.js
- packages/expo-cli/src/commands/client/selectPushKey.js
When a user passes his own distribution cert but lets Expo handle provisioning profile generation we generate the provisioning profile for the last dist cert found on Apple Developer Portal. This PR fixes this bug by choosing the right dist cert for provisioning profile.
> [expo-cli] fix provisioning profile generation

- packages/xdl/src/Project.js
- packages/xdl/src/UrlUtils.ts
Fix "ValidationError: "https" is not allowed" thrown when trying to load the manifest and change the manifest handler so that it logs all errors to make it possible to catch this kind of problems in the future.
> fix: problem loading the requested app

- packages/expo-cli/src/commands/customize.js
Before, `expo customize:web` failed on Windows with the following error:
```
ENOENT: no such file or directory, scandir ''
```
This was due to some pathing logic using `/` as a path delimiter, whereas Windows uses `\` .
This swaps out the `substring` for `path.dirname` which works properly on all platforms.
Tested on Windows and Linux (Ubuntu WSL).
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/4138357/61477520-18820800-a955-11e9-9311-50fce30ac9b3.png)|![image](https://user-images.githubusercontent.com/4138357/61477561-2afc4180-a955-11e9-8139-c01c0db5e715.png)|
> [web] fix `expo customize:web` on Windows

- packages/webpack-config/webpack/loaders/createBabelLoaderAsync.js
Fix blocker for starting expo web.
- editing the global node_module directly with this change fixes the bug
> Fix: "cannot assign to read only property `exports` of object: '#<Object>'"

- packages/xdl/src/detach/IosNSBundle.js
Currently, all standalone apps built by Expo do not support iPad's multitasking feature (Slide Over and Split View). We should add an option to allow developers to enable this feature.
https://expo.canny.io/feature-requests/p/ipad-multitasking-for-standalone-apps
Added an `ios.requireFullScreen` option is added in `app.json`.
This is defaulted to `true` for now to match the current behavior (i.e., the behavior prior to SDK 34), but will change to `false` in a future SDK version.
> From @ide:
> 
> We could release this change in two phases:
> 1. Add `ios.requireFullscreen` and make the default value `true`. If you explicitly specify a value, we’ll use that value. but if you don’t specify any value, then the app is full-screen. this preserves today’s current behavior.
> 2. In a future SDK …
> [xdl] Add support for `ios.requireFullScreen` option in `app.json`

- packages/babel-preset-cli/index.js
- packages/babel-preset-cli/package.json
- yarn.lock
When changing the build configurations to add support for TypeScript, the lazy loading of modules that was previously done using the `babel-transform-inline-imports-commonjs` package was removed from `@expo/xdl` and `expo-cli`:
- https://github.com/expo/expo-cli/commit/b45e9dbf724bc077b7fbaf5041961028c4ddf470#diff-77b4343b244f7776c55c7c643d13efe6
- https://github.com/expo/expo-cli/commit/e3c7af725987e17bac74d0e806c67b0691ca626b#diff-b80134f5b17e5b157842c17b91ec70f4
This affected startup time of the CLI negatively, causing every command to take 3-5 seconds to start.
This commit restores lazy loading of modules, now using the `lazy` option of `@babel/plugin-transform-modules-commonjs`.
Thanks to @ninjaachibi for his investigation and profiling that revealed the source of the slowdown was …
> fix: slow CLI startup time performance regression

- packages/expo-cli/src/commands/optimize.js
Increased default quality for `expo optimize` in https://github.com/expo/expo-cli/pull/721, forgot to update help message (i.e. when you run `expo optimize --help`)
> Update default quality in help message for optimize command

- packages/xdl/src/Exp.ts
Don't guess whether git is installed by checking if Xcode is installed. Just try to use git and warn if it fails.
I've tested with `git` in the path, with `git` not in the path and with a non-executable `git` in the path.
If git is in the path and executable then it is used as expected.
If git is not in the path, the expected warning is printed.
Closes issue #905
> fix: detect git even if Xcode is not installed

- packages/xdl/CHANGELOG.md
- packages/xdl/package.json
- packages/xdl/src/detach/AndroidIcons.ts
- packages/xdl/src/detach/AndroidIntentFilters.ts
- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/AssetBundle.js
- packages/xdl/src/detach/Detach.js
- packages/xdl/src/detach/ExponentTools.ts
- packages/xdl/src/detach/IosAssetArchive.ts
- packages/xdl/src/detach/IosIcons.ts
- packages/xdl/src/detach/IosKeychain.ts
- packages/xdl/src/detach/IosLaunchScreen.js
- packages/xdl/src/detach/IosNSBundle.js
- packages/xdl/src/detach/IosPlist.ts
- packages/xdl/src/detach/IosPodsTools.js
- packages/xdl/src/detach/IosShellApp.js
- packages/xdl/src/detach/IosWorkspace.js
- packages/xdl/src/detach/StandaloneContext.ts
- packages/xdl/src/detach/installPackagesAsync.ts
- yarn.lock
This PR removes Flow from the `xdl/src/detach` folder. The files that could be converted to TypeScript with minor changes have been converted to TypeScript and renamed to the `.ts` extension, and the rest of the files have been kept `.js` and the Flow types have been stripped out.
After this, there's just a handful of other files with Flow types left in the XDL. I'll soon open a separate PR that removes those and removes the `@babel/preset-flow` from the build configuration.
> refactor: remove Flow types from the detach folder

- packages/expo-cli/src/commands/customize.ts
```sh
$ expo customize:web
Cannot read property 'readConfigJsonAsync' of undefined
TypeError: Cannot read property 'readConfigJsonAsync' of undefined
at action (/expo-cli@3.0.10/src/commands/customize.ts:126:3)
at Command.action (/expo-cli@3.0.10/src/exp.ts:82:13)
```
I looked for every import to `@expo/config` and fixed the import, however, only one file needed a fix.
Related to #822 (Which I think this should be closed)
> fix(expo-cli): correctly import @expo/config

- packages/webpack-config/tests/__tests__/basic-test.js
- packages/webpack-config/web-default/expo-service-worker.js
- packages/xdl/src/Webpack.ts
(See also https://github.com/expo/expo-cli/pull/844 and https://github.com/expo/expo-cli/pull/926.)
We copy and serve `/expo-service-worker.js` (and `/service-worker.js`) with Express when using Next.js. This means that `expo start --dev` and `expo start --no-dev` will both support the service worker without any additional configurations.
For services like Now.sh, configurations like https://github.com/hanford/next-offline#now-20 are needed. See docs from https://github.com/expo/expo/pull/5501.
Problem:
- `/static/expo-service-worker.js` will always get created even if the user is not using web Notifications.
> feat(web): add supports for push notifications for Next.js with Expo for Web

- packages/expo-cli/src/exp.ts
Changed the text as to not make it seem as though npm is the only or recommended way of updating expo-cli to avoid confusion for users (such as https://github.com/expo/expo-cli/issues/914).
> Change new cli version warning text

- packages/xdl/src/Android.ts
- packages/xdl/src/Versions.ts
- packages/xdl/src/tools/UpdateVersions.ts
Instead of saving iOS simulator builds and Android APKs urls to the global config, we would like to store them at SDK-specific configuration - it is required for https://github.com/expo/expo/pull/5331.
I've also exported a few more methods and made it possible internally to install an app from any url and not only the latest one.
> [xdl] Make simulator builds and Android APKs SDK-specific

- .circleci/config.yml
https://circleci.com/gh/expo/expo-cli/7454?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- error computing cache key: template: cacheKey:1: function "parameters" not defined
> Fix CI caching parameters

- packages/dev-tools/package.json
- packages/dev-tools/pages/index.js
- packages/dev-tools/server/DevToolsServer.js
- packages/dev-tools/server/dev-server.js
- yarn.lock
This patch adds four measures to limit access to the local WebSocket
API of Dev Tools.
- The WebSocket API endpoint URL now includes a secret token.
Requests to the API without the ticket are unauthorized, for example:
ws://localhost:19002/M2vbMDtkD-hVJGCegdw3BytRFV5JbQXPM2pLbYwgQDo/graphql
- WebSocket connections without a correct `Origin` header are rejected.
- After a connection is established, the client needs to inclue
`clientAuthenticationToken`, another secret token.
- The HTTP server of Dev Tools is only listening connections to `localhost`.
The secret tokens are obtained from a new HTTP endpoint `/dev-tools-info`.
Thanks to Spencer von der Ohe for reporting this issue.
> fix(dev-tools): add authentication to the WebSocket API

- packages/xdl/src/Simulator.ts
Looks like in iOS13 simulators, the glob path (`./data/Containers/Data/Application/*/Library/Caches/Snapshots/host.exp.Exponent`) that we used to check whether the app has been installed is no longer working. In iOS13, the `Snapshots` directory is not under `Caches` but under `SplashBoard` directory. Also, directory whose name was a bundle identifier can now contain some other stuff (it is `host.exp.Exponent - {DEFAULT GROUP}` in my case 🤔)
> [xdl] Fix waiting for Expo app to be installed on the simulator

- packages/xdl/src/Webpack.ts
- Dev flag doesn't provide enough control for debugging a prod build.
- Persistent dev flag causes a lot of confusion
> Prevent prod builds from using dev flag

- packages/json-file/__tests__/JsonFile-test.ts
- packages/json-file/src/JsonFile.ts
When we update templates with new expotools, we remove new line characters from the end of package.json and app.json file. This is bad. 
https://github.com/expo/expo/pull/5679/files
- I added a new line at the end of the stringified object in `writeAsync` function.
- I introduced a new option (`addNewLineAtEOF`) which makes it possible not to add a new line at EOF.
- I added a test for this feature.
Update `@expo/json-file` in expotools once published to npm.
> [json-file] add new line at eof when writing a json to a file

- packages/xdl/src/Webpack.ts
Fix https://github.com/expo/expo-cli/issues/1048.
`env.development` seems to be always `undefined`.
> fix(xdl): Check development mode correctly for Next.js

- packages/expo-cli/src/commands/index.ts
- packages/expo-cli/src/exp.ts
Previously Expo CLI searched every file and directory in the `commands`
folder and imported commands dynamically.
Removing this dynamic importing requires us to list all commands in
`commands/index.ts`, but it is necessary for tools that use static
analysis, such as [`ncc`](https://github.com/zeit/ncc) to to work.
> refactor(expo-cli): make importing commands non-dynamic

- packages/expo-cli/package.json
- packages/expo-cli/src/PackageManager.ts
This fixes #1054. Whenever the NPM package manager needs to install a dependency, it says no to [NPM's](https://github.com/npm/npm/issues/16813) [weird](https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json#answer-31733623) [interpretation](https://github.com/npm/npm/issues/19585) of [semver ranges](https://nodesource.com/blog/semver-tilde-and-caret#caretisthenewnorm).
I split my patch into two commits. The first is the actual patch in the package manager, and the second one is to keep the developer's package indentation and newlines intact. The fix in the second commit is [based on the awesome guys at semantic release](https://github.com/semantic-release/npm/issues/70), it also works fine in …
> Fix NPM interpretation of semver ranges

- packages/expo-cli/src/commands/build/AndroidBuilder.js
- packages/expo-cli/src/commands/build/ios/IOSBuilder.js
- packages/expo-cli/src/commands/fetch/ios.js
- packages/expo-cli/src/commands/publish-info.js
- packages/expo-cli/src/commands/upload/IOSUploader.js
- packages/expo-cli/src/credentials/views/AndroidCredentials.ts
- packages/expo-cli/src/credentials/views/IosDistCert.ts
- packages/xdl/src/Exp.ts
- packages/xdl/src/credentials/Credentials.ts
Fix some cases where expo-cli commands would ignore an owner key specified in app.json
> fix: respect the owner field specified in app.json

- packages/xdl/package.json
- packages/xdl/src/ip.ts
- yarn.lock
This should fix many problems related to showing the wrong
IP address (e.g. Docker, VMWare or Virtualbox network interface).
Using the `internal-ip` module, we choose the network interface that has
the same subnet as the default gateway.
See #712.
> fix(xdl): detect LAN IP from default gateway

- packages/dev-tools/package.json
- packages/expo-cli/package.json
- packages/json-file/package.json
- packages/schemer/package.json
- packages/xdl/package.json
- yarn.lock
See https://www.npmjs.com/advisories/1065
Updated to the latest published Lodash version. I could've just bumped to `^4.17.12` as per the advisory, but figured I might as well use the latest version. Although `^4.17.11` does allow the installation of newer non-vulnerable versions, `4.17.11` satisfies that version range and seems to cause `Snyk` to produce warnings.
> chore: bump lodash from 4.17.11 to 4.17.15

- packages/expo-cli/src/commands/optimize.ts
- packages/xdl/src/AssetUtils.ts
- packages/xdl/src/Project.ts
Not passing an options object caused an error in `Project.optimizeAsync`.
Changed the quality option to be non-mandatory so that the default needs to be defined in just one place and made the options object optional.
> fix(dev-tools): fix publish failing when "optimize assets" is selected

- packages/xdl/src/modules/config.ts
https://blog.expo.io/expo-sdk-35-is-now-available-beee0dfafbf4
> Change module versions to match release

- packages/webpack-config/package.json
- packages/webpack-config/src/loaders/createBabelLoader.ts
- packages/webpack-config/src/utils/paths.ts
- yarn.lock
Add ability to run a project with the bare minimum, this accounts for a missing `babel.config` and a missing `main` in the `package.json`
> Use a min expo web setup

- .circleci/config.yml
- packages/config/babel.config.js
- packages/config/jest.config.js
- packages/config/package.json
- packages/config/src/Config.ts
- packages/config/src/Config.types.ts
- packages/config/src/Modules.ts
- packages/config/src/__tests__/Modules-test.js
- packages/schemer/__tests__/files/schema.json
- packages/schemer/__tests__/test.js
- packages/webpack-config/src/utils/Diagnosis.ts
- packages/webpack-config/src/utils/__tests__/__snapshots__/getConfigAsync-test.js.snap
- packages/webpack-config/src/utils/paths.ts
- packages/xdl/src/Env.ts
- packages/xdl/src/Project.ts
If the `sdkVersion` is not defined in the `app.json` then we should attempt to read it from the installed `expo` version.
> default sdkVersion to expo package version

- packages/babel-preset-cli/ts-declarations/freeport-async/index.d.ts
- packages/dev-tools/package.json
- packages/dev-tools/server/DevToolsServer.js
- packages/xdl/package.json
- packages/xdl/src/Project.ts
- yarn.lock
Fixes #1097.
Blocked on https://github.com/expo/freeport-async/pull/3 to be merged and published.
> fix: EADDRINUSE when running Expo CLI in two projects at the same time

- packages/webpack-config/package.json
- packages/webpack-config/src/webpack.config.ts
- yarn.lock
This module does suboptimal path checks across all `node_modules` which scales exponentially across large projects. 
- `EXPO_DEBUG=true expo start:web --dev`
`index.js`
```jsx
import * as React from 'react';
import { AppRegistry, Text } from 'react-native';
AppRegistry.registerComponent('main', () => <Text>Test min</Text>);
const rootTag = global.document.getElementById('root');
AppRegistry.runApplication('main', { rootTag });
```
`webpack.config.js`
```js
const SpeedMeasurePlugin = require('speed-measure-webpack-plugin');
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
module.exports = async function(env, argv) {
const config = await createExpoWebpackConfigAsync(env, argv);
const smp = new SpeedMeasurePlugin();
return smp.wrap(config);
};
```
```sh
SMP  ⏱  
General …
```
> Removed case-sensitive-paths-webpack-plugin

- packages/xdl/src/Project.ts
Stop passing the `--nonPersistent` option to the React Native CLI for SDK 33 and newer projects.
React Native CLI and Metro no longer support this option, starting from Metro v0.47.0, which corresponds to `react-native@0.57.2`. Therefore, from SDK 33 this flag should have no effect, so we can stop using it. And from SDK 36, passing the `--nonPersistent` option would be an error anyway because it has been removed in React Native CLI, so this change is necessary for supporting SDK 36.
Fixes #1128.
React Native used to translate the `--nonPersistent` flag to the `watch` option of Metro. `watch` was removed here: https://github.com/facebook/metro/commit/0d6c135045a33f2b9effa8ca31b648e6b29ec24c
Then later, the `--nonPersistent` flag was completely removed here: …
> fix: remove the --nonPersistent bundler option

- packages/xdl/src/Project.ts
As of React Native 0.61.x, Metro prints console logs from the
device to console.
Managed apps have a separate remote logging implementation
included in the Expo SDK, so we can just ignore these logs
(otherwise they would be printed twice).
Currently this has to be done by looking for log lines that
look like device logs, i.e. they start with " LOG ", " WARN "
or similar. This is less than ideal, but I plan submit a PR to
Metro to make it use the custom log reporter (if configured)
for these logs so LogReporter is able to filter what gets
printed to the console.
Additionally, the AppRegistry logging was changed recently
(https://github.com/facebook/react-native/commit/1f25d3c4ce605fc3bd2a4deefc754bd07cfbf1cf),
so the code detecting these logs had to be changed as well.
> fix: device logging with React Native v0.61.x

- packages/xdl/src/Project.ts
These warnings get printed with React Native 0.61.
They are not relevant when developing managed apps, so we should just
remove them.
> fix(xdl): filter out "deprecated rnpm config" warnings

- packages/webpack-config/src/types.ts
- packages/webpack-config/src/utils/paths.ts
- packages/webpack-config/src/webpack.config.ts
- packages/webpack-config/src/withWorkbox.ts
`expo customize:web` allows generating `web/register-service-worker.js` but  `webpack-config` only uses the one in web-default because the path is hardcoded.
This PR fixes this issue by using the `locations` object to like the other customizable files.
> fix(webpack-config): use custom register-service-worker.js if available

- packages/xdl/package.json
- yarn.lock
The mismatched version causes `expo build:web` to throw an error when stderr/stdout is piped or when no tty (like in a CI/CD env). See expo/expo-cli#1156
`webpack-pwa-manifest-plugin` is the other package in this repo that uses webpack 4.29.6 but that one isn't causing problems as far as I can tell.
Error can be reproduced by using current version of expo-cli (3.4.1) with its xdl version (^56.4.0) and then building with no TTY or outputs redirected, e.g. `expo build:web 2>&1 | cat`.
> fix(xdl): upgrade xdl webpack version to 4.39.0 to match webpack-config

- packages/config/src/Config.ts
- packages/config/src/Config.types.ts
- packages/config/src/__tests__/Config-test.js
- Help to ease off of using `app.json`
- Reduce the amount of web apps using expo default description
> [config] use package description for config description

- packages/xdl/src/logs/PackagerLogsStream.ts
Editing files in Fast Refresh mode resulted in progress bars that did not go away (https://github.com/expo/expo-cli/issues/1157).
For regular JS builds, Metro first fires a `bundle_build_started` event, followed by a bunch of `bundle_transform_progressed` and ends with either `bundle_build_done` or `bundle_build_failed`. Additionally, there's the `bundling_error` that fires when there are errors. We start the progress bar after `bundle_build_started`, update it after `bundle_transform_progressed` and make it go away after `bundle_build_done`/`bundle_build_failed` events. Simple enough.
When Fast Reload builds a file incrementally and makes an update to the, it turns out, there's no `bundle_build_started`, `bundle_build_done` or `bundle_build_failed` events fired. Metro just spits out some …
> fix: logging in Fast Refresh mode

- packages/xdl/src/Simulator.ts
"fix(xdl): Check if Client is installed via application directory [iOS 13/Xcode 11 compatibility] (#957)"
This reverts commit 3ea697625e760877f04e1468bac8b24f6989fee0.
> Revert back to checking if client installed in Snapshots directory

- packages/expo-cli/src/commands/init.ts
Fixes #1133 
I could only reproduce this issue in a Linux container, on MacOS it works fine. So to run it in a docker image, you can use this (or your own image ofc).
```bash
$ docker run -ti --rm -w /code/test bycedric/expo-cli \
expo init . --template blank --name test --yarn --non-interactive
```
It replaces the template specification's raw property with the prefixed name. Again, no clue why this doesn't happen on MacOS. It's probably related to [this part](https://github.com/npm/npm-package-arg/blob/latest/npa.js#L58-L63) where it also uses the raw property.
> fix(expo-cli): alias raw template spec name in init

- packages/xdl/src/UrlUtils.ts
The current behavior of `constructWebAppUrlAsync` is to always use the LAN IP, even if the user selected "Local" for the network setting (either in the UI or the option `--host localhost` was specified). This is probably not what the user expects.
Note: This is a better solution than #1190 since it fixes the issue at the source, where the URL is generated.
> Ensure webAppUrl respects network setting (LAN/Local)

- packages/expo-cli/src/commands/upgrade.ts
Fixes #1099, the part about "stopping expo service" is receiving some love and attention here #1108.
This change starts the Metro server with the `reset` flag and instantly closes it. It also adds the `nonPersistent` flag, but I think that might be getting deprecated now. Doing this _should_ be sufficient, the [Metro Server is resetting the cache within the server's constructor](https://github.com/facebook/metro/blob/master/packages/metro/src/Server.js#L109-L114).
It might be better if we wait until PR #1111 is merged before merging this one. I didn't check if Expo is running and sort-of assumed it isn't. The prompt asking the user about running servers is still in PR review in PR #1111. (My semi-OCD is so happy I got PR #1111).
> fix(expo-cli): clear metro cache after upgrade

- packages/config/src/Config.ts
- packages/webpack-config/web-default/index.html
- Make `<body />` dark-mode compliant by default. Prevent white flashing when the rest of the app is dark-mode compliant.
- Enable full-screen iOS PWAs by default.
> Improve iOS PWA defaults

- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/Detach.js
- packages/xdl/src/detach/IosWorkspace.js
Fixes a couple of small issues with XDL/detaching that I found while testing yesterday:
- If you try to detach & provide a local EXPO_VIEW_DIR but the SDK version does not exist on the server, it errors with `Could not read property `packagesToInstallWhenEjecting` of undefined`. This should work, so I changed this code to handle the case where the SDK version config is undefined.
- When detaching, the Android shell app modifier uses the local manifest, except for the `android.config` field for which it uses the published manifest. This was probably an oversight. Fixed this to use the local manifest for everything, in order to be consistent.
Note to self: rebase & merge without squashing
> [xdl][detach] fix a couple of local detach issues

- packages/expo-cli/src/commands/eject/Eject.ts
`expo eject` was failing with the following error:
```
Dependency for key `expo` should be a `string`, instead got: `{ expo: [object Object] }`
```
because the code tested `if (typeof value === 'string')` where `value` was the dependencies object such as `{"expo":"^35.0.0","react":"16.8.3","react-dom":"16.8.3","react-native":"0.59.10","react-native-gesture-handler":"~1.4.1","react-native-reanimated":"~1.3.0","react-native-screens":"1.0.0-alpha.23","react-native-unimodules":"0.6.0","react-native-web":"^0.11.7"}`.
> fix: eject failing to validate dependencies

- packages/dev-tools/components/IndexPageErrors.js
- packages/dev-tools/pages/index.js
why
===
Previously, when the root GraphQL query resulted in an error, the resulting interface in dev-tools would be a blank black page (null component). 
how
===
This PR adds a new component to handle that case which displays errors in a more informative way to users (the same way the CLI does in the shell).
test plan
===
1. Create blank test expo project via `expo init`
1. `cd` into `dev-tools` directory within this repo in a new terminal tab.
1. `yarn run dev <path-to-expo-project>`
1. Change the `expo` key to `blah` in `app.json` within the expo project.
1. See that the errors are displayed to the user rather than a blank page.
Also test the production build:
1. In this repo, `yarn start`
1. In expo project from above, run `<path-to-expo-cli-repo>/packages/expo-cli/bin/expo.js start` …
> [dev-tools] Add informative error page when root GQL query fails

- packages/dev-tools/server/graphql/GraphQLSchema.js
why
===
Two issues:
- `project.projectRoot` isn't a valid property, making the call to `ProjectUtils.logError` invalid. `project.projectDir` is the closest (and only available) property.
- Calls to `readConfigJsonAsync` can throw, so a similar try/catch treatment in necessary in `processInfo` which reads the config to determine whether the web platform is supported.
how
===
change the variables and add the try catch. New behavior is to return null `webAppUrl` when config is invalid rather than throwing and returning a GQL error.
test plan
===
1. Create blank expo project
1. Inside `dev-tools` package directory, run `yarn run dev <path to blank project>`
1. Change `app.config` to be invalid. See console errors no longer contain null/undefined object exceptions.
Before: 
```
Uncaught (in …
```
> [dev-tools] Fix graphql errors when config is invalid

- packages/xdl/src/Simulator.ts
Older Xcode versions report device availability differently (see https://github.com/expo/expo-cli/issues/1225#issuecomment-554068190). This PR should address the differences by looking for `availability: '(available)'` in addition to `isAvailable: true`.
> fix: no iPhone devices available in Simulator

- packages/config/src/Modules.ts
- packages/xdl/src/Exp.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/UrlUtils.ts
- packages/xdl/src/__tests__/Exp-test.js
- packages/xdl/src/project/ProjectUtils.ts
- `determineEntryPointAsync` -> `determineEntryPoint`
- `determineEntryPoint` now uses `getEntryPoint` without platforms
- remove unused methods
> [xdl][config] Updated entry point to reuse Webpack entry resolver

- packages/expo-cli/src/commands/upload/BaseUploader.ts
- packages/xdl/src/StandaloneBuild.ts
Docs stated that the owner id would be respected (and is respected on build) but they are currently not being accounted for when searching for built apps
This PR was created to pass the owner name from the app.json context within the files through to the API request to be handled there.
Currently, when uploading an app that belongs to another team you'll be prompted with:
``` 
Failed to upload the standalone app to the app store.
There are no builds on the Expo servers, please run 'expo build:ios' first 
```
The build ran fine with the owner name so I'm assuming some backend work still needs to be taken care of for this to take effect.
> fix: pass owner name into API request

- packages/xdl/src/Exp.ts
Exp.determineEntryPoint needs to return a relative path, because it's
passed to UrlUtils.guessMainModulePath, which expects a path relative
to the project root. This path is used in the bundle URL, assets URLs
and source map URLs.
> fix(xdl): fix Exp.determineEntryPoint regression

- packages/xdl/src/Project.ts
Expo CLI has been passing the `--assetExts` setting to React Native CLI
and Metro, with the default value `ttf`. The consequence of this was
that any `assetExts` value set in `metro.config.js` was overwritten by
the command-line option set by Expo CLI.
It turns out that for a long time now, Metro has included `ttf` in
`assetExts` *by default*. Therefore we can just stop passing it
without changing the default setting and now the configuration
defined in `metro.config.js` will work again.
> fix: stop overriding assetExts

- packages/dev-tools/components/ProjectManagerSidebarOptions.js
Recently while using expo I asked myself why copy to clipboard on project link is not implemented.
Actually it was implemented, but there was no feedback to the user, so I decided to add it.
> feat(dev-tools): copy url to clipboard feedback

- packages/webpack-config/src/webpack.config.ts
- packages/webpack-pwa-manifest-plugin/src/WebpackPWAManifestPlugin.ts
- packages/webpack-pwa-manifest-plugin/src/WebpackPWAManifestPlugin.types.ts
- packages/webpack-pwa-manifest-plugin/src/__tests__/icons-test.js
- packages/webpack-pwa-manifest-plugin/src/icons.ts
- packages/webpack-pwa-manifest-plugin/src/injector.ts
- Reduces build time by a lot 
- on a basic project:
- before: 
- first build: `0m22.948s`
- rebuild: `0m15.136s`
- after:
- first build: `0m22.948s`
- rebuild: `0m8.499s`
- rebuild with new splash screen: `0m14.196s`
- Step 1 in removing sharp
- Cache images based on hash and custom props like resizeMode and color
- Removes old caches after build
> [webpack-pwa-manifest-plugin] cache images for rebuilds

- packages/xdl/package.json
- packages/xdl/src/Project.ts
- packages/xdl/src/reporter/index.ts
- yarn.lock
Not sure why half of the log reporter was included in the expo package and the other half is in XDL. Moving this will help simplify the `expo/metro-config` package I'm working on.
- `expod start --ios`
- test that `console.logs` show in the terminal
- test that `console.logs` show in the dev tools screen under the device
- ensure Metro custom logging looks like before (loading bar)
> [metro][xdl] Move custom log reporter to XDL

- packages/webpack-config/web-default/expo-service-worker.js
It's not safe to assume that event.data is a string, and it's certainly not safe to assume it's valid JSON (for example, I noticed this when implementing Google Signin using Firebase; see screenshots below).
This PR makes it so that we check that it is a string and wrap the JSON.parse in a try/catch in case it's not JSON at all, but just some arbitrary string message sent by a library on the page.
Screenshots from some example exceptions caused by this issue:
> [Web] Service Worker: Conditionally parse event.data as JSON

- packages/webpack-config/src/addons/__tests__/withEntry-test.js
- packages/webpack-config/src/addons/index.ts
- packages/webpack-config/src/addons/withEntry.ts
- packages/webpack-config/src/addons/withUnimodules.ts
- packages/webpack-config/src/webpack.config.ts
- packages/webpack-config/tests/__tests__/basic-test.js
- packages/webpack-config/tests/basic/App.js
- packages/webpack-config/tests/basic/package.json
- packages/webpack-config/tests/basic/yarn.lock
fix #1198 
If the project has `resize-observer-polyfill` installed, then `@expo/webpack-config` will automatically include it as a global polyfill.
> [webpack-config] Add ability to optionally include resize-observer-polyfill

- packages/xdl/src/detach/Detach.js
Right now it's not possible to run `expo eject` if ExpoKit for one of the platforms is not released yet. It would be more convenient to allow such thing as sometimes the release process of these two platforms is at different stages.
Made small changes in a few conditions.
Tested by running `EXPO_STAGING=1 expo eject` on SDK36 project while only iOS ExpoKit is released.
> feat(xdl): Allow ejecting just one platform if the other one is not released yet

- package.json
- yarn.lock
why
===
As mentioned by @brentvatne in #1239 we should run prettier on precommit for both TypeScript and JS files.
how
===
To accomplish this, the eslint config must specify that the typescript parser is used for typescript files. The `eslint-config-universe` config (updated version) specifies this.
test plan
===
Add  a lint error to a `.ts` file, amend this commit, see that the lint error is fixed automatically.
discussion
===
Note that there are a lot of prettier discrepancies in this repo in TypeScript files, so it may be a good idea to just run a prettier fix commit alongside this commit so that a slew of future commits don't include automatic prettier changes as well.
> [expo-cli] Run prettier on TypeScript in precommit hook

- packages/expo-cli/src/commands/build/BaseBuilder.js
- packages/xdl/src/Project.ts
The no-publish option on build commands is not being respected currently when looking up the most recent release
> fix: Respect owner field in build commands with --no-publish option

- packages/expo-cli/package.json
- packages/expo-cli/src/PackageManager.ts
- packages/expo-cli/src/commands/eject.ts
- packages/expo-cli/src/commands/eject/Eject.ts
- packages/expo-cli/src/commands/install.ts
- packages/expo-cli/tsconfig.json
- packages/package-manager/src/PackageManager.ts
- yarn.lock
why
===
Relatively easy to convert, so why not.
how
===
Rename the `eject` and `install` commands to `.ts` and run typechecker on them.
test plan
======
In local sample project, run the following to test the commands, ensure they behave normally:
`~/expo/expo-cli/packages/expo-cli/bin/expo.js install await-lock`
`~/expo/expo-cli/packages/expo-cli/bin/expo.js eject`
> Refactor: convert some Expo CLI commands to TypeScript

- packages/expo-cli/src/commands/build/BaseBuilder.js
This should fix #1251, making the warning log only (non-blocking) as Brent mentioned:
> yeah i think these are good enough reasons to make this a non-blocking warning for now, thanks for getting back to me
~~It's also related to #1224, but I'll open another PR to add the `--force` flag Ville mentioned.~~
I also created PR #1273 to fix this exact issue. But instead of removing the question, I've added a `--force` flag. Maybe we can integrate it even better, making it a bit nicer if we encounter similar problems again. 😄
> fix(expo-cli): make reuse build log only instead of blocking

- packages/webpack-config/src/addons/withWorkbox.ts
- packages/webpack-config/src/index.ts
- packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
fix https://github.com/expo/expo-cli/issues/1330
- deploying to GH Pages should install the SW correctly https://evanbacon.github.io/expo-web-sdk-36-gh-pages-test/
- favicon should be found
> [webpack-config] Fix public path for service workers and favicon

- packages/xdl/src/detach/AndroidShellApp.js
When building Android app bundles with turtle-cli and SDK 36, both locally and in cloud, the build fails with.
> Error: ENOENT: no such file or directory, lstat '/app/turtle/workingdir/android/sdk36/android-shell-app/app/build/outputs/bundle/release/app.aab'
The problem is that the app bundle is saved as 
> /app/turtle/workingdir/android/sdk36/android-shell app/app/build/outputs/bundle/release/app-release.aab
This pull request fixes the issue.
The fix has been tested by modifying `node_modules/turtle-cli/node_modules/@expo/xdl/build/detach/AndroidShellApp.js` locally.
See https://forums.expo.io/t/android-build-fail-with-sdk36/30980/3?u=hilmarh for more information.
> [xdl] Android app-bundle builds failing with SDK 36

- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/IosNSBundle.ts
Buildtime customizations introduced in 70af3e83.
https://github.com/expo/expo-cli/commit/70af3e83628ed51d665331264f7230c1f0f22144
Fixes issue described in https://github.com/expo/expo/pull/5924#issuecomment-562125716.
> [xdl] Fix Facebook buildtime customizations being applied to apps < SDK36

- packages/expo-cli/package.json
- packages/expo-cli/src/commands/upload.js
- packages/expo-cli/src/commands/upload/IOSUploader.ts
- packages/expo-cli/src/commands/upload/utils.ts
- packages/traveling-fastlane/Rakefile
- packages/traveling-fastlane/actions/pilot_upload.rb
- packages/traveling-fastlane/actions/resolve_itc_team_id.rb
- packages/traveling-fastlane/publishing/darwin/index.js
- packages/traveling-fastlane/publishing/darwin/package.json
- packages/traveling-fastlane/publishing/linux/index.js
- packages/traveling-fastlane/publishing/linux/package.json
- packages/traveling-fastlane/wrappers/resolve_itc_team_id_wrapper.sh
- yarn.lock
**Why?** Fixes #971 
**How?** A user doesn't have to pass the ITC team id by himself. We can deduce the id on our own by matching the team names from Apple Developer Portal and iTunes Connect.
I deprecated the `--itc-team-id` option for `expo upload:ios`. Passing this option doesn't have any effect from now.
> [expo-cli] upload:ios - auto resolve itc team id

- packages/webpack-config/src/addons/withWorkbox.ts
- packages/webpack-pwa-manifest-plugin/src/icons.ts
- fix #1161 
- https://stackoverflow.com/questions/58612850/buildweb-fails-inside-npm-script-with-typescript
- https://github.com/tiepp/expo-cli-local-ts
- convert reading methods to sync
- add warnings when things work unexpectedly
- I couldn't repro the issue so this is based on the feedback provided by @brookemitchell and @rickysullivan
- Added bail-out cases to prevent halting development if the problem persists in the future.
> Fix workbox and icon cache bugs

- packages/xdl/src/Api.ts
- packages/xdl/src/ApiV2.ts
- packages/xdl/src/Project.ts
Following @ide's advice, added a EXPO_LEGACY_API variable that we can tell people to set to true while a fix is deployed.
(the server side APIv2 is being reviewed here: https://github.com/expo/universe/pull/3938)
>   Convert publish endpoint to apiV2

- packages/xdl/src/detach/IosCodeSigning.js
This will fix https://github.com/expo/turtle/issues/168 once `@expo/xdl` is updated in turtle.
> [xdl] allow building ios apps with wildcard provisioning profiles

- packages/xdl/CHANGELOG.md
- packages/xdl/src/detach/AndroidShellApp.js
It was recently added in https://github.com/expo/expo-cli/commit/70af3e83628ed51d665331264f7230c1f0f22144 and isn't needed (no [Facebook setup instruction](https://developers.facebook.com/docs/facebook-login/android?sdk=maven) mentions it should be added. Instead, developers are expected to add fully qualified name of the activity in Facebook developers console — see https://github.com/expo/expo/pull/6453).
> [xdl] Do not add fbScheme to MainActivity's intent-filter

- packages/expo-cli/package.json
- yarn.lock
The new version doesn't have `envsub` in the dependencies anymore. `envsub` has been replaced with `@expo/template-file`.
> [expo-cli] upgrade @expo/build-tools to 0.1.3

- packages/expo-cli/src/commands/build/BaseBuilder.js
- packages/expo-cli/src/commands/publish.js
- packages/expo-cli/src/commands/url.ts
- packages/xdl/src/Project.ts
migrating off of apiv1. cli should still call apiv1 build by default, but can opt into apiv2 build.
refactored `Project.buildAsync` into `Project.buildStatusAsync` and `Project.startBuildAsync`.
Set `EXPO_NEXT_API=true` and test against https://github.com/expo/universe/pull/3967
> @jkhales/add apiv2 option build

- packages/expo-cli/src/commands/publish-info.js
This avoids a user having to run `expo publish:details --help` to confirm the correct syntax to enter the `publishId` variable.
> improve error message

- packages/expo-cli/src/commands/publish-info.js
To test locally, checkout this universe branch: @jkhales/move-publishInfo-to-apiV2 
(Also, probably should wait for the above branch to be finished before merging this one)
> add option to call publish:history with apiv2

- packages/expo-cli/src/commands/build/BaseBuilder.js
- packages/expo-cli/src/commands/utils/url.ts
We shouldn't continue to reference the legacy /builds page now that the dashboard builds page has been out for a while and has proven to be stable.
I updated the build page url generator function to return a dashboard link if a username is passed in. The output looks like what is shown below:
---
Thanks for checking this out!
> [expo-cli] direct users to dashboard builds page

- packages/dev-tools/server/DevToolsServer.js
As it was reported and discussed in #1081, recent changes break compatibility with Docker.
Adds one new environment variable, `EXPO_DEVTOOLS_LISTEN_ADDRESS` that can be used to give different ip where devtools bind. If no environment variable is given, defaults to `localhost`, which is currently hardcoded value in codebase.
This fix takes use of already used environment variable `REACT_NATIVE_PACKAGER_HOSTNAME`, as it is already needed when using `expo-cli` in Docker container.
- Run expo-cli as usual in normal environment, and check that port 19002 listens only 127.0.0.1
- Run expo-cli with `EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0 expo-cli start` and check that port 19002 listens all interfaces
Fixes #1081
> [dev-tools] Option to choose devtools bind address

- packages/expo-cli/src/commands/client/index.js
- packages/expo-cli/src/commands/utils/ClientUpgradeUtils.ts
This is a refactor for the `expo client:install:{android|ios}` command. Should make it way more readable and separates some functionality for reuse in both install commands. Right now, I only refactored the simulator (ios) version. Mainly to check if I'm doing the right things here.
- No more hard-to-read stacked `if ... else if` statements
- Gone with some duplicate code, like getting a list of available clients from sdk versions
- Bye to excessive fallback-values for possibly undefined properties
- Added a "recommended" flag, next to "latest", to point developers to the most probable-to-work version. This was one of the nested if-else-if logic, by moving it here we make it easier for us and the developer I think. But I'm not sure if the "recommended" text is the best one, its based on …
> refactor(expo-cli): break functionality in client install for reusabilty

- packages/expo-cli/src/commands/fetch/android.js
- packages/xdl/src/credentials/AndroidCredentials.ts
This bit me when trying to include a google maps api key that was restricted to our app hash. While this notice already shows in the `--help` for this command, it would be useful to show it when running the command directly to avoid confusion.
> Show NOTE when running fetch:android:hashes

- packages/expo-cli/src/exp.ts
why
===
Manual argument parsing (parsing outside of the `commander` framework) is tough to get right as the ordering of arguments and options and commands isn't well-defined (purposeful, best practice for a CLI). In the CLI, the following code is used to accomplish this:
```
let subCommand = process.argv[2];
```
Unfortunately, this results in a bug when the third arg is not the sub command. For example,
```
> expo --non-interactive whoami
[14:53:07] "--non-interactive" is not an expo command. See "expo --help" for the full list of commands.
[14:53:08] Logged in as wschurman
```
The instructions in the help page instruct the user to place global options before the subcommand, so the bug occurs in the recommended format:
```
> expo
Usage: expo [options] [command]
Options:
-V, --version …
```
> [expo-cli] Remove manual CLI parsing

- packages/next-adapter/document.js
For some reason the column direction is row by default in chrome when using Next.js. Fix this by ensuring the style is forced to column to match `react-native` and default expo for web functionality.
> [next-adapter] fix column style

- packages/config/src/Web.ts
if `webManifest.preferRelatedApplications` sets to `false`, `preferRelatedApplications` should be `false` instead of `true`
> FIX: allow `preferRelatedApplications` value to be false

- packages/expo-cli/src/commands/start.js
- packages/expo-cli/src/urlOpts.ts
fixes https://github.com/expo/expo-cli/issues/1307
moved `setIsOffline` logic to urlOpts, so that it's also used by the other `allowOffline` commands (`ios`, `android`, and `send`)
I'm not sure what the use case of it would be, but seemed right to still allow people to use another host type if they want to
> fix: offline mode should default to localhost

- packages/expo-cli/src/commands/publish-info.ts
This fixes #1384 and rewrites the `publish:history` and `publish:details` commands to typescript.
<details>
<summary>UTC timezone</summary>
</details>
<details>
<summary>Amsterdam timezone</summary>
</details>
> refactor(expo-cli): localize publication dates in publish history

- packages/next-adapter/src/customize/manifest.ts
When running `yarn next-expo` a build script will be added to your `package.json` for deployment continuity.
> [next-adapter] added build script to required customizations

- packages/expo-cli/src/commands/build/BaseBuilder.js
I increased the build wait timeout to 3600 sec (1 hour).
Related forums thread: https://forums.expo.io/t/expo-build-timeout/28887/4
> [expo-cli] increase build wait timeout

- packages/xdl/src/Android.ts
- packages/xdl/src/Api.ts
- packages/xdl/src/Simulator.ts
Adds the workaround [described by Brent here](https://github.com/expo/expo-cli/issues/985#issuecomment-562909709).
- I have no clue if the current "30 seconds"-timeout is correct. Are there any metrics available on average install time? Or does anyone knows a better threshold?
- Alternative option was to use a non-awaiting `delayAsync`. But there is no cancel feature in js promises. Using timeouts works around that. If an exception is thrown, the timeout is also not triggered because the code is exiting.
> fix(xdl): add warning when install expo is taking longer than expected

- packages/expo-cli/src/credentials/views/IosDistCert.ts
Fixes some issues that I missed in https://github.com/expo/expo-cli/pull/1381
- fixes logging: `chalk.yellow` -> `log(chalk.yellow...)`
- Autoselect certificates, prioritizing certificates whose expiry date is latest.
> refactor(cli) update dist cert autoselect

- packages/expo-cli/src/credentials/api.ts
- packages/expo-cli/src/credentials/views/IosPushCredentials.ts
- packages/expo-cli/src/credentials/views/Select.ts
- packages/expo-cli/src/credentials/views/SetupIosPush.ts
The iOS Push Key version of https://github.com/expo/expo-cli/pull/1381
> refactor(cli) create ios push key selector

- packages/webpack-config/src/webpack.config.ts
Seems like this causes a lot of mismatch between Metro config and Webpack config. This also throws an incorrect error pointing to the `src/` folder which is something we don't enforce. 
We can investigate adding a solution like this back in the future.
> [webpack] Remove ModuleScopePlugin

- packages/babel-preset-cli/ts-declarations/pnp-webpack-plugin/index.d.ts
- packages/webpack-config/package.json
- packages/webpack-config/src/addons/index.ts
- packages/webpack-config/src/addons/withTypeScriptAsync.ts
- packages/webpack-config/src/webpack.config.ts
- yarn.lock
- Ensure TS checker is added when tsconfig is present. 
- Remove support for TS extensions when a tsconfig isn't present -- this will help debugging TypeScript setup.
> Added proper TypeScript support for Webpack Config

- packages/traveling-fastlane/Rakefile
Traveling ruby is a self-contained ruby with no dependencies. This means they also bundle their own ca certs. Unfortunately many of these certs are expired, causing https://github.com/expo/expo-cli/issues/1436
- we trust Mozilla and cURL
- Mozilla has public Certificate Authorities (CA) available in its source tree: https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt
- cURL parses this certdata.txt and extracts CA Root Certificates into PEM format, and makes it publicly available on their website
- Every time we release traveling fastlane, we replace `traveling-ruby`'s expired ca bundle with cURL's most up to date bundle.
```
$ openssl x509 -enddate -noout -in ca-bundle.crt 
notAfter=Jan 28 12:00:00 2028 GMT
```
> fix(traveling-fastlane) cURL cURL's pem

- packages/webpack-config/src/webpack.config.ts
Metro bundler will allow TypeScript in projects without a `tsconfig.json` so we should disable how other bundlers handle TS to account for this.
> Revert typescript to match Metro functionality

- packages/expo-cli/bin/expo.js
- packages/expo-codemod/bin/expo-codemod.js
Expo CLI supports Node.js current and LTS versions.
Node 8 reached end of life on December 31st 2019, so it is no longer supported.
> BREAKING CHANGE: drop Node.js 8 support

- packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
Currently, all environment variables containing EXPO are exposed. However, if you are using a CI you might have some secrets and passwords defined that shouldn't be part of the build. This PR removes these environment variables explicitly.
> fix(webpack-config): prevent secrets from being exposed

- packages/expo-cli/src/appleApi/authenticate.ts
- packages/expo-cli/src/commands/upload/IOSUploader.ts
Should fix https://github.com/expo/expo-cli/issues/1458
When a user uploaded app credentials on his own, we don't have his `appleId` stored in the database. I made a change so that when we detect this state we ask the user to select the proper team prior to uploading the app binary to App Store.
> [expo-cli] fix an issue when team id is undefined

- packages/webpack-config/package.json
- packages/webpack-config/src/loaders/createAllLoaders.ts
- packages/webpack-config/src/loaders/createWorkerLoader.ts
- packages/webpack-config/src/loaders/index.ts
- packages/webpack-config/src/webpack.config.ts
- yarn.lock
Add support for workers now that we want to use workers in `expo-camera` https://github.com/expo/expo/pull/4166
Any file with the `.worker.js`, `.worker.ts`, `.worker.mjs` extension will be treated as a worker.
> [webpack-config] Add support for web workers by default

- packages/xdl/README.md
- packages/xdl/src/Webpack.ts
https://github.com/react-navigation/react-navigation/issues/6563
- Disable throwing warnings as errors in CI by default
- Add `EXPO_WEB_BUILD_STRICT` env variable to enable throwing warnings as errors in CI. 
- I'm somewhat reluctant to disable treating warnings as errors to circumvent meaningful error messages.
> Add EXPO_WEB_BUILD_STRICT to enable warnings as errors in CI

- packages/webpack-config/src/addons/withWorkbox.ts
Currently, no service worker is registered at all in development which makes it difficult to test service worker related functionality. This PR will always register the `expo-service-worker` but will still avoid Workbox in development.
> fix(webpack-config): register general service worker in development

- packages/expo-cli/src/credentials/api.ts
- packages/expo-cli/src/credentials/views/SetupIosPush.ts
skip setting up apns if users already have the deprecated push certs and dont want to upgrade
> refactor(cli) check for deprecated push certs

- .circleci/config.yml
- packages/expo-cli/e2e/__tests__/init-test.ts
- packages/expo-cli/e2e/__tests__/start-test.ts
- packages/expo-cli/src/commands/init.ts
- Remove the inane `Use Yarn to install dependencies?` prompt: we now just print `Using Yarn to install packages. You can pass --npm to use npm instead.`
- Remove the complex `enquirer` app.json snippet prompt and only ask for project name and template.
* `expo init` asks for a template and project name/folder
* `expo init MyApp` only asks for a template
* `expo init MyApp -t bare-minimum` doesn't ask any questions
* `expo init --yes` (alias for `expo init . -t blank` (@EvanBacon's idea from #1044) also doesn't ask anything
Fixes https://github.com/expo/expo-cli/issues/1240.
> feat(expo-cli): make init simpler

- packages/webpack-config/src/loaders/createBabelLoader.ts
- fixes critical error preventing `file.expo.js` files from being transpiled properly.
fix #1477
> Fix workflow extension support in webpack config

- packages/config/src/Config.types.ts
- packages/config/src/Web.ts
- packages/webpack-config/src/env/__tests__/__snapshots__/getConfig-test.js.snap
- packages/webpack-config/tests/basic/package.json
- packages/webpack-config/tests/nextjs/package.json
- packages/webpack-pwa-manifest-plugin/src/__tests__/__snapshots__/config-test.js.snap
fix #1171 
- color and description aren't needed to make a PWA run
- name will be validated elsewhere
> Remove default description, name, and primary color from web config

- packages/dev-tools/common/state.js
- packages/dev-tools/components/ProjectManager.js
- packages/dev-tools/components/ProjectManagerSidebarOptions.js
- packages/dev-tools/components/QRCode.js
- packages/dev-tools/pages/index.js
- packages/dev-tools/server/graphql/GraphQLSchema.js
- packages/expo-cli/src/commands/start/TerminalUI.js
Now that web support is [approaching V1](https://github.com/expo/expo/issues/6782), we should make it always visible in the dev tools.
- add web to the Terminal UI all the time
- add ability to start Webpack from dev-tools page
> Always show web in dev tools

- packages/webpack-config/README.md
- packages/webpack-config/src/addons/withUnimodules.ts
- packages/webpack-config/src/loaders/__tests__/createBabelLoader-test.js
- packages/webpack-config/src/loaders/createAllLoaders.ts
- packages/webpack-config/src/loaders/createBabelLoader.ts
- packages/webpack-config/src/loaders/index.ts
- packages/webpack-config/src/types.ts
- packages/webpack-config/src/utils/__tests__/search-test.js
- packages/webpack-config/src/utils/search.ts
- packages/webpack-config/src/webpack.config.ts
A highly requested feature for including modules in a better way than through the `app.json`.
> Add ability to include modules to the babel loader

- packages/dev-tools/server/asynciterators/mergeAsyncIterators.js
- packages/dev-tools/server/graphql/GraphQLSchema.js
Fix a memory leak resulting in warnings like this to be generated by Node:
```
(node:14054) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ADDED listeners added to [Issues]. Use emitter.setMaxListeners() to increase limit
(node:14054) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 UPDATED listeners added to [Issues]. Use emitter.setMaxListeners() to increase limit
(node:14054) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 DELETED listeners added to [Issues]. Use emitter.setMaxListeners() to increase limit
```
To reproduce the bug I refreshed the browser tab with Dev Tools in it 10+ times. After this, the  warning shown above was printed in the terminal.
The underlying cause was that each time the …
> fix(dev-tools): fix an EventEmitter memory leak

- packages/xdl/src/Project.ts
`expod ph` was broken:
Seems like `option.mode` was used before...  `mode` is defined by destructing now.
> fix typo options.mode -> mode

- packages/expo-cli/src/commands/publish-info.ts
- packages/expo-cli/src/commands/publish.js
Checked commands:
```
export EXPO_LOCAL=1
expod p
EXPO_LEGACY_API=true expod p
expod ph
EXPO_LEGACY_API=true expod ph
expod pd
EXPO_LEGACY_API=true expod pd
```
Work and call the appropriate endpoints.
> migrate publish commands to default to api v2

- .eslintrc.js
- packages/config/tsconfig.json
- packages/expo-cli/gulpfile.js
- packages/expo-cli/src/commands/eject/Eject.ts
- packages/expo-cli/src/commands/eject/__tests__/Eject-test.ts
- packages/expo-cli/tsconfig.json
- packages/xdl/gulp/build-tasks.js
- packages/xdl/tsconfig.json
- Added the ability to create TS unit tests in the src next to the files they test without copying the tests or mocks into the generated build folder.
- Applied this to both of the packages with incomplete TypeScript (expo-cli and xdl).
- Created a basic test for the Eject command utils.
- test runs in `test-expo-cli`
> [expo-cli] Updated unit test setup

- packages/webpack-config/README.md
- packages/webpack-config/src/env/validate.ts
- packages/webpack-config/src/index.ts
- packages/webpack-config/src/loaders/createAllLoaders.ts
- packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
- packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
- packages/webpack-config/src/plugins/ExpoProgressBarPlugin.ts
- packages/webpack-config/src/plugins/index.ts
- packages/webpack-config/src/types.ts
- packages/webpack-config/src/webpack.config.ts
- Added ability to disable offline mode:
```js
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
module.exports = async function(env, argv) {
const config = await createExpoWebpackConfigAsync({ ...env,  offline: false }, argv);
return config;
};
```
- Updated docs
> [webpack-config] Add prop to disable offline support

- packages/webpack-config/src/webpack.config.ts
Currently, even the compressed versions of all files are included in the manifest which causes the files to be downloaded twice by the service worker. This fix will remove them from the manifest.
> fix(webpack-config): remove compressed versions from manifest

- packages/xdl/package.json
- packages/xdl/src/Config.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/Versions.ts
- yarn.lock
- _getExpAsync(): use slugify to transform config name from ThirdParty module
- Update types
- Remove unused variables
- Add support for app.config.js when starting a project on any platform
- Add support for app.config.js when getting build status, and starting a build.
- I guess you can make config changes then refresh the client (⌘R) to see them.
This effects:
- `expo start`
- `expo start:web`
- `expo publish`
- `expo url`
Each should be run with an `app.config.js` and `app.json`.
`app.json`
```json5
{
"expo": {
"version": "1.0.0"
// ...
}
}
```
`app.config.js`
```js
module.exports = function({ config, mode }) {
return {
...config,
name: "My Project - " + mode
}
}
```
`App.js`
```js
import React from 'react';
import { Text } from 'react-native';
import Constants from 'expo-constants'; …
```
> [xdl][Project] Support app.config.js

- packages/config/src/Config.types.ts
- packages/config/src/Web.ts
This PR add support for putting the firebase web configuration in `app.json`. This is uses for auto-configuration of firebase on Web and to make Firebase Analytics possible on the standard Expo Client, through a pure JS Firebase Analytics tracker which requires the web-config `measurementId`.
> [expo-cli]  Add firebase web-config support

- packages/expo-cli/src/commands/fetch/android.ts
Using the `expo fetch:android:*` commands, users can overwrite previously downloaded keystores, so we should prompt them to rename the new file, or confirm the overwrite
Defaults to overwrite in `non-interactive` mode
> fix: prompt before overwriting credential files

- packages/config/src/Config.ts
- packages/expo-cli/__mocks__/fs.js
- packages/expo-cli/__mocks__/resolve-from.js
- packages/expo-cli/package.json
- packages/expo-cli/src/commands/__tests__/upgrade-test.ts
- packages/expo-cli/src/commands/upgrade.ts
- packages/expo-cli/src/prompt.ts
- Add unit tests to `expo upgrade` command
- Add support for nonInteractive mode in upgrade command
- Fix bug where raw config was being mutated
- Change config writing in upgrade command to only run when the `app.json` is present
> [expo-cli] Refactor and test the upgrade command

- packages/xdl/package.json
`package-manager` is referenced in `xdl` here:
https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Exp.ts#L14
> Adds missing dependency on package-manager

- packages/babel-preset-cli/ts-declarations/pacote/index.d.ts
- packages/expo-cli/package.json
- packages/xdl/package.json
- packages/xdl/src/Exp.ts
- yarn.lock
Pacote has unlisted dependencies that I'll fix as part of https://github.com/npm/pacote/pull/32. This diff upgrades to `^11.1.0` so that Expo can benefit from the fixes as soon as they land.
> Upgrades pacote

- packages/config/src/Web.ts
- packages/config/src/paths/__tests__/paths-test.js
- packages/config/src/paths/paths.ts
- migrate paths to support `app.config.js`
- moved from #1581
> [config][paths] add mode to paths methods

- packages/expo-cli/src/commands/start.ts
- packages/xdl/src/Project.ts
> [expo-cli] Migrate start command to TypeScript

- packages/expo-cli/babel.config.js
- packages/expo-cli/package.json
- packages/webpack-config/babel.config.js
- packages/webpack-config/package.json
- Moved from #1614
- Flow still exists in `expo-codemod->jscodeshift`
```sh
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@babel/preset-flow@7.7.4"
info Reasons this module exists
- "_project_#expo-codemod#jscodeshift" depends on it
- Hoisted from "_project_#expo-codemod#jscodeshift#@babel#preset-flow"
info Disk size without dependencies: "20KB"
info Disk size with unique dependencies: "68KB"
info Disk size with transitive dependencies: "88KB"
info Number of shared dependencies: 2
✨  Done in 1.63s.
```
> Remove preset-flow from expo-cli

- packages/config/jest.config.js
- packages/expo-cli/gulpfile.js
- packages/expo-cli/src/commands/diagnostics.ts
- packages/expo-cli/src/exp.ts
- packages/expo-cli/src/update.ts
- packages/expo-codemod/jest.config.js
- packages/expo-optimize/src/index.ts
- packages/expo-optimize/src/update.ts
- packages/image-utils/src/sharp.ts
- packages/json-file/jest.config.js
- packages/package-manager/jest.config.js
- packages/schemer/jest.config.js
- packages/webpack-config/jest/unit-test-config.js
- packages/webpack-pwa-manifest-plugin/jest.config.js
- packages/xdl/gulp/build-tasks.js
- packages/xdl/jest/unit-test-config.js
- packages/xdl/src/Project.ts
- packages/xdl/src/__tests__/tools/FsCache-test.js
TypeScript will attempt to bundle the `package.json` when it's imported relatively which breaks the bundle. This approach prevents that.
- Moved from #1614
> Migrate all imports of package.json to use node resolution

- packages/xdl/src/Android.ts
New users mostly don't know how to open an Emulator without opening Android Studio. Opening Android Studio can immediately kill your vibe so we should minimize reasons to do that.
Also `expo start --android` should work the same as `expo start --ios`.
- `expo start --android` should open an emulator is no device is connected, then install the expo client and open the project.
> [xdl] Automatically start an emulator when no android device is connected

- packages/expo-cli/src/urlOpts.ts
Running `expo start --ios --android --web` opens all platforms at the same time.
> [expo-cli] Start all platforms at the same time

- packages/webpack-config/withUnimodules.js
Currently it's been deprecated for four months in beta.
> [webpack-config] Delete deprecated withUnimodules import

- packages/webpack-config/src/addons/withCompression.ts
- packages/webpack-config/src/addons/withWorkbox.ts
When rebuilding your project `register-service-worker.js` was created before the clean plugin deleted the web-build folder. This lead to issues where the `web-build/register-service-worker.js` was not included. 
- Target compression to the static folder
- fixes issue created in https://github.com/expo/expo-cli/pull/1457
> [webpack-config] Fix register service worker

- packages/expo-cli/src/commands/build/BaseBuilder.ts
This should prevent from emerging issues like this - https://github.com/expo/expo-cli/issues/1638
I think there's no reason for this timeout to exist. If someone wanted to exit this command before the build succeeds he could do that with `CTRL+C`.
I also changed a little misinformative message about pressing `CTRL+C`. Some people using `expo build` think that exiting from that command cancels the build but it's not true. The build stays in the queue but it either requires checking the status with `expo build:status` or visiting the build logs page.
> [expo-cli] get rid of the build timeout

- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
make cli prompt more clear - original question can be kind of confusing because it implies that an app with the bundle id already exists on the store.
> [cli] better worded prompt

- packages/webpack-config/src/addons/withWorkbox.ts
- yarn.lock
fix #1600 workbox was including compressed files, we now ignore all `.js.gz` files. This could become a problem if in the future we support adding static compressed files (not sure why we would).
> [webpack-config] Exclude compressed files from the precached manifest

- packages/expo-cli/src/appleApi/authenticate.ts
- change authentication logging from a spinner to a regular log - fastlane could ask for 2fa and if a spinner is going on at the same time, user input into the terminal becomes a mess
partially addresses https://github.com/expo/expo-cli/issues/1631
> [cli] fix spinner logging in auth

- packages/webpack-config/src/addons/withWorkbox.ts
- packages/webpack-config/tests/__tests__/basic-test.js
- packages/webpack-config/tests/basic/App.js
- packages/webpack-config/tests/basic/yarn.lock
Currently there is a bug where the built webpack entry registering the service-worker won't compile correctly. This fixes that and adds a test to ensure the SW gets registered properly.
> [webpack-config] fix service worker register on initial build

- packages/expo-cli/src/commands/build/BaseBuilder.ts
- packages/expo-cli/src/commands/url.ts
Note that calls for a builds status now have their own endpoint `build/status` and that this is a `post` instead of a `put`:
https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L1533
Double checked on server side that this is what we want.
Sanity checked by running `expo build:android`. All calls going api v2 and build was successful.
> make build calls api v2 by default

- packages/expo-cli/src/credentials/actions/list.ts
- user uploaded provisioning profiles dont have ids, so when we display credentials, show `-----` (like we do with all our other uploaded creds) instead of saying `credential is missing`
> [cli] better profile logging

- packages/expo-cli/src/appleApi/provisioningProfile.ts
- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
- packages/expo-cli/src/credentials/views/SetupIosProvisioningProfile.ts
- packages/xdl/src/xdl.ts
Have better validation for provisioning profiles, especially if:
- the profile was uploaded by a user 
- there is no access to apple
> [cli] better provisioning profile validation

- packages/xdl/src/Android.ts
- packages/xdl/src/Simulator.ts
Fixes #1636
This breaks the message free from the progress bar, making it way more readable. Unfortunately, there is no `log.newLine` in the global logger, but this is the same approach to that 😄
> fix(xdl): add new lines to client install timeout messages

- packages/expo-cli/gulpfile.js
- packages/expo-cli/src/commands/diagnostics.ts
- packages/expo-cli/src/exp.ts
- packages/expo-cli/src/update.ts
- packages/expo-cli/tsconfig.json
By default, Node does not allow for a package to import itself. This might work in scenarios such as a Yarn monorepo where all linked workspaces are linked under the root directory's `node_modules` folder so searching up the directory hierarchy leads to `<root>/node_modules/<workspace>`. This breaks in reality when a package is taken outside of the monorepo. This notably happens with expo-cli since it is most likely to be installed as a top-level program and not as a dependency.
If we import package.json, TypeScript thinks the package directory is the root directory and emits `build/{package.json,src}`. We don't want that -- we want package.json to be left alone and for the compiled contents of `src` to be emitted into `build`.
Test plan: `rm -fr build tsconfig.tsbuildinfo; yarn tsc` and …
> [ts] Use require() to read package.json instead of import for TypeScript

- packages/expo-cli/src/exp.ts
The UI of the out of date message on the CLI is never properly formatted unless viewed on an huge display. This PR adds a return to make the message properly formatted on more screen sizes.
> [cli] Better formatting of update message

- packages/xdl/src/Api.ts
- packages/xdl/src/ApiV2.ts
https://github.com/expo/expo-cli/issues/1647#issuecomment-598273532
The default upload limit is 10, it was increased to 100 in api v1. This increases it in api v2 as well.
Set the limit to 1 byte to repro the error.
> Increase max upload size of apiv2 to same as in apiv1

- packages/xdl/src/credentials/Credentials.ts
- packages/xdl/src/credentials/IosCredentials.ts
This was already approved here: https://github.com/expo/expo-cli/pull/1431
but github wouldn't let me reopen it.
Was able to remove some of the ios code and make some of the code "android only" due to @quinlanj recent work.
ran:
```
expo build:ios
expo build:android
expo build:ios --clear-credentials
expo build:android --clear-credentials
```
> @jkhales/add apiv2 option credentials

- packages/xdl/src/Project.ts
Missed a publishInfo -> publish/history endpoint.
Since this endpoint has already been converted in other places, it's relatively low risk and can go out in the same publish as another conversion.
> convert publishInfo endpoint

- packages/webpack-config/src/addons/withOptimizations.ts
- packages/webpack-config/src/loaders/createBabelLoader.ts
- packages/webpack-config/src/webpack.config.ts
- Source maps were being generated in the root build folder instead of the static/js folder
- Source maps were using absolute paths instead of relative paths (similar to the Iowa Caucus app lol)
- Source maps now dynamically download better -- harder to link them accidentally.
- Asset manifest was including source maps incorrectly, now the `asset-manifest.json` is split into two objects: `app`, and `entrypoints` (inspired by CRA, but with support for electron). 
- Added `GENERATE_SOURCEMAP` env variable for disabling source maps completely (this is for co-op with CRA users).
> [webpack-config] Fix source maps

- packages/babel-preset-cli/index.js
- packages/config/package.json
- packages/config/src/__tests__/ConfigParsing-test.js
- packages/config/src/__tests__/fixtures/language-support/ts/app.config.ts
- packages/config/src/getConfig.ts
- packages/config/src/scripts/read-config.ts
- yarn.lock
TypeScript is dope, having first-class support for `app.config.ts` will be great.
Use `@expo/babel-preset-cli` (also adds nullish coalescing and optional chaining support).
Unskip the TypeScript format test.
> [config] Added TypeScript support to app.config

- packages/expo-cli/src/commands/build/BaseBuilder.types.ts
- packages/expo-cli/src/commands/build/index.ts
- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- add support for a user to skip checking credentials if they are sure they have everything configured properly. Use case: credentials checking can take some time, and people who run builds frequently will want to skip checks
> [cli] add skip credentials flag

- packages/xdl/src/credentials/Credentials.ts
completed checks of 
```
upload:ios
upload:android
```
mentioned in:
https://github.com/expo/expo-cli/pull/1665
Moving ahead with making it the default choice.
> [expo-cli][credentials]  make credentials query api v2 by default

- packages/config/src/Config.ts
- packages/config/src/Config.types.ts
- packages/xdl/src/project/Doctor.ts
When `app.json` contains invalid json it would fall-though the config loading process and result in an empty JSON object. No error message is then printed pointing to the error location in the JSON file that contains the syntax error. Instead, schema validation errors would be printed which are confusing:
```
• is missing required property 'name'.
• is missing required property 'slug'.
```
After this PR, any syntax errors in your `app.json` file, now report errors like this:
```
Error: could not load config json at /Users/hein/repos/Expo/scratch/blur-animated: JsonFileError: Error parsing JSON: {
"expo": {
"name2": "Blank Template (TypeScript)",
"slug2": "blur-animated",
"privacy": "public",
"sdkVersion": "UNVERSIONED",
"platforms": ["ios", "android", "web"],
"version": "1.0.0", …
```
> Fix app.json parse errors not reported correctly

- packages/image-utils/package.json
- packages/image-utils/src/Image.types.ts
- packages/image-utils/src/index.ts
- packages/image-utils/src/sharp.ts
- packages/image-utils/src/sharp.types.ts
The sharp CLI is sometimes not powerful enough to do what we need. This PR enables us to get access to the instance of sharp used by the globally installed CLI.
- Writing all image operations to temporary directories can cause your computer to get slow over time (ofc this resets after restarting your computer but that's no fun). A better alternative is to use the instance to get a Buffer.
- Webpack requires Buffers of images, meaning we'd be writing to the FS just to read that Buffer again and do nothing with the written file.
- [Compositing](https://sharp.pixelplumbing.com/api-composite) images doesn't work as expected with the CLI.
> [image-utils] Create method for getting sharp instance

- packages/expo-cli/src/commands/build/index.ts
- packages/xdl/src/Webpack.ts
We create an asset cache and a Webpack cache for files to speed up rebuilds. This PR adds a `expo build:web --clear` to clear those caches for more thorough testing.
> [expo-cli] Created option for clearing web caches

- packages/xdl/src/Project.ts
partial step of expo/expo#6517
In order to preserve the current functionality of ExpoKit updates in the new expo-updates unimodule, we want to set certain properties in the native iOS and Android projects when running `expo publish`. This PR adds that functionality for the properties defined in expo/expo#6625 and expo/expo#6787.
> autofill expo-updates properties on `expo publish`

- packages/webpack-config/package.json
- packages/webpack-config/src/plugins/ExpoProgressBarPlugin.ts
- packages/webpack-config/src/utils/__tests__/search-test.js
- yarn.lock
We currently cannot log out any warnings about the build or rebuild without the progress bar format breaking. This will fix that.
> [webpack-config] Use a better progress plugin for improved logging

- packages/config/src/Web.ts
- packages/webpack-config/src/addons/withUnimodules.ts
- packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
- packages/webpack-config/src/webpack.config.ts
This doesn't need to be in the config library.
> [config] Move define plugin reducer method to webpack-config

- packages/image-utils/package.json
- packages/image-utils/src/Cache.ts
- packages/image-utils/src/Download.ts
- packages/image-utils/src/Ico.ts
- packages/image-utils/src/Image.ts
- packages/image-utils/src/index.ts
- packages/image-utils/src/jimp.ts
- packages/image-utils/src/sharp.ts
- yarn.lock
There are only a few limited types of image operations we use across the monorepo, this PR combines all of the expected behavior from Webpack and makes it accessible to the whole repo. 
- Adds support for generating favicons
- Adds support for creating icons using .expo cache, download cache, and jimp fallbacks.
> [image-utils] Created methods for generating favicons and icons

- packages/config/src/Config.types.ts
- packages/config/src/Web.ts
- packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
- packages/webpack-config/web-default/index.html
- `web/index.html` is invalid HTML with this feature enabled.
- This feature has been around for a year and hasn't been used for anything. 
- We should be a bit more prescriptive about the default template to cut down on surface area.
> Deprecate custom `expo.web.build.rootId` key

- packages/config/src/Config.types.ts
- packages/config/src/Web.ts
- packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
- packages/webpack-config/web-default/index.html
This feature was marked as dangerous, it hasn't been useful.
- Add noscript to the default `web/index.html`
- Fix root interpolation
- Add legacy interpolation
> [webpack-config] Deprecate noJavaScriptMessage

- packages/electron-adapter/src/Webpack.ts
- packages/webpack-config/README.md
- packages/webpack-config/src/addons/__tests__/withAlias-test.js
- packages/webpack-config/src/addons/withAlias.ts
- packages/webpack-config/src/addons/withUnimodules.ts
- packages/webpack-config/src/env/alias.ts
- packages/webpack-config/src/env/index.ts
- packages/webpack-config/src/webpack.config.ts
Instead of enforcing the versions of `react-native-web`, dynamically resolve aliases based on file availability.
Run a project with `"@react-native-community/netinfo": "^5.6.2", "react-native-web": "~0.11.7"`. 
Importing `@react-native-community/netinfo` should reflect:
```js
{
"default": {
"isConnected": {}
}
}
```
Using `"react-native-web": "~0.12.2"` should disable the alias and use the community module, resulting in:
```js
{
"NetInfoStateType": {
"unknown": "unknown",
"none": "none",
"cellular": "cellular",
"wifi": "wifi",
"bluetooth": "bluetooth",
"ethernet": "ethernet",
"wimax": "wimax",
"vpn": "vpn",
"other": "other"
},
"NetInfoCellularGeneration": {
"2g": "2g",
"3g": "3g",
"4g": "4g"
},
"default": {}
}
```
https://github.com/expo/expo-cli/pull/1655
> [webpack-config] Use dynamic aliases for Webpack

- packages/config/src/Config.types.ts
- packages/config/src/Web.ts
- packages/webpack-config/package.json
- packages/webpack-config/src/plugins/ExpoHtmlWebpackPlugin.ts
- packages/webpack-config/src/plugins/ModifyHtmlWebpackPlugin.ts
- packages/webpack-config/src/plugins/index.ts
- packages/webpack-config/src/webpack.config.ts
- packages/webpack-config/web-default/index.html
- packages/webpack-pwa-manifest-plugin/src/createMetatagsFromConfig.ts
- yarn.lock
To move past beta, we're resolving all features from the `expo.web.dangerous` object. One of the outstanding ones is the viewport which we currently inject into the `index.html`. This PR makes the viewport static in the template html.
- Add default viewport to the default index.html
- For users with legacy `index.html`s, parse the template and log out that they should add the tag to their project.
- `<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1.00001, viewport-fit=cover" />`
- Running `expo build:web` and `expo start:web` shouldn't log any warnings, the result `index.html` should have a viewport meta tag in the head.
- Running `expo build:web` and `expo start:web` with a custom `web/index.html` without a viewport tag, should log a …
> [webpack-config] Deprecate the expo.web.dangerous.viewport meta tag

- packages/expo-codemod/README.md
- packages/expo-codemod/src/transforms/__tests__/sdk37-imports-test.ts
- packages/expo-codemod/src/transforms/sdk37-imports.ts
This codemod transforms `AuthSession` and `ScreenOrientation` imports to use the new `expo-auth-session` and `expo-screen-orientation` packages.
> feat(expo-codemod): SDK 37 imports codemod

- packages/config/src/paths/extensions.ts
- packages/expo-cli/src/commands/publish.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/ProjectSettings.ts
https://www.notion.so/expo/App-entry-points-94433d55f7524837be7b37bccb2154a1
TL;DR In order to make `expo publish` able to create bundles for both the managed Expo client environment and bare native client environments, we need to be able to choose at runtime whether or not to resolve `.expo.*` files in the project source.
This PR adds a `--target` flag to `expo publish`; for `--target managed`, the packager resolves `.expo.*` files, and for `--target bare` the packager ignores them.
This PR also changes the default behavior for bare projects. Previously, `expo publish` **always** resolved `.expo.*` files, but now it only does so by default for managed workflow projects.
This is a **breaking change** for people who rely on `expo publish` resolving `.expo.*` files in bare workflow projects …
> [expo-cli][xdl][config] add expo publish --target managed|bare

- packages/expo-cli/src/commands/export.ts
- packages/expo-cli/src/commands/publish.ts
- packages/xdl/src/Project.ts
This PR makes #1734 and #1736 no longer a breaking change for existing projects. SDK 36 and below projects will default to `--target managed` in expo publish and export.
Tested the following configurations to ensure the correct target was chosen:
> [expo-cli][xdl] make default target managed for all projects in SDK 36 and below

- packages/xdl/src/Project.ts
(hopefully!) last step in making `expo publish` work out of the box in projects without the `expo` package installed. I've added the `hashAssetFiles` plugin to `expo-asset@8.1.2` so we check this location first and fall back to the `expo` package if it doesn't exist.
> [xdl] check expo-asset for hashAssetFiles plugin

- packages/webpack-config/src/plugins/ApplePwaWebpackPlugin.ts
- packages/webpack-config/src/plugins/ExpoHtmlWebpackPlugin.ts
theme-color and description meta tags went missing in the PWA redesign. This adds them back optionally when they aren't already in the template `index.html`.
> [webpack-config] Added theme-color and description meta tag injection

- packages/xdl/src/EmbeddedAssets.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/tools/ArtifactUtils.ts
Tested out expo-updates with `expo export` (I'd been testing mostly with `expo publish` before) and noticed a few things that would make the experience better.
- added `releaseId` to exported manifests (we add this on the server for published manifests)
- added writing to configuration files & embedding manifest/bundle into native projects, the same way `expo publish` does (originally used for ExpoKit & repurposed for expo-updates). To do this I extracted all of this functionality into `_configureEmbeddedFilesAsync`.
> [xdl] improve compatibility of export with expo-updates

- packages/xdl/src/EmbeddedAssets.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/detach/Detach.js
(depends on #1740)
This PR adds default paths for saving embedded assets to disk in projects with `expo-updates` installed. This removes the need for developers to configure the `ios.publishManifestPath`, `ios.publishBundlePath`, `android.publishManifestPath`, and `android.publishBundlePath` app.json fields upon installation of expo-updates; they can still configure these fields if they want a different location than the default.
The logic here assumes that all ExpoKit apps **will** still have these fields specified (ok since we write them to app.json automatically upon eject), but if `expo-updates` is installed, it will write the files whether or not these fields are specified.
Also, if the iOS files are being created anew, the command will log a reminder to add the files to the Xcode …
> [xdl] add default paths for saving embedded assets to disk

- packages/config/src/ios/Google.ts
- packages/config/src/ios/__tests__/Google-test.ts
- packages/config/src/ios/utils/Xcodeproj.ts
When ejecting to bare, the iOS `GoogleService-Info.plist` file is not copied to the correct location, nor is the `target membership` flag enabled. This will cause the Firebase SDKs to not be initialized.
- Rename `GoogleServices-Info.plist` to `GoogleService-Info.plist`. 
- Enable the `target membership` flag for `GoogleService-Info.plist`.
> [eject] Fix `GoogleService-Info.plist` file after ejecting to bare

- packages/package-manager/src/CocoaPodsPackageManager.ts
- packages/pod-install/src/index.ts
If you run in a project that has an `ios/Podfile`, then pods will be installed in that project. This is the same as running `npx pod-install ios`
> [pod-install] Add support for react-native projects

- packages/xdl/src/credentials/Credentials.ts
Close: https://github.com/expo/expo-cli/issues/1760 and https://github.com/expo/expo-cli/issues/1774
The cli was trying to read `result.data.errors` instead of `result.errors`.
Fixed this and made `EXPO_NEXT_API` the default again.
- checked it built with user supplied keystore. 
- threw a dummy ApiError server side and confirmed it handled it.
The solution and the testing of this was suggested @byCedric 🙏
> [credentials][apiv2] fix credentials bug

- packages/babel-preset-cli/ts-declarations/metro-config/index.d.ts
- packages/babel-preset-cli/ts-declarations/metro/index.d.ts
- packages/babel-preset-cli/tsconfig.base.json
- packages/metro-config/.gitignore
- packages/metro-config/LICENSE
- packages/metro-config/README.md
- packages/metro-config/babel.config.js
- packages/metro-config/package.json
- packages/metro-config/src/ExpoMetroConfig.ts
- packages/metro-config/src/__tests__/ExpoMetroConfig-test.ts
- packages/metro-config/src/__tests__/__fixtures__/hello-world/package.json
- packages/metro-config/src/__tests__/__snapshots__/ExpoMetroConfig-test.ts.snap
- packages/metro-config/src/index.ts
- packages/metro-config/transformer.js
- packages/metro-config/tsconfig.json
- yarn.lock
This PR adds the default Metro configuration for Expo apps as a separate `@expo/metro-config` package. The configuration is a minimal Metro config required to run React Native apps.
This is the first PR towards rolling out `@expo/dev-server`, which will replace the previous setup where we run the React Native CLI as a subprocess. The new dev server will use `@expo/metro-config` as a configuration, when it sets up a Metro server directly.
TBD, still working on this, planning to check that an app can be bundled with Metro CLI when using this config. 
Fixes https://github.com/expo/expo-cli/issues/1701.
> feat: add @expo/metro-config

- packages/expo-cli/src/commands/build/utils.ts
tested locally, although the version endpoint needs to be updated to reflect recent changes in what SDKs we support
> improve error message when using unsupported SDK

- .circleci/config.yml
- packages/config/package.json
- packages/config/src/Config.ts
- packages/config/src/Config.types.ts
- packages/expo-cli/src/commands/export.ts
- packages/expo-cli/src/commands/publish.ts
- packages/metro-config/package.json
- packages/metro-config/src/ExpoMetroConfig.ts
- packages/metro-config/src/__tests__/ExpoMetroConfig-test.ts
- packages/metro-config/src/__tests__/__snapshots__/ExpoMetroConfig-test.ts.snap
- packages/xdl/src/EmbeddedAssets.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/ProjectSettings.ts
- yarn.lock
Earlier discussion: https://github.com/expo/expo-cli/pull/1777#discussion_r402875727
Configuring the `sourceExts` setting of Metro bundler has previously been difficult with Expo CLI (see https://github.com/expo/expo-cli/issues/1019, https://github.com/expo/expo-cli/issues/1786), because we've been passing the `sourceExts` option to RN CLI, which overrides the setting specified in `metro.config.js`.
This PR adds `sourceExts` to the default Metro configuration added in https://github.com/expo/expo-cli/pull/1777. Once Expo CLI has been updated to load the configuration using the new package (I'm working on this), it will be possible to make use of these defaults when writing a custom `metro.config.js` file.
For example, to add an extension to `sourceExts` in a managed/bare Expo app, one …
> feat: add sourceExts to default Metro config

- packages/xdl/src/detach/ExponentTools.ts
This is going to fi.x https://github.com/expo/expo/issues/7701 once we update xdl in Turtle.
expo-cli treats json files as assets. It's totally fine - those could be used for translations. However, we don't handle small json files properly. If a user added a json file with empty json inside (`{}`) to his project and tries to build the app with Turtle he gets an error saying that one of the assets is too small.
```bash
$ echo "{}" > a.json
$  ls -lah a.json
-rw-r--r--  1 dsokal  staff     3B Apr  8 12:15 a.json
```
A file with an empty json is 4 bytes and we require each asset file to be at least 10 bytes.
I got rid of the `if` checking for the size of the asset entirely. If downloading the asset failed we would receive some HTTP error anyway. We don't need to have this strange condition. …
> [xdl] don't fail if the downloaded file is smaller than 10 bytes

- packages/expo-cli/src/exp.ts
closes https://github.com/expo/expo-cli/issues/459
Removing this since it has no effect, and if a command _does_ provide the option to give raw output, it is enabled with `expo [command] --raw`
> fix: remove extraneous '--output' option from --help page

- packages/config/src/Config.ts
- packages/config/src/Config.types.ts
- packages/config/src/__tests__/Config-test.js
- packages/config/src/__tests__/ConfigParsing-test.js
- packages/config/src/__tests__/getConfig-test.js
- packages/config/src/getConfig.ts
- packages/expo-cli/src/commands/__tests__/upgrade-test.ts
- The logic for resolving a config doesn't completely make sense. 
- If you have an app.config.ts and an app.config.js the app.config.ts should be used always. But if the app.config.ts had an error, it would use app.config.js instead.
- It's too difficult to determine if the config was static or dynamic
- app.config.json should be used as a static config instead of a dynamic config
- app.config.json should be able to be used with app.config.js and app.config.ts
- custom config paths should disable static or dynamic config resolution to be consistent across projects. 
- custom config paths point to dynamic files should work. Currently they're read as json and throw an error.
- Return a nullish file when a config isn't resolved.
- Attempt to use nodeModulesPath whenever possible.
- Make it …
> [config] Added strict config resolution and file path references

- packages/expo-cli/src/commands/publish.ts
- packages/expo-cli/src/commands/send.ts
The project manifest URLs (exp.host/@user/project) are different from the website URLs (expo.io/@user/project). The API server sends back a project manifest URL, not a website URL.
This commit changes the text we show to make this slightly clearer.
> Make it clearer that the printed URLs are project manifest URLs, not website URLs

- package.json
- fix https://github.com/expo/expo-cli/issues/1836
- Instead of clean, just run `yarn bootstrap` again.
- Removed `"prebootstrap": "yarn",` as `learna bootstrap` [already runs `yarn`](https://github.com/lerna/lerna/tree/master/commands/bootstrap#usage).
> Remove bootstrap from yarn start

- packages/expo-cli/src/commands/publish-info.ts
- packages/expo-cli/src/commands/publish-modify.ts
- packages/expo-cli/src/commands/utils/PublishUtils.ts
fixes https://github.com/expo/expo-cli/issues/596
- change implementation to do a `publish:set` of the second most recent thing in history for a given sdkVersion, platform and channel instead of actually deleting anything in the history
- add confirmation with the publication that clients will receive as a result of the rollback
- move shared methods into `PublishUtils`
> [cli] fix publish:rollback

- packages/expo-cli/src/commands/build/index.ts
- packages/expo-cli/src/commands/build/utils.ts
Fixes #1377
This is a pretty simple setup for the menu Brent described in #1377. The `askBuildType` accepts both the type (from flag) and available build types with a description (plain object).
1. Moved the `build:ios` type check to `askBuildType` method in `build/utils.js`
2. Added menu when build type is not defined
3. Implemented `askBuildType` in both `build:ios` and `build:android`
4. Removed the default values (in interactive mode, for non-interactive it uses the first default built type)
5. Added nonInteractive check for old behavior to avoid breaking changes in people's CI/CD
> By adding point 4, this change won't be a breaking change for non-internactive environments. Removing this is possible, but that would probably conflict with CI/CD systems where no type is defined.
It …
> feat(expo-cli): add menu for build type

- packages/expo-cli/src/commands/publish.ts
Since we now check the target when saving embedded assets (https://github.com/expo/expo-cli/commit/14d85cca1bf6c842c5baa1e8691885cf43cf0b75), if the user has the `expokit` package installed (probably from an incomplete migration from expokit to bare), `expo publish` will behave as if it's a managed workflow project and will not, by default, save embedded assets to disk.
This PR adds a warning when projects have both the `expokit` and `expo-updates` packages installed, saying the libraries are incompatible. This is mitigation for https://github.com/expo/expo/issues/7798 until we can have on demand updates working.
> [expo-cli] add warning on publish if developer has both expokit and expo-updates installed

- packages/xdl/src/Android.ts
- packages/xdl/src/Project.ts
Fixes #283, #175
This PR requires a fix for the graceful shutdown on Windows, see #1749.
**What did I do**
- Add failure-permitted `Android.maybeStopAdbDaemonAsync` in the XDL
- Add `Android.maybeStopAdbDaemonAsync` in `Project._stopInternalAsync`
**Why did I do**
If you install the CLI locally you have the shipped ADB binaries in your project's `node_modules`. On Windows keeping the daemon running results in a "blocking" node modules folder, you can't remove the file while the process is running.
**How does this do for others**
The impact should be minimal. Even if the developer is using a custom installed ADB, the daemon is restarted automagically by ADB when executing commands 😄
> fix(xdl): try to stop adb when shutting down

- packages/expo-cli/src/exp.ts
Fixes #1770
We can also keep the status bar, and just add a new line. But because [the progress bar is initialized explicitly with `{ clear: true }`](https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/exp.ts#L245) I thought this was the most appropriate fix.
> Edit: If we want to keep the status bar listed as completed, removing `{ clear: true }` will fix that. [Terminate checks if it should be removed or "new-lined"](https://github.com/visionmedia/node-progress/blob/master/lib/node-progress.js#L227-L236)
> fix(expo-cli): terminate bundle progress bar when finished

- packages/expo-cli/package.json
- packages/expo-cli/src/commands/start/TerminalUI.ts
- packages/expo-cli/src/commands/utils/EditorUtils.ts
- yarn.lock
Fixes #1762
This uses Sindre's `env-editor` and `spawnAsync` over some other options I've tried. The env editor basically tries to find the default editor, if that's not found it will fallback to vscode. If none of these 2 options work, it will log with an error and describes how to fix it.
I tested this on _MacOS_, _Windows_ and _Windows WSL_ 😄
**Fun facts(tm)**
- `open-editor` didn't work that well for folders on both MacOS and Windows. On MacOS it thought it was a file and appended line and colon (`/my/path:1:1`) to this. On Windows there were some errors with `--goto` flag.
- `open` didn't work on MacOS, apparently MacOS can't open vscode with `open /my/path -a vscode` (but does work with `open /my/path -a "Visual Studio Code"`). Also `open` didn't reject the first attempt, it …
> feat(expo-cli): add shortcut to open editor

- packages/expo-cli/src/commands/init.ts
- packages/package-manager/src/NodePackageManagers.ts
- packages/package-manager/src/index.ts
- packages/package-manager/src/utils/isYarnOfflineAsync.ts
- packages/package-manager/src/utils/shouldUseYarn.ts
- Disable ads for installs
- Use offline flag in Yarn
- Use `yarn install` when no packages are passed to `addAsync` or `addDevAsync`
- shouldUseYarn now accounts for `process.env.npm_config_user_agent`
> [package-manager] Added offline support to Yarn

- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- packages/expo-cli/src/credentials/test-fixtures/mocks.ts
- packages/expo-cli/src/credentials/views/IosDistCert.ts
- packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
- packages/expo-cli/src/credentials/views/IosPushCredentials.ts
- packages/expo-cli/src/credentials/views/SetupIosDist.ts
- packages/expo-cli/src/credentials/views/SetupIosProvisioningProfile.ts
- packages/expo-cli/src/credentials/views/SetupIosPush.ts
- packages/expo-cli/src/credentials/views/__tests__/IosDistCert-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosProvisioningProfile-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosPushCredentials-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosDist-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosPush-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupProvisioningProfile-test.ts
fixes https://github.com/expo/expo-cli/issues/1873
- Allow people who dont have creds on filesystem to run `expo build:ios` with `--non-interactive` build flag
- We've seen several people who have used `expo build:ios` on CI with this usecase and would like to continue supporting it
- supporting non-interactive allows us to better test these classes
> [cli] better non interactive support for creds

- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- packages/expo-cli/src/credentials/route.ts
- packages/expo-cli/src/credentials/views/Select.ts
- refactor IQuits to classes
- if view errors and our Quit interface is AskQuit - show that view
- if view errors and our Quit interface is DoQuit - propagate error up to caller
- add contextual build errors to `IOSBuilder`
https://github.com/expo/expo-cli/pull/1881
land https://github.com/expo/fyi/pull/4
> [cli] refactor IQuit, contextual errors

- packages/expo-cli/src/exit.ts
Previously, stopping the expo dev server with `Ctrl+C` in PowerShell or
Windows Command Prompt caused the process to end abruptly without
printing "Closing Expo server" or setting the fields of `packager-info.json`
to `null`.
Fixes #1608.
*Tested in Windows Command Prompt, Windows PowerShell 5.1, PowerShell Core 7.0, and git bash on Windows 10.*
1. Navigate to `packages/expo-cli` in the terminal you want to test.
2. `node bin/expo.js start /path/to/any/project`
3. Wait for the QR code to display, then press `Ctrl+C` or `Ctrl+D`.
**Expected behavior:**  
* Expo dev server prints 
```
Stopping packager...
› Closing Expo server
› Stopping Metro bundler
Packager stopped.
```
and then terminates.
* The Node process is terminated. 
* All fieds except `devToolsPort` in the project's …
> fix: handle Ctrl+C correctly in PowerShell/CMD

- packages/expo-cli/e2e/__tests__/start-test.ts
- packages/expo-cli/package.json
- packages/xdl/src/Project.ts
Fixes #1677
This calls the Metro bundler's `/status` endpoint to determine if the project is running. It's performing a request, so that might slow the method down (with a current max time out of 2 seconds). But it provides a more accurate response about the current status. The code is [copied from `startReactNativeServerAsync`](https://github.com/expo/expo-cli/blob/a26baf39c19cefd016eb0acc0445c4a3cba16915/packages/xdl/src/Project.ts#L1925)
I did not check for the expo server, it [closes itself when you start it](https://github.com/expo/expo-cli/blob/master/packages/xdl/src/Project.ts#L1985). So that means it restarts every time you run `expo start`, right? And I think both `expo publish` and `expo build` doesn't require the Expo server to run.
Thanks for thinking along @quinlanj 😄
> fix(xdl): ping metro bundler when fetching current status

- packages/xdl/src/detach/AndroidShellApp.js
Following [Using FCM doc](https://docs.expo.io/versions/latest/guides/using-fcm/) or [GoogleSignIn - Usage with Firebase part](https://docs.expo.io/versions/latest/sdk/google-sign-in/#usage-with-firebase) would not render the expected results — `googleSignIn` configuration was always being applied onto `google-services.json`, even if a custom one has been provided by the user. Most probably this is not how this should work or what the user expect.
When pushed to Turtle builders, should fix https://github.com/expo/expo/issues/7727.
Depending on the SDK version of the built project:
- if the SDK is >= 37:
- only change `google-services.json` if none was provided (so we're operating on a placeholder one)
- if both configuration settings are provided print a warning and not modify the custom …
> [xdl] Do not override google-services.json contents since SDK37

- packages/expo-cli/src/commands/build/AndroidBuilder.ts
- packages/expo-cli/src/commands/google-play/AppSigningOptIn.ts
- packages/xdl/src/credentials/Credentials.ts
Android credentials were not being updated on the apiv2 endpoint when running `expo build:android -c`.
The cli was sending incorrectly formatted credentials to the endpoint.
Followed @wkozyra95 detalied repro:
```
export EXPO_NEXT_API=true
expo init testProject
cd testProject
expo credentials:manager  // and generate generate upload kesytore
expo fetch:android:hashes // returns some hashes
expo fetch:android:keystore // backup keystore (it's better to move it somwhere because it can be overwritten)
expo credentials:manager  // and generate generate upload kesytore new one
expo fetch:android:hashes // verified that hashes changed
expo build:android -c // and provided keystore generated first time
expo fetch:android:hashes // hashes should change back to orignal ones but stayed the same, …
```
> [credentials][android][apiv2] Fix upload keystore

- packages/dev-tools/package.json
When publishing I noticed every time I ran `npm publish` (without success, but that's a different story) the _package size_ increased.
> [dev-tools] Clean dev-tools when preparing

- packages/uri-scheme/src/Android.ts
Append the following to the error message about the project being misconfigured: `\nThis guide can help you get setup properly https://expo.fyi/setup-android-uri-scheme`
> Add FYI guide to uri-scheme for android setup

- packages/xdl/src/detach/AndroidShellApp.js
This check has been added in https://github.com/expo/expo-cli/pull/98 as an effort to ensure that the shell apps contain the pregenerated macros as expected.
I'm not sure this is needed anymore — from my point of view the shell app creation process is very clear now ([one, simple script](https://github.com/expo/expo/blob/master/buildAndroidTarballLocally.sh)), `expotools` consistently generate the macros and I don't think XDL should be tied that closely to internals of the shell app.
If we wanted to, we could replace this check, run for every build, with a post-shell-app-build check in `expo/expo` repo, where the shell apps are created.
Removed spawning of the aforementioned script.
As this only removed the call and doesn't add anything I don't see it breaking anything.
It's unlikely we …
> [xdl] Remove call to check-dynamic-macros

- packages/expo-cli/src/commands/bundle-assets.ts
- packages/xdl/src/detach/Detach.js
https://exponent-internal.slack.com/archives/C5ERY0TAR/p1587135492115900?thread_ts=1587065441.099200&cid=C5ERY0TAR
Added throwing an error in the `bundleAssetsAsync` function if the manifest is empty. In the expo-cli command, we catch errors and log them along with a helpful reminder to run `expo publish`.
Tested by initializing a blank bare project with expo init and changing the asset bundle build steps in iOS/Android projects to use local expo-cli. Before running `expo publish`, both release builds failed and logged the expected message. After running `expo publish` they both succeeded.
> [xdl][expo-cli] log message in `expo bundle-assets` if manifest is empty

- packages/xdl/src/detach/AndroidShellApp.js
I have noticed that not only the `app` project is being built on Turtle, but all the projects.
I've scoped the Gradle command to only build/assemble the `:app` project. It should be safe to do for all SDKs, since on all SDKs the app project was called `app`.
Published an alpha version of XDL to NPM, upgraded Turtle to it, deployed to staging and ran the build. It was over a minute faster than without this change ([new](https://staging.expo.io/dashboard/sjchmiela/builds/5c386cef-e808-49d3-91d8-9ce42af77c36) vs [old](https://staging.expo.io/dashboard/sjchmiela/builds/3d36340e-6ae1-4476-91cb-07d81f1edd1e)).
> [xdl] Assemble/bundle only the :app project

- packages/image-utils/src/sharp.ts
Fixes #1900
This hardcodes the minimal required sharp cli version back to image-utils. As reported in the issue, the problematic [commit is this](https://github.com/expo/expo-cli/commit/8b9b581c732b5a5e8c7f6907de5f7f141f9cf585). It removes the sharp-cli peer dependency from the package, which is actually used by the sharp detection code. As alternatives, we could also revert the change and add the peer dependency back. Or even remove the version required fully.
> fix(image-utils): add minimal required sharp cli version back

- packages/expo-cli/src/commands/upload/AndroidUploader.ts
When one copies the path from finder, it adds a trailing space. This PR trims that space away that leads to better user experience.
> Fix pasting path from finder

- packages/webpack-config/package.json
- packages/webpack-config/src/addons/withWorkbox.ts
- yarn.lock
The workbox plugin is already a year old. We should update it to a recent version as it supports more functionalities.
> [webpack-config] fix: update workbox

- packages/webpack-config/src/loaders/createBabelLoader.ts
This fixes a bug where `babel-preset-expo` couldn't be resolved in a project unless the `webpack-config` package was installed in that project. We can now effectively remove the requirement for a local `babel.config.js` in the project root on web.
> [webpack-config] Resolve babel preset expo from a global CLI

- packages/expo-cli/src/appleApi/authenticate.ts
There is a bug in our code, where if a user runs `expo build:ios --apple-id <their apple id> --non-interactive`, we return:
```
[20:37:26] Input is required, but Expo CLI is in non-interactive mode.
Pass your Apple ID using the --apple-id flag.
```
We tell `inquirer` not to ask this question if someone has set the `--apple-id` flag, but our problem arises when we also pass in the `--non-interactive` flag. This is because we check `nonInteractive` mode and throw an error before we evaluate whether we should ask the question in the `when` option we pass to `inquirer`. 
our code is currently built so that you can pass in one of `{appleId, applePassword}`, and it will prompt you to provide any credential that is missing. I don't really see a use-case where someone would want to pass in *only* …
> [cli] better auth error messages, tweak use case

- packages/config/package.json
I'm updating the Standard Version Expo library and came across this. [`globby` is used in `Config.ts`](https://github.com/expo/expo-cli/blob/58a6cf7556e6e1a708feab52dcc3eec46f17dd5c/packages/config/src/Config.ts#L3), I think it should be added here 😄 It works with this version, but do correct this if it needs an older one!
> fix(config): add missing globby dependency

- packages/expo-cli/src/commands/start/TerminalUI.ts
- packages/expo-cli/src/commands/utils/EditorUtils.ts
This hotfixes the open editor feature for MacOS and terminal editors.
It works, but there are some things that I don't like about the current state:
- Using `EXPO_EDITOR=vim expo start` doesn't open Vim on MacOS. It's because probably because osascript can't resolve vim as name. (even though I have vim installed on MacOS and can execute from terminal).
- The list of "supported" editors by name is less compared to [React's dev tools list](https://github.com/facebook/create-react-app/blob/master/packages/react-dev-utils/launchEditor.js). We can't reuse this because of the same reason we can't use `open-editor`, it opens files only (not folders).
Maybe it's better to update FileSystem to support all platforms, and move this code to that part. But that would be a significant change.
> fix(expo-cli): use expo editor env before guessing default editor

- packages/expo-cli/bin/expo.js
Changes the confusing message of a newer version being "no longer" supported.
Fixes #1955 
I am currently _not_ at a device (except for a phone) so I have not tested this code.
> Add check for newer versions than supported

- packages/expo-cli/src/credentials/__tests__/api-basic-test.ts
- packages/expo-cli/src/credentials/__tests__/api-project-context-test.ts
- packages/expo-cli/src/credentials/test-fixtures/mocks.ts
- packages/expo-cli/src/credentials/views/__tests__/IosDistCert-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosProvisioningProfile-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosPushCredentials-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosDist-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosPush-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupProvisioningProfile-test.ts
tests for https://github.com/expo/expo-cli/pull/1941
includes:
- regular tests for credentials api class
- project context tests for credentials api class
- more mocks + such for credentials
> [cli] tests for credentials api with project context

- packages/babel-preset-cli/tsconfig.base.json
I noticed that in Expo CLI (which we compile with babel) we ship await/async, whereas all other packages that are build with TS create an awaiter method. Using ES2017 reduces bundle size. 
Ex `@expo/json-file`
```
npm notice === Tarball Details === 
npm notice name:          @expo/json-file                         
npm notice version:       8.2.11                                  
npm notice filename:      expo-json-file-8.2.11.tgz               
npm notice package size:  7.9 kB                                  
npm notice unpacked size: 36.4 kB                                 
npm notice shasum:        611d7d915e018737e6ab1328d81558637f54a6b8
npm notice integrity:     sha512-xoGaG04Afl6+0[...]PlAOMyrjl+AYg==
npm notice total files:   9  
```
```
npm notice === Tarball Details === 
npm …
```
> Use ES2017

- packages/expo-cli/src/exp.ts
kinda silly that we make you rerun the command to see what failed the first time. Maybe there's some reason I'm not aware of?
> Always print stack trace

- packages/expo-cli/src/commands/build/AndroidBuilder.ts
- packages/expo-cli/src/commands/fetch/android.ts
- packages/expo-cli/src/commands/google-play/AppSigningOptIn.ts
- packages/expo-cli/src/credentials/__tests__/api-basic-test.ts
- packages/expo-cli/src/credentials/__tests__/api-project-context-test.ts
- packages/expo-cli/src/credentials/api.ts
- packages/expo-cli/src/credentials/context.ts
- packages/expo-cli/src/credentials/test-fixtures/mocks.ts
- packages/expo-cli/src/credentials/views/Select.ts
- packages/expo-cli/src/credentials/views/__tests__/IosDistCert-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosProvisioningProfile-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosPushCredentials-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosDist-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosPush-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupProvisioningProfile-test.ts
- packages/xdl/src/ApiV2.ts
We used to support builds where if User A gave User B permission to build their app, User B would be able to build User A's app. However, User B would need to specify `UserA` was the owner of the app in the owner field of the `app.json`.
When we moved to the new credential checker, we overlooked this use case. We add it back now by doing the following:
- Add `username` field to credential's IosApi
- Add `owner` in the api's request body or query parameter as appropriate
> [cli] add support back for owner field when cred checking

- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
Fixes #1197
It's just a warning, styled like the `expo upgrade` warnings, to tell the developer about possible damaged simulator builds. I put it in twice, so it's always visible when the user starts the build and when the build is completed (or sent, with `--no-wait`).
<details>
<summary>This is how it looks like when starting</summary>
</details>
<details>
<summary>This is how it looks like at the end</summary>
</details>
> fix(expo-cli): add warning about damaged simulator builds catalina

- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
based on weekend slack chat https://expo-developers.slack.com/archives/C04Q3JTSV/p1587257406295000?thread_ts=1586737385.022700&cid=C04Q3JTSV
- throw credentials errors in catch block so we dont continue if there is a fatal error
- Add context specific failures (ie) user knows they failed to setup a particular credential at a certain step
> [cli] better build errors

- CHANGELOG.md
- packages/xdl/src/detach/AssetBundle.ts
- packages/xdl/src/detach/Detach.js
This is a hotfix for the issue discussed in https://forums.expo.io/t/ios-bundle-assets-error-when-building-release-403/36616/9
We should follow up with a better solution and write tests. I don't like that we are depending on the hardcoded Cloudfront URL to determine whether the app was exported or not, there should probably be a field in manifest that gives us this information.
> Get the public exported url set by expo export from the manifest and pass in to bundleAsync

- packages/expo-cli/src/commands/apply.ts
We do the same in `credentials:manager`
> [expo-cli] Validate platform in apply command

- packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
The start of basic unit tests that try to mimic `expo build:ios` as close as possible will help me maintain consistent `nonInteractive` behaviour as I change functionality - i can pass in all the different build params and still check that we don't ask for user prompting. People using `nonInteractive` for CI is somewhat popular, but not so common that we immediately catch it upon a patch release.
we might be planning to have e2e integration tests that make real calls to the server (?), but for now, this is a good way to catch regressions in any behaviours
> [cli] test expo build:ios

- CHANGELOG.md
- packages/config/src/android/UserInterfaceStyle.ts
- packages/config/src/android/__tests__/UserInterfaceStyle-test.js
If you eject an app on Android with `userInterfaceStyle` set to `automatic` then we will add some code to MainActivity that will not work because it depends on classes that haven't been imported. This adds those imports.
> Add imports to fix ejecting on Android with userInterfaceStyle set

- packages/expo-cli/src/commands/android.ts
- packages/expo-cli/src/commands/apply.ts
- packages/expo-cli/src/commands/build-native/index.ts
- packages/expo-cli/src/commands/build/index.ts
- packages/expo-cli/src/commands/bundle-assets.ts
- packages/expo-cli/src/commands/client/index.ts
- packages/expo-cli/src/commands/doctor.ts
- packages/expo-cli/src/commands/eject.ts
- packages/expo-cli/src/commands/export.ts
- packages/expo-cli/src/commands/fetch/index.ts
- packages/expo-cli/src/commands/ios.ts
- packages/expo-cli/src/commands/opt-into-google-play-signing.ts
- packages/expo-cli/src/commands/prepare-detached-build.ts
- packages/expo-cli/src/commands/publish-info.ts
- packages/expo-cli/src/commands/publish-modify.ts
- packages/expo-cli/src/commands/publish.ts
- packages/expo-cli/src/commands/push-creds.ts
- packages/expo-cli/src/commands/send.ts
- packages/expo-cli/src/commands/start.ts
- packages/expo-cli/src/commands/upload.ts
- packages/expo-cli/src/commands/url.ts
- packages/expo-cli/src/commands/webhooks.ts
- packages/expo-cli/src/exp.ts
- `asyncActionProjectDir` accepts three parameters, we've been adding comment blocks to tell what those parameters do. This is bad practice.
- Mostly we disable the validation checks that are done, so I've flipped the condition where you enable the check instead of disabling it.
- Auth check wasn't being used so I removed it.
> [expo-cli] Improve readability of asyncActionProjectDir

- packages/xdl/gulp/build-tasks.js
- packages/xdl/src/Api.ts
- packages/xdl/src/Utils.ts
- packages/xdl/src/project/ExpSchema.ts
There are two locations xdl-manifests are fetched. For the first one in `packages/xdl/gulp/build-tasks.js` replaced the url. Confirmed this worked by repopulating the schema cache (git diff is empty):
```
cd ~/expo-cli/packages/xdl
rm caches/*
yarn prepack
git diff
```
For the second location, Line 69 in `packages/xdl/src/project/ExpSchema.ts`:
1) Refactored the Cache out of the Api v1 class and into its own: `XdlSchemaClient`. 
2) Checked it worked in a similar way to the first point, but this time checking that`~/.expo/caches/` was repopulated by running `expo start` in an expo project. (Note: you have to delete `~/expo-cli/packages/xdl/caches/*` before running this test to force the repopulation to happen from the endpoint instead of the local backup.)
> [xdl] Get xdl-manifests from apiv2 endpoint

- packages/expo-cli/bin/expo.js
Right now, both Node.js 13 and 14 is "Current release"
> Print warning when running on newer version of Node.js

- packages/xdl/src/EmbeddedAssets.ts
The `IosPlist` util leaves behind some artifacts (`*.json`, `*.plist.bak`) which may be confusing to users who aren't expecting them.
In particular, users running `expo publish` in a bare workflow project with `expo-updates` may find these extra files (which come from modifying the data in the Expo.plist config file) confusing. Their utility is limited -- since most people are using version control there's no need to have separate backup files in the same folder. So in this case we should just delete those files after the `IosPlist.modifyAsync` operation completes successfully.
`expo init`, bare-minimum template, `expo publish`
> [xdl] clean up Expo.plist artifacts left behind by IosPlist util

- packages/expo-cli/src/commands/client/index.ts
resolve https://github.com/expo/expo-cli/issues/2002
> [expo-cli] client:ios -- default to using Apple ID email address

- packages/config/package.json
- packages/dev-tools/package.json
- packages/electron-adapter/package.json
- packages/expo-cli/package.json
- packages/expo-codemod/package.json
- packages/image-utils/package.json
- packages/json-file/package.json
- packages/metro-config/package.json
- packages/next-adapter/package.json
- packages/osascript/package.json
- packages/package-manager/package.json
- packages/pwa/package.json
- packages/webpack-config/package.json
- packages/xdl/package.json
Currently, a lot of the cleaning scripts in many of the `package.json` do not work on Windows due to them running the `rm` command. This would work in PowerShell but not in `cmd` which is what Node seems to use to run scripts defined in `package.json`.
As an example, this leads to these errors when running the initial `yarn run bootstrap`:
```
expo-codemod: $ yarn run clean && yarn build
@expo/json-file: $ yarn run clean && yarn build
@expo/osascript: $ yarn run clean && yarn build
@expo/image-utils: $ yarn run clean && yarn build
@expo/package-manager: $ yarn run clean && yarn build
@expo/plist: $ yarn build
@expo/schemer: $ yarn build
expo-codemod: $ rm -rf build ./tsconfig.tsbuildinfo
@expo/json-file: $ rm -rf build ./tsconfig.tsbuildinfo
@expo/osascript: $ rm -rf build …
```
> Make clean scripts platform independent

- packages/expo-cli/src/commands/init.ts
I found the current comment phrased in a kind of weird way, for example "access to a macOS" sounds really off to me.
Feel free to edit if you don't like my suggestion.
> Improve macOS comment printed at end of init

- .github/workflows/test.yml
- packages/babel-preset-cli/ts-declarations/metro-config/index.d.ts
- packages/babel-preset-cli/ts-declarations/metro/index.d.ts
- packages/babel-preset-cli/ts-declarations/react-native-community__cli-server-api/index.d.ts
- packages/dev-server/.gitignore
- packages/dev-server/LICENSE
- packages/dev-server/README.md
- packages/dev-server/babel.config.js
- packages/dev-server/package.json
- packages/dev-server/src/LogReporter.ts
- packages/dev-server/src/MetroDevServer.ts
- packages/dev-server/src/middleware/__tests__/__snapshots__/clientLogsMiddleware-test.ts.snap
- packages/dev-server/src/middleware/__tests__/clientLogsMiddleware-test.ts
- packages/dev-server/src/middleware/clientLogsMiddleware.ts
- packages/dev-server/tsconfig.json
- packages/metro-config/package.json
- packages/metro-config/src/ExpoMetroConfig.ts
- packages/metro-config/src/__tests__/ExpoMetroConfig-test.ts
- packages/metro-config/src/__tests__/__snapshots__/ExpoMetroConfig-test.ts.snap
- packages/xdl/package.json
- packages/xdl/src/Project.ts
- packages/xdl/src/ProjectSettings.ts
- yarn.lock
`@expo/dev-server` will use the new `dev-server-api` and `@expo/metro-config` packages to set up a Metro dev server compatible with React Native projects. In addition to the React Native development endpoints, it will include additional endpoints e.g. for serving Expo manifests and receiving logs from Expo client.
> refactor: add @expo/dev-server

- packages/dev-server/src/MetroDevServer.ts
- packages/metro-config/package.json
- packages/metro-config/src/ExpoMetroConfig.ts
Fixes "Error: Cannot find module 'metro-config'" when running
```
EXPO_USE_DEV_SERVER=true expo start
```
> fix: resolve and import metro-config from the project

- packages/expo-cli/src/accounts.ts
- packages/expo-cli/src/commands/eject/LegacyEject.ts
- packages/expo-cli/src/commands/start/TerminalUI.ts
- packages/expo-cli/src/exp.ts
- packages/xdl/src/User.ts
https://github.com/expo/expo-cli/issues/1024
Paired with @fson. 
Created a new callback function to remove the double call to the server.
Set the silent option to quiet the redundant error message.
Log in to  cli, then log out of all other session with web ui.
`EXPO_STAGING=1 expod ph`
And check the error message.
> [expo-cli][xdl] Reduce warning messages when logged out. [closes:#1024]

- packages/expo-cli/src/commands/build/AndroidBuilder.ts
fixes https://github.com/expo/expo-cli/issues/356
- There are 4 relevant android credential values we track: {`keystore`, `keystore password`, `keystore alias`, `key password`}
- Android Keystore contains a set of keys. This keystore is accessed with a keystore password.
You can index into each value (a key or certificate) in this keystore with a string alias. Each key in the keystore has a key password. 
- When a user asks to upload their own android credentials, the most intuitive order to ask the questions in are 1. keystore path, 2. keystore password, 3. keystore alias and 4. key password.
- The current order is 1. keystore path, 2. keystore alias, 3. keystore password and 4. key password.
> [cli] change ordering of android credential questions

- packages/expo-cli/src/credentials/context.ts
When someone is running something related to ios credentials in a project context, log which user you are configuring for and for which project to help with troubleshooting
logging will show 
```
Configuring credentials for quintest113 in project test47
```
logging will show
```
Configuring credentials on behalf of quintest113 in project test47
```
> [cli] update ios context logging

- packages/expo-cli/bin/expo.js
Follow up to #1992, this makes the guard that prints a nice error when using an older version of Node.js work on older versions of Node.js.
It even supports 0.10 now 😄 
(ping @brentvatne)
> Make Node.js version gate work on older versions

- packages/expo-cli/src/commands/export.ts
or not the files in outputDir, and not outputDir itself, preserving files other files in outputDir.
https://expo.canny.io/feature-requests/p/expo-export-with-existing-dist-directory
> improvement: When 'expo export --public-url <server> ', ask to overwrite

- packages/webpack-config/src/index.ts
Make it easier for people to use react-native-web without Expo CLI.
- `yarn add -D @expo/webpack-config webpack webpack-cli webpack-dev-server`
- `touch webpack.config.js`
```js
const createConfig = require("@expo/webpack-config");
module.exports = () => {
return createConfig();
};
```
- Run `npx webpack-dev-server`
- Build `npx webpack`
This isn't optimal in a lot of ways but it gives people who don't like Expo an alternative way to use ... expo web
> Add a default project root for easier use with Webpack CLI

- packages/expo-cli/src/commands/eject/Eject.ts
- packages/expo-cli/src/commands/init.ts
- packages/xdl/src/EmbeddedAssets.ts
- packages/xdl/src/Project.ts
Depends on https://github.com/expo/expo/pull/8066 to land and be released
This PR removes warnings in expo-cli for expo-updates, regarding publishing before making release builds.
It also stops automatically embedding manifests + bundles in Xcode/Android projects on `expo publish` and `expo export`, except for those projects using expo-updates `0.1.x` or when the files already exist (to support developers who have upgraded to new expo-updates but have not switched over to the no-publish workflow).
Also added a new warning to mitigate the following confusing workflow:
- init new project
- make test release build
- publish OTA update (which automatically sets URL)
- previous build did not have URL yet --> cannot download update --> ???
> [expo-cli][xdl] changes for expo-updates no-publish workflow

- .circleci/config.yml
- CONTRIBUTING.md
- package.json
- packages/expo-cli/package.json
- packages/expo-cli/tsconfig.json
This PR adds type checking with `tsc` to the `build` script in the `expo-cli` package to make sure any type errors are caught in CI. This is necessary because `expo-cli` is compiled with Babel (because [reasons](https://github.com/expo/expo-cli/pull/917)) and Babel doesn't do type checking for TypeScript.
The PR also:
- removes the `yarn bootstrap` script from the root `package.json`, because `lerna bootstrap` is not necessary in projects using Yarn Workspaces (Yarn handles linking and dependencies), and
- adds a `yarn build` script in the root for building all packages. This is mostly going to be used in CI: when developing it's often more convenient to just run `yarn start` to kick off the watcher.
> chore: fix type checking in CI, remove bootstrap

- package.json
- packages/babel-preset-cli/package.json
- packages/expo-cli/package.json
- packages/next-adapter/src/customize/index.ts
- yarn.lock
Upgrade TypeScript to 3.8.x. Also Prettier had to be updated to 2.0.x ([TS 3.8 support was introduced in Prettier 2.0](https://prettier.io/blog/2020/03/21/2.0.0.html#typescript)).
> chore: upgrade to TypeScript 3.8

- packages/config/src/Config.types.ts
- packages/xdl/src/Project.ts
`postPublishHook` aren't strings, just moving this type out of `xdl` and into `config`
> fix(config): add postPublishHook type 

- packages/expo-cli/src/commands/build/BaseBuilder.types.ts
- packages/expo-cli/src/commands/build/index.ts
- packages/expo-cli/src/commands/utils/ProjectUtils.ts
- packages/expo-cli/src/commands/utils/__tests__/ProjectUtils-test.ts
Fixes https://github.com/expo/expo-cli/issues/2109
`findProjectRootAsync` was not respecting the config and `build:*` was not calling `setCustomConfigPath` with the value of the `--config` flag. This resolves both of those issues.
Note: there are other places where we call `findProjectRootAsync`: `install` and `upgrade`. I didn't think it made sense to support the config flag in these places, but I am open to being convinced.
> fix: Rewrite ProjectUtils.findProjectRootAsync to use @expo/config

- packages/expo-cli/src/commands/eject/Eject.ts
Since the native project configuration can change between expo-updates versions, when ejecting we should prefer the expo-updates version in the template project rather than the version the project already has installed (if any).
Otherwise we can end up in a situation where we eject a project with `expo-updates@0.1.2` installed, but the resulting project has the native configuration for `0.2.0` which will make the build fail.
The only time this could be an issue is if we change the JS API, but as long as we don't do this within a single SDK version this won't be an issue.
Tested by: expo init EjectTest -> expo install expo-updates (0.1.3) -> expo eject -> verify 0.2.1 installed.
> [xdl] prefer expo-updates version from template when ejecting

- packages/expo-cli/src/commands/build/AndroidBuilder.ts
- packages/expo-cli/src/commands/build/BaseBuilder.ts
- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- packages/xdl/src/project/Doctor.ts
New docs don't have versioned guides anymore, so this fixes those links.
For android keystore logging-  saying “we’ll store a backup” implies that we keep a copy in case you screw up. The logging now is clear that the backup is in your possession, and the spacing makes that clearer
> fix: dead links & better android keystore logging

- packages/expo-cli/src/commands/upgrade.ts
I was confused by the message `You might have to upgrade your iOS simulator. Before you can do that, you have to run the simulator. Do you want to upgrade it now?`. It sounded like a Simulator/Xcode upgrade might be necessary, and I would have to do it myself. But actually the tool wanted to upgrade the client *app* in the Simulator and this was done automatically.
Clarified the wording to reflect this and used "Expo app" instead of "client" (even though less accurate, I think this is more familiar since "Expo" is the name of the app).
> Clarify wording about upgrading Expo Client in the simulator

- packages/expo-cli/src/commands/client/index.ts
We warn for the other optional configs, so I'm adding the just-added Facebook config
> fix: warn if no facebook config when building custom client

- packages/dev-tools/package.json
Clean up the `.next` folder before building Dev Tools to avoid inflating the package size.
In `@expo/dev-tools@0.13.6`, the unzipped size of the `build/client/_next/static` was 70M and it included 130 folders. It turns out these folders are copied from the `.next` folder when `next export` is run, and the size of the folder grew with every build.
Ran `yarn run prepare && ls build/client/_next/static|wc -l` a bunch of times in a row and verified that the number of folders remained constant `3`.
> fix(dev-tools): add clean up to avoid inflating package size

- packages/pod-install/README.md
This small PR adds `--quiet` option description to the `pod-install` README file. Refs #2102.
> chore: add --quiet to the pod-install README

- packages/expo-cli/__mocks__/ora.js
- packages/expo-cli/src/__tests__/utils.ts
- packages/expo-cli/src/commands/__tests__/publish-info-test.ts
- packages/expo-cli/src/commands/__tests__/publish-modify-test.ts
- packages/expo-cli/src/commands/__tests__/upgrade-test.ts
- packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
I need to mock `@expo/xdl` and `ora` in tests for my other PR. I saw that we're already mocking these modules in few places. I wanted to simplify mocking them so it requires less boilerplate in each test suite.
- I added a global mock for `ora`.
- I added a utility function for mocking `@expo/xdl` (it's type-safe).
> [expo-cli] simplify mocks for @expo/xdl and ora

- packages/traveling-fastlane/actions/supply_android.rb
In the Submission Service PR, I made it possible to pass the release status to `expo upload:android`. 
I also change the way of specifying whether the archive is `.apk` or `.aab`. It'll be possible to upload an archive without the filename extension. Thus the other argument.
> [traveling-fastlane] add two more args for supply_android (archive type and release status)

- packages/expo-optimize/package.json
Because `@expo/config` uses an external script to read the app config ncc shakes it out and effectively breaks the expo-optimize command. This PR externs the expo/config package so it must be installed after the package is npx'd, this adds more time but makes everything work as expected.
> [optimize] Extern the config package

- packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
I've noticed that test cases from this test suite are failing on master occasionally. They exceed the default 5s timeout. I increased it to 10s.
> [expo-cli] increase timeout for build-ios-test.ts

- packages/expo-cli/src/commands/upload/submission-service/android/ServiceAccountSource.ts
Use chalk to bold the first place where the user should read and use terminal link to remove https:// prefix and underline the link
<hr />
In general I think we should try to call attention to where an important log message begins by using bolded text.
If there's an error that's followed by a bunch of text, we can prefix the error message with 🚨, and if it's a warning, we can prefix it with ⚠️. This is useful for people to quickly see what things they need to pay attention to in the scroll buffer. See the eject command for an example. (Note that we use red text for warning still here, this is because it's pretty hard to read yellow text).
terminal-link is used elsewhere in the CLI (eg: eject) and lets us provide links in a more natural way when that is useful. Using it for all links helps …
> Make the Google Services prompt bold/use terminal link

- packages/expo-cli/src/commands/start.ts
- packages/xdl/src/Web.ts
- packages/xdl/src/Webpack.ts
- packages/xdl/src/webpack-utils/WebpackEnvironment.ts
- packages/xdl/src/webpack-utils/createWebpackCompiler.ts
- Don't need two modules that basically do the same stuff. 
- Merge into one and simplify the exports of the remaining one.
> [xdl] Deprecate Web module in favor of Webpack module

- codecov.yml
Codecov is pretty cool and it's nice to have it checking pull requests and notifying through the Commit Status API:
This PR disables the commenting from the codecov bot. Commit status is still updated as before and will show if the PR changes the test coverage.
But the comment that @codecov posts to every PR is too distracting:
- it shows up one the list of PRs as a comment, making you think there's a new comment to your PR from a human being: 
_Both my PRs have comments! I'll go have a look! ...Oh, it's just the bot._ ☠️ 
- it takes more than one screenful of space, so you need to scroll a lot to see the actual comments (if any):
> chore: disable codecov comments on PRs

- packages/configure-splash-screen/package.json
`inquirer` adds more than 20 MB to the installation size of the package, even though it's not used in the package.
> chore(configure-splash-screen): remove unused package inquirer

- packages/next-adapter/src/withExpo.ts
- packages/webpack-config/README.md
- packages/webpack-config/src/addons/withUnimodules.ts
- packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
- packages/webpack-config/src/plugins/__tests__/ExpoDefinePlugin-test.ts
fix #2156
Created an environment variable that changes the behavior of the Expo webpack-config's define plugin. This prevents `process.env` from being created in Next.js environments.
> Prevent overwriting environment variables in Next.js

- packages/xdl/src/detach/IosNSBundle.ts
Once deployed to Turtle, it should fix https://github.com/expo/turtle/issues/219.
The generated IPA file contains two backup files:
- Payload/ExpoKitApp.app/EXBuildConstants.plist.bak
- Payload/ExpoKitApp.app/EXSDKVersions.plist.bak
I added a clean-up of these in the case when we're building a standalone app.
The way I tested it:
- I built an `.ipa` with Turtle, unpacked it with `unzip`, and noticed the two abovementioned .bak files.
- I made the changes in xdl and yarn-linked it in the local Turtle setup.
- I built another `.ipa`, unpacked it with `unzip`, and noticed the .bak files are gone.
I'm a little terrified of moving those two lines outside of the `if`. Per discussion with @tsapeta - it should be probably safe to do that but I think it's not worth the risk of breaking things.
> [xdl] clean up *.bak files when building ipa

- scripts/publish.js
when someone runs `./scripts/publish.js --bump prerelease`, add an alpha tag so we do `npm publish --tag alpha`. We want to do this because otherwise, npm will mark the prerelease as `latest`
> [scripts] add publish support for alpha tags

- CHANGELOG.md
- scripts/publish.js
- I added missing entries to CHANGELOG.md.
- I added descriptive information only for the latest publish.
- I only added `Packages updated` sections for all other publishes without changelog entires.
- I added a reminder about keeping CHANGLOG.md up to date in `scripts/publish.js`.
> update CHANGELOG.md and add a reminder to the publish script

- packages/expo-cli/bin/expo.js
- Drop support for Node 13 ([end-of-life 2020-06-01](https://github.com/nodejs/Release#end-of-life-releases))
- Drop support for Node 12.0.0-12.13.0. ([LTS started from 12.13.0](https://nodejs.org/en/blog/release/v12.13.0/))
- Node 14 is now "current release", adjust the text accordingly
- Node 10 is now "maintenance LTS", adjust the text accordingly
- Clean up the entry point file to make it easier to edit.
> Update Node.js version check, drop Node v13 support

- packages/config/src/Config.types.ts
- packages/xdl/src/Project.ts
We would like to upload our sourcemaps to Sentry after creating an export. Since we don't publish our assets to Expo (we just create a local CDN, export our assets and then generate a build using Turtle), we cannot rely on the existing `postPublish` hook.
As @fson mentioned in https://github.com/expo/expo-cli/issues/298#issuecomment-454192941, it would be nice to have a `postExport` hook.
I tested this locally by running:
```
/Users/vernondegoede/Sites/expo-cli/packages/expo-cli/bin/expo.js export --dump-sourcemap --public-url=https://localhost:3000
```
Outcome (left some stuff out intentionally):
```
[...]
Saving blah.png
Saving foo.png
Files successfully saved.
Processing asset bundle patterns:
- /Users/vernondegoede/Sites/mollie-mobile/**/*
Building sourcemaps
Configuring sourcemaps …
```
> Allow providing a postExport hook

- packages/xdl/src/Project.ts
When trying to publish a project from inside expo/expo, I am getting the following error:
```
Error: Invalid target: 'undefined'. Debug info:
{
"EXPO_TARGET": "undefined",
"default": "managed"
}
at getDefaultConfig (/Users/eric/.volta/tools/image/packages/expo-cli/3.21.5/node_modules/@expo/metro-config/src/ExpoMetroConfig.ts:45:11)
at Object.loadAsync (/Users/eric/.volta/tools/image/packages/expo-cli/3.21.5/node_modules/@expo/metro-config/src/ExpoMetroConfig.ts:107:23)
at runMetroDevServerAsync (/Users/eric/.volta/tools/image/packages/expo-cli/3.21.5/node_modules/@expo/dev-server/src/MetroDevServer.ts:17:45)
at startDevServerAsync (/@expo/xdl@57.9.13/src/Project.ts:2166:32)
at Object.startAsync (/@expo/xdl@57.9.13/src/Project.ts:2406:5)
at action …
```
> [xdl] set EXPO_TARGET to correct value when starting dev server

- packages/xdl/src/detach/Detach.js
- packages/xdl/src/detach/IosPodsTools.js
- packages/xdl/src/detach/IosShellApp.js
- packages/xdl/src/detach/StandaloneContext.ts
Prerequisite to https://github.com/expo/expo/pull/8762
- As per https://github.com/expo/expo/pull/8762, I changed the directory where `ExpoKit.podspec` is stored.
- Since `app.json` config is not required and partially autogenerated, two conditions checking if the config is present have been broken so I added temporary fix for them – this code will be removed soon anyway.
- Fixed broken condition introduced here https://github.com/expo/expo-cli/commit/6e8fbc4dec5c49eab347f9a0b5f7c4005b09356c#diff-b553f80c6b38ba687014b4801a75d808R209-R210 – `manifest` can be undefined at this place.
Tested together with https://github.com/expo/expo/pull/8762
> [xdl] Fix iOS shell app generation

- packages/pwa/src/index.ts
fix https://github.com/expo/expo-cli/issues/2267
> Use default splash.resizeMode on web

- packages/config/src/Config.ts
- packages/config/src/Config.types.ts
- packages/config/src/ios/Scheme.ts
- packages/expo-cli/src/commands/build/BaseBuilder.ts
- packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
- packages/expo-cli/src/commands/client/clientBuildApi.ts
- packages/expo-cli/src/commands/init.ts
- packages/pwa/src/Manifest.ts
- packages/pwa/src/Manifest.types.ts
- packages/pwa/src/index.ts
- packages/webpack-config/src/env/getConfig.ts
- packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
- packages/webpack-config/src/types.ts
- packages/xdl/src/Exp.ts
- packages/xdl/src/Webpack.ts
Some fields (`name`, `slug`, `version`, `platforms`) are always set in `ExpoConfig` because they have default values.
Make sure the `ExpoConfig` type reflects these default and also rewrite `ensureConfigHasDefaultValues` to allow it to pass type checking.
> Adjust config types to take defaults in account

- .github/workflows/test.yml
- packages/image-utils/README.md
- packages/image-utils/jest.config.js
- packages/image-utils/package.json
- packages/image-utils/src/__tests__/sharp-test.ts
- packages/image-utils/src/sharp.ts
- resolves idea in https://github.com/expo/expo-cli/issues/2267
> [image-utils] add env variable to disable sharp resolution

- packages/expo-cli/src/commands/build/BaseBuilder.ts
- packages/expo-cli/src/commands/publish.ts
- packages/expo-cli/src/commands/url.ts
- packages/expo-cli/src/commands/utils/PublishUtils.ts
- packages/xdl/src/Exp.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/__integration_tests__/UserSessions-test.js
These API calls have been using APIv2 by default since March (https://github.com/expo/expo-cli/pull/1537, https://github.com/expo/expo-cli/pull/1660). The old APIv1 code has been available under the special `EXPO_LEGACY_API` environment variable.
This PR removes these old code paths that are no longer used. This should make it easier to do upcoming changes related to authentication (service accounts), as there will be less code branches to update.
> Remove unused legacy API code

- packages/expo-cli/src/commands/build/AndroidBuilder.ts
- packages/expo-cli/src/commands/build/utils.ts
- packages/expo-cli/src/credentials/actions/promptForCredentials.ts
- packages/expo-cli/src/prompt.ts
- packages/expo-cli/src/prompts.ts
- packages/expo-cli/src/validators.ts
~~If you use the `rawlist`, name or short names aren't displayed. Instead, it uses the value of the question. In this case, it would be either `true` or `false`, which is not a clear definition of what's chosen. This switches to the `list` to show the user what his selection is, without modifying the actual returned value. I double-checked if there weren't any other `rawlist`-questions, but there aren't~~ 😄
~~See https://github.com/SBoudrias/Inquirer.js/issues/889~~
See comments 😄
> [cli] Replace inquirer with prompts in the AndroidBuilder

- packages/config/src/Config.types.ts
- packages/expo-cli/src/__mocks__/projects.ts
- packages/expo-cli/src/commands/build-native/Builder.ts
- packages/expo-cli/src/commands/upload/submission-service/SubmissionService.ts
- packages/expo-cli/src/commands/upload/submission-service/__mocks__/SubmissionService.ts
- packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitter.ts
- packages/expo-cli/src/commands/upload/submission-service/android/__tests__/AndroidSubmitCommand-test.ts
- packages/expo-cli/src/projects.ts
Once https://github.com/expo/universe/pull/5160 is merged, submissions will be associated with projects.
This PR makes sure the project exists on Expo servers before sending the submission request to Submission Service.
> [expo-cli] create app on expo servers before scheduling submission

- packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Update-test.ts
- packages/expo-cli/src/prompts.ts
This is a proposal to simplify testing without the need for mocking and typecasting in all tests.
> [cli] Refactor Android keystore update test with prompt inject

- packages/config/src/android/Manifest.ts
- packages/config/src/android/Updates.ts
- packages/config/src/android/__tests__/Updates-test.js
- packages/config/src/android/index.ts
- packages/config/src/ios/IosConfig.types.ts
- packages/config/src/ios/Updates.ts
- packages/config/src/ios/__tests__/Updates-test.ts
- packages/config/src/ios/index.ts
- packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
- packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
Follow up to #2249, partial step of #1494. 
Adds Updates configuration (both the properties set in app.json, and other properties like the update URL) to the `configureAndroidProjectAsync` and `configureIOSProjectAsync` steps of `expo eject`.
This allows workflows like 
- expo eject
- make release build
- publish update
- get update in app right away
without having to set configuration options (like the URL) manually before making a release build.
Tested manually with defaults and with each of the app.json fields set manually (including owner) and verified that the resulting fields in Expo.plist and AndroidManifest.xml were correct in all cases.
> [config][expo-cli] add updates config to expo eject and expo apply

- packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Update-test.ts
- packages/expo-cli/src/prompts.ts
This reverts commit d338ab2cf46ada4b30f165b6e91d1ed3fac23a40.
inject does not handle all the cases the previous version did.
- if you inject to much or to many variables test won't fail
e.g instead of
```
prompts.inject([
true, // Keystore source - User provided
'test', // Keystore credentials
]);
```
there should be 
```
prompts.inject([
true, // Keystore source - User provided
'test','test','test','test', // Keystore credentials
]);
```
but tests are still passing
- if you inject too many variables next test will get values from the previous one and there is no way to reset state
> Revert "[cli] Refactor Android keystore update test with prompts inject (#2290)"

- packages/expo-cli/package.json
- yarn.lock
- upgrade cli to use traveling fastlane with the latest fixes. In particular, there are promising fixes to potentially solve https://github.com/expo/expo-cli/issues/1631
- Upgrades to `traveling-fastlane-linux/darwin` version 1.15.1. We originally had problems in `1.15.0` from the large bundle sizes, and after cleanup, we've got it down to an unpacked size of 107.8MB for darwin and 107.6 MB for linux, a slight increase from 1.14.0.
> [cli] upgrade fastlane

- packages/expo-cli/src/commands/init.ts
Currently if you want to try out OTA updates in a new bare project, this is what likely happens
- expo init bare
- make release build
- expo publish
- relaunch app, OTA update doesn't load ???
This is because expo-updates depends on some native configuration values in Expo.plist/AndroidManifest.xml. `expo publish` sets these values automatically, but in the flow above, by the time the user runs `expo publish` they have already made a release build without the necessary values.
This PR adds configuring these fields with best-guess values on `expo init`. We need the SDK version and project URL; we can get the SDK version from the project config, and we can make a best guess of the URL by combining the project slug with the logged-in user's username. We also show a message warning the user …
> [expo-cli] configure expo-updates plist/xml values in expo init

- packages/config/src/Config.types.ts
- packages/xdl/src/detach/AndroidShellApp.js
This will allow users to set whether or not the app data can be backed up. We've gotten this request from a few partners (specifically for security reasons), so I'd like to add it in. + it would close a couple canny requests: 
- https://expo.canny.io/feature-requests/p/set-allowbackup-for-android-in-appjson
- https://expo.canny.io/feature-requests/p/disable-back-up-on-android
I tested this with some local turtle builds, setting `android.allowBackup=false` resulted in the proper outcome in androidmanifest, and leaving it out did nothing ✅ 
Before I move forward and open PRs for:
I'd like to get feedback on whether we should control this and other settings like it ([list of potential settings here](https://developer.android.com/guide/topics/manifest/application-element)) via an …
> [xdl] add allowBackup customization feature for android

- packages/expo-cli/src/prompt.ts
- packages/xdl/src/Api.ts
- packages/xdl/src/Exp.ts
- packages/xdl/src/credentials/Credentials.ts
- packages/xdl/src/tools/ModuleVersion.ts
I imagine we could do a separate cleanup to get rid of these a bit later, but for now I just want to make it clearer that new code should not depend on these as they are going away eventually.
- xdl.Api
- xdl.Exp.determineEntryPoint
- xdl.Exp.getPublishInfoAsync
- xdl.Credentials
- xdl.ModuleVersion
- expo-cli/src/prompt.ts
(was already deprecated, but add the JSDoc tag to make it more prominent)
Also related: https://github.com/expo/expo-cli/issues/2282
> Mark functions as deprecated

- packages/traveling-fastlane/Rakefile
when i tried publishing traveling fastlane today, I kept getting a timeout message. I figured the package could be too large and my upload speeds not fast enough to put everything to npm before a default timeout. Someone on Stackoverflow suggested this [undocumented timeout flag](https://stackoverflow.com/a/61488783/8611543). It's not in any of the `npm publish` docs, but when i used it, my publish went through successfully. Could be helpful to others in the future!
```
npm notice === Tarball Details === 
npm notice name:          @expo/traveling-fastlane-linux          
npm notice version:       1.15.0                                  
npm notice package size:  24.4 MB                                 
npm notice unpacked size: 173.2 MB                                
npm notice shasum: …
```
> [traveling-fastlane] undocumented timeout flag

- packages/expo-cli/src/commands/eject/Eject.ts
- packages/expo-cli/src/commands/init.ts
- packages/package-manager/src/CocoaPodsPackageManager.ts
- packages/package-manager/src/PackageManager.ts
The recommended way to install cocoapods is with `sudo gem install`, but more often than not they're installing with homebrew on mac. This PR attempts to address this issue by prompting the user to enter their password in interactive mode.
- Fix sudo-prompt integration - not tested as I don't have a win32 machine. We also often skip pod install on non-darwin machines.
- Use sudo on mac and linux - tested and works.
- `pod-install --non-interactive` will skip prompts.
> [package manager] Prompt the user to use sudo to install CocoaPods

- CHANGELOG.md
- packages/expo-cli/src/credentials/views/Select.ts
- fix reading list of apps
- read owner field when selecting experience from current directory
> fix(expo-cli): credentials:manager read credentials fix

- packages/expo-cli/src/credentials/views/IosDistCert.ts
- packages/expo-cli/src/credentials/views/IosPushCredentials.ts
fixes problem in credential manager when the user specifies push key manually and appleCtx is not intialized.
for distribution certificate this worked because there is `await ctx.ensureAppleCtx();`, but because adding teamId and teamName is obsolete(`newDistCert` and `newPushKey` have already teamId) I removed it. We don't need to force users to specify their credentials just for that.
> fix(expo-cli): use user provided teamId, don't access appleCtx

- packages/expo-cli/src/commands/build/AndroidBuilder.ts
- packages/expo-cli/src/commands/build/index.ts
- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- packages/expo-cli/src/commands/eject/ConfigValidation.ts
- packages/expo-cli/src/commands/eject/Eject.ts
- The build:ios bundle ID prompt is awesome, this PR adds the same functionality for Android and shares the methods across `expo eject`, `expo build:android`, and `expo build:ios`
> [expo-cli] Combined ID prompts for build and eject

- packages/webpack-config/README.md
- packages/webpack-config/package.json
- packages/webpack-config/src/__tests__/webpack.config-test.js
- packages/webpack-config/src/env/__tests__/validate-test.js
- packages/webpack-config/src/env/validate.ts
- packages/webpack-config/src/types.ts
- yarn.lock
- yup is not needed.
- deleted the deprecated `polyfill` property.
> [webpack-config] Remove yup validation

- packages/config/src/ios/utils/Xcodeproj.ts
Fixes #2312
Fixes #2326
I noticed `glob` returning paths with the forward-slash on Windows environments, even though the `path.sep` correctly returns a backslash. This uses the `path.basename` to resolve the last folder, regardless of the platform separator. 
To outline the issue, here is a log that I used in `getProjectName` to log the exact output of the `projectRoot`, `sourceRoot`, `sourceRootParts`, `path.sep`, the bad result (old implementation), and the good result (new implementation):
```
getProjectName {
projectRoot: 'C:\\Users\\cedri\\Desktop\\expo-cli\\test-project',
sourceRoot: 'C:/Users/cedri/Desktop/expo-cli/test-project/ios/testproject',
sourceRootParts: [ 'C:/Users/cedri/Desktop/expo-cli/test-project/ios/testproject' ],
resultBad: …
```
> fix(config): use basename to avoid mixed path separators from glob

- packages/xdl/src/Project.ts
- packages/xdl/src/__tests__/Project-test.ts
- packages/xdl/src/__tests__/__snapshots__/Project-test.ts.snap
> Add owner field support to expo start

- packages/expo-cli/src/appleApi/authenticate.ts
Fixes https://github.com/expo/expo-cli/issues/2333
If the user passes invalid Apple ID credentials we prompt him for them again.
> [expo-cli] give another attempt to enter apple id credentials

- packages/expo-cli/src/commands/push-creds.ts
- add owner support for `expo push:android:{upload, show, clear}` commands
- umbrella issue tracked here: https://github.com/expo/expo-cli/issues/2150
- also added useful debug messages (show project and if you are a proxy user, show that you are working on a project on behalf of the main user)
fixes https://github.com/expo/expo-cli/issues/1294
> [cli] add owner support for push:android cmds

- packages/webpack-config/e2e/__tests__/basic-test.js
- packages/webpack-config/e2e/basic/App.js
- packages/webpack-config/e2e/basic/font.ttf
- packages/webpack-config/e2e/basic/random.bacon
- packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
- packages/webpack-config/src/loaders/createAllLoaders.ts
- packages/webpack-config/src/loaders/createFontLoader.ts
In the webpack upgrade the loaders started loading files as modules:
```js
const asset = require('img.png');
console.log(asset);
// Module {default: "data:image/png;base64,", __esModule: true, Symbol(Symbol.toStringTag): "Module"}
```
This PR changes all of the assets to load like metro bundler:
```js
const asset = require('img.png');
console.log(asset);
// data:image/png;base64,
```
I added E2E tests to ensure fonts, images, and wildcard files are loaded as expected.
fix https://github.com/expo/expo-cli/issues/2348
> [webpack-config] Interop assets like Metro bundler

- .github/workflows/test.yml
Codecov keeps randomly failing our tests so we're temporarily removing it.
> Disable codecov

- packages/xdl/src/Project.ts
Following up on some internal discussions, we'd like to start tracking the SDK version of projects that send `Start Project` and `Serve Manifest` events to segment so that we can get an idea of the distribution of development usage across supported SDK versions over time.
I added `sdkVersion` as an extra property when these two events are logged. Ran a project without any issues. @tcdavis does `sdkVersion` need to be added to a table somewhere in our analytics, or will it start being saved automatically?
Did not make a changelog entry as this is not a user-facing change (but let me know if I should anyway).
> [xdl] add sdkVersion to Start Project and Serve Manifest events

- packages/xdl/src/xdl.ts
`source-map-support` causes issues with line numbers when using typescript and jest.
Brief mentions of the issue at:
https://github.com/kulshekhar/ts-jest/issues/727
https://github.com/celo-org/ganache-core/pull/21
It seems the only fix is not to register it when in tests.
This was added a while back in https://github.com/expo/expo-cli/commit/5204b12a83fe59eec2ee7550123d9623c1c4dec2 without much context (or context was lost in phabricator) so I can't really assess whether this is going to break something else, but I think it should be okay.
Test Plan:
- Patch into www in combination with https://github.com/expo/universe/pull/5373 and cause a test to fail, ensure the correct line numbers are reported.
> [xdl] Fix jest typescript line number reporting

- packages/xdl/src/Project.ts
This PR fixes an issue with expo-cli@3.22.x where the number of logged `Start Project` and `Serve Manifest` events are significantly lower than expected.
Paired with @animeeples to investigate and we found the root cause to be that by the time the `Serve Manifest` event should be sent, the `_userId` field in Analytics.ts is not set, meaning the following statement evaluates to false and the event is never sent to segment: 
https://github.com/expo/expo-cli/blob/d7e4d4d6440f8db81282c48ab11248d214f1ec49/packages/xdl/src/Analytics.ts#L41
Following the chain of methods that set the `_userId` field, it looks like this issue was introduced by https://github.com/expo/expo-cli/commit/553eb01540554070c2e8b3894dbb4314ba2cb484 which eliminated a call to `UserManager.ensureLoggedInAsync()` …
> [xdl] fix analytics for expo start

- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/ExponentTools.ts
- packages/xdl/src/detach/Logger.ts
From https://github.com/expo/turtle/issues/221:
> When running `turtle build:android` the logger outputs a lot of dots, which introduces noise for later analysis
I added a logger line transformer which drops lines that only contain dots.
- I yarn-linked `@expo/xdl` in my local `turtle-cli` repository.
- I ran an Android build and verified that no dots are displayed when Gradle Wrapper is downloading the appropriate Gradle version: <img width="1251" alt="Screenshot 2020-07-14 at 15 31 38" src="https://user-images.githubusercontent.com/5256730/87432541-6ec96b80-c5e8-11ea-9ce2-801d3aa5a4a1.png">
> [xdl] don't log dots when downloading gradle

- packages/xdl/src/detach/AndroidShellApp.js
Feature request from `turtle` - https://github.com/expo/turtle/issues/226:
> Allow users to enable the --stacktrace option for their gradle builds
> Making this a little more general, it'd be awesome to just have an option to pass custom args to gradle
I made it possible to pass custom gradle args to the `createAndroidShellAppAsync` function. We call this function to build an Android standalone app in Turtle.
I tested these changes locally.
> [xdl] allow for passing user provided gradle args

- packages/expo-cli/src/commands/upload.ts
- packages/expo-cli/src/commands/upload/IOSUploader.ts
This fixes https://github.com/expo/expo-cli/issues/2280.
NB: in case of conflict we chose to prioritize the flag over the env variable.
Joint with @quinlanj
> [expo-cli] consolidate env variables.

- CHANGELOG.md
- packages/expo-cli/src/commands/upload.ts
- packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts
- packages/expo-cli/src/commands/upload/submission-service/android/__tests__/AndroidSubmitCommand-test.ts
- packages/expo-cli/src/commands/upload/submission-service/android/types.ts
Fixes https://forums.expo.io/t/github-actions-uploading-android-from-ubuntu-runner-use-submission-service/40593
The command option for specifying archive type is called `--type`, yet in the codebase, we were using `archiveType`. We made this error because the commander options weren't typed.
Things I did in this PR:
- I set the correct TS type for upload:android options.
- I renamed `archiveType` to `type`.
- I updated tests.
> [expo-cli] submission service: fix passing archive type from command line

- CHANGELOG.md
- packages/expo-cli/src/commands/upload/submission-service/utils/errors.ts
Follow-up PR to https://github.com/expo/turtle-v2/pull/258.
I've noticed that we're not providing good error messages when we failed to download the archive file.
There are two main reasons for this to happen:
- the user provided an incorrect URL (404 error)
- the download URL has expired (403 error from AWS S3).
In this PR, I'm adding proper error messages for these issues.
> [expo-cli] upload:android - add better error messages for issues with downloading archive file

- packages/configure-splash-screen/README.md
when running 
```
yarn run @expo/configure-splash-screen [options] <backgroundColor> [imagePathOrDarkModeBackgroundColor] [imagePath] [darkModeImagePath]
```
It says command not found.
Changing command to 
```yarn run configure-splash-screen [options] <backgroundColor> [imagePathOrDarkModeBackgroundColor] [imagePath] [darkModeImagePath]```
works fine.
> doc: expo-splash-screen: fix a command instrution

- packages/config/src/Config.types.ts
With the release of SDK 38 the new notifications API "you’ll need to explicitly opt into the new API for now by setting android.useNextNotificationsApi to true in your app configuration". This change implements this value as detailed in the release notes found here - https://blog.expo.io/expo-sdk-38-is-now-available-ab6cd30ca2ee
> Implement "useNextNotificationsApi" configuration SDK 38

- packages/xdl/src/Android.ts
- packages/xdl/src/Project.ts
Stop ADB daemon only when expo launched it.
Fix a behavior introduce by #1876 it kills ADB daemon even if another process uses it.
Test 1
```
#ADB is not running
expo start
#ctrl-c expo
#adb is not running
```
Test 2
```
adb start-server
#use ADB (adb push, scrcpy....)
expo start
#ctrl-c expo
#ADB is always running
```
> @sviande/adb kill

- CHANGELOG.md
- packages/expo-cli/src/prompt.ts
> [expo-cli] check `when` field when inquirer is used in noninteractive mode

- CHANGELOG.md
- packages/expo-cli/src/commands/fetch/ios.ts
`fetch:ios:certs`  creates push notification key base64 encoded
> [expo-cli] base64 decode when saving p8 file

- CHANGELOG.md
- packages/expo-cli/src/commands/fetch/ios.ts
- packages/expo-cli/src/credentials/views/IosPushCredentials.ts
Reverting changes made in #2404 (I initially assumed that push key is base encoded on a server)
Remove encoding from `getPushKeyFromParams`
> [expo-cli] revert PR #2404 and remove encoding from IosPushCredentials

- packages/expo-cli/src/accounts.ts
Currently, if user is not logged in, the function string is printed in the error message because of a typo. This commit fixes it so that the program name is displayed instead.
> [expo-cli] don't print function string in error message

- packages/expo-cli/src/appleApi/authenticate.ts
- packages/expo-cli/src/commands/build/BaseBuilder.ts
- packages/expo-cli/src/commands/build/index.ts
- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- packages/expo-cli/src/commands/client/index.ts
- packages/expo-cli/src/credentials/context.ts
- bestEfortAppleCtx needs to be triggered before clearing credentials (because a user might want to revoke them)
- removing unused code
- env EXPO_APPLE_PASSWORD should be ignored if `--apple-id` is not specified( users in `expo credentials:manager` have seen error to specify apple-id even though that command does not support it)
- passing appleId and password to ensureAppleCtx relies on the order of calls
> [expo-cli] cleanup apple id credentials logic

- packages/webpack-config/src/addons/withUnimodules.ts
- fix https://github.com/expo/expo-cli/issues/2345
Next.js was throwing the following node.js error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
at validateString (internal/validators.js:120:11)
at Module.require (internal/modules/cjs/loader.js:1019:3)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.react-native-web/dist/exports/AppRegistry (/Users/evanbacon/Documents/GitHub/lab/my-next-expo-app/.next/server/static/development/pages/_document.js:813:18)
at __webpack_require__ (/Users/evanbacon/Documents/GitHub/lab/my-next-expo-app/.next/server/static/development/pages/_document.js:23:31)
at Module../pages/_document.js (/Users/evanbacon/Documents/GitHub/lab/my-next-expo-app/.next/server/static/development/pages/_document.js …
```
> Fix next-adapter `external` bug

- packages/config/src/ios/BundleIdentifier.ts
- packages/config/src/ios/Entitlements.ts
- packages/config/src/ios/IosConfig.types.ts
- packages/config/src/ios/ProvisioningProfile.ts
- packages/config/src/ios/__tests__/BundleIdentifier-test.ts
- packages/config/src/ios/__tests__/ProvisioningProfile-test.ts
- packages/config/src/ios/__tests__/__snapshots__/BundleIdentifier-test.ts.snap
- packages/config/src/ios/__tests__/__snapshots__/ProvisioningProfile-test.ts.snap
- packages/config/src/ios/__tests__/fixtures/project.pbxproj
- packages/config/src/ios/index.ts
- packages/config/src/ios/utils/Xcodeproj.ts
- packages/expo-cli/__mocks__/ora.js
- packages/expo-cli/src/commands/build-native/AndroidBuilder.ts
- packages/expo-cli/src/commands/build-native/__tests__/build-test.ts
- packages/expo-cli/src/commands/build-native/build.ts
- packages/expo-cli/src/commands/build-native/credentials.ts
- packages/expo-cli/src/commands/build-native/iOSBuilder.ts
- packages/expo-cli/src/commands/build-native/index.ts
- packages/expo-cli/src/commands/build-native/utils/git.ts
- packages/expo-cli/src/commands/build-native/utils/misc.ts
- packages/expo-cli/src/credentials/local/credentialsJson.ts
- packages/expo-cli/src/credentials/utils/__tests__/provisioningProfile-test.ts
- packages/expo-cli/src/credentials/utils/provisioningProfile.ts
- packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
For generic iOS builds, we want `expo-cli` to autoconfigure the Xcode project so that it's buildable by Turtle workers. 
Generally, in order to do that, a user would need to:
- **have a Mac!**
- if the app's credentials were generated with expo-cli:
- add the provisioning profile to `~/Library/MobileDevice/Provisioning\ Profiles`
- add the distribution certificate to the keychain
- open Xcode
- choose the appropriate provisioning profile on the `Signing & Capabilities` tab
- commit changes to the `project.pbxproj` file
The whole process is described in https://github.com/expo/turtle-v2/blob/master/TUTORIAL.md
We need to automate this process so the user doesn't need to perform tedious tasks whenever he regenerates his credentials or sets up a new project. We also want to allow users to …
> [expo-cli][config] EAS builds: iOS project autoconfiguration

- packages/expo-cli/package.json
- packages/expo-cli/src/commands/eas-build/build/__tests__/build-test.ts
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/templates/gradleContent.ts
- packages/expo-cli/src/commands/eas-build/build/types.ts
- packages/expo-cli/src/commands/eas-build/build/utils/git.ts
- packages/expo-cli/src/commands/eas-build/index.ts
- yarn.lock
For generic Android builds, we want `expo-cli` to autoconfigure Gradle to build it on turtle workers, instead of the manual step described in https://github.com/expo/turtle-v2/blob/master/TUTORIAL.md.
- I updated the `configureProjectAsync` for Android to write the required gradle script (`eas-build.gradle`)
- The gradle script is then imported in user's `build.gradle` file
- It hooks into gradle script and sets the appropriate credentials for release builds based on the `credentials.json` file
- After the changes, it shows the diff and asks the user to commit the changes
- I initialized a new project with `expo init` and select the `bare-minimal` template
- I created a minimal `eas.json`.
- I ran `expo eas:build --platform android`:
- I generated credentials.
- I observed that the gradle …
> [expo-cli] EAS builds: Android project autoconfiguration

- packages/expo-cli/src/__tests__/easJson-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/easJson.ts
For generic Android builds, `buildCommand` is an argument passed to `./gradlew`. Because of that, it'd be better to name it `gradleCommand` to make it self-explanatory.
> [expo-cli] rename eas.json field: buildCommand -> gradleCommand

- packages/config/src/android/Orientation.ts
- packages/config/src/android/__tests__/Orientation-test.js
Fixes #2429 
Tested by just ejecting project and checking if orientation in manifest is correct. Also wrote 2 tests and ran `jest`.
> [expo-cli][eject] Fix generated orientation in AndroidManifest

- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/easJson.ts
- I added the `artifactPath` field for generic iOS build profiles 
- I set `app-bundle` as the default build type for managed Android profiles. (It's not relevant for now but I've decided to fix it now)
> [expo-cli] minor eas.json improvements

- packages/webpack-config/src/loaders/createBabelLoader.ts
This enables default support in Expo web for use-expo hooks packages.
> [webpack-config] Add default support for use-expo namespace

- packages/expo-cli/src/commands/eas-build/build/credentials.ts
It'd be useful to log which credentials (local or remote) will be used for the build.
> [expo-cli] eas builds: log credentials source

- packages/expo-cli/src/credentials/local/__tests__/credentials-json-test.ts
- packages/expo-cli/src/credentials/local/credentialsJson.ts
- packages/expo-cli/src/credentials/provider/AndroidCredentialsProvider.ts
- packages/expo-cli/src/credentials/provider/__tests__/AndroidCredentialsProvider-test.ts
- packages/expo-cli/src/credentials/provider/__tests__/iOSCredentialsProvider-test.ts
- packages/expo-cli/src/credentials/provider/iOSCredentialsProvider.ts
It's not clear what credentials are used during build, misconfiguration of credentials.json might cause expo-cli to use remote ones without any info for the user
> [expo-cli] turtle-v2 credentials change hasLocal,hasRemote bahviour

- packages/expo-cli/src/credentials/views/AndroidKeystore.ts
This makes sure people don't accidentally press enter when they are asked questions. With this, people _have_ to input `y` first and confirm with enter.
> [expo-cli] Force users to confirm deleting android credentials

- packages/package-manager/src/CocoaPodsPackageManager.ts
Currently running `npx pod-install`(or `pod-install` installed locally) in the React Native macOS projects result in error message: "CocoaPods is not supported in this project". 
This simple PR fixes this issue by adding test for `macos` directory as a root of CocoaPods project.
> [package-manager] fix pod-install for macOS projects

- packages/xdl/src/detach/AndroidShellApp.js
This is a replacement PR for #2307, and part of https://github.com/expo/expo/issues/9499. It adds some annotations to the permission list to know why permissions are or were added. This, together with the new Danger script that warns people when adding new permissions to android manifests should keep this up to date in the future 🚀 
The following permissions are added to the list:
- `android.permission.USE_BIOMETRIC` - Is part of the new Biometric Prompt in Android for `expo-local-authentication`.
- `android.permission.SYSTEM_ALERT_WINDOW` - Is only required for debugging (e.g. in Expo Client), [not required in production apps](https://reactnative.dev/docs/removing-default-permissions#docsNav).
- `android.permission.REQUEST_INSTALL_PACKAGES` - This is [dangerous/signature …
> [xdl] Expand Android permissions blacklist and add annotations

- packages/expo-cli/src/commands/eject/ConfigValidation.ts
- packages/expo-cli/src/commands/eject/Eject.ts
- expo-cli supports running and publishing projects without a config or with a dynamic .js config so eject should too.
- crna templates don't have configs but people may want to eject them immediately to use them as bare templates.
- Strip slashes from name android package name suggestion to be more resilient. 
- ex: I run `expo eject` in a project folder `my-cool-app`  (which doesn't have a config or name), the suggestion would've been blank cuz `com.bacon.my-cool-app` is invalid. Now it'll recommend `com.bacon.mycoolapp`.
- When the config file doesn't exist, write the generated config to `./app.json`
- we don't need to account for custom config paths `--config` because those are validated beforehand.
- Remove code that attempts to read from `./app.json` which fails when a project uses …
> [cli][eject] Support projects with dynamic or missing configs

- CHANGELOG.md
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/AndroidBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/utils/ios.ts
- packages/expo-cli/src/commands/eas-build/credentialsSync/action.ts
- packages/expo-cli/src/commands/eas-build/index.ts
- packages/expo-cli/src/credentials/credentialsJson/__tests__/read-test.ts
- packages/expo-cli/src/credentials/credentialsJson/read.ts
- packages/expo-cli/src/credentials/credentialsJson/update.ts
- packages/expo-cli/src/credentials/local/index.ts
- packages/expo-cli/src/credentials/local/update.ts
- packages/expo-cli/src/credentials/provider/AndroidCredentialsProvider.ts
- packages/expo-cli/src/credentials/provider/iOSCredentialsProvider.ts
- packages/expo-cli/src/credentials/views/SetupAndroidKeystore.ts
- packages/expo-cli/src/credentials/views/SetupIosBuildCredentials.ts
We need a simple way to switch between different methods of providing credentials
Added new command
- tested manually
- [in-progress] implement tests for new command
> [expo-cli] command for syncing credentials.json and credentials on www

- packages/expo-cli/src/commands/__tests__/publish-info-test.ts
- packages/expo-cli/src/commands/__tests__/publish-modify-test.ts
- packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
- packages/expo-cli/src/credentials/__tests__/api-android-basic-test.ts
- packages/expo-cli/src/credentials/__tests__/api-ios-basic-test.ts
- packages/expo-cli/src/credentials/api/AndroidApi.ts
- packages/expo-cli/src/credentials/api/AndroidApiV2Wrapper.ts
- packages/expo-cli/src/credentials/test-fixtures/mocks-android.ts
- packages/expo-cli/src/credentials/test-fixtures/mocks-constants.ts
- packages/expo-cli/src/credentials/test-fixtures/mocks-context.ts
- packages/expo-cli/src/credentials/test-fixtures/mocks-ios.ts
- packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Remove-test.ts
- packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Update-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosDistCert-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosProvisioningProfile-test.ts
- packages/expo-cli/src/credentials/views/__tests__/IosPushCredentials-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupAndroidKeystore-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosDist-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupIosPush-test.ts
- packages/expo-cli/src/credentials/views/__tests__/SetupProvisioningProfile-test.ts
The previous version had separate approach for mocking context for android in iOS. Without those changes is hard to mock context in cases where both android and ios credentials are used
- Added apiv2 wrapper for android credentials (the same as in iOS version) 
- Implemented one ctx mock with mocked credentials for both platforms
- unified naming of some helper function between platforms
> [expo-cli] unify credentials fixtures between android & ios

- packages/xdl/src/detach/IosPodsTools.js
This will fix the iOS shell app build job in the expo/expo repo once we add SDK 39. Currently it's failing because the rendered Podfile in the shell app excludes unimodules that are needed in SDK 39 -- `expo-splash-screen` and `expo-updates`. This PR will make the excluded dependencies in the rendered Podfile match the current `ios/Podfile` in the expo/expo repo, while also still supporting older SDK versions.
Tested locally and the job succeeded.
TODO: we need to figure out a way to move this code out of XDL and into the expo repo -- at least determining the excluded unimodules, but potentially the entire process of generating the shell app workspace, now that we don't need to support ejecting to ExpoKit.
> [xdl] update ios Podfile excluded unimodules for SDK 39

- packages/expo-cli/src/commands/doctor.ts
- packages/xdl/src/project/Doctor.ts
I did 2 things here:
1. This makes _absolutely_ sure the Expo services check is only executed with `$ expo doctor` and not commands like `$ expo start` or `$ expo publish`.
2. Disabled the `exp.host` check, people report on the forum that this might be intermittent issues. Eventually, I could randomly reproduce this locally.
> [expo-cli] Only run expo service checks from the doctor command

- packages/webpack-config/README.md
- packages/webpack-config/e2e/__tests__/basic-test.js
- packages/webpack-config/e2e/basic/App.js
- packages/webpack-config/e2e/basic/app.config.js
- packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
- packages/webpack-config/src/__tests__/webpack.config-test.js
- packages/webpack-config/src/index.ts
- packages/webpack-config/src/types.ts
- packages/webpack-config/src/webpack.config.ts
- packages/xdl/src/Webpack.ts
We'll be making offline support opt-in going forward due to increased complexity involved with automatically enabling them.
This effectively makes PWAs not work out of the box.
- https://github.com/expo/expo/pull/9821
- https://github.com/expo/fyi/pull/12
> [webpack-config] Disable offline support

- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/index.ts
- packages/expo-cli/src/credentials/context.ts
- packages/expo-cli/src/exp.ts
- packages/xdl/src/project/Doctor.ts
You may want to run this in an app created with `npx react-native init` and you will not have an Expo SDK version in that context, so we should support that.
> [expo-cli][xdl] Skip SDK version validation for eas:build

- packages/expo-cli/src/commands/start/TerminalUI.ts
- packages/xdl/jest/integration-test-config.js
- packages/xdl/jest/integration-test-config.json
- packages/xdl/jest/integration-test-setup.js
- packages/xdl/package.json
- packages/xdl/src/Api.ts
- packages/xdl/src/ApiV2.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/User.ts
- packages/xdl/src/UserSettings.ts
- packages/xdl/src/__integration_tests__/Simulator-test.ts
- packages/xdl/src/__integration_tests__/UserManager-test.ts
- packages/xdl/src/__integration_tests__/UserSessions-test.ts
- packages/xdl/src/__tests__/Project-publishAsync-test.ts
- packages/xdl/src/__tests__/User-test.ts
This integrates the `EXPO_TOKEN` authentication method, implemented as a `Bearer` authorization token.
- **Added the token retrieval in `UserSettings`**
I think this is the proper place for that. Eventually, it's an environmental setting but still set by the user. We could also move it to the `UserManager` itself, but I think using it from `UserSettings` makes more sense.
- **Added token in the `getSessionAsync` method**
When integrating the robots, I noticed this method is used in other areas to see if people are authenticated. With this, the DevTools also uses the proper username and other authentication stuff (e.g. username).
- ~~**Added to API v1 and v2**~~
~~I can't find traces of API v1 being used somewhere, but I added it using almost identical implementation. Again, the token is …
> [xdl] Add EXPO_TOKEN authentication method

- packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
Cannot run apply after changing the name of the project:
1. Change name in app.json
2. `expo apply`
3. Fails because it looks for `ios/NewName/*` when the folders haven't been renamed.
- glob for the AppDelegate first, if that fails then use the config name for the iOS named folder.
> [apply] Fix iOS name changing

- packages/expo-cli/src/commands/apply.ts
- packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
- packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
- packages/expo-cli/src/commands/eject/ConfigValidation.ts
Right now `expo apply` crashes if the project config doesn't have a bundle ID or package name defined. This prompts the user for the appropriate values using the same logic as eject.
This code does however get executed twice now when ejecting, but it might be ok since it's important that the command bails out as quickly as possible in `expo eject`.
Also added the ability to run in projects without Expo configs. I modified the order of operations, so Android config is done first, this way the package name is optimized for being shared across iOS and Android.
> Prompt for bundle ID and package name in expo apply

- packages/config/src/android/Scheme.ts
Android schemes were being added incorrectly each time apply was being run, this caused the manifest to get bigger on every run of `expo apply`. I fixed this by using the same logic as `uri-scheme`. We now remove all of the schemes, then add them all back each time, we also append the object correctly so it doesn't get duplicated.
I also added an extra warning (in the same place we throw in uri-scheme) which warns the user that their manifest is not properly configured, this warning also links to an fyi for how to fix the issue.
- Current tests should cover this.
> [apply] Fix android schemes being added incorrectly

- packages/config/src/ios/Scheme.ts
- packages/config/src/ios/utils/Xcodeproj.ts
- packages/expo-cli/package.json
- packages/expo-cli/src/commands/eas-build/build/__tests__/build-test.ts
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/types.ts
- packages/expo-cli/src/easJson.ts
- yarn.lock
This fixes an issue with building a project initialized with `react-native init`. Such a project has multiple schemes in the Xcode project. `fastlane` is unable to build the project if we don't specify the target explicitly. This PR fixes it by displaying a prompt select to choose the build scheme if multiple schemes were detected. If the CLI is run with the `--non-interactive` flag then the first scheme (without the `tvOS` suffix) is picked.
> [expo-cli] eas build: allow choosing scheme for ios project build

- CHANGELOG.md
- packages/expo-cli/src/commands/init.ts
Fixes #2472 
Changed default name for bare projects to match regex pattern in `expo init`.
> [expo-cli] Fixed default bare project name for 'expo init'

- packages/image-utils/package.json
- yarn.lock
Fixes #2511
I added the 2 missing dependencies to `image-utils`, used in `expo-optimize`.
- `chalk`, because it's [used here](https://github.com/expo/expo-cli/blob/master/packages/image-utils/src/Image.ts#L1).
- `getenv` + `@types/getenv`, because it's [used here](https://github.com/expo/expo-cli/blob/master/packages/image-utils/src/sharp.ts#L2)
> [image-utils] Add missing dependencies

- packages/pwa/src/Manifest.ts
Currently, there is no possibility to prevent the injection of favicons. This fix allows users to specify an empty favicon and consequently no favicon will be injected nor generated.
> [webpack-config] fix: handle empty favicons

- packages/pwa/src/Manifest.ts
- packages/pwa/src/__tests__/Manifest-test.ts
- Skip favicon generation by passing an empty string `{ web.favicon: "" }`
- Wrote a unit test for this functionality -- missing in #2423
> [webpack-config] Allow empty string to skip favicon generation - added tests

- packages/config/src/Config.types.ts
Following the information provided both in this file and on the docs (found here: https://docs.expo.io/workflow/configuration/#android) - "The default in Expo (Client and in standalone apps) is `false`". Drawing from this I have concluded that this value is not actually required, hence updating the type declaration to reflect this.
> Update "googleMobileAdsAutoInit" to be optional

- packages/expo-cli/package.json
- packages/expo-cli/src/appleApi/authenticate.ts
- packages/expo-cli/src/appleApi/keychain.ts
- packages/expo-cli/src/commands/upload/IOSUploader.ts
- packages/xdl/src/UserSettings.ts
- yarn.lock
- Entering your apple ID and password can get tiring, especially if the command fails and you need to do it multiple times.
- I'm opening this PR as a discussion / proposal for adding keychain support on mac to store the Apple ID password. This is akin to Fastlane which has the same functionality.
- This PR also implements a feature to save the last used email between sessions and suggests it as the default value for the next time.
- When a user has `EXPO_NO_STORE_PASSWORD` truthy, the password and email will be deleted next time the CLI attempts to access it.
- I've also combined the auth logic for `upload:ios` and the other auth systems.
- Finally, since the username and password are being passed to Fastlane, I propose we store the password using the same keychain service name as …
> [Proposal] Implemented keychain storage for Apple ID

- packages/expo-cli/package.json
- packages/expo-cli/src/commands/publish.ts
- yarn.lock
Part 1 of cleaning up, upload logs. This addresses the last two lines.
- format the terminal links better on default terminals that don't support links
- copy project page to the clipboard at the end
- utilize dimming and font treatments better
- remove redundant code
> [cli] Clean up upload results logs

- CHANGELOG.md
- packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitter.ts
Android upload using submission service does not result in a non-zero exit code for failed uploads. This makes the command silently fail in CI environments
- closes #2528 
Run `expo upload:android --use-submission-service --key ./invalid/google/account.json` in a project ensuring that the account does not have access to upload the app. Ensure that the exit code is non-zero. Can be easily seen in bash by using the `echo $?` command after running the upload command.
> Added exitCode of 1 when android upload fails

- CHANGELOG.md
- packages/expo-cli/src/commands/generate-module/configureModule.ts
Due to https://github.com/expo/expo/pull/9319, package `expo-module-templates` changed directory structure (`kotlin` was renamed to `java` under `android/src/main`).
Currently, npm-published `expo-module-template@8.3.1` tagged as `latest` still has `kotlin` directory, but version `8.4.0`/`next` has that directory renamed.
Current CLI `expo generate-module` expects `kotlin` as directory. This PR prepares it to also expect `java`.
Created a function to check which of these directories exist. If both - choose java; if none - throw human readable error.
Tested for both `expo-module-template` versions (`latest` and `next`). Also tested for package with invalid directory structure.
> [expo-cli] Fix 'generate-module' to support latest expo-module-template

- packages/expo-cli/src/commands/eas-build/build/__tests__/build-test.ts
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/AndroidBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/metadata.ts
- packages/expo-cli/src/commands/eas-build/build/types.ts
- packages/expo-cli/src/easJson.ts
I added sending some basic build metadata to www: 
- app version (`expo.version` from `app.json`)
- expo-cli version
- workflow - either `generic` or `managed`
- credentials source - `auto`, `local` or `remote`
- sdk version - the expo package version
> [expo-cli] eas build: collect build metadata

- CHANGELOG.md
- packages/image-utils/src/jimp.ts
`.background()` wasn't working, unless setting the background color to white. 
`composite()` the original image on top of an image of the same height & width with the specified background color
call 
```
await generateImageAsync(
{ projectRoot, cacheType: 'my-cache-type' },
{
src: icon,
width: iconSizePx,
height: iconSizePx,
resizeMode: 'cover',
backgroundColor: "#FF69B4"  // use any color but white
}
)
```
where `icon` is an image with transparency before & after this change to see
> [image-utils] fix: backgroundColor setting when using jimp.resize

- packages/dev-server/src/MetroDevServer.ts
Without this, bundles are ~2x larger on hello world projects.
> [dev-server] use minify in prod

- CHANGELOG.md
- packages/expo-cli/src/commands/eas-build/build/__tests__/credentials-test.ts
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/credentials.ts
- packages/expo-cli/src/credentials/provider/AndroidCredentialsProvider.ts
- packages/expo-cli/src/credentials/provider/__tests__/AndroidCredentialsProvider-test.ts
- packages/expo-cli/src/credentials/provider/__tests__/iOSCredentialsProvider-test.ts
- packages/expo-cli/src/credentials/provider/iOSCredentialsProvider.ts
We want people to be able to skip checking for remote credentials.
> [expo-cli] add --skip-credentials-check option

- packages/xdl/src/detach/IosPodsTools.js
We don't advertise `expo-image` as production ready yet
> [xdl] Remove expo-image from SDK39 standalone apps

- CHANGELOG.md
- packages/expo-cli/src/commands/generate-module/configureModule.ts
- packages/expo-cli/src/commands/generate-module/fetchTemplate.ts
- packages/expo-cli/src/commands/generate-module/promptQuestionsAsync.ts
Continuation of #2510 (that fix was rather critical). Trying to make `expo generate-module` more universal and generic.
- Android test files are now properly renamed
- Java package is now automatically detected based on directory structure
- NPM template package name accepts templates with tags `@next` and `@latest` _(shall we make it less restrictive to accept any string as tag?)_
- Package names are now properly handled regardless of having `expo-` prefix.
- iOS pod name always defaults to `EXPackageName` (it didn't always add `EX` prefix before) - _idk if it's desirable change_.
- IO optimizations - parallelised some file processing.
Tested manually using custom testing template (custom package names etc). Checked if all renamings work as expected.
> [expo-cli] Generate-module fixes and improvements

- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/credentials/provider/iOSCredentialsProvider.ts
- When credentials exist both on Expo servers and in credntials.json, but Expo server ones are incomplete, expo-cli triggers generation of missing credentials when it supposes to just compare existing ones.
- duplicated ensure credentials call
> [expo-cli] Eas build fix prompt for unsynced credentials

- CHANGELOG.md
- packages/xdl/src/detach/AndroidShellApp.js
- packages/xdl/src/detach/ExponentTools.ts
- packages/xdl/src/detach/IosNSBundle.ts
Fixes https://github.com/expo/expo/issues/9922, along with https://github.com/expo/expo/pull/9985
This PR passes the `updates.checkAutomatically` and `updates.fallbackToCacheTimeout` app.json values, which were previously set at runtime, into build-time configuration values for standalone apps built by turtle. These values will then be read and passed directly to expo-updates by the ExpoKit kernels.
Further, starting with SDK 39 the filenames that the ExpoKit kernel expects for the embedded manifest and bundle have changed, from `shell-app-manifest.json` and `shell-app.bundle` to `app.manifest` and `app.bundle`. This PR makes that change accordingly for building standalone apps.
> [xdl] pass app.json updates config to expo-updates in standalone apps

- CHANGELOG.md
- packages/dev-tools/server/graphql/GraphQLSchema.ts
- packages/expo-cli/src/commands/start/TerminalUI.ts
- packages/expo-cli/src/urlOpts.ts
- packages/xdl/src/Android.ts
- Give android parity with https://github.com/expo/expo-cli/pull/2541
- Support multiple connected android devices
- Support opening Android emulators/devices from a list
- Support prompt to update client automatically
- Improve emulator boot-up
- Improve error messages
> [xdl] Improved Android module

- packages/expo-cli/src/commands/upgrade.ts
Fixes #2556
Becuase we didn't declare the optional `sdk-version` value you can provide, Commander returns the command instance to `requestedSdkVersion` parameter. This messes up two things:
1. The requested SDK version by outputting "this is an unknown version, you want to try it anyways"
2. If you continue after the warning, it tries to fetch `options.npm` and `options.yarn`. But, due to 1, this is undefined and breaks the upgrade attempt.
> [cli] Fix requested sdk in upgrade command

- packages/expo-cli/src/commands/credentials.ts
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/build/metadata.ts
- packages/expo-cli/src/commands/eas-build/credentialsSync/action.ts
- packages/expo-cli/src/commands/eas-build/init/action.ts
- packages/expo-cli/src/commands/eas-build/status/action.ts
- packages/expo-cli/src/commands/eas-build/types.ts
- packages/expo-cli/src/commands/eas-build/utils/createBuilderContext.ts
- packages/expo-cli/src/commands/eas-build/utils/createCommandContextAsync.ts
- packages/expo-cli/src/commands/login.ts
- packages/expo-cli/src/commands/logout.ts
- packages/expo-cli/src/commands/register.ts
- packages/expo-cli/src/commands/upgrade.ts
- packages/expo-cli/src/commands/whoami.ts
Add segment events to track the build process
Pass set of event properties to www to be used in Analytics calls in rest of the services
should be merged after https://github.com/expo/universe/pull/5699
> [expo-cli] EAS Build - track build process with Segment

- packages/expo-cli/src/commands/client/index.ts
- packages/expo-cli/src/commands/utils/ClientUpgradeUtils.ts
This avoids calling both `Simulator.upgradeExpoAsync()` and `await Android.upgradeExpoAsync()` without a client URL, from the `$ expo client:install:*` commands.
The versions endpoints contain 2 root client URLs:
As I recall my chats with @tsapeta, these are deprecated and kept in for backward compatibility with the CLI. Calling either Android or Simulator `upgradeExpoAsync` without URL, causes the installers to use these root URLs. 
In the `$ expo client:install:*` commands, we actually know the _latest released sdk_ version and can pass these SDK-specific client urls to the installers.
> We could also add the `await Versions.newestReleasedSdkVersionAsync()` inside the installers, but I'm not 100% sure if that would break existing stuff.
> [cli] Avoid using root client urls and print latest client version

- CHANGELOG.md
- packages/webpack-config/src/webpack.config.ts
- fix https://github.com/expo/expo-cli/issues/2554
> Fix copy webpack plugin for web overrides

- packages/expo-cli/src/appleApi/authenticate.ts
- Seems this broke in PR review, the username will now be saved and used as default for subsequent login attempts.
> Fix last used apple id

- packages/expo-cli/src/commands/eas-build/index.ts
- packages/expo-cli/src/exp.ts
it appears this was intended but the init command was present in help regardless. Now they'll only be visible with EXPO_DEBUG=1
> Hide eas commands from help

- packages/xdl/package.json
- packages/xdl/src/Android.ts
- packages/xdl/src/Prompts.ts
- packages/xdl/src/Simulator.ts
- Adds support for cancelling out of simulator/emulator list and going back to the Terminal UI (currently just ctrl+c)
- Adds auto complete support for searching through lists
- prompts is a much smaller package, better in the long run
- Temporarily removes looping lists
> Use prompts package for simulator/emulator

- packages/xdl/src/detach/IosPodsTools.js
Noticed `EXModuleTemplate` is being compiled when shell app is being built.
> [xdl] Remove expo-module-template from iOS shell apps

- packages/expo-cli/e2e/__tests__/eject-test.ts
- packages/expo-cli/e2e/__tests__/init-test.ts
- packages/xdl/src/Exp.ts
Apps with special characters would break the strings.xml and Info.plist files when added because they weren't being escaped. 
To repro, set the name of your app.json to `&<world/>` and run `expo eject`.
> Add support for escaped names in eject and bare init

- packages/xdl/src/detach/IosPodsTools.js
We may want to omit `DevSupport` from shell apps since they are solely run in production.
> [xdl] Do not add DevSupport in shell app builds

- packages/expo-cli/src/commands/eject/ConfigValidation.ts
- ios config message is blue and the android one is green
- ios newlines the link and android doesn't
- links are formatted poorly in the standard terminal
- messages and hints are redundant
- extra success message is logged after the prompt. I think the absence of an error message or warning is good enough for this.
> [eject] update config validation messages

- packages/expo-cli/e2e/__tests__/init-test.ts
- packages/expo-cli/src/commands/__tests__/export-test.ts
- packages/expo-cli/src/commands/eject/Eject.ts
- packages/expo-cli/src/commands/export.ts
- packages/expo-cli/src/commands/init.ts
- packages/expo-cli/src/commands/utils/CreateApp.ts
- packages/expo-cli/src/commands/utils/__tests__/CreateApp-test.ts
We have some conflicting logic across different commands which have copy/pasted features. This is an initial push to unify some of these features. This PR also implements some logic from our package `create-react-native-app`. I'll address template issues in another PR after this one lands.
- Prompts for the name before prompting for the template since there is a higher probability that the name will fail. This results in less steps for subprime flows. 
- We did this in the past because we were attempting to prevent the usage of dashes and numbers in bare project names. We normalize the names though, and iOS + Android both support numbers and dashes so this isn't even an issue afaict.
- Custom abort message for name prompt. Fails more gracefully instead of just quitting.
- Change slug …
> [cli] improve init

- CHANGELOG.md
- packages/expo-cli/src/commands/eas-build/build/__tests__/build-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/AndroidBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/credentials/credentialsJson/__tests__/read-test.ts
- packages/expo-cli/src/credentials/credentialsJson/read.ts
**[do not merge before turtle changes are deployed]**
Support for private packages 
add `experimental.npmToken` field to credentials.json
> [expo-cli] EAS Build support `experimental.npmToken` in credentials.json

- CHANGELOG.md
- packages/expo-cli/package.json
- packages/expo-cli/src/__mocks__/git.ts
- packages/expo-cli/src/commands/eas-build/build/__tests__/build-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/AndroidBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/utils/git.ts
- packages/expo-cli/src/git.ts
- yarn.lock
**[do not merge before turtle changes are deployed]**
Adds support for monorepo
Upload the entire repository instead of the current directory. 
Add `projectRootDirectory` to the job that represents relative path inside tarball
> [expo-cli] Eas Build: support for monorepo

- packages/xdl/src/ProjectAssets.ts
Fix: Asset batch uploading
Assets were divided into chunks of 5 for uploading, using await promise.all to upload all the chunks at once causes network and system resources issues for big number of assets, instead with this change chunks are uploaded sequentially.
Reference for issue: https://stackoverflow.com/a/30823708
> Fix: Asset batch uploading

- packages/expo-cli/src/commands/publish.ts
It seems `--clear` flag should work with `publish` sub command since it is documented in command description (and it is obviously useful).
```
$ expo publish --help
Usage: publish|p [options] [path]
Deploy a project to Expo hosting
Options:
-q, --quiet                          Suppress verbose output from the Metro bundler.
-s, --send-to [dest]                 A phone number or email address to send a link to
-c, --clear                          Clear the Metro bundler cache
-t, --target [env]                   Target environment for which this publish is intended. Options are `managed` or `bare`.
--max-workers [num]                  Maximum number of tasks to allow Metro to spawn.
--release-channel <release channel>  The release channel to publish to. Default is 'default'. (default: …
```
> fix(cli): let publish command respect clear flag to clear cache

- packages/expo-cli/src/commands/start/TerminalUI.ts
- packages/expo-cli/src/exit.ts
- make the terminal UI shorter
- group the commands 
- match up wording across commands 
- standardize text formatting
currently
> [cli] Clean up TerminalUI

- packages/expo-cli/src/commands/eject.ts
- packages/expo-cli/src/commands/eject/Eject.ts
- packages/expo-cli/src/commands/init.ts
- packages/expo-cli/src/commands/utils/CreateApp.ts
- packages/expo-cli/src/log.ts
- Added `--no-install` flag to `expo eject` which can be used to skip node module installation and cocoapods installation. This follows the same pattern we use for initializing a bare workflow project.
- Added `--npm` flag to `expo eject` which shares the same logic as init for using npm to install modules.
- Added "Cleaning JavaScript dependencies" spinner because the step takes ~5 seconds on my fast computer. Also when the yarn logs are enabled it looks off to see "installing deps.." for a few seconds before you start seeing the logs.
- Added back support for showing the installation logs with `EXPO_DEBUG=true`
- Fix cocoapods logs only showing with `EXPO_DEBUG=false`
- Make spinners automatically unmount from the logs module.
- Make spinners support `newLineIfNone`.
- Unify the node …
> [eject] Added no-install and npm args to eject

- packages/expo-cli/src/commands/init.ts
- packages/expo-cli/src/exp.ts
> Added better logs for invalid custom config paths

- packages/expo-cli/package.json
- packages/expo-cli/scripts/introspect.ts
- packages/expo-cli/src/exp.ts
Move `expo introspect` to a script that can be run from `packages/expo-cli` as `yarn introspect`. Helps to reduce the production bundle and public interface of expo-cli.
resolves https://github.com/expo/expo-cli/issues/2593
> Extract introspect out of expo-cli

- packages/expo-cli/e2e/__tests__/eject-test.ts
- packages/expo-cli/src/commands/eject/Eject.ts
- packages/expo-cli/src/commands/eject/__tests__/Eject-test.ts
- The name prompt will never be invoked because if the name is missing it will be inferred from the folder name.
- Writing an `app.json` seems unnecessary, removing this step in favor of preserving whichever config was in use before ejecting (i.e. app.config).
- Don't delete eject script
- Only delete main field if it's an expo value
- Split metro logic into its own function -- no functionality changes
- Prevent reruns from throwing metro config errors by comparing the file hashes
- hide the metro step when nothing changes to reduce the amount of logs
- Only clean deps if new project files were added
- Only run pod install if new deps or an ios folder get added.
- Split up methods
- Reduce the amount of times that deps get rewritten
> [eject] Remove name prompt and static config writing

- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/credentialsSync/action.ts
- packages/expo-cli/src/commands/eas-build/status/action.ts
- packages/expo-cli/src/commands/eas-build/utils/analytics.ts
- packages/xdl/src/Analytics.ts
- packages/xdl/src/Android.ts
- packages/xdl/src/Project.ts
- packages/xdl/src/Simulator.ts
- packages/xdl/src/User.ts
- packages/xdl/src/project/ManifestHandler.ts
- packages/xdl/src/project/ProjectUtils.ts
- packages/xdl/src/xdl.ts
Amplitude charts can only contain data from a single project, so if we want to show data from multiple services we would need to pipe all XDL events to the project. Supporting multiple Segment projects is solving that issue.
Extracted current implementation to class and instantiate it for Eas Build commands with different  write key
- user information is shared globally(only one instance needs to call `setUserProperties`)
- EAS Build instance have separate projects for production and non-production builds
Run build locally and checked with Segment debugger that events are registered
> [expo-cli] support multiple Segment projects

- packages/xdl/src/detach/IosPodsTools.js
Random screen currently soft crashes the standalone iOS apps on SDK39 and for a good reason — `expo-random` native module is not included.
> [xdl] Add expo-random to SDK39+ iOS shell apps

- packages/dev-tools/server/dev-server.ts
- packages/expo-cli/src/commands/start.ts
- packages/expo-cli/src/commands/start/TerminalUI.ts
- packages/expo-cli/src/commands/upgrade.ts
- packages/expo-cli/src/commands/utils/PublishUtils.ts
- packages/xdl/src/Project.ts
- Reading the config is getting expensive. 
- The "only start webpack when react-native-web is installed and react-native is not installed" feature isn't very useful. The `expo web` / `expo start:web` command is more appropriate.
- Add optional ability to pass an expo config to `Project.startAsync`
> [expo start] remove extra config reads

- CHANGELOG.md
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/utils/misc.ts
Better error messages when deprecating parts of api in EAS Build
> [expo-cli] EAS Build deprecation info

- CHANGELOG.md
- packages/expo-cli/src/commands/credentials.ts
- packages/expo-cli/src/credentials/context.ts
Support credentials manager for people that have multiple projects on a single codebase. For those cases, all credentials management had to be done via build command.
Support config flag. I couldn't use logic from `exp.ts` because that code requires a valid project and in the case of `credentials:manager` command it's optional
> [expo-cli] add --config flag to credentials:manager

- packages/expo-cli/src/commands/__tests__/export-test.ts
- packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
- packages/expo-cli/src/commands/diagnostics.ts
- packages/expo-cli/src/commands/eas-build/init/action.ts
- packages/expo-cli/src/commands/init.ts
- packages/expo-cli/src/credentials/views/AndroidCredentials.ts
Eslint warnings, mostly unused code or imports `yarn eslint packages/expo-cli/ --ext js,ts`
> [expo-cli] fix eslint warnings

- packages/xdl/src/Project.ts
- packages/xdl/src/UrlUtils.ts
- packages/xdl/src/detach/ExponentTools.ts
- packages/xdl/src/detach/IosLocalization.js
- packages/xdl/src/detach/IosNSBundle.ts
- yarn.lock
fix https://github.com/expo/expo-cli/issues/1400
locally ran `expod publish ..` from an upper folder while the config referred to a locale file.
> resolve locales from project root

- packages/babel-preset-cli/index.js
- packages/config/src/evalConfig.ts
- packages/expo-optimize/package.json
Now that the external script is gone we can transpile expo/config in expo-optimize which should drastically reduce npx time. Probably wanna wait to see if we need to revert the config stuff before merging this.
Tested locally and it works as expected when the `require.resolve`s are removed.
> Transpile expo/config in expo-optimize

- packages/expo-cli/src/commands/build/BaseBuilder.ts
resolve #1916 
After `expo build:ios` completes successfully, log about using `expo upload:ios`
> Log about upload after build:ios completes

- packages/xdl/src/detach/IosPodsTools.js
Let's remove IDFA once and for all – this time in Branch. By adding this macro to shell apps we'll remove IDFA code on compilation level:
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/ac991f9d0bc9bad640b25a0f1192679a8cfa083a/Branch-SDK/BNCSystemObserver.m#L49-L75
> [xdl] Exclude IDFA code from Branch

- packages/expo-cli/src/commands/eject/Eject.ts
- We should warn about moving from `Constants.manifest` -> `Updates.manifest` when using the bare workflow
- Assets are bundled into bare workflow binaries differently (don't rely on `assetBundlePatterns`), so we should point to these new docs when you eject
screenshot of the output:
> [expo-cli][eject] warn about Constants.manifest and assetBundlePatterns

- packages/next-adapter/document.js
Since next 9.5.3 the html element in _document.js should be Html instead. This error is rendered:
```
Expected Document Component Html was not rendered. Make sure you render them in your custom `_document`
See more info here https://err.sh/next.js/missing-document-component
```
See also https://github.com/vercel/next.js/discussions/16908
> Fix: Next warning Expected Document Component Html was not rendered

- CHANGELOG.md
- packages/expo-cli/src/credentials/api/IosApiV2Wrapper.ts
This PR fixes a bug reported by our users.
We've set up all our credentials endpoints to accept an `owner` parameter so we can fetch the correct credentials and perform permissioning checks.
When a team member tries to get the project owner's user credentials, the `owner` parameter must be set in the API call otherwise the server will return a permissioning error.
> [cli] add missing owner query param

- CHANGELOG.md
- packages/xdl/src/detach/IosShellApp.js
While moving iOS shell app code from `tools-public` to `expotools` I haven't noticed that XDL outputs build artifacts to a directory relative to current directory, so from `../` from `tools-public` was `expo` root. Now with `expotools` it's out of repository, which required this change to get the `tar` packaging the tarball —https://github.com/expo/expo/commit/b42aba261f6d1ac54b33d780a09ffe282931c36e.
It's not the prettiest, but it works.
See the failed job at https://github.com/expo/expo/runs/1086951550.
> [xdl] Build iOS shell app artifact to current directory

- CHANGELOG.md
- packages/json-file/src/JsonFile.ts
Currently, there are two options two ensure directory is created,
- run `mkdir` on start of the application
- wrap entire JsonFIle api
add option `ensureDirOnWrite`
Run `setAsync` when file does not exists
> [@expo/json-file] add option to create directory on write

- packages/next-adapter/document.js
Got this error today when trying to use Next.js
Fixed by this PR
It was caused by this PR: https://github.com/expo/expo-cli/pull/2661
> [next-adapter] Fixed ReferenceError Html is not defined

- CHANGELOG.md
- packages/expo-cli/src/credentials/views/AndroidKeystore.ts
- packages/expo-cli/src/credentials/views/SetupAndroidKeystore.ts
When keytool was missing update process was stopped before the user had a chance to select the option to manually provide credentials.
Move `keytool` check to later stage
Remove `keytool` and run `expo build:android -c`
> [expo-cli] Allow manually provided credentials when keytool is missing

- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/credentials/credentialsJson/read.ts
missing credentials json should be handled earlier
> [expo-cli] EAS Build - handle missing credentials.json

- packages/expo-cli/src/appleApi/authenticate.ts
Support was removed in 9e267b5dd54de56ee01bce2fd50dc73bde7cf852. Fall back to the `EXPO_APPLE_ID` if it wasn't passed on the command line, restoring the previous behavior.
The docs still say that `EXPO_APPLE_ID` can be used in place of `--apple-id`. Alternatively, the docs could be updated.
> Bring back support for EXPO_APPLE_ID

- CHANGELOG.md
- packages/expo-cli/package.json
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/init/action.ts
- packages/expo-cli/src/commands/eas-build/types.ts
- packages/expo-cli/src/commands/eas-build/utils/createBuilderContext.ts
- packages/expo-cli/src/easJson.ts
- yarn.lock
We've split `@expo/build-tools` into two packages: `@expo/eas-build-job` and smaller `@expo/build-tools`. The former conaints only TS types, Joi schemas, and some utils. Expo CLI doesn't anything else so this PR replaces `@expo/build-tools` with `@expo/eas-build-job` entirely. This PR doesn't change any logic.
> [expo-cli] replace @expo/build-tools with @expo/eas-build-job

- packages/expo-cli/src/commands/eject/ConfigValidation.ts
- packages/expo-cli/src/commands/eject/__tests__/ConfigValidation-test.ts
- fix https://github.com/expo/expo-cli/issues/2686
> Improved package name validation

- packages/xdl/src/Project.ts
Instead of using `NODE_OPTIONS` from the `expo-cli` process, the Metro process overrides it with `METRO_NODE_OPTIONS`.
This has two effects:
- the Metro process can be debugged with `--inspect-brk`
- the `expo-cli` process can be debugged with `--inspect-brk` without causing an "address already in use" error in the Metro process
Fixes https://github.com/expo/expo/issues/9398
> feat: use `process.env.METRO_NODE_OPTIONS` when starting Metro

- packages/xdl/src/Project.ts
Hi, I'm a developer supporting and developing the [VSCode React Native Tools Extension](https://github.com/microsoft/vscode-react-native). For more control of the development environment, we run the React Native Packager on the extension side. This change will allow us to have more control over the Expo apps launching through the extension and launch Expo server without the packager.
> Restore Project.startExpoServerAsync accessibility

- CHANGELOG.md
- packages/config/src/android/SplashScreen.ts
- packages/config/src/ios/SplashScreen.ts
Any single version of `@expo/configure-splash-screen` is only guaranteed to work with a single version of expo-splash-screen. We only include one version of that pkg in @expo/config at any given time.
- For now: disable splash screen to fix ejecting
- Next: find a version that works with SDK 39 and use that on SDK 39 eject, otherwise add warning and don't apply
- Future: use version of script that ships with expo-splash-screen rather than packaging a single version in @expo/config
> [config] Disable splash screen on eject

- packages/config-types/package.json
- packages/config-types/src/index.ts
- packages/config/package.json
- packages/config/src/android/IntentFilters.ts
- packages/expo-cli/src/commands/client/clientBuildApi.ts
- packages/expo-cli/src/commands/eject/Eject.ts
- packages/xdl/src/project/ExpSchema.ts
- packages/xdl/src/project/ManifestHandler.ts
- fix #2702
- pending https://github.com/expo/universe/pull/5900
- bump to 40 beta 1 - maybe we should use rc instead
> [config-types] android.intentFilters.data type fix

- packages/config-types/src/ExpoConfig.ts
- packages/config/src/android/IntentFilters.ts
Makes it easier to read, navigate, and reuse types. 
Creates the following interfaces:
```ts
Splash
IOS
Android
Web
PublishHook
```
> [config-types] Split up platform configs

- packages/configure-splash-screen/src/android/MainActivity.ts
- packages/configure-splash-screen/src/android/__tests__/MainActivity.test.ts
- packages/configure-splash-screen/src/android/__tests__/fixtures/react-native-project-structure-with-splash-screen-configured.ts
Recent change in `expo-splash-screen` https://github.com/expo/expo/commit/2770008129aef794dcdf5fcdaa35ef5056b6ff29#diff-70eefa11c7e96de30d02e5d069488fe2R35-R40
changed the native Android API.
This PR accommodates this native API change.
Resolves https://github.com/expo/expo-cli/issues/2586
> [configure-splash-screen]<feat>: Make Android configuration conform to the new native API

- packages/configure-splash-screen/src/android/MainActivity.ts
- packages/configure-splash-screen/src/android/__tests__/MainActivity.test.ts
- packages/configure-splash-screen/src/android/__tests__/fixtures/react-native-project-structure-with-splash-screen-configured.ts
_don't merge before https://github.com/expo/expo-cli/pull/2698_
Follow up of https://github.com/expo/expo-cli/pull/2698
Follow up of https://github.com/expo/expo/pull/10294
This is supplementary change that accommodates Android API change from expo/expo#10294
> [configure-splash-screen]<feat>: Accommodate Android singletons.SplashScreen import from the subpackage

- packages/config-types/src/ExpoConfig.ts
- deprecated for 15 versions https://github.com/expo/universe/pull/5905
> [config-types] Remove loading object

- lerna.json
- packages/config/src/android/SplashScreen.ts
- packages/config/src/ios/SplashScreen.ts
This modifies the native splash screen configuration *only when the project being configured is on the latest SDK*. This is a workaround that is needed because we only include one version of `@expo/configure-splash-screen` in `@expo/config` at any given time. In the future, we will depend on `expo-splash-screen` providing its own config.
*Note*: I removed `@expo/configure-splash-screen` from the watched projects in lerna because we may make changes to it that aren't backwards compatible with the currently released splash screen versions, and so we need to manually bump the dependencies in `@expo/config` and release `@expo/configure-splash-screen` on its own without using the publish script.
> [config] Configure splash screen for the latest SDK only

- CHANGELOG.md
- packages/expo-cli/src/commands/install.ts
Fixes https://github.com/expo/expo/issues/10424
> [expo-cli] Make expo install work in any React Native app

- packages/expo-cli/src/__mocks__/prompts.ts
- packages/expo-cli/src/__tests__/accounts-test.ts
- packages/expo-cli/src/accounts.ts
- packages/expo-cli/src/commands/login.ts
- packages/expo-cli/src/prompts.ts
- packages/xdl/src/ApiV2.ts
- packages/xdl/src/User.ts
This adds CLI support for the upcoming two-factor authentication feature.
Users are able to configure a set of devices to act as second factor authentication mechanisms. There are two kinds of devices: Authenticator TOTP and SMS. A user has the option to have a "primary" device. A user is also given backup codes during 2FA setup.
Currently there is no public way to set up 2FA since it is still in active development.
See inline docblocks.
Start server locally with https://github.com/expo/universe/pull/5733 patched.
Set up and confirm 2FA for my user in GraphiQL, adding a default authenticator and backup SMS.
```
export EXPO_LOCAL=1
> yarn expo login --username wschurman2 --password <password_in_plain_text_here> --otp 478045
Success. You are now logged in as wschurman2.
> yarn expo logout …
```
> [cli] Add two-factor authentication to login

- packages/expo-cli/src/commands/eas-build/build/templates/gradleContent.ts
Why
===
We handle both absolute and relative paths in `credentials.json` in other places, but it wasn't handled in the gradle script. This commit fixes it.
Test plan
=========
Try both absolute and relative paths in `crdentials.json` for the `keystorePath` in the turtle example project and make sure that the release build passes with `./gradlew assembleRelease`.
> [expo-cli] Support absolute path in credentials.json for gradle

- CHANGELOG.md
- packages/config/src/android/Manifest.ts
- packages/config/src/android/Updates.ts
- packages/config/src/ios/Updates.ts
- packages/expo-cli/package.json
- packages/expo-cli/src/commands/eas-build/build/action.ts
- packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
- packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
- packages/expo-cli/src/commands/eas-build/init/__tests__/init-test.ts
- packages/expo-cli/src/commands/eas-build/utils/expoUpdates/android.ts
- packages/expo-cli/src/commands/eas-build/utils/expoUpdates/getConfigurationOptions.ts
- packages/expo-cli/src/commands/eas-build/utils/expoUpdates/index.ts
- packages/expo-cli/src/commands/eas-build/utils/expoUpdates/ios.ts
- packages/expo-cli/src/commands/eas-build/utils/expoUpdates/isExpoUpdatesInstalled.ts
- packages/expo-cli/src/commands/eas-build/utils/git.ts
- yarn.lock
Why
===
We want to automatically configure required config such as runtime version for expo updates so that it's always uptodate with the app's runtime version.
What
====
Running `expo eas:build:init` will now check if `expo-updates` is in `package.json` and make following changes:
1. On iOS, set `sdkVersion`, `runtimeVersion`, `updateUrl` etc in `Expo.plist`. by reading from `exp` config
2. On iOS, add build phase script for assets in XCode project
1. On Android, set `sdkVersion`, `runtimeVersion`, `updateUrl` etc in `AndroidManifest.xml`. by reading from `exp` config
2. On Android, add build phase script for assets in `build.gradle`
Running `expo eas:build` will now do the following: 
1. Check if either `runtimeVersion` or `sdkversion` are correctly set, and will set them if not
2. …
> [expo-cli] Configure expo updates when building with eas

- packages/expo-cli/src/exp.ts
Override commander and fix the arguments order for individual command prompts. Related https://github.com/expo/expo-cli/issues/2714#issuecomment-699648649
> [cli] Fix command help options order

- packages/expo-cli/src/commands/upload/submission-service/android/ServiceAccountSource.ts
- packages/expo-cli/src/commands/upload/submission-service/utils/errors.ts
standardize the styling around the repo. This uses:
- iTerm: `[Learn more](...)`
- default: `Learn more: ...`
Instead of the verbose `Learn more ( ... )`
> use learn more link

- packages/configure-splash-screen/src/SplashScreenConfig.ts
- packages/configure-splash-screen/src/android/Colors.xml.ts
- packages/configure-splash-screen/src/android/Styles.xml.ts
- packages/configure-splash-screen/src/ios/BackgroundAsset.ts
When adding `@expo/config` to `eas-cli` `color-string` types are missing.
Didn't test if it fixes the issue
> [configure-splash-screen] do not export color-string types

- packages/config/src/__tests__/ConfigParsing-test.js
- packages/config/src/__tests__/fixtures/language-support/js/with-import_app.config.js
- packages/config/src/evalConfig.ts
I have a number of different app configs and was receiving a `Failed to read config` / `MODULE_NOT_FOUND` error on `expo start` since they import shared config variables. This sets `configFile` as the `filename` argument to `require-from-string` so relative modules can be resolved properly
> [config] Fix relative module resolution for config files

- packages/xdl/src/detach/AndroidShellApp.js
Locally I was doing
<details>
<summary>App.json & code</summary>
```json
"android": {
"splash": {
"xxxhdpi": "./assets/splash.png",
"backgroundColor": "#8f31ae"
}
}
```
```
import * as React from 'react';
import * as SplashScreen from 'expo-splash-screen';
import { StyleSheet, View, Text, Button, TouchableOpacity } from 'react-native';
import StatusBarController from './StatusBarController';
function useSplashScreen(loadResources: () => Promise<void>) {
const [isSplashScreenShown, setSplashScreenShown] = React.useState(true);
React.useEffect(() => {
console.log('Loading ...');
const preventAutoHideAndLoadResources = async () => {
try {
const result = await (
SplashScreen.preventAutoHideAsync || SplashScreen.preventAutoHide
)();
console.log(`SplashScreen.preventAutoHideAsync returned: …
```
> [xdl]<feat>: Add support for SDK-39 standalone app configuration & building

- packages/expo-cli/src/commands/start/TerminalUI.ts
- resolve https://github.com/expo/expo-cli/issues/2229
> Disable TerminalUI sign in/out method (s)
