packages/expo-cli/src/commands/start/TerminalUI.ts

I noticed that the message triggered by entering `?` in the `expo start` command displays the wrong value of openDevToolsAtStartup.
<details>
<summary>Here's what it shows:</summary>
````
Automatically opening DevTools disabled.
Press d to open DevTools now.
Expo  Press ? to show a list of all available commands.
› Press a | open Android
› shift+a | select a device or emulator
› Press i | open iOS simulator
› shift+i | select a simulator
› Press w | open web
› Press o | open project code in your editor
› Press c | show project QR
› Press p | toggle build mode (development)
› Press r | restart bundler
› shift+r | restart and clear cache
› Press d | open Expo DevTools
› shift+d | toggle auto opening DevTools on startup (enabled)
› Press e | share the app link by email
› Press s | sign out …
```

[expo-cli] use correct description for openDevToolsAtStartup in the ? message

---

packages/config/src/android/Package.ts

Fixes #2711
The issue originates (once again) from `glob`. This _always returns_ a posix formatted path, even on Windows. This messes up the `path.sep` because that's different on Windows. I think it's a good thing to normalize paths when using glob, it changes the format of the path to the expected one on Windows.
It's also good to use `path.relative` more when stripping root paths. It takes all differences into account related to windows/posix paths and just returns you the path you need.

[config] Fix Android scandir error when ejecting on windows

---

packages/expo-cli/src/commands/eas-build/build/action.ts

Why
===
We want to be able to build projects with EAS without having to spin off multiple watchers and servers. We can pass the JSON for the job directly to turtle workers, but currently there's no way to access the JOSN easily.
This commit checks if `EAS_OUTPUT_JOB_JSON` is set to `true` and if yes, prints the JSON to `stdout` and exits the command. The [`eas-build-cli`](https://github.com/expo/eas-build-cli) can then read this JSON to call respective builders directly.
Example usage:
```sh
EAS_OUTPUT_JOB_JSON=1 expo eas:build --platform android | sed -n '/JSON for the job:/,$p' | tail -n +2 | eas-build-cli | bunyan -o short
```
Test plan
=========
I have tested that it works with `eas-build-cli` by triggering a new build for Android and ensuring that the build completes.

[expo-cli] Add a EAS_OUTPUT_JOB_JSON environment variable to output JSON for the job

---

packages/expo-cli/src/urlOpts.ts

Handles: https://github.com/expo/expo-cli/pull/2763#issuecomment-705264151

Add "client" copy to Android and iOS open option

---

packages/expo-cli/e2e/TestUtils.ts
packages/expo-cli/e2e/__tests__/eject-test.ts
packages/expo-cli/src/commands/eject/Eject.ts
packages/expo-cli/src/commands/eject/__tests__/Eject-test.ts

We want to switch away from using the Expo node_modules/expo/AppEntry when ejecting, but if the user already is not using that, we don't need to do anything. We don't need to create index.js or delete their `pkg.main`. We previously already handled the latter but not the former, this PR addresses that.
Fixes https://github.com/expo/expo-cli/issues/2748

[cli] Only create index.js on eject when it is needed - when we change pkg.main

---

CHANGELOG.md
packages/configure-splash-screen/package.json
packages/configure-splash-screen/src/cli-command.ts
packages/configure-splash-screen/tsconfig.json

I observed that the `yarn expo-splash-screen` was missing a `version` option and therefore it was really hard to tell what version of this command the user is running.
I've fetched the version from the `package.json` as this is the most reliable source.
~Unfortunately I had to change tsc project structure, because tsc was complaining.~
_edit_: I've had to adjust the `tsconfig` file to ignore `json`s, because importing the file from outside the `rootDir` (specified in `tsconfig`, and `package.json` is outside the `src` directory) would change the `build` folder layout and will copy over the `package.json` file and that `package.json` file duplication is not playing well with `lerna` and other other tooling (CI was failing)

[configure-splash-sceen]<feat>: Add missing `--version, -V`

---

packages/config/src/ios/AssetContents.ts
packages/config/src/ios/Icons.ts
packages/config/src/ios/IosConfig.types.ts
packages/config/src/ios/Version.ts

- moved from https://github.com/expo/expo-cli/pull/2706
- abstracts the Contents.json feature (currently for no reason).
- makes the Icons module less complex.

[config] Created AssetContents

---

packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
packages/expo-cli/src/commands/init.ts

- xdl is big and mostly legacy
- unify reading/writing or plists for more expected results
- the IosPlist.modifyAsync API is awkward

[config][cli] Use expo/plist instead of xdl IosPlist

---

packages/config/src/ios/Entitlements.ts
packages/config/src/ios/Paths.ts
packages/config/src/ios/__tests__/Entitlements-test.ts
packages/config/src/ios/__tests__/Paths-test.ts

- Implement a system for deleting all .entitlements files, moving one of them (basically at random (there should never be more than one)) into the new entitlements path if it doesn't exist.
- Log file warnings relative to the project root
- Fix https://github.com/expo/expo-cli/issues/2688
- Test this new complex functionality

[config] fix entitlements functionality

---

packages/pkcs12/src/__tests__/index-test.ts
packages/pkcs12/src/index.ts

a common mistake users make is uploading a pkcs keystore and providing the wrong alias (friendly name) that their credentials are stored under. It'll make it easier if we just returned `null` in this case rather than throwing an error in this package so the client (www) can handle this case and wrap it in an error with more context.

[pkcs12] return null if pkcs keystore has no cert under friendly name

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
packages/expo-cli/src/commands/eas-build/build/metadata.ts
packages/expo-cli/src/easJson.ts
yarn.lock

Why
===
We want to be able to specify the release channel when building our app so that subsequent updates `expo-updates` can be published separately for different profiles.
How
===
I've added the `releaseChannel` field to the `jobs` and `metadata` objects which are sent to the www server when running `expo eas:build`.
Test plan
=========
I verified that the `releaseChannel` is respected by adding a new `releaseChannel` field under the profile in the `eas.json` of the turtle example app, and then running the build to make sure that tis field is received by the turtle worker as well.
Note
====
The PR depends on https://github.com/expo/turtle-v2/pull/302 since it needs changes in the `@expo/eas-build-job`. When that PR is merged and published, I'll update this PR with the latest version of …

[expo-cli] Add `releaseChannel` field to the profile in `eas.json`

---

packages/expo-cli/src/commands/client/index.ts
packages/xdl/src/Android.ts
packages/xdl/src/Simulator.ts

This PR makes it possible to run:
- `expo client:install:ios --latest`
- `expo client:install:android --latest`
This is useful to skip any prompts and just grab and install the latest client. These are convenient commands we can copy/paste in a variety of situations without providing any additional instructions around the cwd of the terminal, eg: `EXPO_BETA=1 expo client:install:ios --latest`.
A drive-by improvement I made here was to include the client version in the "Installing Expo client" message.

[xdl][cli] Add support for --latest flag in client:install:x

---

packages/xdl/src/Logger.ts

This environment var might collide with the [`debug()` package](https://www.npmjs.com/package/debug), if people use it. It's fairly popular so I would imagine this might be the cause of issues like #2803.

[xdl] Rename debug to expo raw log to avoid collision

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/build/AndroidBuilder.ts
packages/expo-cli/src/commands/build/BaseBuilder.types.ts
packages/expo-cli/src/commands/eas-build/build/__tests__/build-test.ts
packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
packages/expo-cli/src/commands/eas-build/build/builders/__tests__/AndroidBuilder-test.ts
packages/expo-cli/src/commands/eas-build/credentialsSync/action.ts
packages/expo-cli/src/commands/eas-build/init/__tests__/init-test.ts
packages/expo-cli/src/credentials/provider/AndroidCredentialsProvider.ts
packages/expo-cli/src/credentials/provider/__tests__/AndroidCredentialsProvider-test.ts
packages/expo-cli/src/credentials/utils/validateKeystore.ts
packages/expo-cli/src/credentials/views/AndroidCredentials.ts
packages/expo-cli/src/credentials/views/AndroidKeystore.ts
packages/expo-cli/src/credentials/views/SetupAndroidKeystore.ts
packages/expo-cli/src/credentials/views/__tests__/AndroidKeystore-Update-test.ts
packages/expo-cli/src/credentials/views/__tests__/SetupAndroidBuildCredentialsFromLocal-test.ts
yarn.lock

Why
===
We want to ensure that the user provided correct keystore file and credentials before starting the build. It'll let us avoid cases such as when users downloade some file from Google play and mistakenly thought that it's a keystore file.
How
===
1. When reading the credentials for Android from 'credentials.json' or when user enters keystore password when prompted for providing own keystore, validate the keystore file with 'keytool' by using the provided credentials, unless '--skip-credentials-check' is specified.
1. If 'keytool' is not present, print an warning and skip the verification.
Test plan
=========
1. Run `expo credentials:manager > android > Update upload Keystore` and ensure that an error is thrown upon entering incorrect credentials.
1. Run `expo build:android` without …

[expo-cli] Validate the credentials for android keystore

---

packages/expo-cli/src/commands/eas-build/index.ts
packages/expo-cli/src/commands/eas-build/init/action.ts

Why
===
We want to be able to configure eas build for specific platforms incase we're not ready to configure all platforms yet.

[expo-cli] Support --platform option for eas:build:init

---

packages/expo-cli/src/commands/eject.ts
packages/xdl/src/Versions.ts

This PR changes `Versions.newestReleasedSdkVersionAsync()`:
- Currently a "released" version is defined as being a version that has a `releaseNoteUrl` field attached to it on the versions endpoint
- For beta releases, we will add a boolean `beta` field.
- We only want to return beta releases as the newest released version when the user opts in to it.
- Users are able to opt-in by setting `EXPO_BETA=1` in their environment.
This small change has the following intended impacts:
- `EXPO_BETA=1 expo upgrade` will now be able to upgrade to a beta version
- `EXPO_BETA=1 expo client:install:[ios/android]` outside of a project directory will install the beta version of the client

[xdl] Support beta versions when EXPO_BETA=1

---

packages/xdl/src/Exp.ts
packages/xdl/src/Project.ts
packages/xdl/src/UserSettings.ts

We don't use this anymore. It was used by XDE. We should possibly remove the `PATH` file too - we used that with XDE.

[xdl] Remove xde-recent-exps

---

packages/config/src/android/EasBuild.ts
packages/config/src/android/EasBuildGradleScript.ts
packages/config/src/android/index.ts
packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts

- [Android] move eas-build.gradle to @expo/config (will be required on turtle during managed build)
- [Android] check `EAS_BUILD` env (always override release keystore on turtle)
- [Android+iOS] override username with EAS_BUILD_USERNAME env variable

[config] EAS Build managed support

---

packages/config/package.json
packages/config/src/ios/Entitlements.ts

This is a fix that doesn't do a lot currently, since we disabled ejecting iOS on windows. But this, in combination [with this `xcode` fork](https://github.com/byCedric/cordova-node-xcode/tree/fix/windows-issues), actually fixes all differences in the iOS files we get from ejecting the same app on both platforms.
I'll try to push the fork to upstream, [but there isn't a lot of activity in the repo](https://github.com/apache/cordova-node-xcode/issues/116). So we probably need to fork and republish instead.
This would fix (partially, the fork changes arent in here yet) #2675 if we enable ejecting ios on windows again.

[config] Force ios entitlement paths to be in posix

---

packages/config/src/android/EasBuildGradleScript.ts

Why
===
Currently, when a user has `react-native-config` configured, our configuration for signing config doesn't work. The resulting app gets signed with debug key instead of release key. I tried to debug but couldn't exactly figure out why it happens. Just adding the following in the `react-native-config`'s gradle script produces this behaviour (which shouldn't affect anything?):
```gradle
tasks.whenTaskAdded { task ->
// Nothing here
}
```
The commit changes the logic to do the configuration on `whenTaskAdded` hook rather than on `afterEvaluate` hook which somehow fixes the issues, probably because then our logic executes before dotenv's script instead of after like previously. Though to be honest, this is result of many trial and errors.
Test plan
=========
I've tested by building the …

[expo-cli] Fix eas gradle script not working when used with react-native-config

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/eas-build/build/builders/AndroidBuilder.ts
packages/expo-cli/src/commands/eas-build/build/builders/iOSBuilder.ts
packages/expo-cli/src/commands/eas-build/build/credentials.ts
packages/expo-cli/src/commands/eas-build/build/metadata.ts
packages/expo-cli/src/easJson.ts
yarn.lock

@sstur pointed out that he was experiencing a new error today when running a build with EAS Build preview:
He noticed that `BuildType` was no longer exported from `@expo/eas-build-job`, I looked into this and it seems that the reason we didn't catch this locally is that we use the semver `^` matcher for the `@expo/eas-build-job` dep in expo-cli and so unless we manually update the lockfile every time we publish a new version of it, it's possible that we won't catch errors. Users installing via npm were getting `0.1.2` and in the expo-cli repo we were getting `0.1.1`.
So, I think for now it is reasonable for us to use a fixed version of `@expo/eas-build-job` for each version of expo-cli.
@wkozyra95 - I left some comments here for your consideration, but I'm going to move ahead with …

[cli] Use exact @expo/eas-build-job version, update it, and fix related TS errors

---

packages/config/src/Errors.ts
packages/config/src/android/Facebook.ts
packages/config/src/android/Manifest.ts
packages/config/src/android/__tests__/Facebook-test.js

- `Document` -> `AndroidManifest`
- Support a proper `assert` function
- Create a typed object instead of parsing a string (async)
- Split `applyFacebookAppIdString` out

[config] Updated Android Facebook module to better accommodate plugins

---

packages/traveling-fastlane/actions/app_produce.rb

By default, `fastlane produce` returns newly created App _"Apple ID"_ number, which is then required for `Transporter.app`/`fastlane pilot` to upload binary to TestFlight without 2FA login.
This PR modifies `app_produce.rb` script to return then number to the caller as JSON result.
Example (using built package):
```sh
/dev/test_proj/node_modules/@expo/traveling-fastlane-darwin/dist/app_produce my.BundleName "Some ApName" my-apple-id@icloud.com English
```
Result:
```
...
[11:27:10]: Creating new app 'Some ApName' on App Store Connect
[11:27:18]: Waiting for the newly created application to be available on App Store Connect...
[11:27:34]: Ensuring version number
[11:27:34]: Successfully created new app 'Some ApName' on App Store Connect with ID 1538xxxxxx …
```

[travelling-fastlane] Update app_produce to return App ID

---

unlinked-packages/configure-splash-screen/package.json

I noticed these weren't matching after I linked it with `yarn link`. Maybe we should include this folder in the `yarn workspace` so installs are easier?

[configure-splash-screen] Use proper bin paths to files

---

packages/xdl/src/detach/AndroidShellApp.js

This PR fixes the updates.checkAutomatically `ON_ERROR_RECOVERY` behavior for SDK 39 standalone Android apps. Currently this setting is not applied properly.
I just found this change in my local working directory -- I think I discovered this issue (and found the fix) during QA, but managed to forget to actually push and PR the change 😮 🤦 
TODO:
- release new xdl with this change
- update xdl in turtle and redeploy Android turtle to production

[xdl] fix updates ON_ERROR_RECOVERY setting for SDK 39 Android apps.

---

packages/expo-cli/src/urlOpts.ts
packages/xdl/src/ProjectSettings.ts
packages/xdl/src/UrlUtils.ts

- Running `expo start --scheme custom` presents a QR with the `custom://` protocol. Running without the `--scheme` property resets the protocol to `exp://`.

Added support for a custom scheme property

---

packages/expo-cli/src/schemes.ts
packages/expo-cli/src/urlOpts.ts

Created `--dev-client` flag for resolving the uri-scheme automatically or warning the user how to set one up. Pending scheme PR https://github.com/expo/expo-cli/pull/2860. Kinda pending https://github.com/expo/expo-cli/pull/2859 for improved Info.plist resolving.
Custom scheme
`--dev-client` in an ejected project
`--dev-client` in a mismatched URI scheme project
`--dev-client` in a managed project

[dev-client][cli] Created scheme resolver

---

packages/config/src/paths/paths.ts
packages/xdl/src/Exp.ts
packages/xdl/src/project/ManifestHandler.ts

reducing the reload time for client reloads. There are still 5 reads taking place each time.

Remove extra config read when resolving entry point

---

packages/config/src/Config.ts
packages/config/src/Config.types.ts
packages/config/src/__tests__/Config-test.js

First piece of `Constants.manifest` support in bare workflow. Later we'll be adding a script to `expo-constants` that evaluates and generates and app config to include in bare apps for `Constants.manifest`.
This PR adds a method to `@expo/config` which that script can use to get the subset of the app config intended for public consumption (e.g. the data that would be served with the manifest from expo-cli or www).
From reading the publish code in XDL, it looks like the pieces of the app config that are deleted *for the purpose of not being visible in the public manifest* are the `hooks`, `ios.config`, and `android.config` fields. (Many other fields are changed, of course, but these seem to be the sensitive ones.) Therefore, the current implementation of this method simply deletes those …

[config] add getPublicExpoConfig method and tests

---

packages/config/src/Config.ts
packages/config/src/Config.types.ts
packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts

Delete `getConfigWithMods` in favor of a `GetConfigOptions` property. Similar to what we do with `isPublicConfig`.

[config] use config option instead of custom config method

---

packages/xdl/src/Project.ts

Follow-up to https://github.com/expo/expo-cli/pull/2863 -- not necessary for `Constants.manifest` support but just to clean up the codebase a little bit.
Since we essentially use the public expo config during `expo publish` and `expo export`, this PR makes those commands use the actual `getPublicExpoConfig` method for this rather than duplicating its logic. Hopefully this will help catch issues and keep the public config in sync between publish/export and `Constants.manifest`.
Tested this by publishing NCL (which does have private config fields) with and without this change and then diffing the resulting manifests served by www. Ensured that no fields changed other than the ones we'd expect due to the time difference between publishes. (Definitely open to suggestions for how to test this …

[config][xdl] migrate project/publish to getPublicExpoConfig

---

packages/expo-cli/src/commands/eject/Eject.ts
packages/expo-cli/src/commands/eject/__tests__/Eject-test.ts

- fix https://github.com/expo/expo-cli/issues/2873
- Ensure that an `index.js` is generated in projects that don't define a main field in their `package.json` if the `./index.js` (and platform extended variations) aren't present.
- Ensure that an `index.js` is not generated if the `package.json` defines a main field that resolves to an existing file, unless that file is the expo managed workflow default (`expo/AppEntry` + variations).

[expo-cli][eject] Resolve main fields to determine if an index.js should be generated

---

packages/expo-cli/src/commands/upload.ts

In order to drop Fastlane supply (Android upload) we need to switch to using the submission service by default.

[expo-cli] Use submission service by default

---

packages/expo-cli/src/commands/upload.ts
packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmissionConfig.ts
packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitCommand.ts
packages/expo-cli/src/commands/upload/submission-service/android/AndroidSubmitter.ts
packages/expo-cli/src/commands/upload/submission-service/android/__tests__/AndroidSubmitCommand-test.ts
packages/expo-cli/src/commands/upload/submission-service/archive-source/ArchiveFileSource.ts
packages/expo-cli/src/commands/upload/submission-service/archive-source/index.ts
packages/expo-cli/src/commands/upload/submission-service/types.ts

Follow up to https://github.com/expo/expo-cli/pull/2876
- Remove "offline" uploader. For future readers, this was not an "offline" method for uploading files to the internet as that would be impossible. 
- Removes the need for fastlane supply running locally on the users computer.

[expo cli] delete legacy upload:android code

---

packages/expo-cli/src/accounts.ts
packages/expo-cli/src/appleApi/authenticate.ts
packages/expo-cli/src/askUser.ts
packages/expo-cli/src/commands/client/index.ts
packages/expo-cli/src/commands/eject/ConfigValidation.ts
packages/expo-cli/src/commands/upload/IOSUploader.ts
packages/expo-cli/src/commands/upload/submission-service/android/AndroidPackageSource.ts
packages/expo-cli/src/commands/upload/submission-service/android/ServiceAccountSource.ts
packages/expo-cli/src/commands/upload/submission-service/android/__tests__/ServiceAccountSource-test.ts
packages/expo-cli/src/commands/upload/submission-service/archive-source/ArchiveFileSource.ts
packages/expo-cli/src/commands/upload/submission-service/archive-source/ArchiveTypeSource.ts
packages/expo-cli/src/commands/utils/ClientUpgradeUtils.ts
packages/expo-cli/src/credentials/views/AndroidCredentials.ts
packages/expo-cli/src/credentials/views/AndroidPushCredentials.ts
packages/expo-cli/src/credentials/views/IosDistCert.ts
packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
packages/expo-cli/src/credentials/views/IosPushCredentials.ts
packages/expo-cli/src/credentials/views/Select.ts
packages/expo-cli/src/prompts.ts

- It's a big messy package that increases our CLI install time by including packages like rxjs
- part of https://github.com/expo/expo-cli/issues/1983
- still three complex cases to remove later. One of which is in `react-dev-utils` https://github.com/facebook/create-react-app/pull/10083
- copy the changes made in eas-cli.
- changed `type`s
- list -> select
- input or undefined -> text
- changed options
- `pageSize` -> `optionsPerPage` (also added the missing type in our abstraction).
- default -> initial
- filter -> format
- choices.name -> choices.title

[expo cli] mostly remove inquirer

---

packages/expo-cli/src/commands/upgrade.ts

- fix https://github.com/expo/expo-cli/issues/2685 -- this will make upgrading expo/examples much easier.
- bit of an aha moment, projects without configs don't need any kind of upgrading, so certain steps can just be skipped.
- tested by running `expo upgrade` in `examples/with-facebook-auth`

[cli][upgrade] support projects without a config

---

packages/xdl/src/Webpack.ts

- Fix issue where warning is being shown even when service workers are being included by expo
- Fix link format

Improve PWA warning

---

packages/expo-cli/package.json
packages/expo-cli/src/CommandError.ts
packages/expo-cli/src/commands/build/BuildError.ts
packages/schemer/package.json
packages/schemer/src/Error.ts
packages/xdl/package.json
packages/xdl/src/Api.ts
packages/xdl/src/ApiV2.ts
packages/xdl/src/TurtleApi.ts
packages/xdl/src/XDLError.ts
yarn.lock

- Doesn't appear as though `es6-error` is adding any value. We have three copies of it in the repo.

Remove es6-error in favor of Error

---

package.json
yarn.lock

Resolve the empty hermes (required by `expo/metro-config`) package in development to cut down on CI time.
```
1.2G	.
921M	./node_modules
140M	./node_modules/@expo
138M	./node_modules/hermes-engine
116M	./node_modules/@expo/traveling-fastlane-darwin/dist/lib
116M	./node_modules/@expo/traveling-fastlane-darwin/dist
116M	./node_modules/@expo/traveling-fastlane-darwin
```
```
1.0G	.
783M	./node_modules
140M	./node_modules/@expo
116M	./node_modules/@expo/traveling-fastlane-darwin/dist/lib
116M	./node_modules/@expo/traveling-fastlane-darwin/dist
116M	./node_modules/@expo/traveling-fastlane-darwin
106M	./packages
```

resolve empty hermes package

---

packages/expo-cli/src/commands/build/BaseBuilder.ts
packages/xdl/src/Project.ts

While investigating https://github.com/expo/expo-cli/issues/2909, noticed that the types here were incorrect. The issue looks like it was fixed in https://github.com/expo/expo-cli/pull/2912 (invalid property access on a possibly undefined variable), but the correct types help verify that it was fixed.
I don't think this is a server issue unless this is widespread, but I'm not sure how to check since we don't seem to have sentry for expo-cli. @EvanBacon, @fson - any suggestions on how to see the rate of this error since it's client-side?
Copy types from www, the source of truth in the matter.
`yarn tsc`

[cli] Fix build/status return types

---

packages/image-utils/src/jimp.ts

Web favicon is blurry, it has been reported in https://github.com/expo/expo-cli/issues/2012, which is closed but problem is still here.
I checked code and notice an error when icons are resized.
Jimp [resize method](https://github.com/oliver-moran/jimp/tree/master/packages/plugin-resize#usage) is mutable, so images were all 16x16.

[image-utils] Fix blurry web favicon

---

packages/config/src/android/Permissions.ts
packages/config/src/ios/Permissions.ts
packages/config/src/ios/__tests__/Permissions-test.ts
packages/config/src/ios/index.ts

Most packages will need a generic method for adding permissions, this provides that.
Example:
```ts
const withImagePicker: ConfigPlugin<{
photoLibraryPermission: string;
cameraPermission: string;
microphonePermission: string;
}> = (
config,
{ photoLibraryPermission, cameraPermission, microphonePermission }
) => {
return withPlugins(config, [
(c) =>
IOSConfig.Permissions.withPermissions(c, {
NSPhotoLibraryUsageDescription: photoLibraryPermission,
NSCameraUsageDescription: cameraPermission,
NSMicrophoneUsageDescription: microphonePermission,
}),
(c) =>
AndroidConfig.Permissions.withPermissions(
c,
[
"android.permission.CAMERA",
"android.permission.READ_EXTERNAL_STORAGE",
"android.permission.WRITE_EXTERNAL_STORAGE",
!!microphonePermission && "android.permission.RECORD_AUDIO", …
```

[config] permissions plugins

---

CHANGELOG.md
packages/xdl/src/Project.ts

Always use in-process Metro (`@expo/dev-server`) for SDK 40 and newer. Metro is used to bundle JS in `expo start` , `expo publish` and `expo export` commands. `@expo/dev-server` is a rewrite of the interface between Expo CLI and Metro bundler that uses the JS APIs of Metro (instead of running React Native CLI as a subprocess) to make bundling faster and handling Metro configurations more predictable.
For older SDK versions, keep the old behavior (in-process Metro can be enabled by setting `EXPO_USE_DEV_SERVER=true` in the environment).
This is not a breaking change because the behavior for already released SDKs stays the same and all SDK 40 testing is done using in-process Metro.
Fixes #2322.

[xdl] Switch to in-process Metro JS bundling starting from SDK 40

---

packages/xdl/src/Project.ts
packages/xdl/src/project/errors.ts
packages/xdl/src/project/ngrok.ts

- Project.ts is too large and diconnected, splitting out ngrok makes it easier to find related code.

split up ngrok code

---

packages/expo-cli/src/commands/fetch/android.ts
packages/expo-cli/src/commands/fetch/index.ts
packages/expo-cli/src/commands/fetch/ios.ts

- improve bundle id resolution with `getOrPromptForBundleIdentifier`
- improve errors
- unify slug assertions
- show config syntax errors correctly
- use single line error format on iOS (switch to CommandError)
- projectDir -> projectRoot
- add async suffix

clean up fetch commands

---

packages/expo-cli/src/askUser.ts
packages/expo-cli/src/commands/client/index.ts
packages/expo-cli/src/commands/publish.ts
packages/expo-cli/src/commands/send.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/prompts.ts
packages/expo-cli/src/sendTo.ts

- use ora instead of simple spinner (this matches the prompts logs closer)
- surface error API message
- unify email prompt validation
- unify exports

clean up send command

---

CHANGELOG.md
packages/xdl/src/detach/AndroidShellApp.js

When a user does not provide a splash image we shouldn't show any image.
Ensured the splash screen image from Expo Client is not propagated to standalones.
Resolves https://forums.expo.io/t/how-to-remove-default-expo-splash-screen/44789/2
I've jumped back to `sdk-39` branch, build local standalone simulator app for Android.

[xdl]<fix>: Remove default splash screen image on Android

---

packages/traveling-fastlane/Rakefile
packages/traveling-fastlane/actions/new_manage_provisioning_profiles.rb
packages/traveling-fastlane/publishing/darwin/index.js
packages/traveling-fastlane/publishing/linux/index.js
packages/traveling-fastlane/wrappers/new_manage_provisioning_profiles_wrapper.sh

This PR adds a slightly modified version of `manage_provisioning_profiles.rb` so I could use it for managing ad-hoc provisioning profiles in EAS CLI (the PR that takes advantage of the new script is here - https://github.com/expo/eas-cli/pull/59). 
Notable changes:
- replaced positional param `isEnterprise` with `profileType` (possible values: `in_house_dist`, `in_house_adhoc`, `app_store_dist`, `app_store_adhoc`)
- all commands which return the provisioning profile include the `devices` property (makes sense only for ad-hoc profiles)
<details>
<summary>Click to expand</summary>
```patch
0a1,5
> # (@dsokal)
> # This is a slightly modified `manage_provisioning_profiles.rb` that's going to be used in eas-cli.
> # I didn't want to modify the original script because I didn't want to spend …
```

[traveling-fastlane] manage_provisioning_profiles: add support for adhoc profiles

---

packages/config/src/plugins/core-plugins.ts

```ts
const plugin = (config, props) => config
withPlugins(config, [
[plugin, { /* props now required*/ }]
// this will now throw a TS error as props are required.
plugin
])
```

Prevent passing a plugin that requires props without props

---

packages/config/src/Plugin.types.ts
packages/config/src/android/Name.ts
packages/config/src/android/Paths.ts
packages/config/src/android/__tests__/Name-test.ts
packages/config/src/plugins/android-plugins.ts
packages/config/src/plugins/compiler-plugins.ts
packages/config/src/plugins/expo-plugins.ts

- resolve https://github.com/expo/expo-cli/issues/2696
- added mod for settings.gradle `android.settingsGradle`
- added mod to update the name property using regex
- tested the name using naming convention I discovered by using a bunch of invalid characters in Android studio then syncing the gradle files. Eventually I got a useful error message regarding which characters couldn't be used (but no docs pages).
- tested building a project using a complex name, added unit tests for core functionality.

Support updating the project settings.gradle name on sync

---

packages/config/src/ios/Entitlements.ts
packages/config/src/ios/__tests__/Entitlements-test.ts
packages/config/src/plugins/__tests__/__snapshots__/expo-plugins-test.ts.snap

- ejected projects have notifications by default so our template should come with notifications enabled by default too. Without this iTunes warns about a binary issue: `ITMS-90078: Missing Push Notification Entitlement`
- wasn't sure if we should do development or production by default but it seems we use development in the Expo client, and Xcode defaults to development.

Enable notifications by default

---

packages/expo-cli/src/commands/upgrade.ts

This is useful so we can easily test standalone app builds on existing apps without needing to manually update deps or make the beta release publicly available through documented mechanisms.

[cli] Make it possible to run expo upgrade with beta release prior to setting flag

---

packages/config-plugins/src/Plugin.types.ts
packages/config-plugins/src/plugins/core-plugins.ts
packages/config-plugins/src/plugins/mod-compiler.ts
packages/config/package.json
packages/config/src/Config.ts
packages/config/src/__tests__/Config-test.ts
packages/config/src/__tests__/ConfigParsing-test.ts

- Fill `config._internal` object with contents of `ConfigContext` -- this will make converting `app.config.js` function signature to `ConfigPlugin` easier.
- Added `config._internal.isDebug` and `config._internal.projectRoot` from `config.modRequest` -- this makes config mods more like regular plugins, and will make static plugins easier to resolve from root.
- Delete `_internal` in public configs to prevent exposing user computer file paths.

[config] fill _internal object

---

packages/expo-cli/src/commands/init.ts
packages/xdl/src/Versions.ts

We always use the latest template unless the user explicitly passes in a version. This PR changes that so if `EXPO_BETA=1` is enabled and the latest release is a beta, then it will append the `@sdk-x` tag to the selected template. When no beta is available or the `EXPO_BETA=1` flag is not set,  this will have no effect.

[xdl][cli] Fix beta integration of init

---

packages/expo-cli/src/commands/__tests__/upgrade-test.ts
packages/expo-cli/src/commands/upgrade.ts

Currently we always use the `jest-expo@sdkVersion` if not specified in bundledNaitveModules or relatedPackages. We should use the `-beta` version the SDK version is in beta.

[expo-cli] Fallback to jest-expo@sdkVersion-beta when using beta sdk 

---

packages/config-plugins/src/plugins/__tests__/core-plugins-test.ts
packages/config-plugins/src/plugins/__tests__/expo-plugins-test.ts
packages/config-plugins/src/plugins/__tests__/plugin-compiler-test.ts
packages/config-plugins/src/plugins/mod-compiler.ts
packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
packages/expo-cli/src/commands/eject.ts
packages/expo-cli/src/commands/eject/Eject.ts

- support managed projects in `eas build` by disabling certain platforms when ejecting
- skips the bundle id or package name prompt
- added `--platform` to `expo eject` to choose platforms (ios, android, all (like eas)).
- tested that a project without a corresponding native folder can sync successfully
- added `platforms` to mod compiler, this is used for skipping any mod on a particular platform.
- third-party plugins that use a particular mod will automatically be compliant
- missing native files won't be written or read

Added ability to skip platforms when ejecting

---

packages/expo-cli/src/commands/utils/url.ts

As a follow-up to https://github.com/expo/universe/pull/6547, which unifies the URL structure of builds pages for Turtle v2, we should stop serving those URLs in our CLIs.

[cli][build] Use unified website route for all builds (no more /v2)

---

packages/config-plugins/src/android/SplashScreen.ts
packages/config-plugins/src/ios/SplashScreen.ts

@expo/configure-splash-screen didn't change much between SDK 39 and 40 and should be compatible with both versions.

[config-plugins] Support splash screen config on SDK 40

---

packages/expo-cli/src/commands/eject/Eject.ts

We embed manifest in bare apps now! https://github.com/expo/expo/blob/master/packages/expo-constants/README.md#optional-set-up-script-to-get-app-config

[cli] Skip warning about expo-constants when ejecting in SDK 40 and greater

---

packages/config-plugins/package.json
packages/config-plugins/src/plugins/core-plugins.ts

Fallback to the env variable when _internal isn't defined. We support the env variable because user mods won't have _internal defined in time.

use env variable for debug when _internal isn't defined

---

packages/config/src/Serialize.ts
packages/config/src/__tests__/fixtures/plugins/my-plugin.js

mods weren't being skipped in post-plugin serialization. I added a test that doesn't work due to the nature of our `requireString()` code.  Tests just run like this without the fix:
```
(node:16415) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property 'modRequest' of '_a' as it is undefined.
(node:16415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled w
ith .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16415) [DEP0018] DeprecationWarning: Unhandled …
```

fix mod serialization

---

packages/xdl/src/__integration_tests__/UserSessions-test.ts

Why: This endpoint is otherwise unused; remove the last caller so we can remove it from www.
How: I replaced the endpoint with the `auth/userInfo` endpoint, which is still used and suffices for this test.
Test Plan: Ran `yarn integration-tests` in XDL after removing `.skip` from `UserSessions-test.ts`.

Remove last call to intercomHash endpoint

---

packages/config-types/src/ExpoConfig.ts

**do not land until orgs release**
Developer Services is getting renamed, and once organizations are announced the `owner` field won't apply to only Developer Services users anyways.

[config-types] replace Developer Services with EAS Priority Plan

---

packages/config-plugins/src/plugins/compiler-plugins.ts
packages/config-plugins/src/plugins/core-plugins.ts
packages/config-plugins/src/utils/errors.ts

passing them as warnings was pretty useless 
completes without any problems and logs the following warnings
```
⚠️  Android config synced with warnings that should be fixed:
- android-manifest: AndroidManifest.xml configuration could not be applied. Assignment to constant variable.
```
Fails immediately with the following error:
```
android.manifest: AndroidManifest.xml mod error:
Assignment to constant variable.
TypeError: Assignment to constant variable.
at /Users/evanbacon/Documents/GitHub/crypto-wallet/withStripe.js:94:21
at action (/Users/evanbacon/Documents/GitHub/crypto-wallet/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:119:29)
at interceptingMod (/Users/evanbacon/Documents/GitHub/crypto-wallet/node_modules/@expo/config-plugins/src/plugins/core-plugins.ts:186:12) …
```

throw mod errors

---

packages/config-plugins/package.json
packages/expo-cli/package.json
packages/expo-cli/src/accounts.ts
packages/expo-cli/src/assert.ts
packages/expo-cli/src/commands/fetch/android.ts
packages/expo-cli/src/commands/webhooks.ts
packages/expo-cli/src/credentials/api/IosApi.ts
packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
packages/expo-cli/src/credentials/views/Select.ts
packages/plist/src/parse.ts
packages/xdl/package.json
packages/xdl/src/detach/IosWorkspace.js
yarn.lock

Remove invariant in favor of built in package assert.
invariant is still thoroughly used in the repo though, this just reduces the amount of top-level dependencies:
```
- "_project_#@babel#preset-env" depends on it
- Hoisted from "_project_#@babel#preset-env#invariant"
- Hoisted from "_project_#metro#invariant"
- Hoisted from "_project_#metro-source-map#invariant"
- Hoisted from "_project_#metro-symbolicate#invariant"
- Hoisted from "_project_#@expo#dev-tools#react-dnd#invariant"
- Hoisted from "_project_#@expo#metro-config#expo#invariant"
- Hoisted from "_project_#@babel#preset-env#@babel#compat-data#invariant"
- Hoisted from "_project_#@babel#preset-env#@babel#helper-compilation-targets#invariant"
- Hoisted from "_project_#metro#jest-haste-map#invariant"
- Hoisted from …
```

remove invariant in favor of assert

---

packages/xdl/src/detach/IosShellApp.js

Since we dropped support for iOS 10.0 in https://github.com/expo/expo/pull/11344, we also have to remove `i386` from the architectures that we build shell apps against.
I could also add `arm64`, but I'm intentionally not doing it because some of our dependencies providing prebuilt binaries don't support this architecture yet.

[xdl] Stop building shell apps for 32-bit architecture

---

packages/expo-cli/src/commands/start.ts
packages/xdl/src/Project.ts

It's possible to develop bare apps with Expo Go as documented in https://docs.expo.io/bare/using-expo-client/
For this use case, we need to use 'managed' as the default target for the dev server, because otherwise bare apps would default to 'bare':
https://github.com/expo/expo-cli/blob/cc4613dc4d9aeedcfb3ea69d9293fb66142c7148/packages/metro-config/src/ExpoMetroConfig.ts#L42

Use 'managed' as the default target for the dev server

---

packages/dev-tools/__mocks__/@expo/xdl.js
packages/dev-tools/server/graphql/GraphQLSchema.ts
packages/expo-cli/src/commands/send.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/commands/url.ts
packages/expo-cli/src/urlOpts.ts
packages/metro-config/src/ExpoMetroConfig.ts
packages/xdl/src/Android.ts
packages/xdl/src/DevSession.ts
packages/xdl/src/ErrorCode.ts
packages/xdl/src/Project.ts
packages/xdl/src/ProjectSettings.ts
packages/xdl/src/Simulator.ts
packages/xdl/src/UrlUtils.ts
packages/xdl/src/__tests__/UrlUtils-test.ts
packages/xdl/src/project/ExpSchema.ts

- ~Should work without having the `expo` package installed.~ We will require that developers either set an SDK version or install the `expo` package (as a regular dependency or dev dependency) to use expo-dev-launcher.
- Should deep link into the app using the url format: `myscheme://expo-development-client/?url=url-encoded-path-to-app-manifest` ([described on Notion](https://www.notion.so/expo/Deep-Linking-URL-Format-for-Development-Clients-b721472abba0426ea1e747c3718aaf4a)).

Update --dev-client for new requirements

---

packages/config/src/plugins/withInternal.ts
packages/config/src/plugins/withStaticPlugin.ts
packages/expo-cli/src/commands/apply/configureManagedProjectAsync.ts
packages/expo-cli/src/commands/eject/Eject.ts

When ejecting a project with expo SDK packages, we'll automatically apply a hardcoded list of package's plugins if they exist. This will create configuration parity with managed apps.
When a plugin can be auto-configured, it'll be removed from the list of plugins with additional setup.

[eject] auto apply optional managed plugins

---

packages/config-plugins/src/android/Version.ts
packages/config-plugins/src/android/__tests__/Version-test.ts

running expo eject in a blank android project would add 1 to the versionCode every time it was run, this fixes that fwict.

fix bug where android version code would append 1 every time eject was run

---

CHANGELOG.md
packages/webpack-config/package.json
packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
packages/xdl/src/project/ManifestHandler.ts

We currently expose the environment variables matching `EXPO_` and `REACT_NATIVE_` in development. This is a security risk and we have other more preferred methods for passing data to the client via the manifest `extras` field. 
- On web, this feature didn't quite work as expected, it only added to `process.env` and not `Constants.manifest.env`. It's now completely disabled as web presents a larger risk.
- On native, this feature will be disabled starting in SDK 41
- Lower the minimum SDK requirement to a released version like `40.0.0`
- Add an environment variable starting with `EXPO_` like `expo EXPO_SOMN=true`
- Run a project with `console.log(process.env, Constants.manifest.env)` in it
- The logs should no longer show these env variables exposed

Don't expose Expo environment variables publicly

---

packages/config/src/Config.ts

Without this expo start throws the following because mods are not part of the schema:
```
Error: Problems validating fields in app.json. See https://docs.expo.io/workflow/configuration/
• should NOT have additional property 'mods'.
```

delete mods after static plugins are added when they aren't requested

---

packages/config-plugins/src/plugins/mod-compiler.ts

- add a scalable system for sorting mod order
- run the XcodeProject mod second because many plugins attempt to read from it

[config-plugins] sort mods better

---

unlinked-packages/configure-splash-screen/package.json
unlinked-packages/configure-splash-screen/src/android/MainActivity.ts
unlinked-packages/configure-splash-screen/src/android/Paths.ts
unlinked-packages/configure-splash-screen/yarn.lock

`@react-native-community/cli-platform-android` consistently fails to resolve the MainActivity file path which causes the plugins to fail unless the splash-screen is run first (no longer possible now that static configs are a thing). Drop-in the resolution we use in config-plugins for now.

[configure-splash-screen] fixed file resolution

---

packages/config/src/paths/__tests__/__snapshots__/extensions-test.ts.snap
packages/config/src/paths/extensions.ts
packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap

wasm isn't supported on native so skip module resolution for `.wasm` files. Removed `.android.wasm`, `.ios.wasm`, `.native.wasm`, and `.wasm` on iOS and Android.

Only use wasm on web platforms

---

packages/expo-cli/src/commands/eject/Eject.ts

- preserve when someone is using a fork or a custom version of react-native during eject or prebuild.

[prebuild] Only change react-native version when it's a fork

---

packages/config-plugins/src/android/Updates.ts
packages/config-plugins/src/android/__tests__/Updates-test.ts
packages/config-plugins/src/android/__tests__/__snapshots__/Updates-test.ts.snap
packages/config-plugins/src/android/__tests__/fixtures/build-with-incorrect-create-manifest-android-path.gradle
packages/config-plugins/src/android/__tests__/fixtures/build-without-create-manifest-android.gradle
packages/config-plugins/src/ios/Updates.ts
packages/config-plugins/src/ios/__tests__/Updates-test.ts
packages/config-plugins/src/ios/__tests__/__snapshots__/Updates-test.ts.snap
packages/config-plugins/src/ios/__tests__/fixtures/project-with-incorrect-create-manifest-ios-path.pbxproj
packages/config-plugins/src/ios/__tests__/fixtures/project-without-create-manifest-ios.pbxproj

This PR fixes configuring expo-updates when the react native project is in a yarn/npm workspace.
There are two cases:
- Android 
- build.gradle can contain a line: `apply from: "../../node_modules/expo-updates/scripts/create-manifest-android.gradle"`
- Currently, `eas build:configure` checks whether `build.gradle` contains a line that looks sth like `apply from: "../../../../node_modules/expo-updates/scripts/create-manifest-android.gradle"` (more `../`)
- The new (correct) line is added to the file but the old one is still there. 
- This causes build failures.
- iOS
- This is similar to the Android case.
- `Bundle React Native code and images` build phase contains a wrong path to `create-manifest-ios.sh`
- `eas build:configure` checks for the existence of the correct path to …

[config-plugins] improve monorepo support - fix setting path to create-manifest-* script

---

packages/expo-cli/src/credentials/views/IosPushCredentials.ts
packages/expo-cli/src/credentials/views/Select.ts

fixes https://github.com/expo/expo/issues/11656
After generating a new push key, we should give the option to assign that key to the current project context, if there is one. Otherwise, it can be confusing that you need to create the key, _then_ assign it

[expo-cli] add option to assign created push key to current project

---

packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/utils/typescript/__tests__/ensureTypeScriptSetup-test.ts
packages/expo-cli/src/commands/utils/typescript/__tests__/updateTSConfig-test.ts
packages/expo-cli/src/commands/utils/typescript/ensureTypeScriptSetup.ts
packages/expo-cli/src/commands/utils/typescript/resolveModules.ts
packages/expo-cli/src/commands/utils/typescript/updateTSConfig.ts

- When running `expo start`, auto detect if TypeScript is in use, then do the following:
- Verify that the required packages are installed. If not, prompt to install them then try again (disabled in CI).
- Ensure the `tsconfig.json` is properly configured.
- Tell users how to remove TypeScript if they added it by accident (tsconfig.json, TypeScript project files).
- Feature can be disabled using `EXPO_NO_TYPESCRIPT_SETUP=1`
- Detect and use `expo/tsconfig.base` as the default `extends` value when it's present (https://github.com/expo/expo/pull/11680).

Auto configure TypeScript

---

packages/config-plugins/src/android/Version.ts
packages/config-plugins/src/android/__tests__/Version-test.ts

Fixes #3081
The issue was that the `versionToReplace` parameter was never provided. There also didn't seem to be a good way of retrieving the value set in `android/app/build.gradle`.
Instead of doing that, I applied the same approach as [this `versionCode` fix](https://github.com/expo/expo-cli/commit/edd590b825db32b2db3dd8f0af324b7b3db24d6c#diff-791f73eecd02a99877dd27c2ea8f8eba5ee22d21ea2cda0c0622bf322b6d6b8fL47-L59)

[config-plugins] Fix app gradle versionName replacement after ejecting twice

---

packages/config-plugins/src/ios/Google.ts
packages/config-plugins/src/ios/Locales.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts

- resolve https://github.com/expo/expo-cli/issues/3085
Not much we can do here to make the plugin idempotent. This problem doesn't occur in prebuild where the feature is considered "stable". 
We'll now warn if a duplicate file reference is skipped because an existing file reference is conflicting. The contents of the file will still be copied over though.

Prevent adding duplicate Xcode references for files

---

packages/xdl/src/Project.ts

Fixes https://github.com/expo/expo/issues/11652
Currently, JS bundles created from `expo export --dump-sourcemap` do not run in an SDK 40 bare project -- they fail with the familiar `Module AppRegistry is not a registered callable module` error. The cause seems to be the following lines:
https://github.com/expo/expo-cli/blob/62339b5fb7300569ca6cbb034251070bf8a63999/packages/xdl/src/Project.ts#L495-L496
The line that's being truncated is:
```
eric@Erics-iMac SelfHostTest % cat bundles/android-bcbcf3a727c6c6465382b49ddcf806e8.js
...
__r(0);
```
The bundles run fine without this line truncated. Since I'm not sure of the context/reasoning around truncating this line in the first place, I've simply added a gate that doesn't truncate for SDK 40+ bare projects.
- self-hosted update created with …

[xdl] fix expo export --dump-sourcemap for sdk 40+ and bare projects

---

packages/expo-cli/src/commands/publish.ts
packages/expo-cli/src/commands/utils/PublishUtils.ts

Right now, people who are using robots without the `owner` field see the "Robots are not supported for this API call" error. Which isn't descriptive about the missing `owner` field. This adds validation with descriptive error messages for all the 3 `expo publish:*` commands we have.
I also added the `Owner: ...` field when publishing as robot, but maybe we should include it whenever the owner isn't the same as the user's username?
publish with robot | publish with user
--- | ---

[expo-cli] Validate project owner when publishing

---

packages/expo-cli/src/commands/eject/Eject.ts

Noticed this bug when trying to eject without `devDependencies` defined in package.json.

Check for optional `devDependencies`

---

packages/xdl/src/detach/AndroidShellApp.js

Support name `Expo Go` in shellapp template

[xdl] Support Expo Go name in shellapp template

---

packages/expo-cli/src/commands/customize.ts

I spent... too long not realizing I simply hadn't selected anything with space before hitting 'enter' in this menu.  The instructional copy was low enough contrast I didn't notice it until after I went debugging here in the code.
Briefly, the answer var will be an empty array if you didn't select anything but still hit "enter", and so this check will always be truthy in that case, firing the subsequent generate function without any copy noting that... nothing happened.  This PR clarifies the copy a bit, and makes sure it fires even when selection set is empty.

[expo-cli] Improve handling of no answer for customize:web

---

packages/expo-cli/src/accounts.ts

Fixes #3119
When users define both `EXPO_CLI_USERNAME` and `EXPO_CLI_PASSWORD`, authenticate them. Even when using an interactive prompt.

[expo-cli] Auto-login when envvars are defined

---

packages/expo-cli/package.json
packages/xdl/package.json
yarn.lock

- remove more lodash copies by allowing flexible versions. In the repo the versions are `4.17.19` but in product there are two `4.17.20` and `4.17.19`. Adding version flexibility cuts down on one more copy of lodash (4mb).
- ignore `**/__integration_tests__/**` tests when bundling expo/xdl.

use less lodash and ignore tests in xdl publish

---

packages/schemer/package.json
packages/xdl/package.json
yarn.lock

Removes two install warnings:
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

upgrade probe-image-size

---

packages/xdl/src/Project.ts

The Gradle/Xcode projects for bare apps [expect the Metro bundler to run on port 8081, unless a different port is specified using the `RCT_METRO_PORT` environment variable.](https://github.com/facebook/react-native/blob/f2c6279ca497b34d5a2bfbb6f2d33dc7a7bea02a/template/ios/HelloWorld.xcodeproj/project.pbxproj#L253)
When running a bare project with `expo start --dev-client`, Expo CLI starts Metro on the first available port from `19000` and up. This is how Expo CLI has always worked, but this means the Gradle/Xcode projects won't find the Metro instance and will always start their own, even if you've already started Expo CLI.
This PR changes the default port used with `--dev-client` to `8081`, or the value of `RCT_METRO_PORT` if set, [matching the behavior of RN …

[xdl] Default to Metro port 8081 with --dev-client

---

packages/expo-cli/src/appleApi/authenticate.ts

- fix https://github.com/expo/expo-cli/issues/3138

[expo-cli] pass username to apple auth check

---

packages/expo-cli/src/commands/eject.ts
packages/expo-cli/src/commands/eject/Eject.ts
packages/expo-cli/src/commands/eject/__tests__/Eject-test.ts

Fix a logic bug where ios warnings weren't being logged on windows.

[expo-cli][eject] warn iOS on windows

---

packages/dev-server/package.json
packages/dev-server/src/MetroDevServer.ts

- pull expo/config from dev-server
- reduce config reads
- related expo/universe#6889

Drop support for nodeModulesPath prop

---

packages/config-types/src/ExpoConfig.ts
packages/schemer/__tests__/files/schema.json
packages/xdl/src/Project.ts

- This is no longer needed now that yarn workspaces exist, drop it to simplify the startup script and Expo config schema.

Drop support for expo.rnCliPath

---

packages/expo-cli/src/commands/utils/CreateApp.ts
packages/expo-cli/src/exp.ts
packages/package-manager/src/CocoaPodsPackageManager.ts

- resolve https://github.com/expo/expo-cli/issues/2879 by skipping the sudo prompt. There is too much going on in the single process to attempt a prompt, so we'll just skip it and warn the user to install CocoaPods CLI and install the pods manually `npx pod-install`. 
- Improved the errors being thrown by `CocoaPodsPackageManager`, you can now see more input on why pod install failed:
```
⚠️  Unable to install the CocoaPods CLI. Continuing with project sync, you can install CocoaPods CLI afterwards.
Failed to install CocoaPods with Homebrew. Please install CocoaPods CLI manually and try again.
└─ Cause: CocoaPodsError: Homebrew installation appeared to succeed but CocoaPods CLI not found in PATH and unable to link.
└─ Cause: Error: brew exited with non-zero code: 1
```

Always install eject pods in non interactive mode

---

CHANGELOG.md
packages/xdl/src/project/ManifestHandler.ts

When the `ManifestHandler` tries to sign the manifest (requested by the client), automatically handle typical errors and fall back to offline mode:
- The project has an `owner` specified, but you lack permissions to that account -> fall back to offline mode! Fixes https://github.com/expo/expo-cli/issues/3062.
- You don't have an internet connection, which results in `Error: getaddrinfo ENOTFOUND exp.host` -> fall back to offline mode! Fixes https://github.com/expo/expo-cli/issues/238.

[xdl] Handle errors when trying to sign the manifest

---

packages/metro-config/src/ExpoMetroConfig.ts

Set default port to 8081 to make sure it's used by default rather than 8080 from the Metro defaults,
as this is required by the build phase scripts in the Xcode project by default.

[metro-config] Set server port in default config

---

packages/xdl/src/Api.ts
packages/xdl/src/ApiV2.ts
packages/xdl/src/project/__tests__/ManifestHandler-test.ts

Fixes #3158 
Axios split `maxContentLength` and `maxBodyLength`. As @fson pointed out, [the first used to imply the latter](https://github.com/axios/axios/blob/8d0b92b2678d96770304dd767cd05a59d37f12cf/lib/adapters/http.js#L175-L177). Now they [split it up into two different config properties](https://github.com/axios/axios/pull/2781). So, we need to define `maxBodyLength` too.
- Create a new project
- [Import an image (20mb+)](https://effigis.com/en/solutions/satellite-images/satellite-image-samples/) in `App.js`, `const Img = require('./assets/my-img.jpg');`
- `npx expo-cli@4.1.4 publish --release-channel=test`, will fail with `Request body larger than maxBodyLength limit`
- CLI with this PR succeeds without errors.

[xdl] Define max content and body lengths in Axios 0.21

---

CHANGELOG.md
packages/config-plugins/src/ios/index.ts
packages/config-plugins/src/plugins/expo-plugins.ts

Fix a small typo in this identifier.

[config-plugins] Rename `IOSConfig.BundleIdenitifer` to `IOSConfig.BundleIdentifier`

---

packages/expo-cli/src/commands/init.ts

- Also dropped all lodash in init

[expo-cli] fix init visual regression

---

packages/package-manager/package.json
packages/xdl/package.json
packages/xdl/src/Webpack.ts
yarn.lock

`devcert` has a bunch of unused dependencies that aren't being removed (https://github.com/davewasmer/devcert/pull/66) so I've forked it and published a more optimal bundle. Tested by running `expo web --https`.

Use devcert fork

---

packages/xdl/src/credentials/AndroidCredentials.ts

When Java is not installed, the legacy `keytool` error messages are cryptic and hard to understand. 
Resolves #3044 
Running `expo ba`
**before**
```
If you don't know what this means, let us generate it! :) › Generate new keystore
Failed to generate Android Keystore, it will be generated on Expo servers during the build
keytool exited with non-zero code: 1
```
**after**
```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
Failed to generate Android Keystore, it will be generated on Expo servers during the build
keytool exited with non-zero code: 1
```

[xdl] Improve keytool errors

---

packages/expo-cli/src/commands/upgrade.ts

- resolve https://github.com/expo/expo-cli/issues/3159

[expo-cli][upgrade] Cancel command on ctrl+c

---

CHANGELOG.md
packages/expo-cli/src/commands/build/BaseBuilder.ts
packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
packages/expo-cli/src/commands/build/findReusableBuildAsync.ts
packages/expo-cli/src/commands/build/getBuildStatusAsync.ts
packages/expo-cli/src/commands/build/getLatestReleaseAsync.ts
packages/expo-cli/src/commands/build/startBuildAsync.ts
packages/expo-cli/src/commands/publish.ts
packages/expo-cli/src/commands/url.ts
packages/xdl/src/Project.ts

- Splitting up the monolith Project module and rearranging legacy code so it's easier to ensure people don't accidentally start using it. All of the `expo build` code will be in a legacy state as soon as managed EAS is working, moving it to expo-cli will ensure other packages don't pull it in and use it.
- Easier to optimize expo-cli when it uses xdl less since xdl is bundled with gulp and has a bunch of features that are harder to minimize.
- follow up #3164
- Move `getLatestReleaseAsync`, `findReusableBuildAsync `, `getBuildStatusAsync`, `startBuildAsync` to expo-cli

Move legacy build methods to expo-cli

---

packages/webpack-config/src/plugins/PwaManifestWebpackPlugin.ts
packages/webpack-config/src/webpack.config.ts

- fix https://github.com/expo/expo-cli/issues/3089
- Following https://docs.expo.io/guides/progressive-web-apps/#manifestjson should work as expected:
- only one manifest.json tag will be in the `web-build/index.html` (a duplicate will not be added).
- Using `/manifest.json` won't break custom `manifest.json` file resolution. The file will now resolve relative to the user's static folder rather than to their computer.
- Standard behavior continues to work:
- In a project without a `web/` folder, `expo build:web` will generate a `web-build/manifest.json` and inject a single manifest.json tag into the head of the generated index.html.

[webpack] Fixed support for disabling automatic manifest.json tag injection

---

packages/config-plugins/src/plugins/static-plugins.ts

In EAS build, the debug error messages are always shown. If the legacy built-in plugins aren't installed they log massive error messages (that are expected).
If a plugin with a fallback fails to resolve (like `expo-ads-admob`), it'll log a one-liner:
```
Could not find plugin "expo-ads-admob"
```
Instead of the current:
```
Error resolving plugin "expo-ads-admob" Error: Cannot find module 'expo-ads-admob'
Require stack:
- /Users/evanbacon/Documents/GitHub/lab/yolo3/noop.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
at resolveFileName (/Users/evanbacon/Documents/GitHub/cli/node_modules/resolve-from/index.js:29:39)
at resolveFrom (/Users/evanbacon/Documents/GitHub/cli/node_modules/resolve-from/index.js:43:9)
at Object.module.exports [as default] …
```

[expo-cli][prebuild] Clean up debug error messages

---

packages/webpack-config/web-default/index.html

Fixed the screen height in the web when the statusBar is transparent. Before this change, in the web was displayed an extra white space in the bottom of the screen.
It works perfectly with react-navigation bottom tabs and header, and also with SafeArea component:
Landscape mode:
In iPhone 6/7/8 works normally:

Update web index.html height style

---

packages/expo-cli/src/commands/export.ts

- seems like this went missing at some point.
- `expo export -c` prints:
```
Your JavaScript transform cache is empty, rebuilding (this may take a minute).
```
and uses any changes to your babel config.

Added clear flag to expo export

---

packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/TerminalUI.ts

Attempt to make startup logs more readable, and tie them closer to the other logs in the CLI
- "Expo DevTools" -> "Developer tools"
- Group developer tools commands (d, shift+d) with other commands under the QR code. This is because the QR code often shifts all the logs up a lot, many users could end up missing them.
- Remove random colors.
- Move QR URL to under the QR and add some message.
- `shift+d` to toggle the developer tools

[expo cli] redesign startup logs

---

packages/expo-cli/src/exit.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/start/startAsync.ts
packages/xdl/src/start/startDevServerAsync.ts

- Server stopping is slow, verbose, and seems to be only closing the new dev server by accident.
- Save dev server instance and stop it manually.
- Parallelize stopping tasks.
- Use a spinner to indicate the entire stopping task.
- `expod start` then stop it with `ctrl+c`
- should only see spinner
- `expod start --tunnel --web` then stop it with `ctrl+c`
- spinner shouldn't be interrupted by webpack log

[expo-cli] Improve server stopping

---

packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/__tests__/Target-test.ts
packages/config-plugins/src/ios/__tests__/fixtures/testproject-2.xcscheme

https://exponent-internal.slack.com/archives/C010FFEQF0A/p1611929974023600
There are iOS projects that have multiple `BuildActionEntries` defined in .xcscheme. Previously, we would take the first entry and use `BlueprintName` as the target name. Unfortunately, this is not correct behavior. The application target is not always the first entry but looking for it is quite simple. Its buildable name ends with `.app`.
Instead of taking the first entry, I added a `.find` that looks for an entry ending with `.app`. 
- Tested against the project from Slack.
- Added unit test.
Bump @expo/config-plugins in eas-cli.

[config-plugins] fix detecting application target

---

packages/config/src/Config.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/xdl/src/BundleIdentifier.ts
packages/xdl/src/Simulator.ts

This is the "v0" version of the dev client simulator flow for iOS. In this version you can open an app in its dev client in the iOS simulator, provided that the dev client has already been built and installed to the device. The v1 version will also build the app and install it on the device.
We're currently splitting up XDL and making it lighter. However, the existing simulator functionality is in included in the `Simulator` module of XDL. It depends on many XDL modules, including `UrlUtils`, `Versions`, `Logger`, `UserSettings`, etc. making it difficult to extract to a separate package until these modules have been moved out. Additionally, Expo Dev Tools depends on the `Simulator` module, so it can't be moved to `expo-cli` itself, as of now.
For this reason, I've added the dev client …

[xdl] Allow dev client apps to be launched in the iOS simulator

---

packages/config-plugins/src/android/Paths.ts
packages/config-plugins/src/ios/Paths.ts

- faster
- iOS glob 
- 6.428ms -> 4.840ms
- 2.613ms -> 1.488ms

Improve native globs

---

packages/expo-cli/src/commands/utils/typescript/resolveModules.ts
packages/expo-cli/src/log.ts

- Make it easier to debug the startup speed
- Added `EXPO_PROFILE` which enables the printing of `console.time` and `console.timeEnd` statements.
`EXPO_PROFILE=true expo start` should print `queryFirstProjectTypeScriptFileAsync: XXXms`

[expo-cli] Added profiling

---

packages/config-plugins/src/ios/BuildScheme.ts
packages/config-plugins/src/ios/Scheme.ts
packages/config-plugins/src/ios/__tests__/BuildScheme-test.ts
packages/config-plugins/src/ios/index.ts

Derived from https://github.com/expo/expo-cli/pull/3222.
- I renamed `Target` to `BuildScheme`.
- I moved `getSchemesFromXcodeproj` from `Scheme` to `BuildScheme`.
Let's see if CI passes.
Bump `@expo/config-plugins` in EAS CLI and refactor update calls.

[config-plugins] extract build scheme functions to separate module

---

packages/metro-config/src/ExpoMetroConfig.ts

If a project uses the default expo/metro-config in their metro.config.js, a giant React logo is shown when running `expo start`. 
- use a `metro.config.js` in a project, run `expo start` no React logo should show.
- run `npx react-native start` the React logo should still show.

Remove default metro logger from default metro config

---

packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/installExitHooks.ts
packages/xdl/src/Project.ts
packages/xdl/src/start/startAsync.ts

- Delete `Project.stopWebOnly`.
- Move exit.ts to the start folder.
- moved from https://github.com/expo/expo-cli/pull/3230
- `expod start:web` then stopping should be slower and log correctly.

[expo-cli] Combine stop methods for web and native

---

packages/next-adapter/package.json
yarn.lock

next.js ships its own types since v9, and anyways `@types/next` should not be installed in projects using Expo automatically.
I have a project that got into a funky state where it was using `@types/next` 8.x which imports types from `@types/next-server`. However the `@types/next-server` version was a higher version using just the "stub" module meaning its deprecated, and because of this `tsc` was failing completely.
I think ideally we'd be able to drop @types/next entirely since it is deprecated, however expo dev-tools is using an older 8.x version, so we need this to satisfy builds.
I've also added `@types/node-fetch` so that if/when `@types/next` is dropped, builds will continue to work.
* Create a project using next-adapter, and use `@types/next` 8.x and `types/next-server` 9.x
* Try …

[next-adapter]: Move @types/next to devDependencies

---

packages/config/src/Config.ts
packages/config/src/isLegacyImportsEnabled.ts
packages/dev-server/src/MetroDevServer.ts
packages/expo-cli/package.json
packages/expo-cli/src/commands/export.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/upgrade.ts
packages/expo-cli/src/commands/utils/deprecatedExtensionWarnings.ts
packages/expo-cli/src/urlOpts.ts
packages/metro-config/package.json
packages/metro-config/src/ExpoMetroConfig.ts
packages/metro-config/src/__tests__/ExpoMetroConfig-test.ts
packages/metro-config/src/__tests__/__snapshots__/ExpoMetroConfig-test.ts.snap
packages/xdl/src/Env.ts
packages/xdl/src/project/exportAppAsync.ts
packages/xdl/src/project/getPublishExpConfigAsync.ts
packages/xdl/src/project/publishAsync.ts
packages/xdl/src/start/startDevServerAsync.ts
packages/xdl/src/start/startLegacyReactNativeServerAsync.ts

- Consolidate all logic for determining which target to use, this was all over the place before but should be much easier to follow now.
- Create a method to determine if .expo extensions are deprecated in the user's version of Expo or not. 
- If the user doesn't have expo installed or an sdk version, .expo will be disabled.
- If `EXPO_LEGACY_IMPORTS` is enabled, then managed could be used. 
- If the SDK <= 40 then managed could be used.
- Add an aggressive warning on `expo start` if any project files are using the `.expo` extension. Adds some time to startup.
- Add a more aggressive warning on `expo upgrade` if any project files or node modules are using the `.expo` extension.
- To test how this works on the unreleased SDK 41, you can lower the cutoff version in …

[expo-cli][start] deprecate .expo extension for start command

---

packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/__tests__/parseStartOptions-test.ts
packages/expo-cli/src/commands/start/openDevTools.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts
packages/expo-cli/src/commands/start/validateDependenciesVersions.ts

Start command is really large and confusing for a script that mostly just starts an https server. This PR aims to simplify the args parsing, merge `start` and `start:web`, reuse types, add more strict typing, and add more tests.
- split up the start command file.
- merge `start:web` logic into `start`.
- move args parsing into it's own file and reuse some commander logic to simplify the amount of steps.
- add tests to the remaining ambiguous functionality of start args.
- add more comments.
- unit tests should cover most functionality changes related to args
- test that start works as expected
- test start:web stops correctly
- test `expo start --lan --localhost --tunnel --host lan` throws an error

[expo-cli] refactor and test start command

---

packages/expo-cli/src/commands/utils/deprecatedExtensionWarnings.ts

- discussed with @brentvatne, it doesn't make a lot of sense in the upgrade command.

remove expo extensions prompt in expo upgrade

---

packages/config-plugins/src/plugins/unversioned/expo-updates.ts

- Passes the expo username to the versioned plugin if it exists, this allows for the expo-updates plugin to be agnostic of the Expo user management (expo/xdl).  https://github.com/expo/expo/pull/11981

[config-plugins] Pass updates props to plugin

---

packages/expo-cli/src/commands/utils/typescript/__tests__/updateTSConfig-test.ts
packages/expo-cli/src/commands/utils/typescript/updateTSConfig.ts

- resolves https://github.com/expo/expo-cli/issues/3220
- instead of rewriting the extends value, we'll only add it.

Make TSConfig less strict by default

---

packages/config-plugins/src/ios/Entitlements.ts
packages/config-plugins/src/plugins/__tests__/__snapshots__/expo-plugins-test.ts.snap
packages/config-plugins/src/plugins/expo-plugins.ts
packages/config-plugins/src/plugins/unversioned/expo-document-picker.ts

- https://github.com/expo/expo/pull/11977
- this will get disabled when someone uses the versioned copy

Added unversioned document picker plugin

---

packages/config-plugins/README.md
packages/config-plugins/src/plugins/static-plugins.ts
packages/config-plugins/src/plugins/unversioned/expo-ads-admob.ts
packages/config-plugins/src/plugins/unversioned/expo-apple-authentication.ts
packages/config-plugins/src/plugins/unversioned/expo-branch.ts
packages/config-plugins/src/plugins/unversioned/expo-document-picker.ts
packages/config-plugins/src/plugins/unversioned/expo-facebook.ts
packages/config-plugins/src/plugins/unversioned/expo-notifications.ts
packages/config-plugins/src/plugins/unversioned/expo-splash-screen.ts
packages/config-plugins/src/plugins/unversioned/expo-updates.ts
packages/expo-cli/src/commands/eject/configureProjectAsync.ts

The error output that is generated in EAS build (EXPO_DEBUG) when running `expo prebuild` is very verbose and concerning. Errors are generated by auto plugins that aren't configured to support config plugins yet (older versions, support not added yet). Since these packages are managed by Expo, it seems safe to assume that they'll be built properly.
Just for the sake of debugging, I've added `EXPO_CONFIG_PLUGIN_VERBOSE_ERRORS` which can be enabled to debug all of the errors. This **should not** be enabled in EAS build.
- `EXPO_DEBUG=1 expo prebuild --no-install` in NCL should produce no errors.
- `EXPO_CONFIG_PLUGIN_VERBOSE_ERRORS=1 expo prebuild --no-install` in NCL should show all default plugin resolution errors.

Added system for hiding legacy plugin errors

---

packages/xdl/package.json
yarn.lock

Our current version of node-forge is flagged by npm as a high risk security vulnerability due to prototype pollution. In reality, this is not actually impacting us at all due to how we use the library, but npm will still warn users when they install expo-cli. node-forge@0.10.0 is the first version that fixes this (it's also the latest version at the time of writing). 
Advisory link: https://npmjs.com/advisories/1561 
Bump the version. As far as I can tell we are not impacted by breaking changes.
I'm not familiar with how to test this code.

[xdl] Update node-forge

---

packages/expo-cli/src/commands/publish.ts

- No longer needed in SDK 41 since the target will only dictate the assets, and the warning is in regards to the bundling (i.e. .expo file extensions).
- Also show the SDK version if it's defined
- Improve logged bullets
- projectDir -> projectRoot

[publish] silence workflow warning in 41

---

packages/config-plugins/src/android/Paths.ts
packages/expo-cli/src/commands/eject/clearNativeFolder.ts
packages/expo-cli/src/commands/eject/createNativeProjectsFromTemplateAsync.ts
packages/expo-cli/src/commands/eject/ejectAsync.ts

- help prevent basic errors like this https://github.com/expo/expo-cli/issues/3116
- Sometimes a user will run `expo eject` then git revert the native changes, effectively leaving the native ios, and android folders in place. 
- Check for some core native files in both ios and android on `expo eject`. Prompt to properly clear the malformed projects before prebuilding the project. 
- This prompt runs after the git prompt.
- In non interactive mode, the malformed projects are cleared automatically.
- in a managed project: `expo eject` -- ensure the malformed prompt isn't shown for standard managed projects.
- in a bare project:
- `rm -rf ios/yourapp/AppDelegate.m`
- `expo eject` -- should prompt to clear the native ios folder
- pressing n should proceed then fail.
- pressing enter or y will …

[eject] Added prompt to clear malformed projects

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/eject/updatePackageJson.ts
packages/expo-cli/src/commands/utils/__tests__/isModuleSymlinked-test.ts
packages/expo-cli/src/commands/utils/isModuleSymlinked.ts
yarn.lock

- Running `expo prebuild` in `expo/apps/native-component-list` doesn't work because it overwrites the `expo-updates` package with a version that isn't symlinked, then it runs the build command which effectively breaks the build. 
- This PR checks to ensure each package that's about to be overwritten is symlinked to ensure custom versions of `'react', 'react-native-unimodules', 'react-native', 'expo-updates'` can still be used.
- Removes the weird logic added to only switch RN versions when the installed version has `expo` in the name. 
- Added unit tests for the new method.
- Running `expo prebuild` in NCL logs:
- `› Using symlinked react-native-unimodules, react-native, expo-updates instead of recommended version(s).`
- The `package.json` also is not modified.
- Running `expo prebuild` …

[prebuild] Skip overwriting modules that are symlinked

---

packages/expo-cli/src/commands/start/TerminalUI.ts

The newline before the help prompt on a clear screen was bothering me a bit. One solution is to remove the newline. Another alternative would be to add a newline after it too. I opted for the former, but could be convinced. Also, added a newline after the full help output because it looked a bit off to me without it.
(you probably need to click on these to see)
Run `expo start` and play with terminal UI to re-create the scenarios from screenshots.

[cli] Newline after full log output and skip newline before help output

---

packages/config-plugins/src/ios/utils/Xcodeproj.ts

finding target fails for target myapp-staging in https://github.com/brentvatne/myapp/blob/master/ios/myapp.xcodeproj/project.pbxproj
check case with `""`
Tested by temporary substituting value in one of the fixtures (I don't think it makes sense to add a separate test for that)

[config-plugins] Support quote marks in target name in pbxproj

---

packages/config-plugins/src/android/EasBuild.ts
packages/config-plugins/src/android/Updates.ts
packages/config-plugins/src/ios/Updates.ts

incorrect behavior on windows when configuring project for eas
https://forums.expo.io/t/eas-build-configure-on-windows-minor-problems/49015/3
- handle CRLF line ending with `.replace(/\r\n/g, '\n')`
- use posix separator on windows `.replace(/\\/g, '/')` 
- remove JSON.stringify (it converted path `a\b\c` into `"a\\b\\c\\"`)
Tested only on linux, implemented based on a diff from a post on the forum linked above

[config-plugins] eas build:configure fixes for windows

---

packages/expo-cli/src/exp.ts
packages/expo-cli/src/utils/__tests__/matchFileNameOrURLFromStackTrace-test.ts
packages/expo-cli/src/utils/matchFileNameOrURLFromStackTrace.ts
packages/metro-config/src/ExpoMetroConfig.ts

- In the client, Metro collapses some irrelevant stack traces in order to make warnings/errors easier to use. 
- When expo-cli prints the stack trace in the terminal, it only skips `/react-native\/.*YellowBox.js/` (with no way to ever see these traces).
- This PR, reuses the regex to filter stack trace files in the client with the terminal so results are much closer and more useable.
- export regex list from `@expo/metro-config`.
- extract file names from stack traces and filter them like Metro bundler.
- omit collapsed frames in regular development, and show them with `EXPO_DEBUG=1`.
- updated call sites regex to match against fast refresh changes better.
For reference, this is what the client is showing:
- Added unit tests

[expo cli] unify terminal stack trace logs

---

packages/metro-config/src/ExpoMetroConfig.ts

- minimize the differences between a JS bundle generated with expo-cli and one [generated with RN CLI](https://github.com/react-native-community/cli/blob/760708fc3216aee565f59877a103a7e35df2d77d/packages/cli/src/tools/loadMetroConfig.ts#L119).

Use relative asset registry path

---

packages/dev-server/src/MetroDevServer.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts
packages/xdl/src/Project.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/start/startAsync.ts
packages/xdl/src/start/startDevServerAsync.ts

- Add the ability to open the dev menu, reload an experience, and toggle element inspector, etc. from the CLI. This feature will only work after the new client is released with https://github.com/expo/expo/pull/12151 https://github.com/expo/expo/pull/12172 merged
- resolves https://github.com/expo/expo-cli/issues/160
- Added Terminal UI commands (version gated to SDK 41):
- `r` to reload any connected apps
- `m` to open the dev menu in the client
- `shift+m` to show a list of extra commands inspect elements, toggle perf monitor, reload, and open menu.
- Removed the ability to restart the bundler ('r', 'shift+r') from Terminal UI.
- "more tools" is disabled in "dev client" because there currently is no way to determine what commands are available on the native device, `reload`, and …

[expo cli] Added socket controls

---

packages/xdl/src/project/Doctor.ts

This may have helped slightly to debug https://github.com/expo/expo/issues/12145
Enable the `exp.host` domain. It was disabled in https://github.com/expo/expo-cli/pull/2474 but now that the check is only run on `expo doctor` and a failure just prints a warning, I think it's fine to leave it enabled even if it is slightly flakey.
`yarn expo doctor`

[doctor] Re-enable checking reachability of exp.host domain

---

packages/expo-cli/src/commands/start/TerminalUI.ts

```
// Prevent terminal UI from accepting commands while the process is closing.
// Without this, fast typers will close the server then start typing their
// next command and have a bunch of unrelated things pop up.
```
- `expo start --ios` (wait until a device connects otherwise the server closes instantly)
- `ctrl+c`, then spam the `d` key, the dev menu should not open, when the server closes the history should now be in the output i.e. `$ dddd`

[expo-cli] Pause interactions after stopping

---

packages/expo-cli/src/commands/eject/__tests__/updatePackageJson-test.ts
packages/expo-cli/src/commands/eject/createNativeProjectsFromTemplateAsync.ts
packages/expo-cli/src/commands/eject/prebuildAsync.ts
packages/expo-cli/src/commands/eject/updatePackageJson.ts
packages/expo-cli/src/commands/prebuild.ts

We need a way to preserve react-native version when building on EAS
- add param to `expo prebuild`
- use comma separated list because variadic params are only supported in newer commander and updating commander version would break a lot of hacks we are using in cli
`expo prebuild`
add tests

[expo-cli] skip updating dependencies in package.json in `expo prebuild`

---

packages/expo-cli/src/commands/index.ts
packages/expo-cli/src/commands/run/buildAndroidClientAsync.ts
packages/expo-cli/src/commands/run/index.ts
packages/xdl/src/Android.ts

This is going to be the v1 of the emulator flow for Android dev client. The command allows building, installing and launching the dev client app on Android.
Launch with `expod run --platform android`.
TODO:
- Create an app
npx crna -t with-development-client my-dev-client-app
cd my-dev-client-app
- Uncomment this line in `android/gradle.properties`: `# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8`
- Build and run it
expod run:android

Add a command to build and run on Android

---

packages/expo-cli/src/commands/eject/configureProjectAsync.ts

- https://linear.app/expo/issue/ENG-393/set-skadnetwork-ids-for-expo-facebook-expo-ads-facebook-and-expo-admob

add expo-ads-facebook to list of auto plugins

---

packages/expo-cli/src/exp.ts

Fixes https://linear.app/expo/issue/ENG-560/hide-expo-cli-update-message-on-eas-build
- There was already a similar check - the `skipUpdateCheck` variable, but it was never set to true. I verified that by looking for all `asyncAction` occurrences in the code.
- I changed the condition so we check the `EAS_BUILD` env variable now.
I didn't test it yet. We'll do it when we update expo-cli on EAS Build and release a new expo-cli version.

[ENG-560][expo-cli] skip update check when EAS_BUILD=1

---

packages/metro-config/src/ExpoMetroConfig.ts

Improved debugging experience.
```log
expo-permissions is now deprecated — the functionality has been moved to other expo packages that directly use these permissions (e.g. expo-location, expo-camera). The package will be removed in the upcoming releases.
at node_modules/expo-permissions/build/Permissions.js:48:7 in askAsync
at node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
at node_modules/regenerator-runtime/runtime.js:293:29 in invoke
at node_modules/regenerator-runtime/runtime.js:63:36 in tryCatch
at node_modules/regenerator-runtime/runtime.js:154:27 in invoke
at node_modules/regenerator-runtime/runtime.js:189:16 in PromiseImpl$argument_0
at node_modules/react-native/node_modules/promise/setimmediate/core.js:45:6 in tryCallTwo
at …
```

Mute regenerator runtime and setimmediate traces

---

packages/xdl/src/SimControlLogs.ts
packages/xdl/src/Simulator.ts

- https://exponent-internal.slack.com/archives/C5ERY0TAR/p1615864760007800
- Automatically attach logger when an app is launched from the terminal. Only attach when using devClient.
- `expo start --dev-client --ios`
```tsx
import * as React from "react";
import { View, Text } from "react-native";
import { usePermissions, CAMERA } from 'expo-permissions'
export default function App() {
// Force a crash
usePermissions(CAMERA, { ask: true })
return (
<View />
);
}
``` 
- `expo start --ios` no extra logs should be shown.

Added debug simctl logger

---

packages/expo-cli/src/commands/prebuild.ts

If you install an auto plugin like `expo-camera` you should be able to quickly apply the plugin changes without having to fully reset everything. This PR proposes that we add a flag like `--clean`. When `--clean` is provided, the native folders will be cleared, otherwise the config plugin changes will just be applied normally. This could lead to projects getting in weird states because some plugins aren't being cleaned up, but we can solve that by just running `expo prebuild --clean`. 
This optimizes for adding new packages more than adding/removing. With this, we can instruct managed v2 users to install packages like:
```
yarn add expo-camera
```
Expo Go users don't need to do anything else. Users with custom clients should continue.
> ⚠️ For users with managed native projects only! …

Added clean flag to prebuild

---

packages/config-plugins/README.md
packages/config-plugins/src/Plugin.types.ts
packages/config-plugins/src/android/Properties.ts
packages/config-plugins/src/android/index.ts
packages/config-plugins/src/index.ts
packages/config-plugins/src/plugins/__tests__/android-plugins-test.ts
packages/config-plugins/src/plugins/__tests__/expo-plugins-test.ts
packages/config-plugins/src/plugins/__tests__/fixtures/react-native-project.ts
packages/config-plugins/src/plugins/android-plugins.ts
packages/config-plugins/src/plugins/compiler-plugins.ts

- We use a custom version in NCL https://github.com/expo/expo/blob/49cdec480538ac229ee91c600c7a2f6312e11176/apps/native-component-list/app.config.js#L22-L27
- It may be useful for other packages like `react-native-webrtc` https://github.com/react-native-webrtc/react-native-webrtc/blob/master/Documentation/AndroidInstallation.md#fatal-exception-javalangunsatisfiedlinkerror and detox https://github.com/expo/examples/blob/5e0ac1a28139a347ab6e4bac551981391da6e0b9/with-detox/app.json#L19.
- Created a `.properties` file parser that supports comments. 
- Added a new base mod `mods.android.gradleProperties` and a helper method `withGradleProperties`
- Created an e2e test for the mod.

Added withGradleProperties mod

---

packages/expo-cli/src/commands/eject/updatePackageJson.ts

If a script is using a dev client script like `expo start --dev-client` then don't replace it on eject.

[eject] preserve expo dev client scripts

---

packages/config-plugins/package.json
packages/config/package.json
packages/expo-cli/package.json
packages/image-utils/package.json
packages/metro-config/package.json
packages/webpack-config/package.json
packages/xdl/package.json
yarn.lock

Current used version of getenv (0.7.0) in metro-config does not include any type of license. Starting v1.0.0 MIT license is included in the package.
Run `npm install getenv@1.0.0` to update `package.json` files in all packages. Run `yarn` to generate new lockfile and `yarn build` to verify local build.

improvement: updated getenv dependencies to 1.0.0

---

.github/workflows/test.yml
packages/config/src/__tests__/ConfigParsing-test.ts
packages/expo-cli/e2e/__tests__/init-test.ts
packages/expo-cli/src/commands/init.ts

[New repositiories on GitHub use `main` as the default branch name](https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name)
Added `git branch -M main` after the initial commit in `expo init`.
Enabled the previously disabled end-to-end test (now with `--no-install` so it won't time out like before, which was the original reason for disabling it, IIRC). Added an assertion that checks that the branch name after running `expo init` is correct.
Additionally, tested running `expo init` manually and checked the branch name using `git status` once finished.

[expo-cli] Change template project default branch from master to main

---

packages/xdl/src/Versions.ts

`facebookReactNativeVersionToExpoVersionAsync` was mapping `react-native` versions to SDK versions that were added to the versions endpoint, but not yet released. This PR makes it only map to released versions.
Fixes #3288.
Used `releasedSdkVersionsAsync` to get applicable versions.
Tested briefly in the `node` console, following statements both printed '40.0.0' after the fix was done:
```
require('xdl').Versions.facebookReactNativeVersionToExpoVersionAsync('0.63.2').then(console.log)
require('xdl').Versions.facebookReactNativeVersionToExpoVersionAsync('0.63.4').then(console.log)
```

[xdl] facebookReactNativeVersionToExpoVersionAsync: only map to released versions

---

packages/expo-cli/src/commands/eject/clearNativeFolder.ts
packages/expo-cli/src/schemes.ts

a user with just ios or just android should still be able to use the dev client bundler.

Allow single platform for dev client schemes

---

packages/config-plugins/package.json
packages/plist/package.json
packages/xdl/package.json
yarn.lock

- `xdl` dependended on `xmldom` and `xcode` but was not using those dependencies anymore
- `@expo/config-plugins` and `@expo/configure-splash-screen` were using different versions of `xcode`
- `xmldom` 0.1.x gets flagged by `npm audit` (https://github.com/expo/expo-cli/issues/3296)
Fixes https://github.com/expo/expo-cli/issues/3296.
Removed unused dependencies from `xdl`. Updated dependencies in `@expo/config-plugins` and `@expo/plist`.
--

Update xmldom and xcode dependencies

---

packages/expo-cli/src/commands/run/ios/developmentCodeSigning.ts
packages/xdl/src/UserSettings.ts

Sort the signing info by “last selected”, not sure if there’s a native way to get the user’s preferred signing identity but this will at least make it so developers who have more than one team (which I think is most devs cuz you'll have a paid team and a personal team) will be able to just mash the enter key to sign the app.
For example, when signing a new app, my list looks like this:
```log
? Development team for signing the app › - Use arrow-keys. Return to submit.
❯   650 Industries, Inc. (XXXXQTF339) - Apple Development: Evan Bacon (XXXXMDXG4H)
Evan Bacon (XXXXR9NU86) - Apple Development: bacon@expo.io (XXXX2U6XNQ)
Evan Bacon (XXXXRJ5UTD) - Apple Development: Evan Bacon (XXXXNJ89KU)
Evan Bacon (XXXX8G34TX) - Apple Development: evanjbacon@gmail.com (XXXX42893T)
```
I almost always …

Sort code signing identities by last selected

---

packages/expo-cli/src/commands/eject/installNodeDependenciesAsync.ts
packages/expo-cli/src/commands/eject/prebuildAsync.ts
packages/expo-cli/src/commands/eject/writeMetroConfig.ts

- The spinners clash with the debug logs, this PR stops the spinners in EXPO_DEBUG so they don't collide.
- Use CommandError instead of Error to prevent unused stack traces
- Make `Config synced with warnings that should be fixed` yellow instead of red

[eject] fix broken debug spinner

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/run/ios/IOSDeploy.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
yarn.lock

- surface the loading progress, copied files info from ios deploy
- allow for retrying the launch if the connected device is locked
- connect ios device (keep locked)
- `expo run:ios -d` select connected
- at end, notice the installing progress and copied files
- without unlocking the phone press y when prompted if you've unlocked the device, this should loop back to the prompt again.
- unlock phone and press y, this should launch the app on the device and end the process.

Improve deploy logging

---

packages/expo-cli/src/commands/run/ios/resolveDeviceAsync.ts

- Apple's `xctrace` is ridiculously slow (1.7s on my machine). To add more transparency to why the CLI is slow to build, I added a temporary loader which hides after it completes.
- `expo run:ios --device`
- `expo run:ios --device foobar`

Added spinner for device searching

---

packages/expo-cli/src/commands/eject/writeMetroConfig.ts

- In SDK 41 the default metro config should be extending `expo/metro-config` (`@expo/metro-config` in older SDK versions).
Updated the warning when the config is modified to reflect the new default `metro.config.js`:
```log
⚠️  Skipped Metro config updates:
› Existing Metro config found; not overwriting.
› You will need to extend the default @expo/metro-config in your Metro config.
Learn more: https://docs.expo.io/guides/customizing-metro
```
- Shortened configuration to config to match some other places in the CLI
- Make the warning message a bit more deliberate as this is common behavior.
- `expo prebuild -p android --no-install`
- Modify the `metro.config.js`, repeating step 2 should log the new warning.
- Optionally you can change the project SDK version to 41.0.0

Updated metro config warning to reflect SDK 41 by default.

---

packages/expo-cli/src/commands/run/ios/XcodeBuild.ts
packages/expo-cli/src/commands/run/utils/binaryPlist.ts
packages/expo-cli/src/commands/upload/submission-service/utils/files.ts

Improve cryptic error message
```
/Users/evanbacon/Documents/GitHub/cli/node_modules/bplist-parser/bplistParser.js:44
return callback(err);
^
TypeError: callback is not a function
at ReadFileContext.callback (/Users/evanbacon/Documents/GitHub/cli/node_modules/bplist-parser/bplistParser.js:44:16)
at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13)
```
applied myself more...
- clean expo go from source and rebuild it (☹️), the error should go away at the end

Improve bplist parsing

---

packages/uri-scheme/src/CLI.ts
packages/uri-scheme/src/Ios.ts

Running `npx uri-scheme add ...` in a project with only android or only ios (without specifying a platform) will throw an error because the CLI defaults to both platforms. This change will disable auto platforms that don't exist.
- `expo prebuild -p android` - creates android only
- `npx uri-scheme add somn` - won't throw an error now, silently just skips ios

[uri-scheme] Improve running in a project with single platform

---

packages/expo-cli/src/commands/run/android/Gradle.ts
packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/android/spawnGradleAsync.ts
packages/expo-cli/src/commands/run/index.ts
packages/xdl/src/Android.ts
packages/xdl/src/utils/downloadApkAsync.ts

- `run:android` currently just opens the Expo Go app after it finishes building (and on an unrelated device no less). This PR adds the ability to install, and open an arbitrary APK, then open it. 
- Also abstracted some functionality out of `Android` since it's getting large. 
- Added a generalized caching system for reading Android device properties.
- `expo run:android` should work as expected, building an APK then installing _that_ APK and opening it on the selected device.

Run built APK on device

---

packages/expo-codemod/README.md
packages/expo-codemod/package.json
packages/expo-codemod/src/transforms/__tests__/sdk41-async-storage-test.ts
packages/expo-codemod/src/transforms/sdk33-imports.ts
packages/expo-codemod/src/transforms/sdk37-imports.ts
packages/expo-codemod/src/transforms/sdk41-async-storage.ts
packages/xdl/src/project/Doctor.ts
yarn.lock

`@react-native-community/async-storage` has been renamed to `@react-native-async-storage/async-storage`. The old `@react-native-community/async-storage` package will not work with SDK 41. 
- Added the codemod `sdk41-async-storage`.
- Added a check in `expo doctor`.
- Unit tests for codemod.
- Manually tested the doctor command on a project with/without this dependency.

Add migration from @react-native-community/async-storage

---

packages/config-plugins/src/ios/Google.ts
packages/config-plugins/src/ios/Maps.ts
packages/config-plugins/src/ios/__tests__/Google-test.ts
packages/config-plugins/src/ios/__tests__/Maps-test.ts
packages/config-plugins/src/ios/__tests__/__snapshots__/Maps-test.ts.snap
packages/config-plugins/src/ios/__tests__/fixtures/AppDelegate.ts
packages/config-plugins/src/ios/__tests__/fixtures/Podfile.ts
packages/config-plugins/src/ios/index.ts
packages/config-plugins/src/plugins/__tests__/__snapshots__/expo-plugins-test.ts.snap
packages/config-plugins/src/plugins/__tests__/expo-plugins-test.ts
packages/config-plugins/src/plugins/expo-plugins.ts
packages/config-plugins/src/plugins/unversioned/react-native-maps.ts
packages/config-plugins/src/utils/generateCode.ts
packages/config-plugins/src/utils/resolvePackageRootFolder.ts

- auto configure react-native-maps upon ejecting.
- created an unversioned plugin for `react-native-maps` namespace which:
- adds `pod 'react-native-google-maps', path: '../node_modules/react-native-maps'` to the podfile if `ios.config.googleMapsApiKey` is defined.
- adds the following blocks to the AppDelegate.m when Google Maps is enabled:
```objc
// @generated begin react-native-maps-import - expo prebuild (DO NOT MODIFY) sync-f2f83125c99c0d74b42a2612947510c4e08c423a
#if __has_include(<GoogleMaps/GoogleMaps.h>)
#import <GoogleMaps/GoogleMaps.h>
#endif
// @generated end react-native-maps-import
...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
// @generated begin react-native-maps-init - expo prebuild (DO NOT MODIFY) …
```

[config-plugins] Created unversioned react-native-maps plugin

---

packages/xdl/src/Android.ts

Emulate iOS functionality of bringing the window to the front when activated.
- `expo start --android` -- activates window
- `shift+a` -- select new device, that window should be activated instead of the other window.

Activate android emulator window

---

packages/expo-cli/src/commands/eject/ConfigValidation.ts
packages/expo-cli/src/commands/eject/__tests__/ConfigValidation-test.ts

- fix https://github.com/expo/expo-cli/issues/3315
- allow `.` and `-` at any position in the bundle id.
- added unit tests
- tested valid options in xcode

Improve bundle identifier regex

---

packages/config-plugins/src/ios/utils/Xcodeproj.ts

- fix https://github.com/expo/expo-cli/issues/3341
- improve algo for getting the ios product name to name the entitlements file. 
- `expo prebuild` a project with `ios.bundleIdentifier: com.bacon.001` -> name should not be `1` unless the project's name is `1`

fix product name getter

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/uri-scheme/src/URIScheme.ts
packages/xdl/src/Android.ts

- only clear logs when selecting a native device and not when simply opening on a device.
- remove "attempting" and "maybe" language from messages.

clean up logging messages

---

packages/config-plugins/src/ios/ProvisioningProfile.ts
packages/config-plugins/src/ios/__tests__/ProvisioningProfile-test.ts

Current error in that case prints
```
Build failed: (intermediate value)(intermediate value)(intermediate value) is not iterable
```
Send better error message
add test case

[config-plugins] Throw better error message when target does not exist

---

packages/xdl/package.json
yarn.lock

XDL had a few dev dependencies missing from `package.json` that happened to work because they were dependencies in other Expo CLI packages. Additionally there were a few dependencies that were no longer used.
Ran `npx depcheck` to find these and double checked with search to find out how the dependencies were used.
N/A

[xdl] Fix missing/extraneous dependencies

---

packages/expo-cli/src/commands/run/ios/resolveDeviceAsync.ts
packages/xdl/src/SimControl.ts
packages/xdl/src/Simulator.ts
packages/xdl/src/Xcode.ts
packages/xdl/src/utils/profileMethod.ts

Checking if xcode was installed took too long so we often skipped it, but this led to cryptic and annoying errors for beginners. This PR changes spawnAsync to execSync which improves the time from `1.705s -> 273.583ms`.  Now we can use perform the xcode check more liberally.

Improve no xcode warnings

---

packages/xdl/src/User.ts

- Required for bare projects to embed the `id` property for AuthSession and Notifications.
- If the `expo-constants` package has to depend on `xdl` it'll be pretty unfortunate to download, so we should investigate splitting this functionality out of xdl.

Added getUserProjectIdAsync method

---

CHANGELOG.md
packages/config/src/Config.types.ts
packages/webpack-config/src/webpack.config.ts
packages/xdl/src/start/ManifestHandler.ts

This property has been deprecated since 2018 and its use in the SDK was removed here:
https://github.com/expo/expo/commit/2807b0994b0139ecf9e7b3ff7c73de9a15535dce
Searched for all references to `xde` in this repo to verify it's not relied on here either.
Verified that editing an app (refresh) and starting the debugger works both on iOS and Android, with Expo Go 2.18.7.

Remove deprecated property "xde" from the manifest

---

packages/xdl/src/BundleIdentifier.ts

We allow bare projects to not have an `app.json` / app config module, but previously trying to run a project without an `app.json` in dev client resulted in an error.
> Please define "ios.bundleIdentifier" in app.json.
This PR changes this so that when `app.json` exists, but we can detect a bundle identifier from the Xcode project, no error is thrown and we simply use the bundle identifier from the native project.
Created an app using ` npx crna -t with-dev-client`, removed `app.json` and verified that `expod run:ios` works.

[dev-client] Allow running projects without app.json

---

packages/dev-tools/server/graphql/GraphQLSchema.ts
packages/expo-cli/src/exp.ts
packages/xdl/src/Config.ts
packages/xdl/src/DevSession.ts
packages/xdl/src/Sentry.ts
packages/xdl/src/UrlUtils.ts
packages/xdl/src/User.ts
packages/xdl/src/start/ManifestHandler.ts
packages/xdl/src/start/startAsync.ts

- Use `ConnectionStatus` instead. Ran `expo start --offline` and observed that the username was always being surfaced as anonymous.

Remove Config.offline

---

packages/config/__mocks__/os.ts
packages/config/src/Config.ts
packages/config/src/__tests__/ConfigParsing-test.ts
packages/config/src/__tests__/getCurrentFullName-test.ts
packages/config/src/__tests__/getUserState-test.ts
packages/config/src/getCurrentFullName.ts
packages/config/src/getUserState.ts
packages/xdl/src/User.ts

- https://github.com/expo/universe/pull/7311
- Required for auth-session and notifications. This will append `currentFullName` to the manifest when `getConfig` is run with `isPublicConfig: true` (what `expo-constants` does). 
- I've moved the UserSettings logic into `expo/config` for now, we can move it out later if needed.
- Deletes changes introduced in https://github.com/expo/expo-cli/pull/3359
- Added unit tests.
- I've verified that the value `currentFullName` will be overwritten by the server so this shouldn't introduce a breaking change.
- Unless we also add this value to `expo.id`, the auth session and notifications modules will need to be updated to use `currentFullName`.

Added `currentFullName` to the public config

---

packages/expo-cli/src/exp.ts
packages/xdl/src/Config.ts
packages/xdl/src/project/Doctor.ts
packages/xdl/src/start/ngrok.ts

Remove unchanging value and dead code paths
- make `Config.developerTool` static `expo-cli` -- no logic change.
- delete `Config.turtleApi` -- unsure if this breaks anything. Doesn't appear to be in use anywhere.
- delete `Config.validation` -- no logic change.
- move Config.ngrok to the ngrok module -- test: ran expo start --tunnel.

Simplify Config module

---

packages/dev-tools/package.json
packages/next-adapter/package.json
packages/next-adapter/src/withExpo.ts
yarn.lock

Currently `@expo/next-adapter` lists the outdated version of `react-native-web` in the `peerDependencies`.
Also the package uses the deprecated and outdate `@types/next` package:
This PR bumps the `react-native-web` version in  `@expo/next-adapter` dependencies to match the one used in Expo environment - `0.13.12`:
* https://github.com/expo/expo/search?l=JSON&q=react-native-web
It also remove the deprecated and unnecessary Next.js types package and ensures that Next `^9` is used in the workspace. To do that, I had to bump explicit `next` dev dependency in `dev-tools`, otherwise dependency was always resolved to `^8.0.0` which do not includes types and was a miss-match for most of `peerDependencies` listed in other packages.
Currently there is no good types for `NextConfig` - …

[next-adapter] update RNW peer, remove deprecated types

---

packages/expo-cli/src/commands/run/ios/XcodeBuild.ts
packages/expo-cli/src/commands/run/utils/binaryPlist.ts

Building bare expo failed without this.

Support building apps with escaped names

---

packages/expo-cli/src/exp.ts

We don't want to support this in every tool, instead we should consolidate on a single easy-to-understand approach for switching between app configs: `app.config.js`. Developers can use env vars to pick the config to use.
We can keep the behavior of this flag around for a long time so developers can keep using it if it's working well for them, but we won't add support for it to new tools like EAS Build, where developers can use `app.config.js` instead.
So far I only deprecated this in the help description, but we may want to add a warning with a link to a docs page or fyi page with more information about how to use `app.config.js` for this use case.

[cli] Add deprecation message to --config flag

---

packages/xdl/src/project/Doctor.ts

it’s not obvious that `src` is defining the path and might be different for your project, plus the lack of newlines makes it a little harder to read:

[xdl] minor improvements to async-storage error message

---

packages/expo-cli/src/commands/upgrade.ts
packages/package-manager/src/NodePackageManagers.ts

`@react-native-community/async-storage` has been renamed to `@react-native-async-storage/async-storage`. The old `@react-native-community/async-storage` package will not work with SDK 41. 
#3342 added a `expo doctor` check for the old package in dependencies and a codemod to migrate imports to use the new package. This PR makes the `expo upgrade` command to automatically update the dependency in `package.json`.
For SDK 41 or newer, if `@react-native-community/async-storage` exists in dependencies, it will be replaced with the appropriate version of `@react-native-async-storage/async-storage`.
Tested using `EXPO_BETA=1 expod upgrade`:
Result diff:

Handle async storage package rename in upgrade command

---

packages/expo-cli/src/commands/export/exportAppAsync.ts
packages/xdl/src/index.ts

Give more user visibility into bundle sizes in the export command. Reuses the code from expo publish.

print bundle sizes in export

---

packages/expo-cli/src/commands/run/ios/ExpoLogFormatter.ts

Some React packages aren't linked in an expected way, to keep the ios logs looking cleaner we can hard code a list of these common packages (every project has them).

Add known packages to improve tracing

---

packages/expo-cli/src/commands/export.ts

- Almost all build tooling overwrites the output folder on rerun, this makes the functionality inline with that.
- Remove the force flag and overwrite the input folder by default.
- Run `expo export` twice

[export] Force overwriting by default

---

packages/expo-cli/src/commands/run/ios/Podfile.ts
packages/expo-cli/src/commands/utils/CreateApp.ts
packages/package-manager/src/CocoaPodsPackageManager.ts

- Fix regression where pod repo update wasn't being run
- Fix error handling
- Improve logging in Expo CLI
- Pause spinner when installing the cocoapods CLI
- Provide better insight into fixing cocoapods errors

improve cocoapods manager

---

packages/config-plugins/src/android/SplashScreen.ts
packages/config-plugins/src/ios/SplashScreen.ts

Launching `eas build -p ios` for SDK 41 results in the following warning: 
`splash-screen` plugin was enabled only for SDK 39 and 40 (and UNVERSIONED), but not for SDK 41.
I've changed the enabling rules for this plugin to be enabled for any SDK greater than 38 (including UNVERSIONED).
Locally the problem was reproducible via `expo-cli prebuild`.
Launching this with command with this change results with no warning message anymore.

[config-plugins] feat: enable splash screen plugin for any SDK greater than 38

---

packages/expo-cli/src/commands/run/ios/startBundlerAsync.ts

- enable r to reload and m to open the dev menu

Enable socket controls in run:ios and run:android

---

packages/config-plugins/src/android/UserInterfaceStyle.ts
packages/config-plugins/src/android/__tests__/UserInterfaceStyle-test.ts
packages/config-plugins/src/ios/UserInterfaceStyle.ts
packages/config-plugins/src/ios/__tests__/UserInterfaceStyle-test.ts

This is the default behavior in Expo Go and standalone apps built with expo build.
The most reasonable place to change this seemed to be in `getUserInterfaceStyle`, but really anywhere would do.
Run tests.

[config-plugins] Make user interface style default to light if not specified

---

packages/expo-cli/src/commands/publish.ts
packages/xdl/src/__tests__/Project-publishAsync-test.ts
packages/xdl/src/project/publishAsync.ts

We are currently returning the website project page URL without the correct path, i.e. `@username/projectname` instead of `@username/projects/projectname` and it can create a "clawback" if the user's project is named `snacks` or `projects`.
More context here: https://github.com/expo/universe/pull/7331#issuecomment-820683580
Created correct project page URL
Run `expo publish` and check if the URL is correct

[expo-cli][xdl] return correct project page url after expo publish

---

packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/expo-cli/src/commands/run/ios/startBundlerAsync.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts
packages/xdl/src/start/startDevServerAsync.ts
packages/xdl/src/start/startLegacyReactNativeServerAsync.ts

`expo start --dev-client` throws a large error when 8081 is not available, this is often the behavior you'd want for the built-in RN dev menu, but we want to optimize for `expo-dev-menu` which supports multi-ports.

Add port selection to start --dev-client

---

packages/expo-cli/src/commands/utils/maybeBailOnGitStatusAsync.ts

- Skip git status checks in upgrade and eject when EXPO_NO_GIT_STATUS is enabled.

Added a flag to skip git status check

---

packages/xdl/src/BundleIdentifier.ts

Steps to repro:
- Change bundleIdentifier in app.json or Xcode project but not both
- Run a server with expo start --dev-client
- Press i to launch in Simulator.app
- From "Which bundle identifier should we use?" choose the one from Xcode project
- The CLI tries to use the other one
The if-else condition in `configureBundleIdentifierAsync` was flipped, when you chose "from Xcode project" it actually updated the *Xcode project to use the bundle identifier from `app.json`*. This PR corrects this error.
Verified the correct bundle identifier is used after this fix:

Fix running dev client from terminal UI using wrong bundleIdentifier

---

packages/expo-cli/src/commands/run/ios/Podfile.ts
packages/expo-cli/src/commands/utils/CreateApp.ts
packages/package-manager/src/CocoaPodsPackageManager.ts

- CocoaPods CLI often prints error messages to stdout and add some random nonsense to stderr. This PR attempts to match the useful error message and prune out the less useful content.
- This PR also quits the process in `expo run:ios` when pods fail to install.

Improve cocoapods error messages

---

packages/config-plugins/src/ios/BundleIdentifier.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/xdl/src/SimControlLogs.ts
packages/xdl/src/Simulator.ts
packages/xdl/src/Xcode.ts

pressing `i` in terminal UI can take roughly 3-4s in NCL, this PR gets that down to about 3.2s the first time, and 1.2 on subsequent opens.
- cached health checks like xcode installed and xcode version
- cut down on useless duplicate tasks
- resolves ENG-939

Improve ios start up times

---

unlinked-packages/configure-splash-screen/package.json
unlinked-packages/configure-splash-screen/src/xml-manipulation/index.ts
unlinked-packages/configure-splash-screen/yarn.lock

Fixes #3184
The `deep-equal` dependency has been replace by function written using basic JS operations.
I have also inlined two unnecessary variables and lint/prettier applied their formatting changes too.
All test from the `configure-splash-screen` package have been successful on `localhost`. 
CC: @EvanBacon

[configure-splash-screen] remove deep-equal dependency

---

packages/expo-cli/src/commands/doctor/index.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/utils/validateDependenciesVersions.ts

Fixes #3075
Currently project dependencies were only checked on the `start` run, but `doctor` command should do the same.
This PR moves the `validateDependenciesVersionsAsync` to the `/utils` directory and refactors the return type, so `doctor` command have a clue if there were any warnings, and can skip the success message in such case.
I have also changed the `doctor` success message color to green and I have added the emoji to differentiate a bit the messaged in console.
Command changes were tested on `localhost` using the local build of `expo-cli` package.
CC: @brentvatne

[expo-cli] validate project dependencies on `doctor` run

---

package.json
yarn.lock

* https://github.com/atlassian/yarn-deduplicate#duplicated-packages
TL/DR: this script ensures that only the newest packages which matches semver are used in the workspace.
I have committed this to several repos and it has been used in (some major examples): 
* React Native core repo (no `postinstall` hook), 
* React Native website,
* React Native Directory,
* Docusuaurs (for all packages and websites, in repo for several months, no issues).
This PR adds `yarn-deduplicate` to the workspace dependencies and hooks it up into `postinstall` check, before the Expo dependencies validation, to ensure that those checks are run on final lock version.
`yarn build` on the workspace level was successful on `localhost`, let's try CI now.
CC: @brentvatne @EvanBacon

[workspace] deduplicate yarn lock in `postinstall`

---

packages/config-plugins/src/plugins/__tests__/static-plugins-test.ts
packages/config-plugins/src/plugins/static-plugins.ts
packages/config-plugins/src/utils/errors.ts
packages/config-plugins/src/utils/plugin-resolver.ts
packages/config/src/__tests__/getConfig-e2e-test.ts

Make it clearer when an invalid plugin is used that the package may not have an config plugin.
Before/After
Also new

Improve errors when a package doesn't have a valid plugin

---

packages/expo-cli/package.json
packages/osascript/package.json
packages/webpack-config/package.json
unlinked-packages/configure-splash-screen/package.json

Refs https://github.com/expo/expo/pull/12743
At the end of April Node 10 will reach it's End-of-life:
* https://nodejs.org/en/about/releases/
Bump `"node"` engines entries in `package.json` to `>=12`.
`yarn` and `yarn build` executed on the workspace root were successful.

bump minimum Node target to 12

---

unlinked-packages/configure-splash-screen/package.json
unlinked-packages/configure-splash-screen/src/utils/string-utils.ts
unlinked-packages/configure-splash-screen/tsconfig.json
unlinked-packages/configure-splash-screen/yarn.lock

Closes #3185 
Since node 10 will be dropped in expo-cli soon (and already dropped by react-native), i think it's safe to upgrade the `engines` to `>=12` and just removing the `matchAll` polyfill.
tests passed on local

[configure-splash-screen]: remove core-js dependency

---

packages/config-plugins/src/utils/plugin-resolver.ts
packages/expo-cli/src/commands/build/AndroidBuilder.ts
packages/expo-cli/src/commands/build/ios/IOSBuilder.ts
packages/expo-cli/src/commands/eject/ConfigValidation.ts
packages/expo-cli/src/commands/eject/configureProjectAsync.ts
packages/expo-cli/src/commands/eject/ensureConfigAsync.ts
packages/expo-cli/src/commands/fetch/ios.ts
packages/expo-cli/src/commands/install.ts
packages/expo-cli/src/commands/utils/__tests__/autoAddConfigPluginsAsync-test.ts
packages/expo-cli/src/commands/utils/__tests__/validateApplicationId-test.ts
packages/expo-cli/src/commands/utils/autoAddConfigPluginsAsync.ts
packages/expo-cli/src/commands/utils/getOrPromptApplicationId.ts
packages/expo-cli/src/commands/utils/modifyConfigAsync.ts
packages/expo-cli/src/commands/utils/validateApplicationId.ts

1. Make setup guides easier
2. Help migrate people away from auto config plugins. Auto config plugins are bad form and shouldn't really exist since they add unexpected functionality to the project, we added them for easier migration from `expo build` to `eas build`. This will enable people to run `expo install expo-camera` and have `expo-camera` be added to their plugins array.
3. Improve migration. Guides can say "run expo install ... with all of your existing packages to add any existing config plugins". This isn't perfect since a package might need a plugin but not have one setup.
When a user installs packages with `expo install`, the command will check if the newly installed packages have any "valid" config plugins included. 
For sanity purposes we'll only enable this feature with …

[install] add config plugins automatically

---

.github/workflows/test_windows.yml
.prettierrc

Fixes #1260
This PR copies the `test` step from linux CI, and changes the runner to Windows.
Unfortunately GitHub currently do not support multiple runners per workflow:
* https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
Run the CI! 😉 
CC: @brentvatne

[CI] add tests on Windows

---

packages/config/src/Config.ts
packages/expo-cli/src/commands/start.ts

It's possible to hit a somewhat misleading error message if a user runs `expo start` before installing node_modules in a project. Instead we can check to see if expo is installed before running any additional logic
Added a fs check to see if expo is installed in the project or workspace, if not throw an error message that indicates they need to run `yarn / npm install` first
I initially included this in the Config module but realized that it broke a ton of tests, so I put it in front of the start command only - wondering if there's a better way to resolve the tests breaking / if this check is in the right place
- `expo start` in a workspace repo before installing node_modules, note the error message appears, `yarn install` and error should go away
- `expo start` in a project repo before …

[cli] "expo is not installed" error

---

packages/expo-cli/src/commands/export.ts

Follow up for https://github.com/expo/expo-cli/pull/3395/files
This will never return false if `overwrite = true`: https://github.com/expo/expo-cli/blob/a2542a74972ec47815f555e974e45943af888f16/packages/expo-cli/src/commands/utils/CreateApp.ts#L53
removed if statement

[expo-cli] remove dead code

---

packages/expo-cli/src/commands/run/ios/Podfile.ts
packages/expo-cli/src/commands/run/ios/XcodeBuild.ts

- Missing pods folder should trigger a rebuild
- Print logs for easier examination

output logs and clear on pod folder

---

packages/expo-cli/src/commands/install.ts

Make the transition less confusing for users who aren't using eas build

Only auto add plugins if the plugins array is defined or the project is greater than 42

---

packages/expo-cli/src/commands/install.ts
packages/expo-cli/src/commands/upgrade.ts
packages/expo-cli/src/commands/utils/__tests__/bundledNativeModules-test.ts
packages/expo-cli/src/commands/utils/__tests__/validateDependenciesVersions-test.ts
packages/expo-cli/src/commands/utils/bundledNativeModules.ts
packages/expo-cli/src/commands/utils/validateDependenciesVersions.ts

https://linear.app/expo/issue/ENG-806/turn-bundlednativemodulesjson-into-an-api-endpoint
https://www.notion.so/expo/SDK-42-Plan-5bde287ed44349ad8740998123223ed0
> Make bundledNativeModules easier to update by moving it to an API endpoint rather than json file embedded in expo package
- https://github.com/expo/universe/pull/7426 added API endpoint that serves the bundledNativeModules.json from the db (and also another endpoint for syncing the json file with www)
- https://github.com/expo/expo/pull/12760 added the script to sync bundledNativeModules.json with www
This PR makes Expo CLI use the versions of bundled native modules from the API.
- https://github.com/expo/expo-cli/pull/3444/commits/7df8c9aea309adc7f5d3882af8c7ef91b9f9f2b6 adds the function `getBundledNativeModulesAsync` that …

[expo-cli] use bundledNativeModules.json from api

---

packages/expo-cli/src/commands/eject/Github.ts
packages/expo-cli/src/commands/eject/createNativeProjectsFromTemplateAsync.ts
packages/expo-cli/src/commands/eject/prebuildAsync.ts
packages/expo-cli/src/commands/eject/resolveTemplate.ts
packages/expo-cli/src/commands/prebuild.ts
packages/expo-cli/src/utils/extractTemplateAppAsync.ts

Make it easier to test local template modifications. Also add ability to start testing other languages.
- Added `expo prebuild --template [template]` where template can be a local tar file packed with npm pack, or a github URL where the root of the repo is a template (this can be scaled to support subpaths).
- Run `npm pack` in the `expo/templates/expo-template-bare-minimum/` project. Run `expo prebuild --template ../expo/templates/expo-template-bare-minimum/expo-template-bare-minimum-41.0.5.tgz --clean`
- Run `expo prebuild --template https://github.com/victorkvarghese/react-native-boilerplate`
- Run `expo prebuild --template https://github.com/victorkvarghese/react-native-boilerplatefake` to test the error message with an invalid URL.

[prebuild] Added template prop 

---

packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/index.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/xdl/src/Simulator.ts

Allow skipping the bundler and native syslogs in run commands when the user passes `--no-bundler` (maybe `--no-serve` is better?). We skip the syslogs to provide the users with a way to run the command and have it end (no long running tasks).

[run] add --no-bundler option

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/run/ios/ExpoLogFormatter.ts
packages/expo-cli/src/commands/run/ios/XcodeBuild.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
yarn.lock

Make things more even:
```
› Preparing Pods/expo-dev-menu-EXDevMenu » ResourceBundle-EXDevMenu-expo-dev-menu-Info.plist
› Signing   Pods/expo-dev-menu-EXDevMenu » EXDevMenu.bundle
› Compiling expo-dev-menu Pods/expo-dev-menu » DevMenuREAAllTransitions.m
› Packaging expo-dev-menu Pods/expo-dev-menu » libexpo-dev-menu.a
› Executing expo-dev-menu Pods/expo-dev-menu » Copy generated compatibility header
```
Add build duration
```
› Build Succeeded (22.382 sec)
```

Pad titles in log formatter and add duration

---

packages/expo-cli/src/commands/publish.ts

It is confusing people: https://github.com/expo/expo/issues/11812
I think there are also too many contexts where this does not actually provide accurate information (eg: publishing to a bare app, or if you built with Turtle CLI, if you are just trying to publish for use in Expo Go, etc), so we should just not show this warning.
Delete the code
Run publish locally, verify that where I previously saw this warning (eg: on a new blank template) that you do not see this warning.

[expo-cli] Remove URL mismatch warning

---

packages/config-plugins/src/android/EasBuildGradleScript.ts

PKCS do not have keyPassword, but gradle requires that field. It seems to work when kesytorePassword is passed as both values in that case.
if keyPassword is not specified pass kesytorePassword
run build locally with modified eas-build.gradle

[config-plugins] support PKCS keystores for android builds

---

packages/config/src/Config.ts

`modifyConfigAsync` never returns an `ExpoConfig` object.
delete type.
yarn tsc

[config] fix return typing of modifyConfigAsync

---

packages/config-plugins/package.json
packages/config-types/package.json
packages/config/package.json
packages/dev-server/package.json
packages/expo-cli/package.json
packages/expo-codemod/package.json
packages/image-utils/package.json
packages/json-file/package.json
packages/metro-config/package.json
packages/next-adapter/package.json
packages/osascript/package.json
packages/package-manager/package.json
packages/pkcs12/package.json
packages/plist/package.json
packages/pod-install/package.json
packages/pwa/package.json
packages/schemer/package.json
packages/webpack-config/package.json
packages/xdl/package.json
unlinked-packages/configure-splash-screen/package.json

I use `yarn start` in the root directory when working on sth in multiple packages. The output of this command is not really helpful as after each file change the console is wiped. Some type errors can be printed just before the console was wiped.
I passed `--preserveWatchOutput` to every `tsc --watch` command.

disable wiping the console in tsc watch mode

---

packages/expo-cli/package.json
yarn.lock

The yarn.lock file introduced here: https://github.com/expo/expo-cli/pull/2913/files was accidentally overwritten here: https://github.com/expo/expo-cli/commit/ab8843a81effd66b418f800ba73c6af40e7eec56
Add additional resolution
tried to install a different module and confirmed it did not overwrite the yarn.lock resolution.

Add additional hermes resolution

---

packages/expo-cli/src/commands/export/exportAppAsync.ts
packages/xdl/src/ProjectAssets.ts

`expo export` doesn't work when run outside of a project directory: https://github.com/expo/expo-cli/issues/3478
Set the `absoluteOutputDir` by resolving to the `projectDir` instead of `process.cwd()`
Went through and enforced usage of `*PathToWrite` by both the section where the directories are created as well as the section where the files are written.
Repro'd the bug in #3478, confirmed that this PR fixes it.
Tested that `expo export` works both inside and outside a project dir.

[expo-cli] fix expo export so it finds the correct projectDir

---

packages/xdl/src/start/ManifestHandler.ts

- Prevent overwriting default metro features https://github.com/expo/expo-cli/pull/3490
- Only support `/`, `/manifest`, `/index.exp` for the manifest middleware.
- Start expo, visit `/`, `/manifest`, `/index.exp` and get the manifest
- Visit `/json/version` to get something other than the manifest

Limit manifest serving to a few URLs

---

packages/config-plugins/src/ios/Swift.ts
packages/config-plugins/src/ios/SwiftBridgingHeader.ts
packages/config-plugins/src/ios/__tests__/Swift-test.ts
packages/config-plugins/src/ios/index.ts
packages/config-plugins/src/plugins/__tests__/expo-plugins-test.ts
packages/config-plugins/src/plugins/expo-plugins.ts

Installing `@react-native-menu/menu`, `react-native-blurhash` and `stripe-react-native` Just Work.
Q: Does this increase base binary size by too much?
A: No, according to TestFlight estimates:
Added an empty Swift file included in the target.
```
expo init hello # some managed project
cd hello
yarn add @react-native-menu/menu
expod prebuild
expo run:ios
```
Possibly remove [this plugin from expo-facebook](https://github.com/expo/expo/blob/master/packages/expo-facebook/plugin/src/withNoopSwiftFile.ts)? Note that these plugins play together nicely so it's not strictly necessary.

[config-plugins] Add noop Swift file to fix builds with Swift deps

---

packages/xdl/src/Android.ts

When opening an app in an Android device or emulator, Expo CLI runs `adb shell monkey` to trigger a launch of the application before opening the deep link.
This was added as a workaround to a bug before SDK 38 was released:
https://github.com/expo/expo-cli/blob/9a3afab44b5c28ec4baa7f0c3c3cf6440fcc68d7/packages/xdl/src/Android.ts#L528-L531
However running the `adb shell monkey` command when opening an app using dev client causes the dev launcher splash screen and UI to briefly flash before showing the app.
Stopped triggering the monkey command when `applicationId` is not `host.exp.exponent` (Expo Go), since the workaround was made for Expo Go.
Note: I also toyed with removing the workaround altogether, since it seemed the issue referred to in the comment might be already fixed …

Stop running `adb shell monkey` when opening apps other than Expo Go

---

packages/config/src/Config.ts
packages/config/src/__tests__/getFullName-test.ts
packages/config/src/getFullName.ts

https://github.com/expo/expo-cli/pull/3376 added `currentFullName` for use as a stable identifier, but it is not stable through project transfers. `originalFullName` is, so it should be used instead in libraries like auth-session and notifications.
1. The xdl schema was defined in https://github.com/expo/universe/pull/7590
2. This PR is the equivalent of https://github.com/expo/expo-cli/pull/3376 but for `originalFullName`. `currentFullName` is kept so that the CLI continues to function until we change the auth-session and notifications libraries to use `originalFullName`.
3. Next up, I'll change the auth-session and notifications libraries to use `originalFullName` similar to expo/expo#12465 and expo/expo#12464.
Run same unit tests that were added in …

Add `originalFullName` to the public config

---

packages/expo-cli/src/commands/start/TerminalUI.ts

Closes ENG-1146.
Enable socket controls when the dev-client flag is present. 
Recently, I've added a WebSocket support into dev-meu:
- https://github.com/expo/expo/pull/12979 [ios]
- https://github.com/expo/expo/pull/12983 [android]
This PR addresses the CLI part of this task. It enables socket controls in dev-client. 
- tested using PRs above ✅

[cli] Enable socket controls in dev-client

---

packages/config-plugins/src/Plugin.types.ts
packages/config-plugins/src/index.ts
packages/config-plugins/src/plugins/__tests__/android-plugins-test.ts
packages/config-plugins/src/plugins/__tests__/mod-compiler-test.ts
packages/config-plugins/src/plugins/__tests__/withMod-test.ts
packages/config-plugins/src/plugins/createBaseMod.ts
packages/config-plugins/src/plugins/mod-compiler.ts
packages/config-plugins/src/plugins/withDangerousMod.ts
packages/config-plugins/src/plugins/withMod.ts
packages/config-plugins/src/utils/errors.ts

Add stricter rules to modifiers to help prevent any possible errors in setup. Also enables the ability to automatically skip running mods that don't have providers.
- Added ability to specify if a mod is a "provider".
- Assert when adding multiple providers.
- Assert when adding a child mod after a provider has already been added.
- Added strict flag to compiler which skips mods that don't have a provider.
- Remove unused functions like `clearMods`
- Added tests

[config plugins] added provider validation

---

packages/config-plugins/src/plugins/__tests__/android-plugins-test.ts
packages/config-plugins/src/plugins/__tests__/mod-compiler-test.ts
packages/config-plugins/src/plugins/mod-compiler.ts

Rename strict to assertMissingModProviders

---

packages/config-plugins/src/ios/BuildScheme.ts
packages/config-plugins/src/ios/BundleIdentifier.ts
packages/config-plugins/src/ios/ProvisioningProfile.ts
packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/__tests__/BuildScheme-test.ts
packages/config-plugins/src/ios/__tests__/BundleIdentifier-test.ts
packages/config-plugins/src/ios/__tests__/ProvisioningProfile-test.ts
packages/config-plugins/src/ios/__tests__/Target-test.ts
packages/config-plugins/src/ios/__tests__/__snapshots__/ProvisioningProfile-test.ts.snap
packages/config-plugins/src/ios/__tests__/fixtures/multitarget.xcscheme
packages/config-plugins/src/ios/__tests__/fixtures/project-multitarget.pbxproj
packages/config-plugins/src/ios/index.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts
packages/expo-cli/src/commands/run/ios/developmentCodeSigning.ts
ts-declarations/xcode/index.d.ts

In EAS CLI, we want to support managed credentials for multitarget iOS projects.
An example of a multitarget project is a project with a Share Extension. Such a project consists of a (main) application target and an extension target. They have distinct bundle identifiers. Currently, there's no way of reading the bundle id for a particular target. We always read the bundle id for the first native target defined in the .pbxproj file.
The bundle identifier for a particular target is stored in an XCBuildConfiguration entry in .pbxproj. The entry can be found by the target name and build configuration pair, e.g. `target = myproject, build configuration = Release`.
- I made `IOSConfig.BundleIdentifier.getBundleIdentifierFromPbxproj` accept a target name and build configuration. Unless the …

[config-plugins] make bundle identifier getter aware of multiple targets

---

packages/expo-cli/scripts/introspect.ts

Fixes https://github.com/expo/expo/pull/13036/files#r639228722
This appears to be the easiest way for us to use `|` in our markdown doc tables, based on https://stackoverflow.com/a/43070960/659988
- Run `yarn introspect md | pbcopy`
- Paste results in expo-cli docs as usual
- Format the markdown
- Notice that `expo publish:history` docs work as expected

[introspect] Add pipe sanitization

---

packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts

https://github.com/expo/eas-cli/issues/430
In https://github.com/expo/expo-cli/pull/3483 I unintentionally changed the behavior of `findFirstNativeTarget` so it can return a non-application target (e.g. test target). Also, `getBuildConfigurationsForListId` had a bug when getting build configurations for a configuration list associated with a test target (because of the `.filter(isNotTestHost)` filter) so the `Build configuration 'Release does not exist in list with id` error.
- I made `findFirstNativeTarget` always return an application target (if exists).
- I fixed the `getBuildConfigurationsForListId` so it works for test targets.
yarn link-ed `@expo/config-plugin` to local EAS CLI and followed the repro steps from https://github.com/expo/eas-cli/issues/430#issuecomment-850932792

[config-plugins][ENG-1225] fix finding first native target

---

packages/xdl/src/start/startDevServerAsync.ts

https://github.com/expo/expo/issues/13114 reported that serving an app in Expo Go doesn't work when there is an index.html in project root. I looked into it and it turns out that this is because static file serving from the React Native CLI server runs before our manifest handler. So, this is a little hack to move our manifest handler middleware to the front of the middleware stack.
I'm not sure `stack` is meant to be part of the public API but looking at [the source code for `connect`](https://github.com/senchalabs/connect/blob/master/index.js) this seems fine to use.
Follow steps from repro for https://github.com/expo/expo/issues/13114 then use Expo CLI with this patch.

[xdl] Prepend manifest handler

---

packages/config-plugins/src/ios/Google.ts
packages/config-plugins/src/ios/Locales.ts
packages/config-plugins/src/ios/Swift.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts

Silence the `noop-file.swift` warning

Silence duplicate file warnings

---

CONTRIBUTING.md

I had some issues while trying to begin working with the `expo-cli` repository, it was unclear how to use the `expo-cli` itself, didn't know which script to run, the steps seemed to be incomplete. I've reached out @brentvatne that was helping on other issue, explaning that I couldn't begin the feature because I couldn't even configure the repository correctly. He helped me with some steps and managed to make the repository start running as it should. After that, I suggested including the steps at the `CONTRIBUTING.md` file, so that other developers won't need to pass the same as I did.
Clone the `expo-cli` repository from GitHub, follow the steps, if all of them worked as expect and you managed to start the test repository, it should be working fine.

Improves CONTRIBUTING.md file for newer developers

---

packages/config-plugins/src/Plugin.types.ts
packages/config-plugins/src/android/Colors.ts
packages/config-plugins/src/android/NavigationBar.ts
packages/config-plugins/src/android/PrimaryColor.ts
packages/config-plugins/src/android/Resources.ts
packages/config-plugins/src/android/RootViewBackgroundColor.ts
packages/config-plugins/src/android/StatusBar.ts
packages/config-plugins/src/android/Styles.ts
packages/config-plugins/src/android/__tests__/Colors-test.ts
packages/config-plugins/src/android/__tests__/NavigationBar-test.ts
packages/config-plugins/src/android/__tests__/PrimaryColor-test.ts
packages/config-plugins/src/android/__tests__/Resources-test.ts
packages/config-plugins/src/android/__tests__/RootViewBackgroundColor-test.ts
packages/config-plugins/src/android/__tests__/StatusBar-test.ts
packages/config-plugins/src/index.ts
packages/config-plugins/src/plugins/__tests__/mockMods.ts
packages/config-plugins/src/plugins/android-plugins.ts
packages/config-plugins/src/plugins/withAndroidBaseMods.ts
packages/config-plugins/src/utils/XML.ts
packages/prebuild-config/src/plugins/icons/__tests__/withAndroidIcons-test.ts
packages/prebuild-config/src/plugins/icons/withAndroidIcons.ts
packages/prebuild-config/src/plugins/unversioned/expo-notifications/__tests__/withAndroidNotifications-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-notifications/withAndroidNotifications.ts

- Too many android plugins are using dangerous for very simple static modifications
- We held off on adding these mods because it was unclear if we wanted to add support for multi-file mods. It's been a while and we still haven't _needed_ them so it seems safe to proceed without them. Re: https://github.com/expo/expo-cli/pull/2992
- I'm thinking for splash screen we will just manually add colorsNight or colorsDark, colorsV23, etc. to support other file variations. This will work better for dev tooling like the vscode extension which previews a single mod as a file.
- Created withAndroidColors & withAndroidStyles for providing the default colors.xml and styles.xml for a project.
- Added support for two new base mods android.colors android.styles
- Migrated all plugins using colors and …

[config plugins] add styles and colors mods

---

packages/expo-cli/src/commands/build/BaseBuilder.ts
packages/expo-cli/src/commands/utils/__tests__/url-test.ts
packages/expo-cli/src/commands/utils/url.ts

Our paths for build details pages are now: "/accounts/[account]/projects/[project]/builds/[buildId]". We are still showing the path without the "/projects/[project]" segment. This causes us to redirect to the correct page on the website. This change goes directly to the correct page, which makes it load faster.
Run `expo build:ios` or `expo build:android`, then check the output for the output above. You should see the projects path appear if it exists. Also, run unit tests.

[expo-cli] Add "/projects/[project]" to website build url

---

packages/expo-cli/src/schemes.ts
packages/expo-cli/src/urlOpts.ts

It should be possible to use dev client with a managed project.
- Removed the "can only be used in bare workflow apps" warning
- Added a check to look up the schema in `app.json`/`app.config.*s` when there are no native project (managed project)
- ~Added a prompt for schema when it's not configured.~
- ~Prompt has a good default.~
Created a managed project and verified that `expo start --dev-client` started the dev server. Tested with:
- `app.json` including a schema -> started without warnings
- no `scheme` -> error
Also set the `scheme` property in `app.json` to the URI scheme of an app that I had previously built and installed on my Android device. Running `expod start --dev-client` and pressing `a` opened the app.

Allow `expo start --dev-client` in managed projects

---

packages/expo-cli/src/commands/init.ts

This template is out of sync with the other bare template, things like this https://github.com/expo/expo/pull/13216 will potentially cause confusion as the templates diverge.
Remove `expo-template-bare-typescript` from init

Remove bare typescript template

---

packages/xdl/src/project/Doctor.ts

Who needs proper semver versions when you can have a custom internal format that nobody can parse? 😄  This checks on both the existing semver and if the pattern [matches the newer version in Homebrew](https://github.com/Homebrew/homebrew-core/commit/d299c2867503cb6ad8d90792343993c80e745071#diff-35c4226d33f9dd956e8656e92e9ba8606ae1ddea05fff181850e81751d8b1103).
- Added "is valid semver" check for the semver format
- If the semver isn't valid, try validating if the version format is equal to `XXXX.XX.XX.XX` (where `X` is a number).
- `$ brew upgrade watchman`
- `$ expo doctor` (on any project)
- Invalid watchman version shouldn't pop up

[xdl] Update watchman version check to allow new format

---

packages/config-plugins/src/android/index.ts
packages/config-plugins/src/ios/index.ts
packages/prebuild-config/src/plugins/unversioned/expo-ads-admob.ts
packages/prebuild-config/src/plugins/unversioned/expo-ads-admob/__tests__/withAndroidAdMob-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-ads-admob/__tests__/withIosAdMob-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-ads-admob/expo-ads-admob.ts
packages/prebuild-config/src/plugins/unversioned/expo-ads-admob/withAndroidAdMob.ts
packages/prebuild-config/src/plugins/unversioned/expo-ads-admob/withIosAdMob.ts
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

- Make `expo/config-plugins` smaller
- Make AdMob modules less accessible
- Starts possible deprecation process for unversioned expo-ads-admob module
- Moved tests

Migrate expo-ads-admob plugin to prebuild-config

---

packages/config-plugins/src/android/StatusBar.ts
packages/config-plugins/src/android/__tests__/StatusBar-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withAndroidSplashScreen.ts

Prevent the status bar from flashing to the background color by setting the androidStatusBar.backgroundColor to the splash screen background color. This will cause the status bar to be an unexpected color in the app unless `<StatusBar style="auto"/>` is used (which seems reasonable enough).
This PR also drops support for `translucent` as the backgroundColor as this breaks things

Patch android status bar to match the color of the splash screen

---

packages/expo-cli/package.json
packages/expo-cli/src/schemes.ts

We're starting to support dev client in managed projects. However, the project might not have a URI scheme defined that's same for iOS and Android, which is currently a requirement for launching the client app. To fix this we have made the `expo-dev-client` config plugin always add a default scheme generated from the slug (e.g. slug `1-up-app` -> scheme `exp+1-up-app`).
Scheme generation was added in https://github.com/expo/expo/pull/13147 and refined & publicly exposed in https://github.com/expo/expo/pull/13230.
This PR makes the `expo start --dev-client` command always use the autogenerated default scheme for managed projects.
- Import the module `expo-dev-client/getDefaultScheme` from the project and run it, passing the app config as an argument.
- Use the returned string as a scheme. …

[expo-cli] Use the default scheme to launch managed dev client apps

---

packages/dev-server/src/HermesBundler.ts
packages/dev-server/src/MetroDevServer.ts
packages/dev-server/src/__tests__/HermesBundler-test.ts
packages/expo-cli/e2e/__tests__/export-test.ts
packages/expo-cli/src/commands/export/exportAppAsync.ts
packages/xdl/src/logs/TableText.ts
packages/xdl/src/project/createBundlesAsync.ts
packages/xdl/src/project/publishAsync.ts

this pr addresses some missing parts of hermes support.
closes [ENG-1223](https://linear.app/expo/issue/ENG-1223)
1. add hermes bytecode bundle to `printBundleSizes`.
2. add hermes bytecode bundle support for `expo publish`.
3. support managed workflow by reading the `android.jsEngine` config in app.json.
4. `android.jsEngine` in app.json is now the single source of truth to determine  if we need to generate hermes bytecode bundle.
5. introduce `maybeInconsistentEngineAsync()` to show an error prompt if there are inconsistencies between app config and native project.
1. expo export + managed workflow app with `android.jsEngine=hermes` in app.json.
make sure exported assets has hermes bytecode bundle.
2. expo publish + managed workflow app with `android.jsEngine=hermes` in app.json. …

[expo-cli] Enhance Hermes support for expo export and publish

---

packages/config-plugins/src/android/Permissions.ts
packages/config-plugins/src/android/__tests__/Permissions-test.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap

The android permissions code used to be used for something else and it injected "default permissions", along with adding "all permissions" if no permissions were defined. This leads to unfortunate side effects where removing permissions is difficult to do.
This PR removes all side-effects and simplifies permission adding, all android permissions will now come from plugins, config, and the template.
- ENG-1227
Updated unit tests.

[config plugins] Remove permission side effects

---

CHANGELOG.md
packages/config-plugins/src/android/Updates.ts
packages/config-plugins/src/ios/Updates.ts

For EAS updates, we use are able to set the "update request headers" through the plist/manifest. This adds it to the config-plugin enum

[config-plugins] add config request headers enum

---

packages/expo-cli/src/StatusEventEmitter.ts
packages/expo-cli/src/analytics/getDevClientProperties.ts
packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/installExitHooks.ts
packages/expo-cli/src/exp.ts
packages/xdl/src/User.ts
packages/xdl/src/logs/PackagerLogsStream.ts

In order to improve the experience of using dev client, we're recording a few key events from the CLI.
Events:
- `expo start --dev-client`: event `dev client start command`
- `expo run:ios`: event `dev client run command` with property `platform: "ios"`
- `expo run:android`: event `dev client run command` with property `platform: "android"`
Properties included in all of these events:
- `account_name`: the `owner` of the project, if defined. Otherwise current username.
- `dev_client_version`: semver version of the currently installed `expo-dev-client` package (if installed)
- `is_managed`: `true` if the project has `managed` as it's default target, i.e. iOS and Android native projects don't exist.
- `status`: `started` when the command is starting, `ready` once the dev server is running …

Add analytics to dev client commands

---

packages/expo-cli/e2e/__tests__/__snapshots__/export-test.ts.snap
packages/expo-cli/e2e/__tests__/export-test.ts

Don't need to test against exact bundle hashes, doing so can lead to annoying tests breaking.

[expo-cli][export] Prevent testing against bundle hashes

---

CHANGELOG.md
packages/config-plugins/src/ios/IosConfig.types.ts
packages/expo-cli/e2e/__tests__/__snapshots__/export-test.ts.snap

Follow up to https://github.com/expo/expo-cli/pull/3571
This adds typing to the `ExpoPlist`.
There is no analog for Android.

[config-plugins] add EXUpdatesRequestHeaders to ExpoPlist type

---

packages/config-plugins/src/ios/Version.ts
packages/config-plugins/src/ios/__tests__/Version-test.ts

Apple rejects apps that use version `0.0.0`.

[config-plugins] Default version number to 1.0.0

---

packages/expo-cli/src/commands/utils/deprecatedExtensionWarnings.ts
packages/expo-cli/src/commands/utils/glob.ts
packages/expo-cli/src/commands/utils/typescript/resolveModules.ts

Disabled using `abort()` as it breaks the entire glob package across all instances.
https://github.com/isaacs/node-glob/issues/279 & https://github.com/isaacs/node-glob/issues/342 
For now, just collect every match, which is much slower in the case where a large project is not using TypeScript.
Also added a timeout functionality in case another library accidentally uses abort in the future and breaks it again.
`rm -rf tsconfig.json && expo start` in a project with a `*.ts` file should no longer hang.

[expo-cli] Add workaround for glob abort

---

packages/config-plugins/src/ios/Target.ts
packages/expo-cli/src/commands/run/ios/__tests__/developmentCodeSigning-test.ts
packages/expo-cli/src/commands/run/ios/developmentCodeSigning.ts

When you have a multi-target app, you need to setup signing for each bundle identifier, it doesn't seem likely that a user would want to register a child bundle id with a different account than their parent bundle id. This PR will sign all runnable targets with the same Apple team in development before running.
- Setup a multi target iOS app in Xcode, run locally with `expo run:ios -d` (select a connected device).

[run:ios] Improve multi-target support by signing all targets at once

---

packages/config-plugins/src/ios/BuildScheme.ts
packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts
packages/expo-cli/src/commands/run/index.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts

It's not always clear what build schemes are available, so if the user passes `--scheme` with no name, then we'll fetch a list of schemes and prompt the user which to pick. If only one is available (most projects) then we'll default to that. 
- It's not clear if this is the correct way to read all of the build schemes, but the existing method `getSchemesFromXcodeproj` doesn't work. Afaict, the files in `ios/*.xcodeproj/xcshareddata/xcschemes/*.xcscheme` don't represent the valid schemes, it's unclear to me why this approach is used.
- Determine the default scheme by comparing it against the type `com.apple.product-type.application` and label it as default.
- In a project, add an extra target, then run `expo run:ios --scheme`.
- In a regular project run `expo run:ios --scheme` and it'll …

[run] prompt for scheme

---

packages/config-plugins/src/android/__tests__/Styles-test.ts
unlinked-packages/configure-splash-screen/src/android/Styles.xml.ts
unlinked-packages/configure-splash-screen/src/android/__tests__/Styles.xml-test.ts
unlinked-packages/configure-splash-screen/src/android/__tests__/fixtures/react-native-project-structure-with-splash-screen-configured.ts

By not extending the default theme, we lose all of the predefined styles. Related https://github.com/expo/expo/pull/13196

[splash-screen] Extend default theme

---

packages/config-plugins/src/android/StatusBar.ts

This is the closest we can get to iOS parity atm.

default translucent to off

---

packages/config-plugins/src/plugins/mod-compiler.ts
packages/expo-cli/src/commands/config/config.ts
packages/expo-cli/src/commands/eject/configureProjectAsync.ts

As new versions of config plugins come out there may be mismatched providers, this PR will prevent them from breaking and instead warn that a mod will be skipped in expo prebuild, eject, and config.
In a project:
`plugin.js`
```js
module.exports = (config) => {
config.mods = {};
config.mods.ios = {};
config.mods.ios.foobar = () => null;
return config;
};
```
`app.json`
```json
{ "expo": { "plugins": ["./plugin"] } }
```

Skip unprovided mods and warn

---

packages/dev-server/package.json
packages/dev-server/src/HermesBundler.ts
packages/dev-server/src/MetroDevServer.ts
packages/expo-cli/e2e/__tests__/export-test.ts

Users sometimes see the "JavaScript engine configuration is inconsistent" for SDK 41 or lower.
e.g. https://github.com/expo/expo-cli/pull/3536#issuecomment-867639323
Only check or build hermes stuffs for SDK 42 or higher.
Includes a fix in `maybeInconsistentEngineAsync` that gradle.properties has no chances to be checked. 
Verify matrix below by `expo export` command.
- android.jsEngine=hermes in app.json -> ✅
- enableHermes=true in android/app/build.gradle -> ✅
- android.jsEngine=hermes in app.json + enableHermes=true in android/app/build.gradle -> ✅
- android.jsEngine=hermes in app.json -> ❌
- expo.jsEngine=hermes in android/gradle.properties ->  ❌
- android.jsEngine=hermes in app.json + expo.jsEngine=hermes in android/gradle.properties -> ✅
- android.jsEngine=hermes in app.json + …

[dev-server] Only check or build hermes stuffs for SDK 42 or higher

---

packages/config-plugins/src/ios/BundleIdentifier.ts
packages/config-plugins/src/ios/InfoPlist.ts
packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts
packages/config-plugins/src/ios/utils/__tests__/getInfoPlistPath-test.ts
packages/config-plugins/src/ios/utils/getInfoPlistPath.ts
packages/config-plugins/src/plugins/withIosBaseMods.ts

In multi-target projects, there will be more than one Info.plist, right now we warn and guess, this PR uses the Xcode project to resolve the exact Info.plist. If the fs doesn't have a pbxproj, then fallback on the existing behavior.
- Added tests
- Ran locally with ios-stickers

Resolve exact Info.plist filepath

---

packages/config-plugins/src/ios/utils/Xcodeproj.ts

Using `@config-plugins/react-native-dynamic-app-icon` with `@config-plugins/ios-stickers` doesn't work reliably because the icons can sometimes get added to the wrong target. I imagine this will happen with Google services files and locales in multi-target projects too.

Add to the main target if possible

---

packages/config-plugins/src/android/Updates.ts
packages/config-plugins/src/ios/Updates.ts

When working on https://linear.app/expo/issue/ENG-1460/add-runtimeversion-to-build-job-metadata I've noticed that EAS CLI always prints "Native project configuration is not synced with values present in your app.json" even if the native project is properly configured.
It turns out that when we configure the native configuration and the runtime version is defined in the app config, we remove the value of the SDK version. Later, we once again check if the values are synced. But this time we're checking if the SDK version from the app config (which is always defined) matches the nonexistent value in the native config. 
I fixed the `areVersionsSynced` (Android) and `isPlistVersionConfigurationSynced` (iOS) functions so they check if the versions are synced conditionally (similarly to how …

[ENG-1460][config-plugins] fix expo updates native configuration checks

---

packages/expo-cli/src/commands/run/android/spawnGradleAsync.ts
packages/expo-cli/src/commands/run/ios/XcodeBuild.ts
packages/xdl/src/SimControl.ts

Cancelling `run:android` or `run:ios` throw confusing error messages, this PR cleans the errors up a bit.

Cancel run commands better

---

packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts
packages/expo-cli/src/commands/run/utils/resolvePortAsync.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/utils/choosePortAsync.ts

We want to prompt users to use another port if the 8081 is too busy for the project they are currently starting. We have the ability to loosely identify if the port is already running the current project in another window. 
This PR bails out when the project is already being hosted on the requested port elsewhere. 
Only reuse the default port for `run:ios` and `run:android`, and skip this behavior for `expo start`.
- `expo run:ios` 
- in another window, run `expo run:ios`, it should print `skipping dev server...`
- Running `expo start --dev-client` in multiple windows should always prompt.

Skip prompting to start dev server on another port

---

packages/config-plugins/src/ios/Scheme.ts

As described in #3625, a newly created URL type entry in XCode doesn't have any properties yet, so it's not safe to assume the CFBundleURLSchemes property exists and is an array, in fact it crashes the `uri-scheme` CLI tool.
This fix adds a type check in the same coding style as the one right above it to ensure the existence of the array before trying to access it.
As I am not extremely familiar with this huge monorepo, I am not aware of any automated test cases covering this functionality. However, the fix is small and self-explanatory, and aligns perfectly with the stacktrace thrown by the `uri-scheme` CLI tool.

Handle empty entries when parsing URL types in iOS projects

---

packages/config-plugins/src/ios/Scheme.ts
packages/xdl/src/internal.ts
packages/xdl/src/start/startAsync.ts
packages/xdl/src/start/watchBabelConfig.ts

Resolve https://github.com/expo/expo-cli/issues/151
Observe file changes for babel config and log a warning to restart the server. 
- `expo start` 
- modify the babel.config.js 
- See logs in terminal
- Repeat but with `expo web`

Warn about babel config changing

---

packages/config/src/Config.types.ts
packages/xdl/src/start/ManifestHandler.ts

Flipper's "React Native" section only works if it can detect a certain string in the `/` path of the server hosted at `localhost:8081` [ref](https://github.com/facebook/flipper/blob/9ca8bee208b7bfe2b8c0dab8eb4b79688a0c84bc/desktop/app/src/dispatcher/metroDevice.tsx#L37). This PR ensures that the string is present in the manifest. 
- https://twitter.com/Baconbrix/status/1412921581542658049?s=20
- `expod start` then opened flipper with `METRO_SERVER_PORT=19000 open -a flipper.app`, React Native section was enabled and available.
- `expod start --dev-client` then opened flipper normally, React Native section was enabled.

Added flipper hack to manifest JSON

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/build/startBuildAsync.ts
packages/expo-cli/src/credentials/credentialsJson/read.ts
packages/xdl/package.json
packages/xdl/src/UrlUtils.ts
yarn.lock

Now that we've dropped support for Node 10, we can upgrade this dep.
related https://github.com/expo/expo-cli/issues/1659 https://github.com/expo/expo-cli/pull/3132

Upgrade hapi/joi to joi

---

packages/image-utils/src/Image.ts
packages/image-utils/src/jimp.ts

Sharp allows for passing undefined width, height, resizeMode, but jimp does not.

[image-utils] Allow any size or resize mode for jimp

---

packages/expo-cli/src/commands/run/utils/resolvePortAsync.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/start/startAsync.ts
packages/xdl/src/start/startDevServerAsync.ts

Added `--port` option to `expo start` and `expo start --dev-client`
- default port for Expo Go: 19000
- default port for Expo dev client: 8081
Doesn't apply to tunnel (ngrok) or web (webpack). `expo web --port` exists for webpack control.
- `expo start --port 8081`, should reuse the port selection prompt that we use across the CLI.
- `expo start --dev-client --port 8089`, should reuse the port selection prompt that we use across the CLI.
- `expod start` -> 19000 (metro)
- `w` -> 19006 (webpack)
- `expod start --dev-client` -> 8081 (metro)
- `w` -> 19006 (webpack)
- `WEB_PORT=3000 expod web --port 8081` -> 8081 (webpack)
- `WEB_PORT=3000 expod web` -> 3000 (webpack)
- `expod start --port 8081` -> 8081 (metro)
- `w` -> 19006 (webpack)

Added port option to expo start

---

packages/config/src/Config.types.ts
packages/xdl/package.json
packages/xdl/src/DevSession.ts
packages/xdl/src/ProjectAssets.ts
packages/xdl/src/internal.ts
packages/xdl/src/project/ExpSchema.ts
packages/xdl/src/start/ExpoUpdatesManifestHandler.ts
packages/xdl/src/start/ManifestHandler.ts
packages/xdl/src/start/__tests__/ExpoUpdatesManifestHandler-test.ts
packages/xdl/src/start/__tests__/ManifestHandler-test.ts
packages/xdl/src/start/startAsync.ts
packages/xdl/src/start/startDevServerAsync.ts
yarn.lock

We'd like to move `expo start` to use the [new format manifests](https://docs.expo.io/technical-specs/expo-updates-0/). This PR starts that process by serving the new format manifest at a separate URL on the local webserver.
Next up:
- figure out how to embed scopeKey in this manifest format (top level field on the manifest probably)
- figure out how to sign scopeKey for Expo Go (cert chain probably)
- figure out how this interacts with eas-cli for embedding things like extra.eas.projectId in the manifest and signing the scopeKey.
- create a way to run `expo start --new-manifest-format` (or something like that) that will serve the new manifest and use it for the development session and QR code by default
This PR is where we're designing the format of the new manifest `extra` field. It's …

feat: serve new expo-updates format manifests

---

packages/json-file/__tests__/JsonFile-test.ts
packages/json-file/package.json
packages/json-file/src/JsonFile.ts

We no longer support node 10, and can freely use the new `fs` features.
Hoping the unit tests work well enough to catch these changes.

Remove fs-extra from json-file

---

packages/expo-cli/jest.config.js
packages/expo-cli/package.json

expo-cli e2e tests are long and a bit poorly written atm (i.e. cleanup has issues). All tests currently run when the user does `yarn test` in expo-cli, I found that this often leads to me writing less tests for expo-cli. Now they'll only be run with `yarn test:e2e` or in CI.

Split up e2e tests so they're only run when the user specifies

---

packages/expo-cli/src/commands/run/android/runAndroid.ts

`expo run:android` cannot connect metro server because reverse tunnel not setting up.
Add adb reverse
```sh
expo init testapp
expo run:android
```

[run][android] fix cannot connect metro in a pure managed app

---

packages/dev-server/src/MetroDevServer.ts
packages/dev-server/src/middleware/remoteDevtoolsCorsMiddleware.ts
packages/dev-server/src/middleware/remoteDevtoolsSecurityHeadersMiddleware.ts
packages/dev-server/src/middleware/replaceMiddlewareWith.ts

Follow existing pattern. Moved from https://github.com/expo/expo-cli/pull/3659

[dev server] refactor middleware into other files

---

packages/config/src/evalConfig.ts
packages/config/src/getConfig.ts

- Make things like this easier to debug in the future https://github.com/expo/expo/issues/13577
- `app.json` - `expo config` should still work
- `app.config.js` - `expo config` should still work
- `app.config.ts` - `expo config` should still work
- import a missing file in the app.config.js -- the error message should point to the exact issue.
- import a file with a missing file, the stack trace should point to the exact location.

[config] Improve missing file errors

---

packages/config-plugins/src/android/UserInterfaceStyle.ts

`addJavaImports` does not add imports after package line for kotlin files. kotlin does not end lines with semicolon.
for the package regular expression, the semicolon is optional.
Test splash-screen config-plugins with MainActvivity.kt

[config-plugins] Fix addJavaImports broken for kotlin files

---

packages/expo-cli/package.json
packages/xdl/package.json
yarn.lock

After the removal of hapi/joi in https://github.com/expo/expo-cli/pull/3639, `@types/hapi__joi` can be removed. Joi already contains built-in package definitions, so the package can be removed altogether.
Remove all instances of `@types/hapi__joi` and run `yarn install`. 
Run `yarn build` and no compilation error should occur. 
(This is my first PR, sorry if I'm doing any wrong).

Remove types hapi joi dependency

---

packages/config/src/Config.ts
packages/config/src/Config.types.ts
packages/config/src/__tests__/ConfigParsing-test.ts
packages/config/src/plugins/withConfigPlugins.ts
packages/expo-cli/src/commands/install.ts
packages/expo-cli/src/exp.ts

If a user incorrectly adds a plugin to their app.json plugins array before installing the plugin, the `expo install` command will fail. This PR dangerously allows for deleting the plugins array so expo install can just read the sdkVersion and package.json. 
Add an invalid plugin and run `expo install lodash` or somn. It should install the package and fail to resolve the plugins for auto plugin adding.

Added skipPlugins prop to getConfig to support expo install better

---

packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/getIosSplashConfig.ts

Currently, the plugin is so good at removing the splash screen that it causes the app to shrink vertically, so instead of defaulting to removing the splash, we'll default to a blank white splash screen on iOS.

Added better default splash screen on iOS

---

packages/expo-cli/e2e/__tests__/eject-test.ts
packages/expo-cli/src/commands/eject.ts
packages/expo-cli/src/commands/ejectAsync.ts
packages/expo-cli/src/commands/install.ts
packages/expo-cli/src/commands/installAsync.ts
packages/expo-cli/src/commands/prebuild.ts
packages/expo-cli/src/commands/prebuildAsync.ts
packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/index.ts
packages/expo-cli/src/commands/run/ios/runIos.ts

- related https://github.com/expo/expo-cli/pull/3672
- lazy load contents of: install, eject, prebuild, run:ios, run:android
- Ran each command

[expo cli] lazy load install, eject, prebuild, run:ios, run:android

---

packages/xdl/src/start/startLegacyReactNativeServerAsync.ts

- Resolve https://github.com/expo/expo-cli/issues/3687
Port selection won't work in the legacy dev server since it uses react-native-community cli under the hood. This PR ensures that a free port be used for the legacy server.
- `expo start` in a project using SDK 39 or less.

Fix legacy dev server port selection

---

packages/expo-cli/src/commands/customizeAsync.ts

Helps to ensure that the files work with the local project. We will check if files from the installed version of `@expo/webpack-config` exist, and if so, we'll use them over the global package.
In a project, install `@expo/webpack-config`, the `expo customize:web` command should pull from those files instead.

Allow customization to use local files

---

packages/expo-cli/scripts/introspect.ts
packages/expo-cli/src/exp.ts

This was used to sort and hide eas commands back when we were testing them in expo-cli.

[expo-cli] Remove eas sort group

---

package.json
packages/config-plugins/package.json
packages/config/package.json
packages/dev-server/package.json
packages/dev-tools/package.json
packages/expo-cli/package.json
packages/expo-codemod/package.json
packages/expo-optimize/package.json
packages/image-utils/package.json
packages/json-file/package.json
packages/metro-config/package.json
packages/next-adapter/package.json
packages/osascript/package.json
packages/package-manager/package.json
packages/pod-install/package.json
packages/pwa/package.json
packages/schemer/package.json
packages/uri-scheme/package.json
packages/webpack-config/package.json
packages/xdl/package.json
yarn.lock

- Removing shared deps help make update diffs smaller. 
- Removed extra prettier copy.
- Moved memfs and rimraf to the base package.json since almost all packages use them.

Remove shared monorepo deps

---

packages/image-utils/package.json
packages/image-utils/src/Download.ts
packages/image-utils/src/jimp.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withIosSplashAssets.ts
yarn.lock

jimp-compact is [very small](https://packagephobia.com/result?p=jimp-compact@0.16.1) and doesn't require that we download any extra jimp packages. Since `expo/image-utils` is our abstract interface for jimp, we can safely assume that no other packages are attempting to install duplicate packages.
- jimp also includes 31 plugins which each take a nominal amount of time to install and link. That is reduced to just one.
- using jimp 14 as it's a bit smaller than jimp 16
- `npm uninstall -g sharp-cli`
- Added an icon to a project, and ran `rm -rf .expo/ && expo prebuild --no-install`.

[image utils] Use jimp compact

---

packages/webpack-config/package.json
packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/loaders/createAllLoaders.ts
packages/webpack-config/src/loaders/createWorkerLoader.ts
packages/webpack-config/src/loaders/index.ts
yarn.lock

We added this experimentally to see if it would help with packages that required worker functionality. It didn't prove helpful, dropping as it's non-standard, undocumented, and adds bloat.

[webpack] Drop support for worker-loader

---

packages/webpack-config/README.md
packages/webpack-config/jest/build-project.js
packages/webpack-config/package.json
packages/webpack-config/src/env/__tests__/__snapshots__/validate-test.js.snap
packages/webpack-config/src/env/validate.ts
packages/webpack-config/src/types.ts
packages/webpack-config/src/webpack.config.ts
yarn.lock

We added this experimentally to see if it would help to reduce native code passed in expo packages, but we've removed most of the need for this by migrating all expo packages to support web. Drops `removeUnusedImportExports` option.

[webpack] Drop support for deep-scope plugin 

---

packages/dev-server/src/HermesBundler.ts

fix https://github.com/expo/expo/issues/13626
on windows, the resolving path should include `.exe` suffix.
setup jsEngine as hermes
```sh
$ jq .expo.android.jsEngine app.json
hermes
```
expo export on macos and windows

Fix hermesc.exe resolving on windows

---

packages/expo-cli/src/commands/publish/getUsageAsync.ts
packages/expo-cli/src/commands/publish/publishHistoryAsync.ts
packages/expo-cli/src/commands/utils/PublishUtils.ts
packages/xdl/src/project/__tests__/getPublishExpConfigAsync-test.ts
packages/xdl/src/project/getPublishExpConfigAsync.ts

Support `runtimeVersion` in classic updates. 
Companion PR to https://github.com/expo/universe/pull/7663.
If the user wishes to publish with a `runtimeVersion`, they can add it to the app.json and the `sdkVersion` will be ignored.
If the user wishes to go back to `sdkVersion`, they just need to delete the `runtimeVersion` key from the app.json.
- Made @expo/config not define `sdkversion` <-> `runtimeVersion` is not defined in the config.
- `@expo/config.getConfig` is called here: https://github.com/expo/expo-cli/blob/master/packages/xdl/src/project/getPublishExpConfigAsync.ts#L33 when we publish an update.
- In expo-cli, updated types and added extra column where necessary.
Tested in demo repo against https://github.com/expo/universe/pull/7663 running on docker.
With only sdkVersion:
With …

[expo-cli][config][xdl] support runtimeVersion in classic updates

---

packages/config-plugins/src/ios/RequiresFullScreen.ts
packages/config-plugins/src/ios/__tests__/RequiresFullScreen-test.ts

If you build an app with SDK 43, requireFullScreen will be false, after the build is successfully compiled, Transporter will fail with:
```
ERROR ITMS-90474: "Invalid Bundle. iPad Multitasking support requires these orientations: 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown,UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight'. Found 'UIInterfaceOrientationPortrait,UIInterfaceOrientationPortraitUpsideDown' in bundle 'com.bacon.app'."
```
Xcode bootstraps a project with:
```js
{
'UISupportedInterfaceOrientations~ipad': {
'UIInterfaceOrientationPortrait',
'UIInterfaceOrientationPortraitUpsideDown',
'UIInterfaceOrientationLandscapeLeft',
'UIInterfaceOrientationLandscapeRight',
}
}
```
This PR proposes that we inject these values when …

[config-plugins] Fix multitasking ipad orientations

---

packages/config-plugins/src/android/Version.ts
packages/config-plugins/src/android/__tests__/Version-test.ts

Version code is the Android equivalent of the build number. In the case when the build number is not defined, we use a default value - `1.0.0` (https://github.com/expo/expo-cli/blob/master/packages/config-plugins/src/ios/Version.ts#L22). However, for 
the version code, we don't fall back to `null`.
We've noticed that because we record the version code / build number as the app build version in EAS Build build metadata (https://github.com/expo/eas-cli/blob/main/packages/eas-cli/src/build/metadata.ts#L68). We should make the build version consistent across platforms.
I updated `getVersionCode` so that it returns `1` if `android.versionCode` is not defined.
I updated the unit test.

[ENG-1601][config-plugins] use default value for android version code

---

packages/expo-cli/src/commands/publishAsync.ts

@tcdavis noticed that the manifest link displayed after a publish ignored the runtimeVersion and displayed the associated SDK version:
Further we display the SDK instead of the runtime version in the informational log:
override SDK and use runtimeVersion if it is present.
confirmed with test publish in demo project:
and double checked the backend directed a url with runtime version query parameter to a runtimeVersion manifest
:

[expo-cli] display correct manifest link after publish

---

packages/config-plugins/src/android/Manifest.ts
packages/config-plugins/src/android/WindowSoftInputMode.ts
packages/config-plugins/src/android/__tests__/SoftwareKeyboard-test.ts
packages/config-plugins/src/android/index.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

- Resolve https://forums.expo.dev/t/softwarekeyboardlayoutmode-pan-works-in-expo-go-and-expo-build-android-but-not-in-eas-build/54978
Tests should cover all important cases

[config-plugins] Added window soft input mode

---

packages/xdl/package.json
packages/xdl/src/Session.ts
packages/xdl/src/UserSettings.ts
packages/xdl/src/__integration_tests__/UserManager-test.ts
packages/xdl/src/__integration_tests__/UserSessions-test.ts
packages/xdl/src/credentials/AndroidCredentials.ts
packages/xdl/src/start/ExpoUpdatesManifestHandler.ts
yarn.lock

Drops install warning:
```
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

[xdl] Upgrade uuid

---

packages/config-plugins/src/ios/BuildScheme.ts
packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/__tests__/BuildScheme-test.ts
packages/expo-cli/src/commands/run/ios/resolveDeviceAsync.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts
packages/expo-cli/src/exp.ts
packages/xdl/src/Logger.ts
packages/xdl/src/SimControl.ts
packages/xdl/src/Simulator.ts
packages/xdl/src/__tests__/SimControl-test.ts

When running a project that supports different OSs, automatically detect which simulator should be opened. This enables users to run projects with something like tvOS support by simply doing `expo run:ios --scheme` and choosing the TV scheme. A best effort approach will be used to find the ideal simulator and open it before building. This prevents unexpected build errors related to using the incorrect target.
- Move scheme resolution before device resolution.
- Filter devices based on selected scheme.
- Fix debug logging in XDL.
- Added improved xcrun error handling.
- Added detection for tvOS since is uses the same application type as iOS.
- Testing on this project: https://github.com/react-native-tvos/TVReanimated
- Run `expo run:ios --scheme` -- should show you a list of schemes: 
- …

[expo-cli][run:ios] Auto detect device type for scheme

---

packages/metro-config/src/ExpoMetroConfig.ts

Reduce useless traces coming from HMR:
```
TransformError SyntaxError: /Users/evanbacon/Documents/GitHub/lab/yolo39/App.js: Expected corresponding JSX closing tag for <Text2>. (10:38)
8 | export default () => (
9 |   <View>
> 10 |     <Text2>hey {String(haveRemoteDev)}</Text>
|                                       ^
11 |   </View>
12 | );
13 |
at node_modules/react-native/Libraries/Utilities/HMRClient.js:320:31 in showCompileError
at node_modules/react-native/Libraries/Utilities/HMRClient.js:227:26 in client.on$argument_1
at node_modules/react-native/Libraries/WebSocket/WebSocket.js:231:8 in _eventEmitter.addListener$argument_1
at node_modules/react-native/Libraries/vendor/emitter/EventEmitter.js:189:10 in emit
at [native code]:null in callFunctionReturnFlushedQueue
```
Down to
``` …
```

[metro-config] Restrict [native code] in stack traces

---

packages/xdl/src/project/publishAsync.ts

`expo publish` with a runtime version was failing for the project described here:
https://exponent-internal.slack.com/archives/C020VQQ8WAE/p1628129369013400
Pass the correct runtime headers when making a `getManifestAsync` call.
I'm unfamiliar with how this part of classic publishing works, but it seems safe to assume that where we were requesting an sdk runtime manifest, we should now be getting a runtime OR sdk manifest.
`grep -i` for other instances of `expo-sdk-version` and `exponenet-sdk-version` and found none.
Repro'd error
Confirmed publish works with rtv.
Confirmed publish still works without rtv.

[xdl] pass appropriate headers when making getManifestCall

---

packages/expo-cli/src/commands/run/android/resolveDeviceAsync.ts
packages/expo-cli/src/commands/run/ios/resolveDeviceAsync.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/commands/start/startAsync.ts

- Split out of https://github.com/expo/expo-cli/pull/3737
- Only validate expo package in Expo Go contexts 
- Combine TerminalUI commands
- `expo start` press i, I, a, A

[expo cli] Refactor TerminalUI commands

---

packages/xdl/src/project/publishAsync.ts

As part of uploading dogfooding builds of Expo Go as part of the expo/expo CI with an access token, we're publishing a copy of the home app (kernel) to `@expo-dogfooding/home`. https://github.com/expo/expo/pull/13871 https://github.com/expo/expo/pull/13883
To do this, we need to be able to publish the actual kernel and not just a modified version of the manifest with the kernel fields removed like we do for expo-dev-home.
Allow publishing kernel with robot when owner field is supplied in the manifest (we artificially mutate the home app.json to add the `expo-dogfooding` owner field just before publishing).
1. Artificially point the expo cli runner in expotools to point to local version.
1. Run `et publish-dogfood-home`, see it correctly publishes the kernel to `@expo-dogfooding/home` and …

[expo-cli] Support robot publishing of kernel when owner is supplied

---

packages/config-plugins/src/ios/utils/Xcodeproj.ts
packages/config-plugins/src/ios/utils/__tests__/Xcodeproj-test.ts
packages/expo-cli/src/utils/extractTemplateAppAsync.ts
packages/xdl/src/EmbeddedAssets.ts

- resolve https://github.com/expo/eas-cli/issues/458 
- When name sanitization strips all characters from a name, fallback to "app".
- I've also added a step to use slugify if all characters are stripped, this would attempt to add extra diversity to project names.
- Unified name sanitization across the repo.
- `expo prebuild` in an app named: `あいう`

Added fallback support for complex characters in prebuild

---

packages/dev-server/package.json
packages/dev-server/src/MetroDevServer.ts
packages/dev-server/src/metro/createDevServerAsync.ts
packages/dev-server/src/metro/importMetroFromProject.ts

Extract code for creating the server instance into expo/dev-server so we can start replacing metro dev server features with bundler agnostic versions that can be applied across platforms and bundlers.
Extract `Metro.runServer` into `createDevServerAsync`. This gives us the ability to replace `MetroHmrServer`, `MetroServer`, and `attachWebsocketServer` with bundler agnostic versions in a set of future PRs.
- `expo start`
- open in sim (bundle middleware) 
- `console.log`
- throw error (symbolication)
- press `r` -- sends reload event (websockets)
- make a change and save (hmr)

[dev server] extract metro run layer into dev server

---

packages/dev-server/src/HermesBundler.ts
packages/dev-server/src/metro/importMetroFromProject.ts

Follow up #3759 collecting up functions that perform dynamic metro imports so we can target them when bundling expo-cli with webpack.

[dev-server] Refactor project imports

---

packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/webpack.config.ts

Webpack config's context property must point to the project root (where the webpack.config.js would normally be located). If this is anywhere else, the source maps and errors won't show correct paths.

[webpack] Use proper project context

---

packages/xdl/__mocks__/resolve-from.ts
packages/xdl/src/DevSession.ts
packages/xdl/src/Env.ts
packages/xdl/src/UrlUtils.ts
packages/xdl/src/__tests__/Env-test.ts
packages/xdl/src/__tests__/UrlUtils-test.ts
packages/xdl/src/start/ManifestHandler.ts
packages/xdl/src/start/startAsync.ts
packages/xdl/src/start/startLegacyReactNativeServerAsync.ts

Extracted from https://github.com/expo/expo-cli/pull/3737
Flip sdkVersion checks so undefined or UNVERSIONED defaults to the latest sdkVersion behavior.
Added more tests

[xdl] support undefined SDK version cases

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/addons/withSourceMaps.ts
packages/webpack-config/src/loaders/createAllLoaders.ts
packages/webpack-config/src/webpack.config.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/start/startAsync.ts
yarn.lock

Currently webpack can be used to load native projects, but only if they support code loading from index.html which hasn't been implemented in any public package yet. This PR makes native webpack work like a regular project by hosting a manifest from `/` so it can be loaded in Expo Go. This PR also adds support for Expo Go opening the project and Terminal UI support.
- `EXPO_WEBPACK_PLATFORM=ios expo web`
- pressing `i` should open in the simulator
- pressing `a` should open in the emulator
- Expo Go should show the project in the project's page

[webpack] added manifest middleware

---

packages/expo-cli/__mocks__/@expo/rudder-sdk-node.ts
packages/expo-cli/jest/setup.ts
packages/expo-cli/src/__tests__/exp-test.ts
packages/expo-cli/src/exp.ts
packages/xdl/__mocks__/@expo/rudder-sdk-node.ts
packages/xdl/jest/fs-mock-setup.ts
packages/xdl/package.json
packages/xdl/src/Analytics.ts
packages/xdl/src/Env.ts
yarn.lock

We are deprecating Segment usage on our platform in favor of RudderStack. This PR will introduce RudderStack as our analytics client.
- adds the RudderStack client to the `XDL` `Analytics` file
- adds types for the RudderStack analytics client
- keeps Segment around for now to ensure event volumes match
- the RudderStack client is using a fork that has all logs go through Winston. This way we can silence the error logs.
- I've run `XDL` commands locally and confirmed they reach the proper destinations. 
- This PR logs analytics events to both Segment and RudderStack. Once this is merged we'll need to confirm event volumes match. Afterwards, we'll follow up with a PR to remove the `segmentClient` from `Analaytics`.

[xdl][expo-cli] Introduces RudderStack

---

packages/expo-cli/src/commands/start/TerminalUI.ts

Pressing <kbd>shift+i</kbd> then <kbd>ctrl+c</kbd> should silently return to the menu in terminal UI, currently it prints "escaped".

[expo-cli] Don't print escaped message

---

packages/config-plugins/src/ios/utils/Xcodeproj.ts

iOS projects that have fully numeric names currently fail to build with run:ios due to a bug in the ascii plist parser used by the xcode npm package. This PR adds a check to ensure we convert the numeric value to string when needed.
- `expo init`
- Change `name` in app.json to `3` or some other stringified name
- Run `expo run:ios` -- this will work now

Support ios projects with numeric names

---

packages/config-plugins/src/ios/Paths.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts
packages/uri-scheme/src/Ios.ts
unlinked-packages/configure-splash-screen/src/ios/Paths.ts

`expo run:ios` may fail on projects that use Bundler to manage CocoaPods and Fastlane versions.
With `Gemfile` at ios project root:
```
source 'https://rubygems.org'
gem 'cocoapods'
gem 'cocoapods-keys'
gem 'fui', '~> 0.3.0'
gem 'xcpretty'
gem 'second_curtain', '~> 0.2.3'
gem 'fastlane'
```
When you run `cd ios && bundle exec pod install`, Bundler saves files to `vendor/bundle` paths such as `ios/vendor/bundle` and `android/vendor/bundle`, which may have unrelated xcodeproj files.
For example, after `bundle exec pod install`, my project end up having files like below:
```
'XXXX/android/vendor/bundle/ruby/2.5.0/gems/fastlane-2.157.2/fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj',
'XXXX/ios/ExampleApp.xcodeproj',
'XXXX/ios/Pods/Pods.xcodeproj', …
```

[config-plugins] add vendor paths used by Bundlers to ignoredPaths

---

packages/expo-cli/src/commands/eject/installNodeDependenciesAsync.ts
packages/expo-cli/src/commands/eject/updatePackageJson.ts
packages/expo-cli/src/commands/eject/writeMetroConfig.ts

We currently clean the node modules before installing after running prebuild/eject, I guess this is supposed to prevent issues when changing the react-native fork to the upstream react-native. I haven't encountered this error in the latest Expo SDK (I only use yarn), so this PR proposes we skip that step and go straight to relying on yarn to work as expected. 
In blank projects, this reduces prebuild time by over 30% (~6 seconds), this metric would only grow as the project adds more dependencies (also wifi conditions vary). 
- On a clean blank project: `expo run:android`
- On a clean blank project: `expo run:ios`

Skip cleaning node modules for yarn users

---

packages/expo-cli/src/commands/eject/clearNativeFolder.ts
packages/expo-cli/src/commands/eject/ejectAsync.ts
packages/expo-cli/src/commands/prebuildAsync.ts
packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/ios/runIos.ts

Resolve https://github.com/expo/expo-cli/issues/3772
- Added malformed project check to run commands and prebuild.
- Added platform specifier to malformed project check.
revert the contents of a binary folder and run `expo prebuild`

[expo cli] prompt to remove malformed projects

---

packages/expo-cli/src/commands/client/clientInstallAndroidAsync.ts
packages/expo-cli/src/commands/client/index.ts
packages/expo-cli/src/commands/run/android/resolveDeviceAsync.ts
packages/xdl/src/Android.ts

- Resolve https://github.com/expo/expo-cli/issues/2991
- Auto opens an emulator (best-effort) if no device is connected and no emulator is open.
- Provide `--device` or `-d` to get a device picker.
- Pass `--device "Pixel_4_XL_API_30"` to automatically open a specific device (basically the same as `expo run:android`).

Added device selection to `expo client:install:android`

---

packages/expo-cli/package.json
yarn.lock

Adds improved error handling for the new Apple server errors that have been showing up for users that use ASC API with cookies auth https://github.com/fastlane/fastlane/pull/19273 https://github.com/expo/third-party/pull/63
- one user says this works for them https://github.com/expo/expo-cli/issues/3788#issuecomment-904943841

Bump apple-utils to v25

---

packages/plist/package.json
packages/plist/src/parse.ts
yarn.lock

Security vulnerability reported by a partner, see https://www.npmjs.com/advisories/1769
this package is now published under the namespace, see https://github.com/xmldom/xmldom/issues/271
`yarn tsc` and `yarn test`

[plist] Update xmldom to account for security vulnerability

---

packages/config-plugins/package.json
packages/config-plugins/src/android/GoogleServices.ts
packages/config-plugins/src/android/Name.ts
packages/config-plugins/src/android/NavigationBar.ts
packages/config-plugins/src/android/Package.ts
packages/config-plugins/src/android/Scheme.ts
packages/config-plugins/src/android/UserInterfaceStyle.ts
packages/config-plugins/src/android/Version.ts
packages/config-plugins/src/ios/DeviceFamily.ts
packages/config-plugins/src/ios/Locales.ts
packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/ios/RequiresFullScreen.ts
packages/config-plugins/src/ios/__tests__/DeviceFamily-test.ts
packages/config-plugins/src/ios/__tests__/Locales-test.ts
packages/config-plugins/src/utils/warnings.ts
packages/expo-cli/__mocks__/ora.js
packages/expo-cli/src/commands/eject/logNextSteps.ts
packages/expo-cli/src/commands/eject/prebuildAsync.ts
packages/expo-cli/src/commands/utils/logConfigWarnings.ts
packages/expo-cli/src/utils/ora.ts
packages/prebuild-config/src/plugins/unversioned/expo-document-picker.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/__tests__/getIosSplashConfig-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/__tests__/withIosSplashInfoPlist-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/getIosSplashConfig.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withAndroidSplashScreen.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withIosSplashInfoPlist.ts

- resolve https://github.com/expo/expo-cli/issues/3757
- change `WarningAggregator` to just be a wrapper around `console.warn`
- make our spinners support arbitrary console logs during prebuild so plugins can easily log to the terminal.

[config-plugins] Improved warnings system in config plugins

---

packages/expo-cli/src/exp.ts

- resolve https://github.com/expo/expo-cli/issues/3160
- I'm not really sure this is a great idea since the update info is still relevant.

[expo-cli] Disable update check in non-interactive mode

---

packages/dev-server/src/MetroDevServer.ts
packages/dev-server/src/middleware/devServerMiddleware.ts
packages/xdl/src/Webpack.ts

- Adds support for piping logs to the terminal via the `/logs` endpoint by adding all middleware to the webpack dev server.
- Also attaches any extra features that we'd expect when using Metro bundler.
- Adds support for inspecting the JS context from a browser.
- `EXPO_WEBPACK_PLATFORM=ios expod web`
- Open the project with `i` (reloads with `r` since HMR isn't done).
- `console.log` should show up in the terminal
- Open Safari > Develop > [Simulator name] > JSContext: breakpoints and other inspection works

[webpack] Add all native middleware to webpack

---

packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/runtime/metro-runtime-shim.ts
packages/webpack-config/src/webpack.config.ts

react-native `HMRClient` runtime code adds the following:
- event hooks (for web sockets) that map to `metro-runtime` (`metro` in the current version 0.55) HMR features.
- socket code for piping logs to metro -- we currently ignore these in favor of the `expo` [RemoteLogging](https://github.com/expo/expo/blob/50661f5c77b26c1192492496b17ed251d4965ff0/packages/expo/src/logs/RemoteLogging.ts#L122-L126) code.
- cherry-picked onto https://github.com/expo/expo-cli/pull/3808 to test that logs still worked.
- HMR shouldn't change because it isn't implemented.

[webpack] Add metro runtime shim

---

packages/expo-cli/jest/setup.ts
packages/expo-cli/src/__tests__/exp-test.ts
packages/expo-cli/src/exp.ts
packages/xdl/jest/fs-mock-setup.ts
packages/xdl/package.json
packages/xdl/src/Analytics.ts
packages/xdl/src/Env.ts
packages/xdl/src/__tests__/tools/FsCache-test.js
yarn.lock

Volumes are look even between Segment and RudderStack. Removing Segment to finish the migration to RudderStack.
Removed Segment from xdl and expo-cli. 
Slight refactor to the `Env.shouldDisableAnalytics` method  => `Env.shouldEnableAnalytics`. This way I could pull it out of `boostrapAnalyticsAsync` and remove the mock for it inside `exp.ts`. It's a bit simpler and cleaner, imo.
Tested locally to confirm events fired outside of tests.

[expo-cli][xdl] Removes Segment

---

packages/config-plugins/src/android/Resources.ts
packages/config-plugins/src/android/Strings.ts
packages/config-plugins/src/android/__tests__/Strings-test.ts
packages/prebuild-config/package.json
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/__tests__/withAndroidSplashLegacyMainActivity-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/__tests__/withAndroidSplashStrings-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withAndroidSplashLegacyMainActivity.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withAndroidSplashScreen.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withAndroidSplashStrings.ts

support https://github.com/expo/expo/pull/14061
- add `withAndroidSplashStrings` to update `resizeMode` and `statusBarTranslucent`
- rename `withAndroidSplashMainActivity` as `withAndroidSplashLegacyMainActivity` and only process if expo-splash-screen version satisfies `< 0.12.0`
```
PASS   @expo/prebuild-config  src/plugins/unversioned/expo-splash-screen/__tests__/withAndroidSplashStrings-test.ts
setSplashStrings
✓ add expo_splash_screen_strings (148 ms)
✓ override old expo_splash_screen_strings
PASS   @expo/config-plugins  src/android/__tests__/Strings-test.ts
setStringItem
✓ add item from empty xml (2 ms)
✓ support adding multiple items (1 ms)
✓ override existing item
```
```
expo init sdk42
cd sdk42 # select managed layout
expo prebuild -p android
cd node_modules/expo-splash-screen …
```

[prebuild-config] Support new expo-splash-screen to manage resizeMode in resource

---

packages/dev-server/src/webpack/getFileAsync.ts
packages/dev-server/src/webpack/symbolicateMiddleware.ts
packages/metro-config/src/ExpoMetroConfig.ts

Currently it fails to symbolicate with some non-standard paths

Improve the symbolicator

---

packages/xdl/src/EmbeddedAssets.ts

https://github.com/expo/expo-cli/issues/3820
Use method that throws with an informative error if MainApplication is missing. Also filters for only MainApplication as that is all that is needed.
tested in demo repo with MainApplication both present and missing.

[xdl] throw if AndroidManifest.xml is missing a MainApplication

---

packages/next-adapter/src/babel.ts

The current Babel config isn't working correctly with latest Next.js version
- Check if loader name is `next-babel-turbo-loader` to detect web
- Add `next/babel` preset before `babel-preset-expo`
The adapter should work correctly when using the latest Next.js version

[next-adapter] update Babel config

---

packages/dev-server/package.json
packages/dev-server/src/HermesBundler.ts
packages/dev-server/src/MetroDevServer.ts
packages/dev-server/src/__tests__/HermesBundler-test.ts

support building hermes bytecode bundle for ios
- add ios and shared `jsEngine` support to `isEnableHermesManaged` 
- some refactoring to make `maybeAddHermesBundleAsync` clear
= move sdk check into HermesBundler.ts
= move throwing error of `maybeInconsistentEngine*` into HermesBundler.ts
- add `maybeInconsistentEngineIosAsync` to support Podfile.properties.json
```
PASS   @expo/dev-server  src/__tests__/HermesBundler-test.ts
isEnableHermesManaged
✓ should support shared jsEngine key
✓ platform jsEngine should override shared jsEngine
✓ should exclude old SDK (18 ms)
maybeThrowFromInconsistentEngineAsync - ios
✓ should resolve if ":hermes_enabled => true" in Podfile and "jsEngine: 'hermes'" in app.json (1 ms)
✓ should throw if ":hermes_enabled => true" in Podfile but no "jsEngine: …
```

[dev-server] support building hermes bytecode bundle for ios

---

packages/config-plugins/src/android/Name.ts
packages/config-plugins/src/android/__tests__/Name-test.ts

https://github.com/expo/eas-cli/issues/599
Replace any `'` character in the output with `\'`, so that it becomes a valid string.
I've added a test to the package in question, and will try to test this with upstream `eas-cli` as soon as I figure out how to do that 😅

[config-plugins] Escape single quotes in project name

---

packages/dev-tools/components/ProjectManager.js
packages/dev-tools/components/ProjectManagerSidebarOptions.js
packages/dev-tools/pages/index.js
packages/dev-tools/server/graphql/GraphQLSchema.ts
packages/dev-tools/server/graphql/__tests__/GraphQLSchema-test.ts
packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/expo-cli/src/commands/run/ios/startBundlerAsync.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts
packages/xdl/src/start/startDevServerAsync.ts

Remake of https://github.com/expo/expo-cli/pull/3782 by @cruzach but with better resolution for users who accidentally disable platforms.
- Attempting to open a disabled platform will warn how to enable the platform.
- Hovering over disabled platforms in dev tools will show how to enable the platform.
Pressing `w` will log:
```
Web is disabled, enable it by installing react-native-web, and adding web to the platforms array in your app.json or app.config.js
```

use platforms array for disabling platforms

---

packages/metro-config/src/ExpoMetroConfig.ts

Try to use the copy of `metro-react-native-babel-transformer` from the local project before falling back on the global copy.

[metro-config] resolve project metro-react-native-babel-transformer

---

packages/config/src/Config.types.ts
packages/xdl/src/ProjectAssets.ts
packages/xdl/src/start/ExpoUpdatesManifestHandler.ts

This is the simplest solution towards getting EAS update manifests working in development in Expo Go and the dev client. This doesn't require client changes as the client currently assumes that EAS update manifests are signed using the same strategy (which they are on the server as well).
Closes ENG-1756.
The way this works is by looking for the EAS project ID in the config, and then manufacturing a manifest at the time it is served with the values from the EAS server for `manifest.extra.eas.projectId` and `manifest.extra.scopeKey` if an EAS project ID was set in the config.
If the EAS project ID is not set in the config, the anonymous setting is used which allows access to most scoped modules but not EAS services like push notifications or auth session.
This is tested in tandem with the …

[xdl][config] Implement naive manifest signing for EAS update manifests

---

packages/expo-cli/src/commands/run/index.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts
packages/expo-cli/src/commands/run/ios/runIos.ts

sometimes you don't want the pods to be installed

Add --no-install option to expo run:ios

---

packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/expo-cli/src/commands/run/ios/startBundlerAsync.ts
packages/xdl/src/Project.ts
packages/xdl/src/ProjectSettings.ts
packages/xdl/src/UrlUtils.ts

- When the `--no-bundler` flag is used, the global linking settings aren't set, and then linking gets the wrong URL.
- Split from https://github.com/expo/expo-cli/pull/3856
- Deleted deprecated functions.
- `expo run:ios --no-bundler` should open in-app and not in Expo Go.

[expo-cli][run] Fix linking issues

---

packages/expo-cli/src/commands/upgradeAsync.ts

These questions during `expo upgrade` were made before we checked the Expo Go version when loading the app. This is a proposal to remove these questions, to make upgrade ask less questions to the user.
These prompts helps users to get the right version of Expo Go:
Android | iOS
--- | ---
This is just a cleanup, no new code added.

[cli] Remove prompts to install Expo Go on upgrade

---

packages/config-plugins/src/Plugin.types.ts
packages/config-plugins/src/index.ts
packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/plugins/createBaseMod.ts
packages/config-plugins/src/plugins/mod-compiler.ts
packages/config-plugins/src/plugins/withAndroidBaseMods.ts
packages/config-plugins/src/plugins/withIosBaseMods.ts
packages/config-plugins/src/plugins/withMod.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap

Follow up: https://github.com/expo/expo-cli/pull/3839#issuecomment-920415032
- Added static mod property `isIntrospectCapable` which will prevent a base mod from being removed during introspection.
- Combined introspection providers with regular providers for a more unified interface, and as a way to test the public interface for introspection providers.
- Exposed `BaseMods.provider` helper and `BaseMods.withGeneratedBaseMods` so users could create their own base mods locally and add them to the compiler sequence.
- Existing tests
- Locally using:
```ts
import {
ConfigPlugin,
IOSConfig,
Mod,
withMod,
BaseMods,
} from "../../cli/packages/config-plugins/build/index";
import fs from "fs";
export function withCustomBaseMods(config) {
return …
```

[config plugins] extend base mods

---

packages/xdl/src/ProjectAssets.ts
packages/xdl/src/start/ExpoUpdatesManifestHandler.ts
packages/xdl/src/start/__tests__/ExpoUpdatesManifestHandler-test.ts

Assets in the manifest are only used in production as far as I understand. In development, these don't matter (the bundler creates a map and serves and uses them).
This also fixes the issue I created by trying to use the new asset format for local development manifest assets (splash screen URL for example). I was planning to try to use a new augmented format in the manifest for these, but it is far easier to just reuse the `${field}Url` augmentation pattern from legacy manifests since all the client libraries are already looking for this field.
Revert the asset portion of https://github.com/expo/expo-cli/commit/d8eb71f0d778514349f43d78829d635fbb68f7be and replace it with a) an empty manifest.assets array, and b) the same logic as is used in classic manifests for local development.
1. …

[xdl] Fix expo-updates EAS manifest assets for iOS

---

packages/expo-cli/src/commands/run/ios/IOSDeploy.ts
packages/expo-cli/src/commands/run/ios/installOnDeviceAsync.ts
packages/expo-cli/src/commands/run/ios/resolveDeviceAsync.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/xdl/LICENSE-third-party
packages/xdl/package.json
packages/xdl/src/SimControl.ts
packages/xdl/src/apple/AppleDevice.ts
packages/xdl/src/apple/native-run/ios/lib/client/afc.ts
packages/xdl/src/apple/native-run/ios/lib/client/client.ts
packages/xdl/src/apple/native-run/ios/lib/client/debugserver.ts
packages/xdl/src/apple/native-run/ios/lib/client/index.ts
packages/xdl/src/apple/native-run/ios/lib/client/installation_proxy.ts
packages/xdl/src/apple/native-run/ios/lib/client/lockdownd.ts
packages/xdl/src/apple/native-run/ios/lib/client/mobile_image_mounter.ts
packages/xdl/src/apple/native-run/ios/lib/client/usbmuxd.ts
packages/xdl/src/apple/native-run/ios/lib/index.ts
packages/xdl/src/apple/native-run/ios/lib/lib-errors.ts
packages/xdl/src/apple/native-run/ios/lib/manager.ts
packages/xdl/src/apple/native-run/ios/lib/protocol/afc.ts
packages/xdl/src/apple/native-run/ios/lib/protocol/gdb.ts
packages/xdl/src/apple/native-run/ios/lib/protocol/index.ts
packages/xdl/src/apple/native-run/ios/lib/protocol/lockdown.ts
packages/xdl/src/apple/native-run/ios/lib/protocol/protocol.ts
packages/xdl/src/apple/native-run/ios/lib/protocol/usbmux.ts
packages/xdl/src/apple/native-run/ios/utils/xcode.ts
packages/xdl/src/apple/native-run/utils/process.ts
packages/xdl/src/index.ts
packages/xdl/src/internal.ts
yarn.lock

To install `.app` binaries on connected iOS devices, we currently use the package `ios-deploy`, which the user must globally install before running. This new approach is pure JS and substantially faster, it's unclear how long it will last, Apple could change the underlying API, but then `ios-deploy` would probably have the same issue.
To list connected devices (required for `expo run:ios -d`) we use xctrace, which doesn't have a very reliable system for finding connected devices (https://github.com/expo/expo-cli/issues/3843). xctrace is also very slow, it takes about two seconds on fast computers, and the time varies unreliably, I've also observed that around iOS updates, xctrace can sometimes not detect the connected device unless the computer is also up to date. The new JS approach has …

[expo-cli][run:ios] JS API for iOS binary install, and connected devices

---

packages/metro-config/package.json
packages/metro-config/src/ExpoMetroConfig.ts
packages/metro-config/src/importMetroFromProject.ts
packages/metro-config/src/transformer/__tests__/createMatcher-test.ts
packages/metro-config/src/transformer/createExoticTransformer.ts
packages/metro-config/src/transformer/createMatcher.ts
packages/metro-config/src/transformer/generateFunctionMap.ts
packages/metro-config/src/transformer/getBabelConfig.ts
packages/metro-config/src/transformer/getCacheKey.ts
packages/metro-config/src/transformer/metro-expo-babel-transformer.ts
packages/metro-config/src/transformer/metro-expo-exotic-babel-transformer.ts
packages/xdl/src/logs/PackagerLogsStream.ts
ts-declarations/metro-babel-transformer/index.d.ts
ts-declarations/metro-source-map/index.d.ts
yarn.lock

Create an interface for Metro to transform babel like Webpack does. Instead of running a single babel preset against all files, we now have an array of loader rules which parses some files faster than others. This system enables users to have all the same customization as before, and rewards projects that pre-transpile their JS code. 
The API also surfaces helper functions so projects can extend the system locally to fit their needs. For now, we'll be rolling it out behind a feature flag name `EXPO_USE_EXOTIC`. 
When exotic is enabled:
- remove react-native resolver field
- add cjs to the src extensions
- use a custom transformer which parses:
- bob modules with passthrough.
- expo, react-native, and known community modules with sucrase.
- all remaining modules with passthrough.
- and all …

[metro-config] Added improved babel loading

---

packages/expo-cli/src/utils/ora.ts

ora.complete is not changing the message.
`expo prebuild -p ios` should log correctly:
```
✔ Updated package.json and added index.js entry point for iOS and Android
🧶 Using Yarn to install packages. Pass --npm to use npm instead.
✔ Installed JavaScript dependencies 1559ms
✔ Config synced
✔ Installed pods and initialized Xcode workspace.
```

Fix loader bug

---

packages/expo-cli/src/commands/__tests__/upgrade-test.ts
packages/expo-cli/src/commands/upgradeAsync.ts
packages/xdl/src/project/Doctor.ts

Close [ENG-1900](https://linear.app/expo/issue/ENG-1900/remove-forked-react-native-for-managed-apps)
- `expo doctor` supports to check react-native version satisfying to sdk's `facebookReactNativeVersion`
- `expo upgrade` will use `facebookReactNativeVersion` version in managed apps
```sh
$ expo init exmanaged # select managed blank
$ cd exmanaged
$ expo doctor
$ yarn add 'react-native@0.63.4'
$ expo doctor
$ yarn add 'react-native@~0.59.0'
$ expo doctor
```
```
PASS   expo-cli  src/commands/__tests__/upgrade-test.ts
getDependenciesFromBundledNativeModules
react-native
✓ upgrades react-native to fb version in sdk < 43.0.0 bare workflow
✓ upgrades react-native to expo fork in sdk < 43.0.0 managed workflow
✓ upgrades react-native to fb version in bare workflow
✓ upgrades react-native to fb …
```

[expo-cli][xdl] Remove expo forked react-native from managed apps 

---

packages/pod-install/README.md

Refs #2461 
Since the PR above the `pod-install` package will also check the `macos` directory for the Xcode project, but the information was missing in the Readme file.
Add information that also `macos` directory is checked. Feel free to suggest grammar corrections if needed. 😉 
N/A

[pod-install] mention `macos` directory in Readme

---

packages/expo-cli/src/exp.ts
packages/xdl/package.json
packages/xdl/src/Analytics.ts
yarn.lock

Updates the analytics client to the latest version. Will reduce the size and remove unneeded dependencies.
Patched the npm package. Made small adjustments to code around the new async flush.
Ensured analytics events are still being sent by running locally.

[xdl][expo-cli] Bump @expo/rudder-sdk-node

---

packages/expo-cli/src/commands/start/startAsync.ts

The `dev client start command` analytics event should, per spec, never include the `platform` property, which is only used in events triggered by `expo run:ios` and `expo run:android` commands, where we know the platform.
🤷‍♂️ 
N/A

Remove incorrect platform from 'dev client start command' event

---

packages/expo-cli/__mocks__/resolve-from.js
packages/expo-cli/src/commands/utils/__tests__/validateDependenciesVersions-test.ts
packages/expo-cli/src/commands/utils/validateDependenciesVersions.ts

Fixes #3781 
Firebase JS SDK v9 uses a [new "exports" system](https://nodejs.org/api/modules.html#modules_exports) that defines all importable modules from this package. Right now, we don't support this when detecting the versions of installed libraries. It results in weird errors like #3781:
> "firebase" is added as a dependency in your project's package.json but it doesn't seem to be installed. Please run "yarn" or "npm install" to fix this issue.
This is a wacky-workaround to extract the path from [the "ERR_PACKAGE_PATH_NOT_EXPORTED" error](https://nodejs.org/api/errors.html#errors_err_package_path_not_exported), thrown by Node. It can have two different formats:
<details>
<summary><code>$ node -e "require.resolve('firebase')"</code></summary>
<pre>
> Error …

[expo-cli] Add version check fallback for packages with exports

---

packages/metro-config/src/transformer/getBabelConfig.ts

Project `babel.config.js` was being ignored in exotic mode.

[metro-config][exotic] Fix bug preventing babel.config.js from being used

---

packages/dev-server/package.json
packages/dev-server/src/JsInspector.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/xdl/src/start/startAsync.ts

this pr addresses an unfriendly experience on macos. chrome does not exit process even all windows be closed. with the following steps, press `j` to open inspector will nothing happen.
1. press j in expo-cli terminal ui to open inspector
2. press cmd-w in the inspector to close the window
3. press j in terminal ui again. nothing will happen because the previous process is still alive.
1. add a `Opening JavaScript inspector in the browser...` message
2. specific on macos, use `spawn` to control process lifecycle. when pressing j to open inspector, we try to kill previous process if needed.
1. press j multiple times and see if previous inspector process be killed.
2. ctrl-c to stop server and see if inspector process be killed.
3. press j to open inspector on ubuntu host. this makes sure …

[dev-server] Enhance hermes inspector opening experience

---

packages/expo-cli/package.json
yarn.lock

Adds support for the new recursive pod logging
https://github.com/expo/third-party/commit/b5a71125709afc5efd9b62725feab8ef600458ac
`expo run:ios` should now associate more operations with node modules.

Bump @expo/xcpretty@4.0.0

---

packages/expo-cli/src/commands/eject/updatePackageJson.ts

It's pretty stable and users who are used to expo managed may find it confusing when features like auto TypeScript don't work.
- potential fix for https://github.com/expo/expo-cli/issues/3962

Use expo start --dev-client instead of react-native start

---

packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/InterfaceBuilder.ts

- Even though this isn't needed, fix for convenience https://github.com/expo/expo-cli/issues/3961
- Also found unlinked npm package uuid.
- IDs remain the same between updates

[prebuild-config] Preserve splash ids

---

packages/config-plugins/README.md
packages/config-plugins/src/plugins/withStaticPlugin.ts

Make it easier to test plugins like `expo-splash-screen` which probably already have a versioned copy installed.
Add `EXPO_USE_UNVERSIONED_PLUGINS` which skips plugin resolution for unversioned plugins.
```
EXPO_USE_UNVERSIONED_PLUGINS=1 expo config --type introspect
```

Add environment variable for forcing the use of unversioned config plugins

---

packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/__tests__/withAndroidSplashImages-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withAndroidSplashImages.ts
packages/prebuild-config/src/plugins/unversioned/expo-splash-screen/withIosSplashAssets.ts

We already use `generateImageAsync` for all other image related plugins. This will help us ensure that we support the same types of image references everywhere. The system also reduces the image size a bit when sharp is installed.
- Jimp `EXPO_IMAGE_UTILS_NO_SHARP=1 expod prebuild --no-install`
- Sharp `expod prebuild --no-install`

[prebuild-config] Add url support for splash screens

---

packages/expo-cli/src/commands/start/TerminalUI.ts

Follow up to https://github.com/expo/expo-cli/pull/3207 (9 months ago).
Dev Tools UI has race conditions and many other issues where it hasn't kept up with Expo CLI / Terminal UI and therefore is not the most optimal thing for new users to see.
We added a PR a while ago to persist the user's current preference so this PR should only effect first time users.
- My current setting should continue to work.
- Deleting `~/.expo/state.json` and rerunning `expo start` should not open the dev tools UI.

[expo-cli] Skip showing dev tools UI on startup for new users

---

packages/config-plugins/src/android/Package.ts
packages/config-plugins/src/ios/Maps.ts
packages/config-plugins/src/ios/Permissions.ts
packages/config-plugins/src/plugins/createBaseMod.ts
packages/config-plugins/src/plugins/mod-compiler.ts
packages/expo-cli/src/commands/config/configAsync.ts
packages/expo-cli/src/commands/eject/configureProjectAsync.ts
packages/prebuild-config/src/getPrebuildConfig.ts
packages/prebuild-config/src/index.ts
packages/prebuild-config/src/plugins/unversioned/createLegacyPlugin.ts
packages/prebuild-config/src/plugins/unversioned/react-native-maps.ts
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

- Split out of https://github.com/expo/expo-cli/pull/3926
- Many of the changes in the autolinking PR are general fixes and improvements, merging these ahead of time to make the autolinking PR simpler.
- This PR includes a breaking change for `@expo/prebuild-config` by changing the main exported function to async.

Fixes from autolinking PR

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/exp.ts
packages/expo-cli/src/utils/handleErrors.ts

Metro now hijacks the unhandled errors which overwrites our unhandled error behavior, this causes the Terminal UI errors to be formatted poorly.
This PR extracts the error handling code and applies it to TerminalUI.
Break `Android.ts`:
```diff
- if (!allDevices.length) {
+ if (allDevices.length) { 
```
Then run `expo start` and press `a` at the Terminal UI, the formatting should be fixed and not mention hermes.

[expo-cli] Handle unhandled errors from Terminal UI

---

packages/config-plugins/src/ios/Entitlements.ts

Fixes https://github.com/expo/eas-cli/issues/496
Surround entitlements path with double-quotes.
Followed the repro steps from https://github.com/expo/eas-cli/issues/496#issuecomment-969438233

[config-plugins] fix setting CODE_SIGN_ENTITLEMENTS

---

packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap
packages/prebuild-config/src/plugins/unversioned/expo-system-ui/__tests__/withIosRootViewBackgroundColor-test.ts
packages/prebuild-config/src/plugins/unversioned/expo-system-ui/withIosRootViewBackgroundColor.ts

We moved the background color logic out of the template and into the `expo-system-ui` module, which means users will now need to install that module when the backgroundColor is defined.
- https://github.com/expo/expo/pull/15213
- https://github.com/expo/expo/pull/15146

[prebuild-config] Added warning for using backgroundColor on iOS

---

packages/expo-cli/src/commands/run/ios/XcodeBuild.ts

Now that the formatter can be used as a standalone tool, we don't really need the markdown file reporting of xcodebuild logs. xcodebuild logs are also pretty big and take up a lot of space, this will reduce the size by half.
We'll now export:
- `.expo/xcodebuild.log`
- `.expo/xcodebuild-error.log`
In the future this may change to be `.expo/ios/run/date-id/`

[expo run:ios] Don't export logs as markdown

---

packages/prebuild-config/package.json

```
[stderr] [01:45:18] [ios.xcodeproj]: withIosXcodeprojBaseMod: (intermediate value).parseStringPromise is not a function
[stderr] [01:45:18] TypeError: [ios.xcodeproj]: withIosXcodeprojBaseMod: (intermediate value).parseStringPromise is not a function
[stderr]     at createTemplateSplashScreenAsync (/usr/local/eas-build-worker/node_modules/@expo/prebuild-config/src/plugins/unversioned/expo-splash-screen/InterfaceBuilder.ts:327:29)
[stderr]     at getSplashStoryboardContentsAsync (/usr/local/eas-build-worker/node_modules/@expo/prebuild-config/src/plugins/unversioned/expo-splash-screen/withIosSplashXcodeProject.ts:74:19)
[stderr]     at setSplashStoryboardAsync (/usr/local/eas-build-worker/node_modules/@expo/prebuild-config/src/plugins/unversioned/expo-splash-screen/withIosSplashXcodeProj …
```

[prebuild-config] add missing dependency

---

packages/xdl/src/EmbeddedAssets.ts

Expo FYI links should be without md extension, it's added by the redirect.
See https://github.com/expo/expo-fyi/pull/1
Removed md extension
Try opening fixed link.

[xdl] Remove md extension from expo updates config fyi link

---

packages/expo-cli/src/commands/publish/publish.ts

Move `publish` out of "core" (top of `expo --help`) and down to the "publish" group:
This is part of an effort to divide the EAS commands from the versioned commands.

[expo-cli] Move publish command to the publish help group

---

packages/expo-cli/src/commands/run/index.ts
packages/expo-cli/src/commands/run/ios/XcodeBuild.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts

Good for testing profiling. Split out of #3970 
`expo run:ios --no-build-cache`

[expo-cli] Add --no-build-cache to clear the derived data folder for ios builds

---

packages/install-expo-modules/src/plugins/android/withAndroidModules.ts

aligned template change in https://github.com/expo/expo/pull/15109
passing rootDir to `execute()`
verify class react-native project with install-expo-modules

[install-expo-modules] Fix workspace support

---

packages/expo-cli/package.json
yarn.lock

- Adds support for formatting hermes logs
- Adds support for architecture warning

Bump @expo/xcpretty

---

packages/xdl/package.json
yarn.lock

There was a [bug](https://github.com/expo/rudder-sdk-node/pull/30) where flushing an empty queue would clobber some flush state. This caused subsequent flushes to return an outdated nullResponse.
Bumped to the newest rudder client which included a fix
Ran some commands and saw events made it to the backend

[xdl] bumps rudder sdk version

---

packages/config-plugins/src/android/Updates.ts
packages/config-plugins/src/ios/Updates.ts
packages/config-plugins/src/utils/Updates.ts

We want to export `getRuntimeVersionNullable` for use in cases such as: https://github.com/expo/eas-cli/pull/785
Consolidate `getRuntimeVersionNullable` to make it more generally applicable.
inspect

[config-plugins] consolidate getRuntimeVersionNullable

---

packages/expo-cli/e2e/__tests__/init-test.ts
packages/expo-cli/src/commands/initAsync.ts
packages/expo-cli/src/commands/utils/CreateApp.ts

This pull request resolves the following issue:
https://github.com/expo/expo-cli/issues/3979
If project names such as `react-native` or `expo` is fed to the command  `expo init <project_name>`, it leads to the project being correctly initialized however crashing upon starting up. These edge cases should be caught and handled. 
There is an array of blacklisted project names. Upon initializing the project, it is checked if the project name is included in this array. If so, the user is stopped from creating the project with that name.  
Here is how the result looks like:
For testing using the command line simply run `node ./packages/expo-cli/bin/expo.js init react` and the error should pop up. Make sure the project is built and running in the background using `yarn build` and `yarn start` …

Forbidden project names

---

packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap
packages/prebuild-config/src/plugins/unversioned/expo-apple-authentication.ts

Recommend installing `expo-apple-authentication` instead of using unversioned setup for apple authentication.
Warn when users enable `ios.usesAppleSignIn` and don't have `expo-apple-authentication` installed.

[prebuild-config] Drop unversioned apple authentication support

---

packages/prebuild-config/src/plugins/unversioned/__tests__/createLegacyPlugin-test.ts
packages/prebuild-config/src/plugins/unversioned/createLegacyPlugin.ts

fix regression introduced in https://github.com/expo/expo-cli/pull/3993 causing https://github.com/expo/eas-cli/issues/804 to break.
- `expo config --type introspect` in a project with `expo-apple-authentication` installed.

[prebuild-config] Fix autolinking issue

---

packages/config-plugins/src/ios/ProvisioningProfile.ts
packages/config-plugins/src/ios/__tests__/ProvisioningProfile-test.ts
packages/config-plugins/src/ios/__tests__/__snapshots__/ProvisioningProfile-test.ts.snap
packages/expo-cli/src/commands/run/ios/developmentCodeSigning.ts

[Reported on discord](https://discord.com/channels/695411232856997968/809586753719238656/914984858592354335). The build fails if the Team ID or DevelopmentTeam has a space inside.

Ensure TeamID has quotes around it

---

packages/config-plugins/package.json

`@expo/sdk-runtime-version` is used here: https://github.com/expo/expo-cli/blob/main/packages/config-plugins/src/utils/Updates.ts#L2
But was missing from our dependencies.

[config-plugins] add missing sdk-runtime-versions dep

---

packages/config-plugins/src/ios/BundleIdentifier.ts
packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/__tests__/Target-test.ts
packages/config-plugins/src/ios/__tests__/fixtures/watch.pbxproj
packages/config-plugins/src/ios/__tests__/fixtures/watch.xcscheme
packages/config-plugins/src/ios/utils/__tests__/string-test.ts
packages/config-plugins/src/ios/utils/string.ts

Part of the fix for https://github.com/expo/eas-cli/issues/795
Projects with a watch application have a watch extension that is associated with the watch application. We don't read dependency dependencies when resolving the application target.
Resolve dependency dependencies.
Added tests.

[config-plugins] fix reading target dependencies

---

packages/config-plugins/src/android/IntentFilters.ts
packages/config-plugins/src/android/Manifest.ts
packages/config-plugins/src/android/__tests__/IntentFilters-test.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap

intent filters stack up on subsequent runs of `expo prebuild` (not recommended). This PR adds a tag to the generated intent-filters so we can safely remove them on subsequent runs.
Also fixes https://github.com/expo/eas-cli/issues/558 by adding support for multiple intent filters. The old syntax appears to have only parsed the first filter. ENG-2572
- `expo run:android` and `expo run:android --variant release` to ensure the tags are accepted by Gradle.
- Added improved unit tests to support testing for removing filters and adding multiple filters.

[config-plugins] Automatically remove auto generated intent filters

---

packages/config-plugins/src/android/Updates.ts
packages/config-plugins/src/android/__tests__/Updates-test.ts
packages/config-plugins/src/ios/Updates.ts
packages/config-plugins/src/ios/__tests__/Updates-test.ts
packages/config-plugins/src/utils/Updates.ts

expo-updates 0.11.x will have a new native config setting that better matches the description & intended behavior of app.json's `updates.checkAutomatically: 'ON_ERROR_RECOVERY'` (which previously was only implemented in Expo Go-derived shell apps). We should map to this new config setting when it's available.
Read expo-updates version number from package.json, and if it can be found and is >= 0.11.0, then use the new native setting; otherwise, default to the old `NEVER` setting (which doesn't have a perfect analog in app.json).
Added a few test cases, all pass. Also tested manually with `expo prebuild --clean --no-install` / local `@expo/config-plugins`:
✅ expo-updates@0.10.15 `checkAutomatically: 'ON_ERROR_RECOVERY'` -> `NEVER`
✅ expo-updates@0.11.0 `checkAutomatically: …

[config-plugins] use new error recovery setting in config plugin for updates 0.11.x

---

packages/expo-cli/src/commands/info/upgradeAsync.ts

Fixes #3919
The upgrade command doesn't upgrade the `expo` package during prerelease. It's disabled to avoid some issues at react-navigation (cc @satya164, do you know which one and/or if we can remove this check all together?). But, doing this causes issues like #3919. 
We could also remove the check, but I don't want to break the react-navigation repo. It would help installing newer patch versions though, these aren't installed atm.
This adds an exception to that rule when the installed `expo` package is a prerelease (e.g. alpha/beta/rc versions).
Upgrading from `expo@43.0.0-beta.3` | Upgrading from `expo@43.0.0`
--- | ---
- Initialize a new project
- Use the prerelease `expo` version
- Run `expo upgrade`
- This should always reinstall `expo`, using the newer prerelease or stable …

[expo-cli] Always upgrade expo package when prereleased

---

packages/expo-cli/src/commands/start/startAsync.ts
packages/xdl/src/Android.ts
packages/xdl/src/Simulator.ts
packages/xdl/src/UrlUtils.ts
packages/xdl/src/index.ts
packages/xdl/src/start/LoadingPageHandler.ts
packages/xdl/static/loading-page/index.html

Closes ENG-2268.
- Added a listener that triggers every time user selects something on the interstitial page.
- Pipe `platform` value through interstitial page to obtain it in the listener. 
I couldn't verify if the events are sent, but I replaced them with console logs. Everything seems to work.

[interstitial] Capture analytics event when user selects "custom client"

---

packages/expo-cli/src/commands/start/parseStartOptions.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/start/startDevServerAsync.ts

Inspired by https://github.com/expo/expo-cli/pull/3890. Closes ENG-2607.
If a developer has an `updates.url` that matches "https://u.expo.dev" or "https://staging-u.expo.dev", and they also have not specified a `--force-manifest-type` flag when running `expo start`, we should serve the modern manifest format.
This makes is so that developers previewing EAS Update do not have to run `expo start --force-manifest-type=expo-updates` when running their project locally.
Removes logic that detected the presence of a project id, and adds logic to choose the `"expo-updates"` format when no format is present and the URL matches the EAS Update URL pattern.
Make sure that you can run:
- `expo start --force-manifest-type=expo-updates` and that you get the new manifest format
- `expo start …

[expo-cli] Server modern manifest type with EAS Update updates.url

---

packages/expo-cli/src/commands/eject/__tests__/updatePackageJson-test.ts
packages/expo-cli/src/commands/eject/updatePackageJson.ts

`expo-updates` was removed as default dependency in bare template, there's a side effect of `expo prebuild` in managed projects where `expo-updates` will be removed after prebuilding.
the required packages should also be listed in template dependencies.
```
PASS   expo-cli  src/commands/eject/__tests__/updatePackageJson-test.ts
updatePackageJSONDependencies
✓ default bahaviour (398 ms)
✓ with skipDependencyUpdate (1 ms)
✓ test expo-updates not required by default in sdk 44
```
1. `expo init -t blank@sdk-44 sdk44`
2. `expo install expo-updates`
3. `expo prebuild`
3. `ls node_modules/expo-updates`

[cli] prebuild should keep expo-updates package in sdk 44

---

packages/next-adapter/src/withExpo.ts

I was working on the `with-nextjs` Expo example update to use Next 10+, when I spotted that besides Next was using Webpack 4 for the compilation, Next was failing with an Internal Error pointing out to the code guarded by `isWebpack5` flag.
After an investigation in code, it looks like the `webpack5` flag was set incorrectly a level up, in `next-adapter`, when there was no `webpack5` entry in `args`.
This small change fixes the incorrect Webpack 5 detection and allows in the future update of `with-nextjs` example (after the new version of package including fix will be released).
I have init app using `npx create-react-native-app -t with-nextjs`, bumped the Next dependency to `~10.2.3` and `next-adapter` to latest version, then I have copied in the updated build files of `next-adapter` to …

[next-adapter] fix incorrect detection of webpack 5

---

packages/prebuild-config/src/getAutolinkedPackages.ts

`expo-dev-client` doesn't use our own tooling so we need to add a permanent unversioned workaround to make it linked even if the package isn't installed. This will break monorepo support when one app has dev client but another doesn't.

Force link expo-dev-client

---

packages/config-plugins/src/android/Manifest.ts
packages/config-plugins/src/android/__tests__/Manifest-test.ts

Better support updates code which uses config plugins to partially configure projects https://github.com/expo/expo-cli/issues/3971#issuecomment-970732766
Check if the application ends with `.MainApplication` rather than `==`
Added a test

Resolve against fully qualified MainApplications

---

packages/config-plugins/src/ios/Maps.ts
packages/config-plugins/src/ios/__tests__/Maps-test.ts
packages/config-plugins/src/ios/__tests__/__snapshots__/Maps-test.ts.snap

- `react-native-maps` doesn't use expo modules autolinking so we can't auto disable it in monorepos.
- Add dynamic pod resolution for monorepos (which won't work due to the previously mentioned autolinking issue).
- Run in a project with `expo.ios.config.googleMapsApiKey` set to some string, then `expo run:ios` and render a Google Map (not to be confused with Apple Map).

[config plugins] Fix adding Google maps pods

---

packages/schemer/src/Util.ts

This is first PR from the upcoming series in which I would like to focus on removing Lodash methods from the CLI codebase.
The idea is to keep the changeset small so the potential issues can be easily caught or even revert if needed.
Replace `fill` and `flatten` methods by the native counterparts.
`tsc` compilation and `fieldPathToSchemaPath` tests were successful.

[schemer] replace few Lodash methods with native code

---

packages/expo-cli/src/commands/build/ios/utils/image.ts
packages/expo-cli/src/credentials/api/IosApi.ts
packages/expo-cli/src/credentials/context.ts

Another PR of the Lodash removal series. This time I have converted the easy occurrences in the `expo-cli`.
Rest of the Lodash usages might need a bit more changes which will introduce small logic changes, so I left those for the separate PR in the future.
Replace some of `pick` and `forEach` usages in `expo-cli` with native code equivalents.
`yarn` and `yarn test` commands ended with a success.
`yarn lint` do not report any warnings.

[expo-cli] replace few Lodash methods with native code

---

packages/install-expo-modules/src/index.ts
packages/install-expo-modules/src/plugins/ios/__tests__/__snapshots__/withIosModulesAppDelegate-test.ts.snap
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/AppDelegate.h
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/AppDelegate.m
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/AppDelegate.swift
packages/install-expo-modules/src/plugins/ios/__tests__/withIosModulesAppDelegate-test.ts
packages/install-expo-modules/src/plugins/ios/withIosModulesAppDelegate.ts
packages/install-expo-modules/src/utils/expoVersionMappings.ts

add sdk44 support
- add `44.0.0` to supported version list and also to be default version.
- add `ExpoReactDelegate` code mod support for sdk 44. 
```
PASS   install-expo-modules  src/plugins/ios/__tests__/withIosModulesAppDelegate-test.ts
updateModulesAppDelegateObjcHeader
✓ should migrate from classic RN AppDelegate header (6 ms)
updateModulesAppDelegateObjcImpl
✓ should migrate from classic RN AppDelegate implementation (12 ms)
updateModulesAppDelegateSwift
✓ should migrate from basic RN AppDelegate.swift (1 ms)
withIosModulesAppDelegate sdkVersion snapshots
✓ sdkVersion 43.0.0 (1 ms)
✓ sdkVersion 44.0.0 (1 ms)
```
```
npx react-native init RN066 --version 0.66
npx install-expo-modules
yarn ios
```
```
npx react-native init RN066 --version 0.66
npx install-expo-modules -s 43.0.0
yarn …
```

[install-expo-modules] Add Expo SDK 44 support

---

packages/prebuild-config/package.json
yarn.lock

the version `expo-modules-autolinking@~0.4.0` is for sdk 44 beta only. since `expo-splash-screen` depends on `@expo/prebuild-config`
this will cause multiple `expo-modules-autolinking` issue.
may to fix https://forums.expo.dev/t/expo-updates-breaking-ios-build-on-sdk-44-with-yarn-2/60238
```
$ yarn why expo-modules-autolinking
├─ @expo/prebuild-config@npm:3.0.14
│  └─ expo-modules-autolinking@npm:0.4.0 (via npm:~0.4.0)
│
└─ expo@npm:44.0.0
└─ expo-modules-autolinking@npm:0.5.1 (via npm:0.5.1)
```
which break especially on yarn 2 where `expo-modules-autolinking@0.4.0` be hoisted to node_modules.
`yarn add expo-modules-autolinking@~0.5.1` which is sdk 44 official version.
`expo config --type introspect` in `expo/apps/bare-sandbox`

[prebuild-config] update expo-modules-autolinking version

---

packages/config-plugins/src/android/Updates.ts
packages/config-plugins/src/ios/Updates.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap

When a user has set the runtime version in the native config files, but not in app.json, we silently delete the runtime version when building.
This can be confusing: [(https://github.com/expo/eas-cli/issues/855)](https://github.com/expo/eas-cli/issues/855)
It seems better to throw and ask the user to specify what they want explicitly.
Since updates won't work without an sdk or runtime version defined, we should throw in this case as well.

[config-plugins] throw if there is a runtime version mismatch

---

packages/expo-optimize/src/update.ts
packages/next-adapter/src/cli/update.ts
packages/pod-install/src/update.ts
packages/pwa/src/update.ts
packages/uri-scheme/src/update.ts

Yarn CLI has a lot of issues installing modules globally. This PR removes the prompt to globally install tools with `yarn global add` and instead just always uses `npm i -g`.

Remove all `yarn global add X` prompts

---

packages/install-expo-modules/src/plugins/ios/__tests__/__snapshots__/withIosModulesPodfile-test.ts.snap
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/Podfile
packages/install-expo-modules/src/plugins/ios/__tests__/withIosModulesPodfile-test.ts
packages/install-expo-modules/src/plugins/ios/withIosModulesPodfile.ts

Support https://github.com/expo/expo/pull/15655
when the target installation is sdk 44 or above, insert `expo_patch_react_imports!(installer)` inside the `post_integrate do |installer|` block. if there's no existing post_integrate hook, append one right after `use_expo_modules!`
```
PASS   install-expo-modules  src/plugins/ios/__tests__/withIosModulesPodfile-test.ts
updatePodfile
✓ should support classic rn podfile (14 ms)
✓ minimum support for existing post_integrate hook (1 ms)
withIosModulesPodfile sdkVersion snapshots
✓ sdkVersion 43.0.0 (1 ms)
✓ sdkVersion 44.0.0
```

[install-expo-modules] Add expo_patch_react_imports! for sdk 44

---

packages/package-manager/src/CocoaPodsPackageManager.ts
packages/package-manager/src/__tests__/CocoaPodsPackageManager-test.ts
packages/pod-install/src/index.ts

- Resolve https://github.com/expo/expo-cli/issues/4051
When the 'silent' feature was added it broke the `output` collection of forked processes, meaning we'd match for 'pod repo update' against an empty string. This is a bit tricky since the code in Expo CLI is often silent but the usage in `npx pod-install` is verbose.
This PR also adds support for automatically running `pod update [package]` which can often be more useful than `pod repo update` since it will fix broken versions. If `pod update X` doesn't work, we'll fallback on `pod repo update` like before.
An example of this new feature working would be to open your `Podfile.lock`:
```diff
PODS:
-  - boost-for-react-native (1.63.0)
+  - boost-for-react-native (420.63.0)
- DoubleConversion (1.1.6)
- EXApplication (4.0.0):
```
Running …

Fix `pod repo update` not automatically running

---

packages/expo-cli/src/commands/auth/accounts.ts
packages/expo-cli/src/commands/eject/clearNativeFolder.ts
packages/expo-cli/src/commands/eject/createNativeProjectsFromTemplateAsync.ts
packages/expo-cli/src/commands/eject/ejectAsync.ts
packages/expo-cli/src/commands/eject/logNextSteps.ts
packages/expo-cli/src/commands/eject/prebuildAppAsync.ts
packages/expo-cli/src/commands/eject/setupWarnings.ts
packages/expo-cli/src/commands/eject/writeMetroConfig.ts
packages/expo-cli/src/commands/initAsync.ts
packages/expo-cli/src/commands/installAsync.ts
packages/expo-cli/src/commands/publish/publishAsync.ts
packages/expo-cli/src/commands/utils/CreateApp.ts
packages/expo-cli/src/commands/utils/TerminalLink.ts
packages/expo-cli/src/commands/utils/bundledNativeModules.ts
packages/expo-cli/src/commands/utils/environment.ts
packages/expo-cli/src/commands/utils/getOrPromptApplicationId.ts
packages/expo-cli/src/commands/utils/logConfigWarnings.ts
packages/expo-cli/src/commands/utils/modifyConfigAsync.ts
packages/expo-cli/src/commands/utils/sendTo.ts
packages/expo-cli/src/commands/utils/validateApplicationId.ts
packages/expo-cli/src/exp.ts

- move legacy updates check
Prepping CLI code to move into expo package.

[expo-cli] Refactor chalk imports

---

packages/plist/__tests__/build-test.ts
packages/plist/src/build.ts

https://github.com/expo/eas-cli/issues/860
```
'com.apple.developer.icloud-container-environment': undefined,
'com.apple.developer.icloud-container-identifiers': [ 'iCloud.bundle.identifier' ],
```
is serialized to 
```
<key>com.apple.developer.icloud-container-environment</key>
<key>com.apple.developer.icloud-container-identifiers</key>
<array>
<string>iCloud.bundle.identifier</string>
</array>
```
build does not fail, but error `Unexpected key "com.apple.developer.icloud-container-identifiers" while parsing <dict/>.` is displayed
I did not find any documentation that clarifies if this is valid format for plist, but based on the error at least fastlane does not allow it
skip key if undefined
run prebuild

[plist] Skip plist keys if value is undefined

---

CHANGELOG.md
packages/xdl/src/ProjectAssets.ts
packages/xdl/src/detach/AssetBundle.ts

This PR swaps out the hard coded `d1wp6m56sqw74a.cloudfront.net` cdn with `classic-assets.eascdn.net`
Replacing domains will help us gradually shift traffic away from CloudFront to Cloudflare if we wanted to. However, we make assumptions, including in shipped client code in end-user apps, about https://d1wp6m56sqw74a.cloudfront.net.

[xdl] switch cloudfront domain to classic-assets.eascdn.net

---

packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts

Expo CLI used to persist options across runs, for example:
1. `expo start` app starts in dev mode.
2. `expo start --no-dev` app starts in prod mode.
3. `expo start` app starts in prod mode again.
As a result, we needed to add a bunch of redundant flags to reset the persisted settings. This was a bit unfortunate for DX so we removed persistence when adding web support, now we're deprecating the unused flags. We can remove them in the future when migrating to `npx expo start`.
- Partially resolves ENG-2759
- `expo start --no-https --no-minify --dev` same with `expo web` and `expo start:web`
- `expo start -h`

[expo-cli] deprecate unused `expo start` options

---

CHANGELOG.md
packages/expo-cli/src/commands/auth/accounts.ts
packages/expo-cli/src/commands/auth/logoutAsync.ts

Resolves #4050.
> When you use 'logout of all sessions' in the web UI, the next time you try to login (or logout), you get a warning message that you need to be logged in.
The user retrieval already provided a silent switch, used for the `whoami` command. The same logic applies to `login` and `logout`, so I used the same switch.
Manually tested.

[expo-cli] suppress unauthorized warning on login and logout after logging out of all sessions on website

---

lerna.json
package.json
yarn.lock

During development, `lerna` threw 2 warnings:
```
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in a future major release, please use the JS API instead.
```
and
```
lerna WARN project Deprecated key "commands" found in lerna.json
lerna WARN project Please update "commands" => "command"
```
- A more recent version of `lerna` bumped their `yargs` dependency and config, making the warning go away. I stayed with 3.x to minimize possible side effects.
- I followed the recommendation for the deprecated key by simply renaming it 
Ran a clean dev env setup from scratch locally with these changes applied, and everything still works.

[workspace] chore: lerna version bump and config update

---

packages/install-expo-modules/src/index.ts

fix #4125
`yarn add expo@">=44.0.0-* <45.0.0"` is an invalid command for yarn 2. i did that because i want to support pre-release package installation. however, `*` is also an invalid pre-release name; that's why yarn 2 doesn't support it.
```
<pre-release identifier> ::= <alphanumeric identifier>
| <numeric identifier>
```
the pr changes the installation command to `yarn add expo@">=44.0.0-0 <45.0.0"` for the issue.
```sh
$ npx react-native init RN066 --version 0.66
$ yarn add expo@">=44.0.0-0 <45.0.0"
$ yarn why expo
```
```sh
$ npx react-native init RN066 --version 0.66
$ yarn set version berry
$ yarn add expo@">=44.0.0-0 <45.0.0"
$ yarn why expo
```

[install-expo-modules] Fix invalid installation for yarn 2

---

packages/expo-cli/src/commands/initAsync.ts

- Remove flags from git init function since it's only used once.
- Provide better logs.
- Auto skip git init in a git repo to better support monorepos. It's easy enough to manually set one up later.
- Feature split out of https://github.com/expo/expo-cli/pull/4088
- `expo init my-app && cd my-app && expo init inner-app` -- `my-app/inner-app/.git` won't exist.

[cli][init] Skip git init in monorepo

---

packages/xdl/src/Simulator.ts
packages/xdl/src/UrlUtils.ts
packages/xdl/src/start/ngrok.ts
packages/xdl/src/start/resolveNgrok.ts
packages/xdl/src/start/startAsync.ts

- Fix "pressing `i` in TerminalUI doesn't open ngrok URL".
- Prevent opening multiple ngrok servers when the new dev server API is in use.
- Fix "Tunnel URL not found (it might not be ready yet), falling back to LAN URL." warning on `rm -rf .expo && expo start --tunnel`
- Add better inline documentation about what's going on.
- `rm -rf .expo && expo start --tunnel` then open on iOS and Android.
- Ensure Android doesn't crash (possible when port is missing).
- Ensure iOS opens using ngrok URL and not localhost URL.

[xdl] Fix various ngrok bugs

---

packages/install-expo-modules/src/plugins/ios/__tests__/__snapshots__/withIosModulesPodfile-test.ts.snap
packages/install-expo-modules/src/plugins/ios/__tests__/withIosModulesPodfile-test.ts
packages/install-expo-modules/src/plugins/ios/withIosModulesPodfile.ts

sync to latest sdk-44 template
https://github.com/expo/expo/blob/fadd71f60b8b429e6602bcb33ee57fb66f07bdc6/templates/expo-template-bare-minimum/ios/Podfile#L41-L47
add begin-rescue block
```
updatePodfile
✓ should support classic rn podfile (12 ms)
✓ minimum support for existing post_integrate hook
withIosModulesPodfile sdkVersion snapshots
✓ sdkVersion 43.0.0 (1 ms)
✓ sdkVersion 44.0.0
```

[install-expo-modules] Add begin-rescue to Podfile

---

CHANGELOG.md
packages/expo-cli/scripts/introspect.ts

The current introspection script breaks formatting when there's multiple pipe characters in the flags
Replace _all_ occurences instead of only the first. Properly escape them instead of replacing them with a less appealing unicode character.
Generated json and markdown locally to verify.

[expo-cli][docs] update broken flags in docs generation

---

packages/xdl/src/DevSession.ts
packages/xdl/src/ProjectSettings.ts
packages/xdl/src/__tests__/ProjectSettings-test.ts
packages/xdl/src/start/ManifestHandler.ts

closes ENG-1987, closes ENG-1988
In order to make it easier for dev client users to find their development sessions before logging in, we're adding an installation ID flow similar to snack's device ID flow. We generate and persist an ID on the client, and pass it to expo-cli in the first manifest request (via QR code or other method) so expo-cli can persist it locally and include it in future calls to `development-sessions/notify-alive`. This PR adds those two pieces of functionality to expo-cli.
- read a device ID from a manifest request and persist to disk (in `.expo/devices.json` as of now -- but definitely open to renaming/moving this)
- prune old IDs so there is a max of 10 persisted at any one time
- also prune any IDs that haven't been used in 30 days or longer
- start a …

[xdl] persist dev client ids locally, use to start dev sessions

---

packages/xdl/src/Analytics.ts

We'd like to remove personal data from all track calls as much as possible due to GDPR regulations.
Removed IP from the context object of the track call.
N/A

[xdl] drop IP from track context

---

CHANGELOG.md
packages/xdl/src/start/ExpoUpdatesManifestHandler.ts

Closes https://github.com/expo/expo-cli/issues/4129.
This is a leftover from https://github.com/expo/expo-cli/pull/3929.
Fix case where extra key exists but eas key does not by using conditional property access.
Same as https://github.com/expo/expo-cli/pull/3929.

[cli] fix reading EAS project ID from app.json during start

---

CHANGELOG.md
packages/expo-cli/src/commands/info/doctor/doctorAsync.ts
packages/expo-cli/src/commands/info/doctor/index.ts
packages/expo-cli/src/commands/utils/validateDependenciesVersions.ts

- https://github.com/expo/expo-cli/issues/2221
Added option to `doctor` command, internally using the `install` command for the installation.
Tested manually.

feat: new --fix-dependencies option for doctor

---

packages/pkcs12/package.json
packages/pkcs12/src/__tests__/__snapshots__/index-test.ts.snap
yarn.lock

- To fix https://github.com/expo/eas-cli/security/dependabot/yarn.lock/node-forge/open
- Generally, to keep the `node-forge` dependency up-to-date.
- Upgrade `node-forge` to the latest.
- Update test snapshot.
- Existing tests 
- I had to update the snapshot but it seems there are only some node-forge internal changes there are the update is fine.

[pkcs12] upgrade node-forge

---

packages/xdl/package.json
packages/xdl/src/ProjectSettings.ts
packages/xdl/src/UrlUtils.ts

https://linear.app/expo/issue/ENG-3965/replace-joi-with-regular-assertions-and-types-in-xdl
- Replaced Joi validation with equivalent checks in vanilla JS.
- Extended existing TS definitions to include missing fields.
Ran the test cases for UrlUtils to verify validation behavior hasn't changed for the described use cases.

[xdl] refactor UrlUtils to not use Joi

---

packages/config-plugins/src/ios/Scheme.ts
packages/config-plugins/src/ios/__tests__/Scheme-test.ts

- `appendScheme` insert the same schema twice if I call it twice. It should insert only once
- Exists test

[config-plugins] avoid duplicate CFBundleURLTypes

---

packages/xdl/src/Android.ts
packages/xdl/src/Env.ts
packages/xdl/src/Simulator.ts

Close ENG-2211.
Before opening a deep link to the interstitial page, we need to check if everything is installed. So I've added a logic that will install the `Expo Go` and check if the development build is available. If not we will fall back to the expo go. 
Test scenarios:
- app without dev-client 
- check if the expo go will be installed if not present 
- check what happens if the development build isn't present 
- check what happens if both development build and expo go isn't available

[Interstitial page] Ensure that development build is installed

---

CHANGELOG.md
packages/config-plugins/src/ios/ProvisioningProfile.ts
packages/config-plugins/src/ios/__tests__/ProvisioningProfile-test.ts
packages/config-plugins/src/ios/__tests__/__snapshots__/ProvisioningProfile-test.ts.snap
packages/config-plugins/src/ios/__tests__/fixtures/project-multitarget-missing-targetattributes.pbxproj

Resolves https://github.com/expo/eas-cli/issues/948.
Create target attributes object first if missing.
Added two test cases for the provisioning profile logic, one for a multitarget project with existing target attributes, and one without, and recorded snapshots to verify the functionality.

[config-plugins] handle missing targetattributes in project file when setting provisioning profile

---

packages/metro-config/package.json

It's imported here: https://github.com/expo/expo-cli/blob/34bc461a9a81bdab198e10b14d77dd0cda8d7d54/packages/metro-config/src/ExpoMetroConfig.ts#L10
But it's not included in the package.json for @expo/metro-config
May be related to https://forums.expo.dev/t/expo-environment-setup-problem/61363/9 - not clear why it's only happening to this user though.
--
--

[metro-config] Add missing resolve-from dependency

---

packages/expo-cli/src/commands/publish/publishAsync.ts

`eas branch:publish` has been renamed `eas update`

[expo-cli] update error message when publish is misconfigured

---

packages/expo-cli/src/commands/initAsync.ts
packages/expo-cli/src/commands/utils/ProjectUtils.ts

Now that expo-updates isn't required, we should skip the bare updates notice.

Skip updates warning in bare projects when expo-updates isn't in the package.json

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/xdl/src/Android.ts
packages/xdl/src/Simulator.ts
packages/xdl/src/UrlUtils.ts
packages/xdl/src/start/LoadingPageHandler.ts
packages/xdl/static/loading-page/index.html

Adjusting a couple of things according to the feedback https://www.notion.so/expo/Interstitial-page-testing-c4ee6e71e936460c8df786410d33e3fe
- Replaced the link in the warning with the new one. 
- Detected the platform from the user-agent header if the get parameter wasn't provided 
- `Development App` -> `Development Build`
- Update QR code to point to the interstitial page if needed. 
- The deep links generated by the interstitial page aren't local anymore. 
Test scenarios:
- app without dev-client
- check if the expo go will be installed if not present
- check what happens if the development build isn't present
- check what happens if both development build and expo go isn't available
- test QR code

[Interstitial page] Improving user experience

---

packages/expo-cli/src/commands/publish/publishAsync.ts

As of sdk 44 we no longer include expo-updates.
Prevent accidental publishes.
Tested in demo repo.

[expo-cli] check expo-updates is installed before a publish

---

packages/xdl/src/project/publishAsync.ts

The project page url redirects to an eas QR code.
Fix typo
navigated to page and loaded in expo-go.

[expo-cli] fix project page param typo

---

packages/expo-cli/src/commands/utils/createFileTransform.ts

Fixes regression introduced here https://github.com/expo/expo-cli/pull/4088/files#diff-380dbe5016dbdaea46a5d3b7680df2e3ece26d1f0b728044ef75467278d98664L56 that corrupts font files on initialization

[expo init] Skip parsing font files on init

---

CHANGELOG.md
packages/expo-cli/e2e/__tests__/__snapshots__/export-test.ts.snap
packages/expo-cli/src/commands/utils/__tests__/npm-test.ts
packages/expo-cli/src/commands/utils/npm.ts

Resolves https://github.com/expo/expo-cli/issues/4203.
Adjusted regular expression used to sanitize package name to allow numbers as per npm specs (https://github.com/npm/validate-npm-package-name/#naming-rules)
- Initialized a project with a number in the name
- Verified package.json to see the package name still contains the number
- Added a test case to automated tests for a package name with a number, used it to verify the old and the new behavior

[expo-cli]: don't sanitize numbers from project names for npm package name on init

---

packages/xdl/src/start/LoadingPageHandler.ts
packages/xdl/static/loading-page/index.html

Currently, if someone scans the QR code, we can't detect if the device can handle a deep link to `Expo Go` or `Development Build`. So we're trying to detect if the redirection was successful. If not we display a message. 
When the user clicks, we trigger a timeout. After some time, we check if the document became inactive (if so, we know that the redirection was successful). This flow gets more complicated on iOS because the user will see a modal. In that case, we need to fire the timeout after the document will be focused. 
- manual tests with Android device and iOS simulator.

[Interstitial page] Try to detect if a deep link succeed

---

packages/dev-tools/components/ProjectManager.js
packages/dev-tools/components/ProjectManagerSidebarOptions.js
packages/dev-tools/pages/index.js
packages/dev-tools/server/graphql/GraphQLSchema.ts
packages/xdl/src/start/LoadingPageHandler.ts
packages/xdl/static/loading-page/index.html

Fixes that QR code on web UI pointed to the `Expo Go` directly instead of to the interstitial page.
Fallback to the SDK version if the runtime version wasn't defined. 
- Extended the dev graphQL server to serve Interstitial page URL if available. 
- runs the local version of the CLI and confirms that the web QR code points to the correct place.
- checks if the SDK version was detected when the runtime version isn't available.

[Interstitial page] Fix QR on web UI & fallback to SDK version if the runtime version wasn't defined

---

packages/expo-cli/src/commands/publish/publishAsync.ts
packages/xdl/src/project/__tests__/createBundlesAsync-test.ts
packages/xdl/src/project/createBundlesAsync.ts

```
expo publish --max-workers 1
``` 
In the publish command the `max-workers` option is not being passed through to metro causing it to ignore the option and always use the default.
This is causing our CI build to run out of memory when attempting to publish even when specifying to use `--max-workers 1`
This area of the code did not appear to be tested so I took a stab at adding a test for at least part of it. Happy to add more tests or change or remove it.

[expo-cli] Publish command correctly passes max-workers option through to metro

---

packages/config-plugins/src/utils/Updates.ts
packages/config-plugins/src/utils/__tests__/Updates-test.ts
packages/xdl/src/start/ExpoUpdatesManifestHandler.ts

When running `EXPO_DEBUG=1 expo prebuild` you get an error that could be a red herring when trying to debug prebuild issues:
```
ios.expoPlist: withVersionedExpoSDKPlugins ➜ withPlugins ➜ withStaticPlugin ➜ withExpoUpdates ➜ withStaticPlugin ➜ withRunOnce ➜ withUpdates ➜ withUpdates ➜ withExpoPlist
- Config syncing
Error: There is neither a value or a policy set for the runtime version on "ios"
at getRuntimeVersion (/Users/brentvatne/code/mappy/node_modules/@expo/config-plugins/src/utils/Updates.ts:106:11)
at getRuntimeVersionNullable (/Users/brentvatne/code/mappy/node_modules/@expo/config-plugins/src/utils/Updates.ts:88:12)
at setVersionsConfig (/Users/brentvatne/code/mappy/node_modules/@expo/config-plugins/src/ios/Updates.ts:99:26)
at setUpdatesConfig …
```

[config-plugins] Don't warn in EXPO_DEBUG when runtimeVersion isn't set

---

packages/expo-cli/e2e/__tests__/init-test.ts
packages/expo-cli/e2e/__tests__/start-test.ts
packages/expo-cli/src/commands/init.ts
packages/expo-cli/src/commands/initAsync.ts
packages/expo-cli/src/exp.ts

When the `--name` parameter is used (and the CLI throws), the CLI fails with:
```
/Users/evanbacon/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/src/exp.ts:352
await handleErrorsAsync(err, { command: this.name() });
^
TypeError: this.name is not a function
at Command.<anonymous> (/Users/evanbacon/.nvm/versions/node/v16.13.0/lib/node_modules/expo-cli/src/exp.ts:352:52)
```
Commander doesn't support using the `--name` argument since it is reserved internally. We always recommend users do `expo init [my-app]` since this plays nicely with the working directory paradigm.
Also fixes the test from https://github.com/expo/expo-cli/pull/4025 which doesn't test the output at all.
- Add deprecation notice to `expo init --name` and force exit. 
- Drop the use of `--name` in the tests.
- E2E …

[expo-cli] Deprecate the `--name` argument of the init command.

---

packages/config-plugins/src/utils/XML.ts
packages/config-plugins/src/utils/__tests__/XML-test.ts

reading and writing string resources is escaping characters twice.
This is not a proper fix, the correct approach would be to remove escaping from `writeXMLAsync`, but there is probably a bunch of places that rely on this behavior.
this PR is attempting to revert changes that `escapeAndroidString` will do on write
added test
verified with local builds by applying a similar patch in eas-build code directly
https://github.com/expo/eas-build/pull/76

[config-plugins] Unescape values when reading strings.xml

---

.github/ISSUE_TEMPLATE/bug_report.yml

`expo diagnostics` is deprecated in favor of `npx expo-env-info`
Updated issue template
N/A

[chore] switch issue template to `expo-env-info`

---

packages/config-plugins/src/android/Scheme.ts
packages/config-plugins/src/android/__tests__/Scheme-test.ts
packages/config-plugins/src/android/__tests__/fixtures/react-native-AndroidManifest-with-host.xml
packages/expo-cli/src/commands/run/utils/schemes.ts

Expo CLI should pick the scheme with the empty host
or it's much exactly matched to `expo-development-client`
close https://github.com/expo/expo-cli/issues/4227
- Unittests

[expo-cli]: pick correct scheme for open android app

---

packages/config-plugins/src/ios/Google.ts
packages/config-plugins/src/ios/__tests__/Google-test.ts
packages/config-plugins/src/ios/__tests__/fixtures/GoogleService-Info.plist
packages/config-plugins/src/plugins/ios-plugins.ts

While writing a new plug-in for Google Sign In, I noticed that `ios.config.googleSignIn.reservedClientId` is used to add a new scheme to the iOS configuration.
We can do this automatically by reading the `REVERSED_CLIENT_ID` field from the `GoogleService-Info.plist` file
- Update `withGoogle` plugin to read the field from the `GoogleService-Info.plist` file.
- We still respect the old `ios.config.googleSignIn.reservedClientId` config for backward compatible.
- *Next step*: Update the Google SignIn module to remove mention about `ios.config.googleSignIn.reservedClientId`.
- Unit test

[config-plugin] append scheme REVERSED_CLIENT_ID from GoogleService-Info.plist

---

packages/config-plugins/src/ios/Maps.ts
packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/ios/__tests__/Paths-test.ts

- React Native 68 uses `AppDelegate.mm` instead of `AppDelegate.m` which means the existing prebuild check would assert that vital project files are missing and the Google Maps dangerous plugin would fail.
- Add `objcpp` which is returned when the AppDelegate file extension is `.mm`.
- In a local project, rename `AppDelegate.m` to `AppDelegate.mm` and rerun `expo prebuild -p ios --no-install` -- no error should be thrown.
- It's unclear what the new template file will look like so we don't have a continuous test in place for the Maps plugin.
- Added a FS unit test.

[config-plugins] Added support for `AppDelegate.mm`

---

packages/expo-cli/src/commands/eject/eject.ts

- Update the description to reflect that users should move to expo prebuild instead.
- We want to deprecate `expo eject` but we can do this naturally by waiting until the `expo-cli` package is deprecated in favor of `npx expo`.
- Waiting until `npx expo` is in beta ready adding a proper notice that would detect the SDK version and prompt the user to use `npx expo prebuild` instead.

[expo-cli] Move `expo eject` to the deprecated help group

---

.github/workflows/test.yml
packages/expo-cli/e2e/__tests__/__snapshots__/export-test.ts.snap

As test coverage has improved over time, and the companion repo `expo/eas-cli` has code coverage enabled as well, we should look at re-enabling it again on `expo/expo-cli` as well.
Reverted the change that was done to disable it in the past.
Not sure if GH picks up on .github changes in PRs, so here's to hoping it will run in this PR.

[test] re-enable codecov

---

CHANGELOG.md
packages/metro-config/src/ExpoMetroConfig.ts
packages/metro-config/src/__tests__/ExpoMetroConfig-test.ts

When we create update bundles, metro includes all assets necessary to run the app in its output. Part of our metro `resolver` configuration includes `assetExts` and `sourceExts`. `assetExts` are file extensions that metro will include as discreet assets alongside the JS bundles. `sourceExts` are file extensions that metro will include inside the JS bundle, inline.
I noticed that we have `json` in both `assetExts` and `sourceExts`, which means we are inlining `json` files in the main JS bundle and then including them again as discreet assets. In other words, all `json` files in update bundles are duplicated.
With EAS Update, developers often have node modules that include many `json` files (like translations etc), which we then count against our 400 asset limit. This can make it hard for …

[metro-config] Remove json assetExt

---

packages/next-adapter/package.json

Next adapter's babel plugin is out of date. I wonder if this should be a peer dependency instead to avoid clashes.
n/a
Using it in my app.

Upgrade `babel-preset-expo`

---

packages/config-plugins/src/ios/Locales.ts

Close: https://github.com/expo/expo/issues/15441
If the user run `expo prebuild -p ios` in their local and submit a new build with `eas build`. Then, the absolute path to locales files becomes wrong.
- This PR fixes the issue by using a relative path for them.

[config-plugins] use relative path for locales

---

packages/expo-cli/package.json

It doesn't work with Node 17 right now. Make this clear in `engines`.
Verified that `>=12 <=16` matches numbers like `12.4.5` and `16.1.2`.

[cli] Cap Expo CLI at Node 16

---

CHANGELOG.md
packages/expo-cli/bin/expo.js

The Node.js versions warning doesn't reflect the current version scheme (https://nodejs.org/en/about/releases/).
Changed the warning copy.
- Select different node version with `nvm`
- View warning

[cli] update supported Node version warning to reflect current LTS schema

---

packages/webpack-config/package.json

Versioned expo CLI will require webpack-dev-server to be installed in the project, adding the dependency to `@expo/webpack-config` enables us to ensure all Webpack dependencies are versioned with the config.

add webpack-dev-server dependency to expo/webpack-config

---

packages/config-plugins/__mocks__/fs/promises.ts
packages/config-plugins/package.json
packages/config-plugins/src/android/EasBuild.ts
packages/config-plugins/src/android/GoogleServices.ts
packages/config-plugins/src/android/Manifest.ts
packages/config-plugins/src/android/Package.ts
packages/config-plugins/src/android/Paths.ts
packages/config-plugins/src/android/__tests__/GoogleServices-test.ts
packages/config-plugins/src/android/__tests__/Updates-test.ts
packages/config-plugins/src/ios/BundleIdentifier.ts
packages/config-plugins/src/ios/Entitlements.ts
packages/config-plugins/src/ios/Google.ts
packages/config-plugins/src/ios/Locales.ts
packages/config-plugins/src/ios/Maps.ts
packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/ios/ProvisioningProfile.ts
packages/config-plugins/src/ios/Swift.ts
packages/config-plugins/src/ios/XcodeProjectFile.ts
packages/config-plugins/src/ios/__tests__/Entitlements-test.ts
packages/config-plugins/src/ios/__tests__/ProvisioningProfile-test.ts
packages/config-plugins/src/plugins/__tests__/android-plugins-test.ts
packages/config-plugins/src/plugins/__tests__/mod-compiler-test.ts
packages/config-plugins/src/utils/XML.ts
packages/config-plugins/src/utils/__tests__/XML-test.ts
packages/config-plugins/src/utils/__tests__/fs-test.ts
packages/config-plugins/src/utils/fs.ts

Noticing an increasing number of issues regarding `json-utils` this is due to a bug in node modules resolution where too many packages are nested in each other.
One way to mitigate the risk of this error occurring is by reducing the amount of copies of common libraries like `@expo/config-plugins` and `fs-extra`. When we migrate to the versioned CLI we should be able to reduce the copies of `@expo/config-plugins` and this PR address `fs-extra` by dropping it.
- Tests should continue to pass.
- New tests should also work.

chore(config plugins): drop fs-extra

---

packages/next-adapter/src/withExpo.ts

Quoting comment from https://github.com/expo/expo-cli/pull/4058
> This PR did the opposite of its intention and actually broke `withExpo` by causing it to default to `webpack5: undefined` instead of `webpack5: true`
> 
> The idea of the previous logic was to default to passing `webpack5: true` to `withUnimodules` if `next.config.js` had a truthy value or it wasn't declared (undefined)
> 
> It should only pass `false` to `withUnimodules` if the user explicitly set `webpack5: false` in their `next.config.js`
> 
> ```
> const webpack5 = undefined
> const previous = webpack5 !== false // previous === true
> const current = webpack5 && webpack5 !== false // current === undefined
> ```
> 
Reverting this change will fix [Issue using turborepo and …

[next-adapter] revert webpack5 detection

---

packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/ios/__tests__/Paths-test.ts

https://github.com/expo/eas-cli/issues/1033
We use `getPBXProjectPath` to detect if the project is bare or managed in eas-cli (if the file is not gitingored)
Changed the order of sort calls, I'm not sure what was the original intention but the current implementation does not make sense, the second sort would always override whatever the first one did. I'm assuming that the intention was to ensure order regardless of what glob returns.
With sort calls inverted the first sort  will order paths alphabetically and the second one will pick direct children of ios directory while still preserving alphabetical order in both groups
search files only in the ios directory
verified that `'ios/**/*.xcodeproj` is matching `ios/something.xcodeproj` in separate script
tests that verify the order of …

match `xcodeproj` in ios directory only

---

packages/xdl/src/logs/PackagerLogsStream.ts

Required for react-native 68 support [new events](https://github.com/facebook/metro/blob/4875f3df0af55f1c3e8caa7a714cd568381e4273/packages/metro/src/Bundler.js#L35-L41). Versioned CLI shouldn't have this issue since we extend all of the built-in logging. 
- Adds `transformer_load_started `, and `transformer_load_done` events -- doing nothing with them.

chore(xdl): add new metro logging events

---

.github/workflows/test_windows.yml

Windows tests are currently failing with socket timeout errors. This should fix it.
- Confirmed we are not using a proxy/vpn ([see this run](https://github.com/expo/expo-cli/runs/6026912201?check_suite_focus=true#step:4:5))
→ mentioned in yarnpkg/yarn#4890
- Adding `--network-timeout` set to 2 minutes (120 000 ms)
→ mentioned in yarnpkg/yarn#4890
- Removing `--check-files`
→ mentioned in https://github.community/t/yarn-esockettimedout-on-windows/118776/8
- See if CI passes

[ci] Set timeout to 2 minutes and remove check files on windows

---

packages/dev-server/package.json
packages/dev-server/src/MetroDevServer.ts
packages/dev-server/src/metro/importMetroFromProject.ts
packages/dev-server/src/middleware/devServerMiddleware.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts
packages/xdl/src/Webpack.ts
ts-declarations/metro/index.d.ts
yarn.lock

- React Native community CLI broke the public interface for setting up the dev server across versions. Since our implementation is global we need to support both versions. https://github.com/react-native-community/cli/pull/1560
- Replaces https://github.com/expo/expo-cli/pull/4305
- Import `@react-native-community/cli-server-api` from the project instead of vendoring. This will ensure the installed version works with the installed `metro` package.
- If `attachToServer` exists, then attach using the legacy API, otherwise use the new API.
- Sanity: I created a new React Native project using `npx react-native init`, a couple hours later I was able to run `npx react-native run-ios` then `npx react-native start` -- pressing `r` works but pressing `d` does not work.
- Test: in the new project I …

feat(dev-server): support new API for Expo SDK 45

---

packages/config-plugins/src/ios/Entitlements.ts
packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/ios/__tests__/Entitlements-test.ts
packages/config-plugins/src/ios/__tests__/fixtures/project-with-entitlements.pbxproj
packages/config-plugins/src/plugins/withIosBaseMods.ts
packages/prebuild-config/src/plugins/__tests__/withDefaultPlugins-test.ts

Pick entitlements files for specific targets based on pbxproj values, necessary to support app extensions (both for manged and bare projects)
- getEntitlementsPath does not modify or delete files anymore
- ensureApplicationTargetEntitlementsFileConfigured exists for legacy reason
- it ensures that CODE_SIGN_ENTITLEMENTS is defined for the default application target
- it ensures that the file specified by that value exists
- if CODE_SIGN_ENTITLEMENTS points to a file that does not exist new entitlements file is created in the default location and value CODE_SIGN_ENTITLEMENTS is changed
- if the entitlement file is not in the default location we are not doing anything, this is a supported case
- do not delete any entitlement files
- files should not be modified at all in introspect mode
- …

[config-plugins] resolve target specific entitlement files

---

CHANGELOG.md
packages/expo-env-info/jest.config.js
packages/expo-env-info/package.json
packages/expo-env-info/tsconfig.json
yarn.lock

More and more modules that we use in our CLI tools are moving to ESM only. Which means that in order to continue to use them, our packages _also_ need to move to ESM. @dsokal reached out to me about `eas-cli`, but it seemed like a smaller package like this would be a good test case first.
For `expo-env-info`, the only 'breaking' change is the engine specification `"node": "^12.20.0 || ^14.13.1 || >=16.0.0"`, which is slightly narrower than before, but given that we're dropping Node 12 support in expo-cli, still totally acceptable. All the other heavy lifting is taken care of by NCC/TypeScript/Jest, after properly configuring those.
All tests are passing, also ran `expo-env-info` locally.

[expo-env-info] convert expo-env-info from CJS to ESM

---

packages/config-plugins/src/ios/BuildScheme.ts
packages/config-plugins/src/ios/Target.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts

- why not
- `expo run:ios --scheme` -- this will prompt to choose any runnable scheme (which now includes app clips).

feat(config-plugins): add initial app clip support

---

packages/config-plugins/src/android/Manifest.ts
packages/config-plugins/src/android/Permissions.ts
packages/config-plugins/src/android/__tests__/Manifest-test.ts
packages/config-plugins/src/android/__tests__/Permissions-test.ts
packages/config-types/src/ExpoConfig.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap
packages/prebuild-config/src/plugins/__tests__/withDefaultPlugins-test.ts
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

- Alternative to this lazy, bloated solution: https://github.com/expo/expo-cli/pull/4322
- Implements the new schema property proposed here: https://github.com/expo/universe/pull/9504
- If the user defines `android.blockedPermissions`, then prebuild will apply the blocked permissions to the `AndroidManifest.xml`.
- Added tests.

[config plugins] support android.blockedPermissions

---

packages/config-plugins/src/android/Permissions.ts

https://github.com/expo/expo/issues/17380
[The `expo-image-picker` config plugin uses `withBlockedPermissions`](https://github.com/expo/expo/blob/091d1acebb5cdaacaf45decc1fb179ce6770d082/packages/expo-image-picker/plugin/src/withImagePicker.ts#L56-L62), but it's possible that at the time that this plugin runs the `permissions` config is empty - depending on the order the plugins are executed. So we shouldn't show this warning in this case.
Remove the warning
Make the change manually in `node_modules` and verify there is no warning in [this repro](https://github.com/expo/expo/issues/17380#issuecomment-1120195369).
Does it matter that we might have a permission listed in both the `permissions` and `blockedPermission` key? Should we update the permissions config plugin to skip adding a …

[config-plugins] Remove warning when permissions config is empty when using blockedPermissions

---

packages/create-expo-app/src/fetch.ts

Make the cache use a hidden directory in the home folder

fix(create-expo-app): use hidden directory for home cache

---

packages/package-manager/src/utils/nodeWorkspaces.ts

Object keys in js are ordered since ECMA 2015, but relying on that behavior is neither safe nor readable.
create an explicitly ordered list of package managers
tests are passing

[package-manager] explicitly order package managers

---

packages/config-plugins/src/ios/ProvisioningProfile.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts

If someone creates build configuration with space the middle e.g. `Release production` value in pbxproj will be in quotes which is not handled correctly in util functions that search for build configuration by name
trim quotes when comparing
- reproduce the issue described above (`eas build` fails with ` Error: Build configuration 'Release' does not exist in list with id '13B07F931A680F5B00A75B9A'`)
- yarn link config-plugins with above changes to eas-cli
- run build on eas (build works)

[config-plugins] Handle quoted build configuration

---

packages/config-plugins/src/android/Package.ts
packages/config-plugins/src/android/__tests__/Package-test.ts
packages/config-plugins/src/plugins/__tests__/fixtures/react-native-project.ts

react-native 0.68 added jni code in templates for new architecture support. in the jni code, there are some java descriptors mapping to java class names. e.g.:
```c++
static constexpr auto kJavaDescriptor =
"Lcom/helloworld/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate;";
```
we should also rename these descriptors. otherwise apps will crash from new architecture mode.
rename descriptors in jni folders
```sh
$ expo init -t blank sdk45
$ expo prebuild -p android # use package name other than com.sdk45
$ expo run:android
```
also tested on a sdk 44 project to make sure the pr is backward compatible.
```
PASS   @expo/config-plugins  src/android/__tests__/Package-test.ts
renameJniOnDiskForType
✓ refactors a main project (5 ms)
```

[config-plugins] rename android jni java descriptors from prebuild

---

packages/expo-cli/src/commands/utils/deprecatedExtensionWarnings.ts
packages/metro-config/src/getModulesPaths.ts
packages/metro-config/src/getWatchFolders.ts
packages/package-manager/src/utils/__tests__/nodeWorkspaces-test.ts
packages/package-manager/src/utils/nodeWorkspaces.ts
packages/webpack-config/src/env/paths.ts

- fix ENG-4914
- Added tests to the package-manager copy of the function.

fix: prevent throwing when an upper-level directory has an invalid package.json

---

packages/expo-cli/src/commands/info/doctor/doctorAsync.ts

Follow-up to https://linear.app/expo/issue/ENG-4643/improve-error-reporting-for-expo-doctor-phase
On the website, we want to make it clear to the user that the `expo doctor` returned some warnings/errors. For that, currently, I decided to detect whether `Didn't find any issues with the project` was printed. It's not perfect because it'll break when we change the log message here.
We need a deterministic way to know if `expo doctor` failed.
Set exit code to 1 if there are validation errors.
@EvanBacon do you think this is fine or you'd prefer to do sth different? If we end up not doing this (because this could break people's workflows), @wkozyra95 proposed that we could have an env var (sth like `EXPO_DOCTOR_FAIL_ON_VALIDATION_ERROR`) and we'd set the exit code only in this case.
I ran …

[expo-cli] set non-zero exit code when expo doctor fails

---

packages/package-manager/src/utils/nodeWorkspaces.ts

https://github.com/expo/eas-build/pull/96#issuecomment-1122205110
EAS Build prioritized yarn when both lockfiles existed so if we don't want to introduce breaking changes and unify the logic change has to be here
change order in which package managers are resolved
CI

[package-manager] Prefer yarn over npm if both lockfiles exists

---

packages/expo-cli/src/commands/utils/validateDependenciesVersions.ts

SDK 45 needs @expo/config-plugins@^4.1.0. Because the error when using older version is quite cryptic, an explicit warning is added to `expo doctor`
The required version is hardcoded for now. The warning doesn't show which packages actually use which versions (like npm/yarn why) because that test is complex.
Tested manually.
Combined output:
Solo output:

[expo-cli] warn for outdated `@expo/config-plugins` in deps' deps

---

packages/create-expo-app/src/Update.ts
packages/create-expo-app/src/index.ts
packages/create-expo-app/src/legacyTemplates.ts
packages/create-expo-app/src/npm.ts

- Fail faster
- Fix format
- Improve help
- Add template prompt

feat(create-expo-app): fail on invalid template before prompting for the app name

---

.github/workflows/test.yml
.github/workflows/test_windows.yml

We're dropping node 12 support and adding node 16 support.
Updated the workflow settings.
All tests should pass.

[ci/cd] Add node 16 testing and drop node 12

---

packages/create-expo-app/src/__tests__/telemetry.test.ts
packages/create-expo-app/src/analytics.ts
packages/create-expo-app/src/index.ts
packages/create-expo-app/src/paths.ts
packages/create-expo-app/src/sessionStorage.ts
packages/create-expo-app/src/telemetry.ts

We'd like to ensure package health and understand developer usage.
- adds analytics methods such as identify, track, and flush
- adds paths and sessionStorage from eas-cli for reading and writing
device + user-id to ~/.expo/state.json
- adds analytics event tracking to create expo app
- build the package (preferably with a test writekey -- the 'rudderstack-sandbox' one)
- create a new expo app
- ensure the events make it to the backend when
- the initialization finishes successfully
- the command fails partway through
- delete your local ~/.expo/state.json file 
- ensure the above still works
- run eas build with the new state file, ensure the other properties get filled in and the cli does not crash
Using `ls -hl (build output path)`:
Old bundle size: 1.3M
New bundle size: 1.3M

feat(create-expo-app): adds analytics

---

CHANGELOG.md
packages/expo-cli/src/commands/info/doctor/depedencies/explain.ts

`expo doctor` crashes on Node 14/npm 6 because `npm why is not available.
Detect the standard npm output for running an unknown npm command, and log.
- Run `expo doctor` on Node 14/npm 6

[doctor] Gracefully handle not being able to run dependency tree validation on older Node/npm versions

---

packages/expo-cli/src/commands/utils/npm.ts

The `npm pack` produces a tgz file and shows the path with the `filename` property of the command output.
Unfortunately for scoped package names, this is outputting an incorrect filename.  This is causing initialising
expo projects from a template with a scoped package name to fail.
This is due to a bug in npm (https://github.com/npm/cli/issues/3405)
This PR applies a workaround.
This closes #4416
The fix checks if the package name and the filename from the `npm pack` command start with `@`.  If so, then it removes the `@` and replaces `/` with `-` from the `npm pack` filename output.   It's checking both package name and filename, as it is possible that npm will fix their bug at some time in the future.
To manually test this, use the following command:
```
expo init RealmJsApp -t …
```

fix: Support scoped package names for initialising projects

---

packages/package-manager/src/NodePackageManagers.ts
packages/package-manager/src/utils/__tests__/shouldUseYarn-test.ts
packages/package-manager/src/utils/nodeWorkspaces.ts
packages/package-manager/src/utils/shouldUseYarn.ts

- This fixes [#4355](https://github.com/expo/expo-cli/issues/4355#issue-1229575049)
As Brent says [here](https://forums.expo.dev/t/android-failure-for-managed-workflows-due-to-npm/63576/8?u=wodin):
>it appears that the default logic when running expo run:android defaults to using yarn if you have it installed, rather than checking for lockfile as it should
So now Yarn is still favored over NPM, but if there's already a `package-lock.json` in the project root, NPM will be used.
- See tests

fix(package-manager): should not use yarn when npm lockfile exists

---

packages/expo-cli/src/commands/info/doctor/depedencies/explain.ts
packages/expo-cli/src/commands/info/doctor/doctorAsync.ts

If there is wrong version of autolinking installed or config plugins, `expo dotor` still states that there are no issues with the project plus exit code is zero
return boolean form functions that are doing the validation and if there were any issues exit with non-zero exit code
before (exit code zero)
after (exit code 1)

[expo-cli] return non-zero exit code if package versions are incorrect

---

.github/workflows/test.yml

codecov is throwing too many false positives in PRs. When CI fails consistently and constantly then it reduces confidence in the review cycle.
We won't be drastically improving the testing of this repo since it is pretty much in maintenance mode until the versioned CLI migration is complete.
Revert change to enable the feature.

ci: disable codecov

---

packages/schemer/package.json
yarn.lock

Github advisory recommends to update ajv to a version `>=6.12.3` due to a vulnerability https://github.com/advisories/GHSA-v88g-cgmw-v5xw.
Update ajv to ^6.12.6 in package.json
Ran the test cases to make sure version 6 was still compatible.

Upgrade Schemer ajv to fix known vulnerability

---

CHANGELOG.md
packages/expo-cli/src/commands/installAsync.ts

Existing plugins were ignored retrieving the config for `expo install`.
No longer skip resolving plugins. I'm not sure if the behavior of `skipPlugins` for `getConfig` in @expo/config has changed, but this makes it work here as intented.
Update: this comes down to this line: https://github.com/expo/expo-cli/blob/391f8faae3b3d497b4472bc9bd8c8b989f20ad11/packages/config/src/plugins/withConfigPlugins.ts#L22 where the plugins array is deleted from config when `skipPlugins` is `true`.
- Initialize a blank project
- expo install expo-camera
- Add expo-camera plugin to app.json: "plugins": ["expo-camera"]
- Run expo install sentry-expo
- Notice that both plugins exists in the plugins array
Will look into automated testing, but suggestions are welcome.

[cli] fix ignored existing plugins on expo install

---

packages/expo-cli/src/commands/utils/typescript/resolveModules.ts

Ensure we check against the package.json for versions.

fix: fix auto TypeScript version check

---

packages/create-expo-app/src/Template.ts
packages/create-expo-app/src/__tests__/Template.test.ts
packages/create-expo-app/src/createAsync.ts

- improve failure error.
- reduce complexity file path resolution.
- resolve more file paths to attempt to fix relative path bugs on windows -- appears NPM on windows doesn't resolve paths manually.

chore(create-expo-app): possibly fix windows bug for relative paths

---

packages/prebuild-config/package.json
packages/prebuild-config/src/getAutolinkedPackages.ts
packages/prebuild-config/src/importExpoModulesAutolinking.ts

`expo-modules-autolinking` being a dependency of `@expo/prebuild-config` is the most common reason of duplicated versions of the autolinking installed in the project. To avoid such issues the `expo` package must be the only one that depends on `expo-modules-autolinking`.
- Instead of importing the autolinking statically, I use Node's resolution to find the path to `expo-modules-autolinking` that is installed in the project where the prebuild command is run
- Removed `expo-modules-autolinking` from the dependencies
- Tested `dexpo prebuild` on a fresh project and confirmed that the results are the same as before (`searchPaths` and `platformPaths`)
- Ensured that `require.resolve` and especially `paths` option is available in all versions of Node that we support (it's available as of v8.9.0 …

[prebuild-config] Remove the dependency on expo-modules-autolinking

---

packages/expo-cli/src/commands/info/doctor/depedencies/explain.ts
packages/expo-cli/src/commands/info/doctor/doctorAsync.ts

Any SDK 45+ project that includes `@unimodules/core`, `@unimodules/react-native-adapter`, and `react-native-unimodules` is likely not going to build. We should let people know about this and `doctor` is a good spot.
I adapted our existing checks for deep dependencies to let us check for the existence of a package that should not exist. I changed the output slightly for this to make sense and to remove some (I think) unnecessary logs. See below for some examples.
https://user-images.githubusercontent.com/90494/176566254-808fa54d-c983-4f7b-aa6c-d4649ce706e6.mov
https://user-images.githubusercontent.com/90494/176566264-f4766dff-000d-4ab3-a0fd-e5ef80331fb0.mov
https://user-images.githubusercontent.com/90494/176566279-0f0bc8b9-debf-4e07-bc79-1b2cfeb2d4e7.mov

[doctor] Validate that projects do not include illegal packages

---

packages/dev-server/src/metro/importMetroFromProject.ts

we used the `hermesc` from [the hermes-engine node dependency to compile hermes bundle](https://github.com/expo/expo-cli/blob/eda8fe6eafde912a9a37eaa3197e7fb48aa50f42/packages/dev-server/src/metro/importMetroFromProject.ts#L66-L82).  the hermes-engine dependency in react-native 0.69 is outdated, instead we should use the hermesc bundled in react-native 0.69.
close ENG-5677
tries to resolve hermesc from multiple locations:
- `${process.env['REACT_NATIVE_OVERRIDE_HERMES_DIR']}/build/bin/hermesc` - building hermes from source with override dir
- `node_modules/react-native/ReactAndroid/hermes-engine/build/hermes/bin/hermesc` - building hermes from source
- `node_modules/react-native/sdks/hermesc/...` - the one bundled in react-native npm package
- `node_modules/hermes-engine/...` - support …

[dev-server] Support prebuilt hermes in react-native 0.69

---

packages/next-adapter/document.js

`renderPage` is now async. Otherwise this error shows even after adding expo to a barebone next app

Fix showstopper in next-adapter/document.js

---

packages/create-expo-app/src/Template.ts
packages/create-expo-app/src/utils/npm.ts

Running EXPO_BETA should use the beta templates in create-expo-app

feat: add support for EXPO_BETA flag

---

packages/install-expo-modules/src/index.ts
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-no-delegate-updated.java
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-no-delegate-updated.kt
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-rn068-updated.java
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-rn068-updated.kt
packages/install-expo-modules/src/plugins/android/withAndroidModulesMainActivity.ts
packages/install-expo-modules/src/plugins/ios/__tests__/withIosDeploymentTarget-test.ts
packages/install-expo-modules/src/plugins/ios/withIosDeploymentTarget.ts
packages/install-expo-modules/src/utils/expoVersionMappings.ts

close ENG-5724
- add react-native 0.69 with sdk 46 version info
- add missing `BuildConfig.IS_NEW_ARCHITECTURE_ENABLED` migration in MainActivity. this is also available from sdk 45. it's just me forgot to add it from template.
- skip the prompt for ios deployment target update if the requirement is already meet.
- ci  and unit tests passed
- `npx install-expo-modules` on a react-native 0.68 project
- `npx install-expo-modules` on a react-native 0.69 project

[install-expo-modules] Add SDK 46 support

---

packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/addons/__tests__/withOptimizations-test.js
packages/webpack-config/src/addons/withOptimizations.ts
packages/webpack-config/src/webpack.config.ts
yarn.lock

- Fix regression introduced in https://github.com/software-mansion/react-native-reanimated/pull/3278
- Alternative to https://github.com/facebook/metro/issues/760
- Enable tree shaking feature https://webpack.js.org/configuration/optimization/#optimizationusedexports
- Not sure if this will have other repercussions.
- `EXPO_BETA=1 yarn create expo-app -t tabs` 
- `yarn expo install react-native-reanimated`
- This won't fail when using the proposed changes.

fix(webpack-config): fix import export treeshaking

---

packages/xdl/src/tools/ModuleVersion.ts

Because `xdl` caches package information by name only, it will not refresh the information if a new version of the package is available. This leads to issues like #4483.
Include the provided `currentVersion` in the filename
There's no test coverage in `xdl` for it, and it's not worth adding it, as the method is already deprecated.
Also hard to test because `xdl` is a dependency of `expo-cli`, but it should be testable by:
- Installing `expo-cli` 5.5.2 or 5.6.0 (which are deprecated)
- Run `expo start`, or another command to trigger the version check
- Upgrade `expo-cli` to a version with the new `xdl`
- Run `expo start` again, and see that a separate file is created in cache for the new version, and the deprecation warning isn't shown.

[xdl] include version number in package info cache

---

packages/expo-cli/src/commands/eject/clearNativeFolder.ts

currently, if someone has a managed project with an ios directory, or is writing eas secrets to ios directory e.g.
```
echo "$IOS_GOOGLE_SERVICES_BASE64" | base64 -d > ios/GoogleService-Info.plist
```
then only warning they are getting that ios directory is deleted is log
```
- Clearing ios
✔ Cleared ios code
```
print working when rebuilding in non-interactive mode

add better warning when prebuilding in non-interactive mode

---

packages/expo-cli/src/commands/build/buildWebAsync.ts
packages/expo-cli/src/commands/eject/customizeAsync.ts
packages/expo-cli/src/commands/eject/ejectAsync.ts
packages/expo-cli/src/commands/eject/prebuildAsync.ts
packages/expo-cli/src/commands/export/exportAsync.ts
packages/expo-cli/src/commands/info/config/configAsync.ts
packages/expo-cli/src/commands/initAsync.ts
packages/expo-cli/src/commands/installAsync.ts
packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/expo-cli/src/commands/start/startAsync.ts
packages/expo-cli/src/utils/migration.ts
yarn.lock

- resolve ENG-5940
- When the user is running a replaced command in an SDK 46 project that doesn't have the local CLI disabled, warn that they should migrate.
- `expod start` in an SDK 46 project -- warning.
- `expod config` in an SDK 44 project -- no warning.
- `expo init` anywhere -- warning.

feat(cli): add migration logs when available

---

CHANGELOG.md
packages/webpack-config/package.json

Remove `@expo/config` dependency that is causing nested dependency version conflicts, and instead have it pulled it via the `expo` devDependency.
Fixes #4511.
Updated package.json
🙏🏻

[webpack-config] remove explicit @expo/config dependency

---

packages/xdl/src/project/__tests__/ExpSchema-test.ts

Refs #4536
Replace removed schema property with the existing one.
XDL tests do not fail locally.

[xdl] fix schema test

---

packages/install-expo-modules/package.json
packages/install-expo-modules/src/index.ts
packages/install-expo-modules/src/plugins/ios/withIosDeploymentTarget.ts
packages/install-expo-modules/src/plugins/ios/withIosModulesAppDelegate.ts
packages/install-expo-modules/src/plugins/ios/withXCParseXcodeProject.ts
yarn.lock

`simple-plist@1.3.1` is a transitive dependency of the xcode package. it has [an incompatible issue](https://github.com/wollardj/simple-plist/issues/58) with ncc. the issue is pending for a while without publishing newer version as latest dist-tag. that blocks us from updating install-expo-modules.
replace xcode with the awesome xcparse. this pr introduces a `withXCParseXcodeProject` config-plugin internally.
- ✅ unit test passed
- ✅ manual test on a react-native 0.68 project
- ✅ manual test on a react-native 0.69 project

[install-expo-modules] Replace xcode with xcparse

---

packages/install-expo-modules/package.json
packages/install-expo-modules/src/index.ts
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/AppDelegate-rn068-updated.mm
packages/install-expo-modules/src/plugins/ios/withIosDeploymentTarget.ts
packages/install-expo-modules/src/plugins/ios/withIosModulesAppDelegate.ts
packages/install-expo-modules/src/plugins/ios/withXCParseXcodeProject.ts
yarn.lock

react-native 0.68 introduced a `RCTAppSetupDefaultRootView` to create the RCTRootView in AppDelegate.mm. i missed the pattern update in install-expo-modules. this pr will fix https://github.com/expo/expo/issues/19179.
migrate `RCTAppSetupDefaultRootView`
- ✅ unit test for AppDelegate-rn068

[install-expo-modules] Fix RCTRootView for react-native 0.68 or above

---

packages/image-utils/src/Image.ts
packages/image-utils/src/env.ts
packages/image-utils/src/sharp.ts

Fixes ENG-2724
This warning doesn't make a lot of sense when building your app. For new people, it's pretty hard to know you have to install this library before building your app. And once you are building it, you probably won't cancel the build to restart for a minor speed improvement compared to node image optimizations.
That being said, it can still be helpful to know which one of the image libraries is being used. So, instead of entirely dropping the message, it's now behind `EXPO_IMAGE_UTILS_DEBUG`. When setting this to true, it will output the warnings again.
Run a build with this version of image utils.

[image-utils] Silence sharp related warnings by default

---

packages/create-expo-app/src/Template.ts
packages/create-expo-app/src/resolveProjectRoot.ts

This PR solves the following issue: #4533 
If ```create-expo-app``` is used with app names such as expo or react-native it leads to the app being correctly initialized however crashing upon starting up because it would conflict with a dependency of the same name. ```expo-cli```already prevents this. This should be handled in create-expo-app too.
Upon init, projectName will be checked if it's present in a list of Forbidden project names. If yes, log error and exit.
Build the changes and run ```node index expo``` from the build path and the error should pop up.

[CEA] Prevent Forbidden/ Conflicting app names

---

packages/image-utils/src/Image.ts

When using Jimp instead of sharp for image generation, the images are modified and exported in the original format. This proposed change will always export as PNG (same as Sharp).
Related to https://github.com/expo/eas-cli/pull/1477
- `expo.android.adaptiveIcon.foregroundImage` set to a jpg
- `yarn expo run:android --variant release` should not fail

fix(image-utils): make jimp export buffers as png like sharp

---

packages/install-expo-modules/src/utils/expoVersionMappings.ts

add sdk 47 (react-native 0.70) support
close ENG-6698
react-native 0.70 didn't introduce template breaking changes. we don't have to change in install-expo-modules. just the minimum ios deployment target as 13.0 for expo sdk 47.
- unit test passed
- integration test from react-native 0.70 project

[install-expo-modules] add sdk 47 support

---

packages/plist/package.json
yarn.lock

[Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') in @xmldom/xmldom and xmldom · CVE-2022-37616 · GitHub Advisory Database](https://github.com/advisories/GHSA-9pgh-qqpf-7wqj)
Fixes #4569
`@xmldom/xmldom` has already been patched:
[fix: Avoid iterating over prototype properties by karfau · Pull Request #437 · xmldom/xmldom](https://github.com/xmldom/xmldom/pull/437)
newer versions exist but this is the latest patch version and there shouldn't be any breaking changes
`yarn build` and `yarn test`

[plist] Update xmldom for security reasons

---

packages/xdl/src/ApiV2.ts
packages/xdl/src/Env.ts
packages/xdl/src/User.ts
packages/xdl/src/gating/FeatureGateEnvOverrides.ts
packages/xdl/src/gating/FeatureGateKey.ts
packages/xdl/src/gating/FeatureGateTestOverrides.ts
packages/xdl/src/gating/FeatureGating.ts
packages/xdl/src/gating/__mocks__/FeatureGateTestOverrides.ts
packages/xdl/src/gating/__tests__/FeatureGate-test.ts
packages/xdl/src/internal.ts

This is the legacy CLI equivalent of https://github.com/expo/eas-cli/pull/1475. This uses the new www API to fetch the feature gates since there isn't a graphql client available in this CLI.
This will be used to roll out features to encourage users to move to EAS update before the deadline.
Add similar code, update to be in the style of this repo and with the `internal` module stuff.
Run test.

[xdl] Add feature gates

---

packages/uri-scheme/src/Android.ts

Currently, `npx uri-scheme open --android "myscheme://test?varA=1&varB=2"` launch the app with a deeplink `myscheme://test?varA=1` instead of `myscheme://test?varA=1&varB=2`
Apparently adb expects the character `&` to be escaped.
Tested with the current version and `npx uri-scheme open --android "myscheme://test?varA=1\&varB=2"`

Handle multiple query parameters in Android URIs

---

packages/json-file/__tests__/JsonFile-test.ts
packages/json-file/package.json
yarn.lock

The `@expo/json-file` package has an old version of `json5` as a dependancy. This has a  **high severity** vulnerability:
[CVE-2022-46175](https://github.com/advisories/GHSA-9c47-m6qq-7p4h). This was published 29/12/2022
It has been fixed in version [2.2.2](https://github.com/json5/json5/releases/tag/v2.2.2).
This PR updates `json5` to version 2.2.2 where the issue has been patched
- Update the version number in package.json. 
- Also updated `@types/json5` to version 2.2.2
The existing tests pass - the only change required was increasing the timeout.

fix(update): json5 to v2.2.2 where vulnerability has been patched

---

packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-rn071-updated.java
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-rn071-updated.kt
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-rn071.java
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainActivity-rn071.kt
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainApplication-rn071-updated.java
packages/install-expo-modules/src/plugins/android/__tests__/fixtures/MainApplication-rn071.java
packages/install-expo-modules/src/plugins/android/__tests__/withAndroidModulesMainActivity-test.ts
packages/install-expo-modules/src/plugins/android/__tests__/withAndroidModulesMainApplication-test.ts
packages/install-expo-modules/src/plugins/android/withAndroidModulesMainActivity.ts
packages/install-expo-modules/src/plugins/android/withAndroidModulesMainApplication.ts
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/AppDelegate-rn071-updated.h
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/AppDelegate-rn071.h
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/AppDelegate-rn071.mm
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/Podfile-rn071
packages/install-expo-modules/src/plugins/ios/__tests__/fixtures/Podfile-rn071-updated
packages/install-expo-modules/src/plugins/ios/__tests__/withIosDeploymentTarget-test.ts
packages/install-expo-modules/src/plugins/ios/__tests__/withIosModulesAppDelegate-test.ts
packages/install-expo-modules/src/plugins/ios/__tests__/withIosModulesPodfile-test.ts
packages/install-expo-modules/src/plugins/ios/withIosDeploymentTarget.ts
packages/install-expo-modules/src/plugins/ios/withIosModulesAppDelegate.ts

support react-native 0.71 for sdk 47 in early preview
- [android] nothing particular. original approach works for the new `DefaultReactActivityDelegate` and `DefaultReactNativeHost`
- [ios] for `platform :ios, min_ios_version_supported` to migrate minimal ios version, we should further lookup the `min_ios_version_supported` inside react-native
- [ios] only AppDelegate.h needs migration for the `RCTAppDelegate` for 0.71. original AppDelegate.mm changes will be handled internally in our EXAppDelegateWrapper. see https://github.com/expo/expo/pull/20470 for more details
- adding unit tests for 0.71
- manual testing on an 0.71 project

[install-expo-modules] Add react-native 0.71 support

---

packages/next-adapter/README.md

Next.js transpileModules seems to be using aliases for modules, meaning you now need to add `react-native` instead of `react-native-web`.

update docs to reflect next config bug

---

packages/create-expo-app/src/utils/git.ts

Part of ENG-7078
When already inside a Git repo, we shouldn't be creating a new one.
Added `return false;` to stop creating a new repo.
- `$ git clone git@github.com:bycedric/expo-monorepo-example.git ./test`
- `$ npx create-expo-app ./test/apps/new-without-subrepo`
- `$ cd ./test/apps/new-without-subrepo` should not have `.git`

fix(create-expo-app): skip creating a git repo when inside existing repo

---

README.md

Why: the local CLI is the only maintained CLI aside from critical security fixes for now. Everyone looking at this repo should be aware that Expo CLI has moved repos.
How: added a bold section above everything else in the README.

[readme] Highlight the modern local CLI over everything else

---

packages/expo-cli/bin/expo.js
packages/expo-cli/package.json

- `expo-cli` is deprecated in favor of `npx expo`, any existing use cases are unstable and subject to breakage.

Remove Node.js limitations on the legacy CLI

---

packages/webpack-config/package.json
packages/xdl/package.json
yarn.lock

Makes versioned CLI usage a bit easier, also bumps the version to latest.

fix(webpack): add webpack-dev-server as a dependency of webpack-config

---

packages/create-expo-app/src/createAsync.ts

- A spinner should only be used for short-running, indeterminate tasks.
- @gaearon mentioned that the current behavior is not sparking joy: https://twitter.com/dan_abramov/status/1621355168792039426?s=20&t=T-XihEJP2vTJuHT1igMpcg
- Dropping the spinner in favor of the raw logs because we support three different package managers and it's not entirely obvious how we can create a consistent loading bar UI across all three (`yarn install --json` output differs a lot from `npm install --json`)
- Ran locally
- Unit tests (minimal overlap)

feat(create-expo-app): drop loading spinner when installing dependencies

---

packages/xdl/src/project/createBundlesAsync.ts

CI is currently failing on all PRs due to an eslint issue
Fixed that eslint issue
See if CI passes

fix(xdl): remove unused import from `createBundlesAsync`

---

packages/create-expo-app/package.json
packages/create-expo-app/src/Examples.ts
packages/create-expo-app/src/Template.ts
packages/create-expo-app/src/__mocks__/fs.ts
packages/create-expo-app/src/__mocks__/ora.ts
packages/create-expo-app/src/__tests__/Examples.test.ts
packages/create-expo-app/src/cli.ts
packages/create-expo-app/src/createAsync.ts
packages/create-expo-app/src/utils/__tests__/log.test.ts
packages/create-expo-app/src/utils/log.ts
yarn.lock

Fixes ENG-7493
- Based on the code from [`create-react-native-app`](https://github.com/expo/create-react-native-app/blob/main/src/Examples.ts), but adopted to this repository
> **Warning**
> I ran into the "premature close" error when testing this: https://github.com/isaacs/node-tar/issues/321. I upgraded `tar@6.1.11` to `tar@6.1.13` to avoid this.
See tests and help info:
```bash
$ yarn create expo-app --help
$ yarn create expo-app --example
$ yarn create expo-app --example with-router
```

feature(create-expo-app): add `--example` flag to initialize from example

---

packages/install-expo-modules/src/utils/expoVersionMappings.ts

officially add sdk 48 support for install-expo-modules
add sdk 48 to the version mappings
```sh
$ npx react-native init RN071 --version 0.71
$ cd RN071
$ /path/to/expo/expo-cli/packages/install-expo-modules/build/index.js
```

[install-expo-modules] add sdk 48 support

---

packages/install-expo-modules/src/index.ts
packages/install-expo-modules/src/plugins/android/withAndroidGradles.ts
packages/install-expo-modules/src/utils/expoVersionMappings.ts

since sdk 48 requires AGP 7.4.1, we should help this migration in the install-expo-modules tool
prompt and update agp version
```sh
$ npx react-native init RN071 --version 0.71
$ cd RN071
$ /path/to/install-expo-modules/build/index.js
```

[install-expo-modules] support to update AGP version for Expo SDK 48

---

packages/expo-doctor/src/checks/GlobalPackageInstalledCheck.ts
packages/expo-doctor/src/checks/__tests__/GlobalPackageInstalledCheck.test.ts
packages/expo-doctor/src/doctor.ts

We now recommend users upgrade by using `npx expo install --fix`, but some have `expo-cli` installed in project for legacy reasons, and that can break the `--fix` flag with `error: unknown option --fix’`.
Added a check, much like the other illegal package checks.
NOTE: I think we'll end up with many illegal package checks, so will likely eventually refactor to reduce that to adding package name and customized advice without so much ceremony, just not yet.
- Add `expo-cli` to a project, get warning.
- Remove from project, no more warning.

[doctor] check if global cli is installed in project

---

packages/xdl/src/project/__tests__/createBundlesAsync-test.ts

Wanted tests to pass. UPDATE: didn't notice others were failing; oh, well, a little closer I suppose!
Per [this commit](https://github.com/expo/expo-cli/commit/5ce6893721da5af1b54ebcf9ff9c2529341d8bf3), it looks like `target` should no longer be passed, so removed it from the check.
XDL unit tests pass!

[xdl] fix failing unit test

---

packages/expo-doctor/__mocks__/child_process.ts
packages/expo-doctor/src/checks/GlobalPrereqsVersionCheck.ts
packages/expo-doctor/src/checks/__tests__/GlobalPackageInstalledCheck.test.ts
packages/expo-doctor/src/checks/__tests__/GlobalPrereqsVersionCheck.test.ts
packages/expo-doctor/src/checks/__tests__/InstalledDependencyVersionCheck.test.ts

Resolves https://linear.app/expo/issue/ENG-7606/doctor-dont-require-watchman. Expo works fine without watchman on macOS, so let's not warn about it.
Removed the check
Tried without watchman installed; no warning

[doctor] remove watchman check

---

packages/expo-doctor/__mocks__/fs.js
packages/expo-doctor/src/checks/PackageJsonCheck.ts
packages/expo-doctor/src/checks/__tests__/PackageJsonCheck.test.ts
packages/expo-doctor/src/doctor.ts

Check package.json for scenarios [identified here](https://www.notion.so/expo/Expo-Doctor-Roadmap-Q1-Q2-2023-32343debd75549d38dd282a249e3cb52):
- check for direct inclusion of expo-modules/ autolinking
- no scripts should be named "expo"
- package name shouldn't match a project dependency
Added a check class and unit tests.
Ran doctor against a project with and without the following changes:
- added expo-modules to project
- named a script "expo"
- named a package after a direct dependency (question: should we be checking deep dependencies for this, too?)

[doctor] added basic package.json sanity checks

---

packages/expo-doctor/src/utils/env.ts
packages/expo-doctor/src/utils/interactive.ts
packages/expo-doctor/src/utils/ora.ts

Doctor had 2 different parts from legacy and newer code.
- **Legacy**: the `nonInteractive` flag on `commander`'s `program` singleton
- **Newer**: uses `args` instead of `commander`
- Added `isInteractive()` function in **./utils/interactive.ts**
- Added `CI` environment variable in **./utils/env.ts**
- Refactored Ora's `disabled` check to use `isInteractive() || env.EXPO_DEBUG`
Ora should now be disabled in non-interactive environments.

fix(doctor): replace commander-based interactivity check with tty/ci check

---

packages/expo-doctor/src/checks/IllegalPackageCheck.ts
packages/expo-doctor/src/checks/SupportPackageVersionCheck.ts
packages/expo-doctor/src/checks/__tests__/IllegalPackageCheck.js
packages/expo-doctor/src/checks/__tests__/SupportPackageVersionCheck.test.ts

[Per these early results from Doctor running on EAS Build](https://exponent-internal.slack.com/archives/C5ERY0TAR/p1680180597751169?thread_ts=1679999034.565819&cid=C5ERY0TAR), looks like we could shave some time off on these deep dependency checks.
I just parallelized the deep dependency checks within each test that had more than one. This was something I could do quickly without changing any structure outside of the individual tests in order to see some fast feedback.
Next up, I would want to extract/ parallelize the network requests, and then run all of the deep dependency checks in parallel.
Tested on a project, made sure both checks caught the same stuff as before

Run some deep dependency checks in parallel

---

packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/loaders/createBabelLoader.ts
packages/webpack-config/src/webpack.config.ts

a regression from webpack 5 upgrade where it should explicitly specify full js extension like `import './foo.js';`. this breaks metro assumption and existing code in [expo-noifications](https://github.com/expo/expo/blob/1120c716f35cb28d88800e8f5d963d2b2ac94705/packages/expo-notifications/src/DevicePushTokenAutoRegistration.fx.ts#L1)
fixes https://github.com/expo/expo/issues/22064
close ENG-8248
add `resolve.fullySpecified=false` as webpack doc mentioned: https://webpack.js.org/configuration/module/#resolvefullyspecified
based on https://github.com/viveksc1994/expo-48-web and apply the patch
**patches/@expo+webpack-config+18.0.3.patch**
```diff
diff --git a/node_modules/@expo/webpack-config/webpack/loaders/createBabelLoader.js b/node_modules/@expo/webpack-config/webpack/loaders/createBabelL …
```

[webpack] fix error for not specifying full extension

---

packages/dev-tools/package.json
packages/expo-cli/package.json
packages/expo-doctor/package.json
packages/webpack-config/package.json
packages/xdl/package.json

- @expo/dev-tools@0.13.182
- expo-cli@6.3.5
- expo-doctor@1.0.4
- @expo/webpack-config@18.0.3
- xdl@60.0.7

commit version bumps after publish

---

packages/expo-doctor/package.json

After this[ latest publish of Doctor](https://github.com/expo/expo-cli/commit/680639dc7b923fde9002d7288bb17168654091c9), pretty much everyone started seeing this warning:
It comes from `ajv` by way of `schemer`
My guess is that this is due to some machine-specific difference in what version of schemer was used on publish, because the dependency wasn't specified in package.json. I'm guessing a bit because I can't tell from changelogs what versions of `ajv` would or would not cause this warning, and it's murky to me when I crawl through the NPX install folders exactly what version of `schemer`/ `ajv` is being used, other than that it is old/ wrong. But what I do know is that there's no warning in my local dev environment, where it's clearly using the latest `schemer` with `ajv@8.x.x`.
Added …

[doctor] Specify schemer version to eliminate 'NOT SUPPORTED' warning

---

packages/expo-cli/src/commands/publish/deprecationNotice.ts
packages/expo-cli/src/commands/publish/publish.ts
packages/expo-cli/src/commands/publish/publishAsync.ts
packages/expo-cli/src/commands/publish/publishDetailsAsync.ts
packages/expo-cli/src/commands/publish/publishHistoryAsync.ts
packages/expo-cli/src/commands/publish/publishRollbackAsync.ts
packages/expo-cli/src/commands/publish/publishSetAsync.ts

- expo publish:* commands should say they’re deprecated and replaced by eas
- when someone runs one of these commands, print a link to the [sunset blog post](https://blog.expo.dev/sunsetting-expo-publish-and-classic-updates-6cb9cd295378)
- update command description
- print deprecation notice on `expo publish:*`

[ENG-8317][cli] deprecate publish:*

---

packages/expo-cli/src/commands/info/doctor/doctorAsync.ts

Fulfills https://linear.app/expo/issue/CX-223/in-global-expo-cli-tell-people-about-new-doctor-when-they-run-old
Added an error log and exited when SDK Version >= 46
Tested on SDK 46+, errored out:
Proceeded as before when SDK 45 is installed.

[expo-cli] Advise to use new doctor on SDK 46+

---

packages/expo-cli/src/commands/credentials.ts
packages/expo-cli/src/commands/fetch/index.ts
packages/expo-cli/src/commands/push.ts

Applying feedback from https://github.com/expo/expo-cli/pull/4686#pullrequestreview-1391116636
This PR replaces the description of deprecated commands and provides information about their superceded commands.  These changes should be made into a patch release for the last major/minor version with all the cli functionality

[cli] replace deprecated commands with superceded ones

---

packages/expo-cli/src/commands/fetch/index.ts
packages/expo-cli/src/commands/publish/publish.ts
packages/expo-cli/src/commands/push.ts

feedback from https://github.com/expo/expo-cli/pull/4693#issuecomment-1518429839
add commands to deprecated helpgroup

[cli] add deprecated commands to helpgroup

---

packages/expo-doctor/src/checks/InstalledDependencyVersionCheck.ts
packages/expo-doctor/src/checks/__tests__/InstalledDependencyVersionCheck.test.ts

Expo Doctor's dependency version check isn't working at all on Windows right now (other than in WSL) 🙈 .
When calling npx expo install --check, we had to pipe a "y" into the command so it would finish, [necessitating this technique for calling a child process](https://stackoverflow.com/a/39482554). Since this uses sh, it doesn't work in Windows.
Fortunately, there's a WAY easier way to do this
Use the `CI=1` environment variable, which causes the versioned CLI to disable the interactive prompt on `npx expo install --check`.

[doctor] remove sh command from dep check for Windows compat

---

packages/expo-doctor/package.json
packages/expo-doctor/tsconfig.json

Optimize for NCC, hopefully resulting in quicker start times when first installing (e.g., on EAS Build)
- Moved all dependencies to `devDependencies`
- Added `ora` dep because it's used in the app but wasn't in package.json
- Set `allowSyntheticDefaultImports` to true due to import TS errors after clearing node_modules and starting over. I could have fixed the references, but some were using a combination of the default export and other exports, and it wasn't clear on how to fix them all.

[doctor] Move dependencies to devDependencies

---

packages/install-expo-modules/src/utils/expoVersionMappings.ts

add instal-expo-modules support for sdk 49
sdk 49 doesn't come new changes to templates (in expo-modules point of view). this pr just adds the version mapping.
```sh
$  npx react-native init RN072 --version 0.72
$ cd RN072
$ /path/to/install-expo-modules/build/index.js
$ yarn android
$ yarn ios
```

[install-expo-modules] add sdk 49 support

---

packages/expo-doctor/src/checks/ExpoConfigSchemaCheck.ts
packages/expo-doctor/src/checks/GlobalPackageInstalledCheck.ts
packages/expo-doctor/src/checks/GlobalPrereqsVersionCheck.ts
packages/expo-doctor/src/checks/IllegalPackageCheck.ts
packages/expo-doctor/src/checks/InstalledDependencyVersionCheck.ts
packages/expo-doctor/src/checks/SupportPackageVersionCheck.ts

Fulfills https://linear.app/expo/issue/ENG-8979/unify-expo-doctor-test-descriptions
Changed the check names as suggested, trying to explain a little more specifically/ plainly what they were doing.
In the long run, I kind of want to get away from these descriptions entirely. They were originally an attempt to componentize things that were tested together, but now they result in sometimes having to worry about how the technical category (e.g., a deep dependency check) matches or doesn't match with the logical category of the check (e.g., support package version check vs. checking for unimodules, various categories of things that could all be considered "package.json checks", etc.).

[doctor] clean up check names

---

packages/expo-doctor/src/checks/PackageJsonCheck.ts
packages/expo-doctor/src/checks/__tests__/PackageJsonCheck.test.ts

(At least partially) fulfills https://linear.app/expo/issue/ENG-9160/[cli]-expo-doctor-and-expo-install-should-warn-on-dev-launcher-in
Add these packages to the existing transitive-only package checks

Warn if expo-dev-launcher / expo-dev-menu are installed

---

packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/webpack.config.ts

- Fix https://github.com/expo/expo/issues/23296
- Related https://github.com/alewin/useWorker/issues/138
Filter out sourcemaps from useWorker.

fix(webpack-config): fix sourcemap bug with expo camera

---

packages/expo-doctor/src/checks/ProjectSetupCheck.ts
packages/expo-doctor/src/checks/__tests__/ProjectSetupCheck.test.ts
packages/expo-doctor/src/doctor.ts

Multiple "project structure" tests in here (to avoid chicken-and-egg-esque merge mayhem):
- Warn on multiple lock files
- Warn if possibly-unintentionally bare
For the lockfile check, just checking for the existence of more than one lockfile.
For the bare check, right now I'm checking if you have config plugins and ios/ android folders. I know that's not the only situation where you could be unintentionally bare (and you could be intentionally bare and just have left those lines in your Expo config), but not sure of a better way to detect this, and I would really like to detect it, as misunderstanding prebuild and what it means to "use" it comes up pretty regularly in support requests.
One of the pain points with adding individual checks to doctor right now is that you either have to a) …

[doctor] multiple lock file, unintentionally-bare detection

---

packages/expo-doctor/src/checks/DirectPackageInstallCheck.ts
packages/expo-doctor/src/checks/DoctorMultiCheck.ts
packages/expo-doctor/src/checks/PackageJsonCheck.ts
packages/expo-doctor/src/checks/__tests__/DirectPackageInstallCheck.test.ts
packages/expo-doctor/src/checks/__tests__/PackageJsonCheck.test.ts
packages/expo-doctor/src/doctor.ts

`@types/react-native` is now included with `react-native`. Including the wrong/ old version of types could lead to... issues with types.
This looks more complicated than it sounds. That's because I'm starting a refactor with bigger goals in mind :D. I could have wedged this check as a conditional into the existing `PackageJsonCheck`, but the SDK filter happens for each check file, so I'd either duplicate that, or....
...introduce a `DoctorMultiCheck` that can filter by SDK by each individual item in a check, but, at least for now, without breaking the `DoctorCheck` interface. Combined with extracting the precise message for each package, this makes it easier to define additional checks of the same type as configuration. This use case is very simplistic, but the pattern would really sing …

[doctor] check for @types/react-native on 48+ (and other things you shouldn't install directly)

---

packages/expo-doctor/src/doctor.ts
packages/pod-install/package.json
packages/pod-install/src/index.ts
packages/pod-install/src/utils.ts

Fixes ENG-5760
This small PR adds a check which attempt to determine the workflow used in the current project. 
If it's `managed` an alternative message is being print in the console, to avoid the confusion.
Logic has been inspired by the XDL `ProjectUtils` helpers.
The changes have been tested by building `pod-install` locally and then running it in various directories.

[pod-install] show alternative message in managed projects

---

packages/expo-doctor/src/api/getSchemaAsync.ts
packages/expo-doctor/src/api/getVersionsAsync.ts
packages/expo-doctor/src/checks/SupportPackageVersionCheck.ts
packages/expo-doctor/src/checks/__tests__/SupportPackageVersionCheck.test.ts
packages/expo-doctor/src/doctor.ts
packages/expo-doctor/src/utils/env.ts

Based on an i[ssue faced by a user](https://exponent-internal.slack.com/archives/C1QP38NQ5/p1688747375186529?thread_ts=1688726115.843029&cid=C1QP38NQ5), it was suggested we include `@expo/metro-config` in deep dependency version checking, to check any case where this package is the wrong version, not just direct installs.
1. Added `@expo/metro-config` to the staging API with `et update-versions -k 'relatedPackages.@expo/metro-config' -v '~0.10.0'`.
2. Updated Doctor to respect `EXPO_STAGING=1` for API calls, so then we could test the additional related package in the API.
3. Added `@expo/metro-config` to the existing list of deep dependency version checks
- Update release documentation to note that we should update the `@expo/metro-config` version …

[doctor] @expo/metro-config deep dependency check

---

.github/workflows/test.yml
.github/workflows/test_windows.yml
packages/pwa/src/Manifest.ts
packages/pwa/src/Manifest.types.ts
packages/pwa/src/cli.ts
packages/pwa/src/index.ts
packages/webpack-config/e2e/basic/App.js
packages/webpack-config/e2e/basic/app.config.js
packages/webpack-config/e2e/basic/babel.config.js
packages/webpack-config/e2e/basic/package.json
packages/webpack-config/e2e/basic/yarn.lock
packages/webpack-config/e2e/custom-homepage/babel.config.js
packages/webpack-config/e2e/custom-homepage/package.json
packages/webpack-config/e2e/custom-homepage/yarn.lock
packages/webpack-config/e2e/minimum/babel.config.js
packages/webpack-config/e2e/minimum/index.js
packages/webpack-config/e2e/minimum/package.json
packages/webpack-config/e2e/minimum/yarn.lock
packages/webpack-config/package.json
packages/webpack-config/src/plugins/ExpoAppManifestWebpackPlugin.ts
packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
packages/webpack-config/src/plugins/ExpoPwaManifestWebpackPlugin.ts

- Nothing breaking, this just adjusts the repo to be on latest

feat(webpack): Bump expo to SDK 49

---

packages/create-expo-app/src/utils/npm.ts

Realm has a scoped package for its expo template.  This was not working with `expo-create-app`.
Fixes #4749 
This change detects a scoped package name for templates and correctly determines its location. 
Tested with `@realm/expo-template`
```
node build/index.js --template @realm/expo-template testProj
```

fix(create-expo-app): allow scoped template package names

---

packages/create-expo-app/README.md
packages/create-expo-app/e2e/__tests__/index-test.js
packages/create-expo-app/src/__tests__/resolvePackageManager.test.ts
packages/create-expo-app/src/cli.ts
packages/create-expo-app/src/resolvePackageManager.ts

Depends on https://github.com/expo/expo/pull/24168
Detect bun package manager in `create-expo-app`
- Checks `npm_config_user_agent` for `bun`
Tests have been addeed to `resolvePackageManager.test.ts`

feat: detect bun package manager

---

packages/babel-preset-cli/__tests__/__snapshots__/index-test.js.snap
packages/expo-doctor/package.json
packages/image-utils/package.json
yarn.lock

Let's bring the CI back to life.
- Ran `yarn test -u` in **./packages/babel-preset-cli**
- Snapshot update seems ok, just an additional var being used without changing meaning of code.
- Added missing `@types/node-fetch` to **./packages/image-utils**
- Added missing `debug` and `@types/debug` to **./packages/expo-doctor**
See CI

chore(babel-preset-cli): update snapshot failure

---

packages/install-expo-modules/src/index.ts

I fixed a typo by removing the extra "some" from the promptCliIntegrationAsync function prompt
I noticed this typo while integrating Expo into my React Native application
I fixed it by removing a word
Not necessary

Typo: Update index.ts

---

packages/expo-cli/bin/expo.js
packages/expo-cli/src/exp.ts

Error messages that point to the [new Expo CLI medium post](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421)
With the way it was, it was including the period (with some CLI GUIs), this fixes that.
Just removed the period so no matter what CLI the user is using, it doesn't 404 when they click on the url.
N/A

[Doc] [Bug Fix]: fixes 404 issue on click with some cli's
