expo/expo-cli

packages/exp/src/exp.js

[exp] Show a message about upgrading to expo-cli

---

packages/exp/src/commands/bundle-assets.js

Typo in command description

---

packages/xdl/src/Project.js

Currently, the release channel of an ExpoKit project is set only once, at the time of ejecting. If the developer then publishes to a different release channel, the new manifest + bundle will be copied to the filesystem and embedded in the app, but the app will still be pointing to the old release channel. This can lead to a confusing situation in which it appears that OTA updates are broken.
This PR makes `publishAsync` also update the release channel of an ExpoKit project. This means that the embedded manifest + bundle will always match the hardcoded release channel after publishing, which should mitigate the situation above. I don't think this is unexpected behavior (and if developers did not want to change the release channel of their app, it would be easy enough to notice this …

[xdl] update release channel when publishing an ExpoKit project

---

.circleci/config.yml

[circleci] use 'yarn bootstrap' instead of 'bin/boostrap'

---

packages/xdl/package.json

Fix http adapter to allow HTTPS connections via HTTP

---

packages/expo-cli/src/commands/build/AndroidBuilder.js
packages/expo-cli/src/commands/build/BaseBuilder.js
packages/expo-cli/src/commands/build/IOSBuilder.js
packages/xdl/src/Project.js

I've observed that the same users are rebuilding their apps over and over again, I guess they don't know Expo has over-the-air updates.
In this PR I added printing a reminder about over-the-air updates if a user has already built his app before.
Tested locally.
https://github.com/expo/universe/pull/3253

[expo-cli] print a reminder about expo publish

---

packages/expo-cli/src/commands/build.js
packages/expo-cli/src/commands/build/IOSBuilder.js
packages/xdl/src/Project.js

[exp] Apple credentials available to supply via cmd

---

packages/xdl/src/Project.js

Should fix https://forums.expo.io/t/could-not-load-embedded-manifest-android/14713/6?u=sjchmiela

Fix Android detach not being able to load embedded manifest

---

packages/xdl/src/detach/Detach.js

To fix iOS standalone app builds from a shell app with unversioned code only.

[xdl] add TEMPORARY_SDK_VERSION to the EXBuildConstants file

---

package.json
yarn.lock

Automatically run `prettier` for staged files before committing.

Add prettier configuration back

---

packages/expo-cli/src/commands/publish.js

Fixes a misspelling in a warning log while publishing.

Fixes cli typo

---

packages/xdl/src/detach/AndroidShellApp.js
packages/xdl/src/detach/Detach.js

Step of https://github.com/expo/expo/issues/2621, prerequisite for https://github.com/expo/expo/pull/2836 and https://github.com/expo/universe/pull/3316.

[android] Shell and ejected apps unified

---

packages/xdl/src/Project.js
packages/xdl/src/detach/AndroidShellApp.js
packages/xdl/src/detach/AssetBundle.js
packages/xdl/src/detach/Detach.js
packages/xdl/src/detach/IosNSBundle.js

[xdl] fix bundling assets for self-hosted apps

---

packages/expo-cli/src/commands/eject/Eject.js
packages/expo-cli/src/exp.js
packages/expo-cli/src/log.js

Output with warnings:
Happy path:
Fixes #161.

 Improve wording in output of `expo eject`

---

.gitignore
packages/expo-cli/.flowconfig
packages/expo-cli/src/commands/build.js
packages/expo-cli/src/commands/build/AndroidBuilder.js
packages/expo-cli/src/commands/build/BaseBuilder.js
packages/expo-cli/src/commands/build/IOSBuilder.js
packages/xdl/src/Project.js

Detect unnecessary builds and informs the user about them.

[expo-cli] try to reuse existing builds

---

packages/xdl/src/modules/config.js

Merge https://github.com/expo/expo/pull/3187 first

[xdl] Add expo-av universal module

---

packages/xdl/src/modules/config.js

Published as `xdl@52.0.14-beta.3`

[xdl] Add expo-blur universal module

---

packages/xdl/src/modules/config.js

Corresponds to https://github.com/expo/expo/pull/3284

[xdl][expo-document-picker] Add module config

---

packages/xdl/src/modules/config.js

Corresponding update for https://github.com/expo/expo/pull/3245

[xdl][expo-image-manipulator] Update modules config

---

packages/xdl/src/modules/config.js

Blocked by https://github.com/expo/expo/pull/3427

[xdl] add expo-intent-launcher config

---

packages/expo-cli/src/commands/build/ios/appleApi/authenticate.js

Previously when the `--apple-id` flag was passed to `expo build:ios`, but the `EXPO_APPLE_PASSWORD` environment variable was not set, Expo CLI prompted for both Apple ID and password.
This PR changes the behavior to only prompt for a password, if the username is provided through the `--apple-id` flag and and additionally makes a few minor adjustments to the output.

[expo-cli] Allow passing --apple-id without EXPO_APPLE_PASSWORD

---

packages/expo-cli/package.json
packages/expo-cli/src/exp.js
yarn.lock

This makes it easier to distinguish it from other green colored output that might follow.

[expo-cli] Put the update notification in a box

---

packages/xdl/src/Project.js

Minify production source code from `expo export`

---

packages/expo-cli/src/commands/upload.js
packages/expo-cli/src/commands/upload/IOSUploader.js
packages/expo-cli/src/commands/upload/utils.js

- run fastlane with stdin
- add `--itc-team-id` option to upload ios
Closing #182

[expo-cli] add select itc team in upload:ios command

---

packages/xdl/src/detach/AndroidShellApp.js

Response to https://github.com/expo/turtle/commit/2771ad0829f07500fc6a925e5a1ae6032cd70ddf regarding  https://github.com/expo/turtle/pull/3

[xdl] Apply SplashScreen on standalone fixes since SDK33

---

packages/expo-cli/src/commands/build/index.js

Teeny tiny typo

---

packages/expo-cli/src/commands/build/ios/IOSBuilder.js

[expo-cli] don't allow to use png icon with alpha channel

---

packages/webpack-config/package.json
packages/webpack-config/webpack.config.js
packages/webpack-config/webpack/createBabelConfig.js
packages/webpack-config/webpack/webpack.common.js
packages/webpack-config/webpack/webpackLocations.js
yarn.lock

* Moved aliases from babel-preset-expo
* Added optional override for root webpack.config.js
* Added optional override for root webpack.dev.js
* Added optional override for root webpack.prod.js
* Fixed absolute location function
* Moved babel config to method
* Bump 0.1.3 -> 0.1.4

Added unimodules to config

---

packages/expo-cli/src/commands/start.js
packages/expo-cli/src/commands/start/TerminalUI.js
packages/expo-cli/src/commands/url.js
packages/expo-cli/src/urlOpts.js
packages/webpack-config/webpack/webpack.dev.js
packages/xdl/src/Project.js
packages/xdl/src/UrlUtils.js
packages/xdl/src/Web.js

* Added web flag to url command. 
* Updated `https`
* Run on ip by default

`expo url --web`

---

packages/xdl/src/Web.js

warn users that web is not ready for prod yet.

Added web warning

---

packages/webpack-config/webpack/Metatags.js
packages/webpack-config/webpack/createClientEnvironment.js
packages/webpack-config/webpack/createIndexHTMLFromAppJSON.js
packages/webpack-config/webpack/createMetatagsFromConfig.js
packages/webpack-config/webpack/webpack.common.js
packages/webpack-config/webpack/webpackLocations.js

* Added default values for app.json
* Fixed RNCLI name usage
* Unified more values (pending expo/config)
* Added metatags
* moved from #436

Added metatag data to webpack config

---

packages/webpack-config/web-default/index.html

* Fixed no script
* Added default font size
* Using same language iso code in HTML as manifest

Updated default HTML style

---

packages/webpack-config/webpack/webpack.common.js

* Can disable service worker
* Can change default settings of service worker

Added basic service worker config

---

packages/xdl/src/Exp.js

Fix creating .gitignore in `expo init`

---

packages/webpack-config/web-default/index.html
packages/webpack-config/webpack/webpack.common.js

fixed: web styles preventing body scrolling

---

packages/dev-tools/server/graphql/GraphQLSchema.js
packages/expo-cli/src/commands/eject/Eject.js
packages/xdl/src/Exp.js
packages/xdl/src/Project.js
packages/xdl/src/__tests__/project/ProjectUtils-test.js
packages/xdl/src/detach/Detach.js
packages/xdl/src/project/ProjectUtils.js

These functions have moved to @expo/config

Remove legacy config functions from xdl

---

packages/webpack-config/webpack/webpack.common.js
packages/webpack-config/webpack/webpack.dev.js

* Fix dev utils not displaying errors correctly
* Clean up logging
#434

[web] Updated dev server logging

---

packages/webpack-config/webpack/webpack.common.js

Added support for new NetInfo pending web support https://github.com/react-native-community/react-native-netinfo/pull/47

Added alias for community netinfo package

---

packages/config/src/Config.js
packages/webpack-config/webpack.config.js
packages/webpack-config/webpack/createBabelConfig.js
packages/webpack-config/webpack/createIndexHTMLFromAppJSON.js
packages/webpack-pwa-manifest-plugin/src/Metatags.js

Fixed syntax errors from PWA manifest plugin using config library

Fixed manifest CLI bugs

---

packages/expo-cli/src/commands/start.js
packages/xdl/src/Web.js

Trying to create a very simple path to starting web so things like code sandbox can use it easily.

[web] Removed QR when metro isn't fired up

---

packages/expo-cli/src/commands/start/TerminalUI.js
packages/expo-cli/src/urlOpts.js
packages/xdl/src/Project.js

Ensure webpack is running before attempting to open web

---

packages/config/package.json
packages/config/src/Config.js

* Moved constants
* Added web.dangerous
* Added addPlatform from #434
* Added isUsingYarn from #434

[config] Split manifest validation into multiple methods

---

packages/webpack-pwa-manifest-plugin/src/createMetatagsFromConfig.js
packages/webpack-pwa-manifest-plugin/src/icons.js
packages/webpack-pwa-manifest-plugin/src/index.js
packages/webpack-pwa-manifest-plugin/src/injector.js

* prevent the `env` from being added to the `manifest.json`
* prevent `icon` from overriding `icons`
* Generate metatags from `expo.web.meta`

[pwa-manifest] Fix env bug and icons

---

packages/config/src/Config.js
packages/webpack-config/webpack/webpack.common.js
packages/webpack-config/webpack/webpackLocations.js
packages/webpack-pwa-manifest-plugin/src/createMetatagsFromConfig.js
packages/webpack-pwa-manifest-plugin/src/index.js
packages/webpack-pwa-manifest-plugin/src/injector.js
packages/xdl/src/Web.js

* Added support for legacy 'all' platform
* Moved validation to expo-config
* Added apple metatag validation
* Reading locations from validated config
* Moved meta validation to config
* Generating icons correctly

meta tag validation updates

---

packages/xdl/src/Project.js
packages/xdl/src/detach/AndroidShellApp.js

- add package.json to manifest when publishing
- create enabled-modules directory in turtle shellapp

[expo-cli][xdl] support android custom builds

---

packages/xdl/src/modules/config.js

Ref https://github.com/expo/expo/pull/3980

Add expo-video-thumbnails to the config

---

packages/expo-cli/src/commands/build/BaseBuilder.js

Add some messages telling users that they can now upgrade to get faster priority builds.
`expo build:ios` / `expo build:android`:
`expo build:status`, build in progress (only first build on the list includes the message):
`expo build:status`, build finished:

Add messaging about priority builds in the build commands

---

packages/config/src/Config.js
packages/webpack-config/web-default/index.html
packages/webpack-config/webpack/utils/getPaths.js
packages/webpack-config/webpack/webpack.common.js
packages/webpack-config/webpack/webpack.dev.js
packages/webpack-config/webpack/webpack.prod.js
packages/webpack-pwa-manifest-plugin/src/createMetatagsFromConfig.js
packages/webpack-pwa-manifest-plugin/src/icons.js
packages/webpack-pwa-manifest-plugin/src/index.js
packages/webpack-pwa-manifest-plugin/src/injector.js
packages/xdl/src/Webpack.js

* Set a non-zooming viewport 
* Notify user which mode they're running
* Fix undefined icons type
* Added override for lib require 
* Removed extra apple parsing
* Filter out startup images to prevent android PWA bundling
* Update `createMetatagsFromConfig.js`
* Removed public path for manifest
* Ensure plugins are in the correct order
* Removed extra process

[web] Fixed various bugs related to building PWAs

---

scripts/publish.js

Now you can publish using `./scripts/publish.js`
Also changed file permissions to make it executable.

Add node shebang to publish script

---

packages/xdl/src/detach/IosPodsTools.js

For https://github.com/expo/expo/pull/4158

[xdl] Add HAVE_GOOGLE_MAPS=1 preprocessor definiton

---

packages/xdl/src/modules/config.js

[xdl] remove duplicated expo-facebook module

---

packages/xdl/src/detach/IosPodsTools.js

CocoaPods 1.6 changed the Ruby API so we need to make some changes in the emitted Ruby code within the generated Podfiles. This is not backwards-compatible with CocoaPods 1.5. So for SDK 33 we'll require CocoaPods 1.6, and for SDK 32 we'll require CocoaPods 1.5 (and want to keep 1.5 compatibility so that people can keep the version of CocoaPods they already have for SDK 32 projects).
This commit changes the way we get the `native_target` object to use an approach recommended by one of the CocoaPods maintainers. It also changes the way we set up the framework search paths; namely, we want to fall back on `$(inherited)`, which gets set to look for all of the installed CocoaPods' frameworks. This is so that we can use `@import` syntax in Objective-C, which is necessary for FBAudienceNetwork …

[xdl] Update Podfile generator for CocoaPods 1.6 support for SDK 33

---

packages/expo-cli/bin/expo.js

See https://github.com/expo/expo-cli/issues/457.

Drop Node v6 support

---

packages/xdl/src/Web.js
packages/xdl/src/Webpack.js

Custom configs could be async, this'll account for that possibility

Account for webpack config being async

---

packages/xdl/src/Web.js
packages/xdl/src/createWebpackCompiler.js

Added an environment variable for making prod debugging easier.
Related: https://github.com/expo/expo-cli/issues/614

Added EXPO_WEB_DEBUG to disable minimizer and add file paths

---

packages/webpack-config/web-default/index.html

Make CSS body > div style less intrusive

---

packages/webpack-pwa-manifest-plugin/package.json
packages/webpack-pwa-manifest-plugin/src/icons.js

Reduce PWA image generation (`expo build:web`) time by ~60 seconds

Replace Jimp with sharp

---

packages/expo-codemod/README.md

docs: remove misleading paths example

---

packages/webpack-config/webpack/webpack.common.js

* Don't cache any assets in dev mode.

feat(webpack-config): enable SW in dev mode for notifications

---

packages/xdl/src/detach/IosShellApp.js

https://github.com/expo/expo/pull/4645

[xdl] Add option to use modern build system for SDKs > 33

---

packages/webpack-config/webpack/utils/getPathsAsync.js

Resolves: https://github.com/expo/expo/issues/4613

[web] Added new main entry point

---

packages/xdl/src/detach/Logger.ts

[xdl] fix extraFields in logger

---

packages/xdl/src/detach/IosPodsTools.js

Having default deployment targets raises warnings in Xcode. Fixes a TODO left by Ben.

feat(xdl): set deployment target for all pods

---

packages/xdl/src/modules/config.ts

- Add expo-battery package to config 
- Reorder expo-device in config to be in correct alphabetical order

feat(xdl): add expo-battery package

---

.circleci/config.yml

We should be able to support this and I've been worried about a few reports of problems.

chore: test on node 12.x

---

packages/config/src/Config.ts

fixes https://github.com/expo/expo/issues/4784

Added support for `manifest.extra` in the expo-constants lib

---

packages/expo-cli/src/commands/upload/BaseUploader.js

This is in regard to Issue #777 
Hi, I've changed the file I just don't know how to continue with the test plan... Any suggestions?

improvement: fix a little typo in `expo upload:ios`

---

packages/babel-preset-cli/ts-declarations/expo__bunyan/index.d.ts
packages/xdl/src/detach/ExponentTools.ts
packages/xdl/src/detach/Logger.ts
packages/xdl/src/logs/PackagerLogsStream.ts

I simplified `LoggerDetach` and fixed printing logs (with "extra fields") in Turtle at the same time.

fix(xdl): fix LoggerDetach

---

packages/expo-cli/src/commands/build/ios/credentials/generate.js
packages/traveling-fastlane/actions/ensure_app_exists.rb

Fixes https://github.com/expo/expo-cli/issues/830
Thanks @cruzach :)

enable push notifications by default

---

packages/xdl/src/detach/AndroidShellApp.js

https://github.com/expo/turtle/issues/115

[xdl] fix android debug builds

---

packages/xdl/src/detach/AndroidShellApp.js

This will fix https://github.com/expo/expo-cli/issues/870 once updated in Turtle.

[xdl] fix setting Constants.nativeAppVersion (Android)

---

packages/xdl/src/detach/IosShellApp.js

Disable CocoaPods stats before automating the build

---

packages/xdl/src/detach/IosPodsTools.js
packages/xdl/src/modules/config.ts

- Ensure the module isn't included in the managed workflow

[bluetooth] Added module stub for expo-bluetooth

---

packages/webpack-config/tests/__tests__/basic-test.js
packages/webpack-config/tests/basic/App.js
packages/webpack-config/webpack/createClientEnvironment.js

Projects should be able to act a certain way when running in CI

[webpack-config] Pass the CI env down to projects

---

.circleci/config.yml
packages/expo-cli/e2e/TestUtils.ts
packages/expo-cli/e2e/__tests__/init-test.ts
packages/expo-cli/e2e/__tests__/start-test.ts
packages/expo-cli/package.json
yarn.lock

This PR adds end-to-end tests for the `expo start` and `expo init` commands.

test(expo-cli): add e2e (end-to-end) tests for start and init

---

packages/xdl/src/detach/IosCodeSigning.js

https://github.com/expo/expo/pull/5421

[xdl] handle ios.usesAppleSignIn manifest key for SDK 35

---

.circleci/config.yml
packages/schemer/__tests__/helper-test.js
packages/schemer/__tests__/test.js
packages/schemer/babel.config.js
packages/schemer/jest.config.js
packages/schemer/package.json
yarn.lock

[schemer] Fixed tests

---

packages/webpack-config/package.json
packages/webpack-config/src/createDevServerConfigAsync.ts
packages/webpack-config/src/index.ts
packages/webpack-config/src/types.ts
packages/webpack-config/src/utils/__tests__/__snapshots__/validate.js.snap
packages/webpack-config/src/utils/__tests__/validate.js
packages/webpack-config/src/utils/validate.ts
packages/webpack-config/src/webpack.common.ts
packages/webpack-config/src/webpack.config.unimodules.ts
packages/webpack-config/src/webpack.dev.ts
packages/webpack-config/src/webpack.prod.ts
packages/webpack-config/src/withUnimodules.ts
packages/webpack-config/withUnimodules.js
packages/xdl/src/Web.ts
packages/xdl/src/Webpack.ts
yarn.lock

Validate the config and ensure that errors are more clear.

[webpack-config] Added env validation

---

packages/expo-cli/src/commands/build/ios/credentials/prompt/index.js

The current message does not flow very well so I made some minor changes.

Update missing credentials warning

---

.circleci/config.yml
packages/android-manifest/.gitignore
packages/android-manifest/LICENSE
packages/android-manifest/README.md
packages/android-manifest/babel.config.js
packages/android-manifest/jest.config.js
packages/android-manifest/package.json
packages/android-manifest/src/Manifest.ts
packages/android-manifest/src/__tests__/Manifest-test.js
packages/android-manifest/src/__tests__/__snapshots__/Manifest-test.js.snap
packages/android-manifest/src/__tests__/fixtures/react-native-AndroidManifest.xml
packages/android-manifest/tsconfig.json
yarn.lock

- created `android-manifest` to read/write the project manifest
- tested E2E cases
- tested individual methods for writing permissions
- Moved from #991

Created android-manifest

---

packages/expo-cli/src/commands/build/index.js
packages/webpack-config/package.json
packages/webpack-config/src/webpack.common.ts
packages/xdl/src/Web.ts
packages/xdl/src/Webpack.ts
yarn.lock

Deprecated the expo-cli build:web polyfill flag

---

packages/expo-cli/package.json
packages/expo-cli/src/PackageManager.ts
packages/expo-cli/src/commands/eject/Eject.js
packages/expo-cli/src/commands/index.ts
packages/expo-cli/src/commands/install.js
packages/expo-cli/src/commands/upgrade.ts
packages/expo-cli/src/commands/utils/ProjectUtils.ts
packages/xdl/src/Versions.ts
yarn.lock

Just putting it up here, still some more work to do, feel free to review though

[expo-cli] First pass at expo upgrade command

---

packages/webpack-config/src/webpack.common.ts
packages/webpack-config/web-default/index.html

@FiberJW pointed out that this disrupts the browsers A11Y font adjustment.

[webpack-config] Removed font-size 14px on the HTML root

---

packages/expo-cli/src/commands/customize.ts
packages/webpack-config/template/babel.config.js

Added babel.config.js to customize

---

packages/webpack-config/src/webpack.common.ts

fix https://github.com/expo/expo-cli/issues/997

[webpack-config] Disable performance warning in CI

---

packages/config/src/Config.ts
packages/json-file/src/JsonFile.ts

Should fix https://github.com/expo/expo-cli/issues/1011

Added support for sync reading JSON5 files

---

packages/xdl/src/Webpack.ts

Prevent bug where running expo build:web causes the next use of expo start to use production mode

[xdl][Webpack] Fix dev caching issue

---

packages/webpack-config/extensions.js
packages/webpack-config/src/extensions.ts
packages/webpack-config/src/index.ts
packages/webpack-config/src/types.ts
packages/webpack-config/src/utils/loaders.ts
packages/webpack-config/src/utils/paths.ts
packages/webpack-config/src/webpack.common.ts
packages/webpack-config/src/withWorkbox.ts
packages/webpack-config/web-default/index.html
packages/webpack-config/web-default/register-service-worker.js

Because this changes a lot of static files, we should release this as a major bump.
fix https://github.com/expo/expo-cli/issues/449

Added offline support for expo web projects

---

packages/xdl/src/modules/config.ts

Add `expo-network` unimodule to config.ts

Add expo-network to config

---

packages/webpack-config/web-default/index.html

ref [expo/expo#5081](https://github.com/expo/expo/issues/5081)

[web] fixed screen height

---

packages/webpack-config/web-default/index.html

Revert "[web] fixed screen height"

---

packages/config/__mocks__/fs.js
packages/config/__mocks__/resolve-from.js
packages/config/package.json
packages/config/src/Config.ts
packages/config/src/Modules.ts
packages/config/src/__tests__/Config-test.js
packages/config/src/__tests__/Modules-test.js
packages/webpack-config/src/utils/__tests__/__snapshots__/getConfigAsync-test.js.snap
yarn.lock

- Tests for https://github.com/expo/expo-cli/pull/1103

Added tests for sdk version resolution

---

packages/xdl/src/detach/AndroidShellApp.js
packages/xdl/src/detach/IosNSBundle.ts

x-ref https://github.com/expo/expo/pull/5924

[xdl] Add support for Facebook buildtime customizations

---

packages/webpack-config/src/extensions.ts
packages/webpack-config/src/loaders/createFontLoader.ts
packages/webpack-config/src/webpack.config.ts
packages/webpack-config/src/withUnimodules.ts

Added woff2 and eot formats to webpack-config

---

packages/xdl/src/detach/IosNSBundle.ts

https://github.com/expo/expo/pull/5977

[xdl] add note to generated entitlemnts file

---

packages/config/src/Config.ts
packages/config/src/__tests__/Config-test.js

Test results of the three different methods for modifying the results of `getWebOutputPath`

Added tests for `getWebOutputPath`

---

packages/expo-cli/src/commands/whoami.ts
packages/xdl/src/User.ts

fix(expo-cli): fix whoami result after "log out of all sessions"

---

packages/webpack-config/src/__tests__/withAlias-test.js
packages/webpack-config/src/extensions.ts
packages/webpack-config/src/loaders/createBabelLoader.ts
packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
packages/webpack-config/src/plugins/index.ts
packages/webpack-config/src/types.ts
packages/webpack-config/src/utils/getConfig.ts
packages/webpack-config/src/utils/loaders.ts
packages/webpack-config/src/utils/paths.ts
packages/webpack-config/src/utils/validate.ts
packages/webpack-config/src/webpack.config.ts
packages/webpack-config/src/withAlias.ts
packages/webpack-config/src/withUnimodules.ts

- moved from electron PR #1180

[webpack-config] Add more composition methods

---

README.md

¯\\\_(ツ)_/¯ 
Preview: https://github.com/expo/expo-cli/blob/@evanbacon/readme-updates/README.md

Added CI link to readme

---

.circleci/config.yml
packages/webpack-config/package.json

Split NextJS E2E tests in CI

---

packages/image-utils/src/index.ts
packages/image-utils/src/sharp.ts
packages/webpack-config/jest/build-project.js
packages/webpack-config/src/webpack.config.ts
packages/webpack-config/tests/__tests__/basic-test.js
packages/webpack-pwa-manifest-plugin/src/icons.ts
packages/xdl/src/Web.ts
packages/xdl/src/Webpack.ts

make it so that E2E tests don't fail when run locally because they aren't in CI

[webpack-config] fix test regarding running CI locally

---

packages/xdl/src/detach/AndroidShellApp.js
packages/xdl/src/detach/IosNSBundle.ts

x-ref: https://github.com/expo/expo/pull/6237

[xdl] handle googleMobileAdsAutoInit field

---

packages/config/src/Config.ts
packages/expo-cli/src/commands/eject/Eject.ts
packages/expo-cli/src/commands/push-creds.ts
packages/xdl/src/Exp.ts
packages/xdl/src/Project.ts
packages/xdl/src/detach/Detach.js
packages/xdl/src/project/Doctor.ts

Deprecated
- findConfigFileAsync
- configFilenameAsync

[config] deprecate methods

---

packages/config/package.json
packages/config/paths/index.d.ts
packages/config/paths/index.js
packages/next-adapter/src/withExpo.ts
packages/webpack-config/getWebExtensions.js
packages/webpack-config/src/loaders/createBabelLoader.ts
packages/webpack-config/src/utils/extensions.ts
packages/webpack-config/src/utils/paths.ts

We should consider splitting this into a new package

[config] export paths from alias

---

packages/expo-cli/src/commands/upgrade.ts

feat(expo-cli): ask to close expo when upgrading

---

packages/xdl/src/Project.ts

- use the same extension order across web and native
- do we support MJS on native?

[xdl] unify source extensions on native

---

packages/expo-cli/src/credentials/actions/list.ts
packages/expo-cli/src/credentials/views/AndroidCredentials.ts
packages/expo-cli/src/credentials/views/IosDistCert.ts
packages/expo-cli/src/credentials/views/IosPushCredentials.ts

- `durring` -> `during`
- `assingned` -> `assigned`
- auto prettier formats upon saving changed file

credentials: fix typos + format nits

---

packages/dev-tools/server/graphql/GraphQLSchema.js
packages/xdl/src/project/ProjectUtils.ts

Add back methods removed in https://github.com/expo/expo-cli/pull/1194
fix https://github.com/expo/expo-cli/issues/1227

[xdl] Revert deprecation

---

packages/webpack-pwa-manifest-plugin/package.json
yarn.lock

noticed this extra copy, it breaks electron adapter in prod

remove webpack-cli from PWA manifest

---

packages/electron-adapter/README.md

- Hold for PR https://github.com/expo/expo/pull/6240

[electron-adapter] redirect to expo docs

---

packages/electron-adapter/bin/expo-electron.js

[electron-adapter] Fix missing webpack-config bug

---

packages/xdl/src/detach/IosPodsTools.js

Due to React Native upgrade to 0.61 in SDK36, we need to slightly change iOS Podfile generation for ejected projects.
- Used `use_react_native!` instead of listing all React Native podspecs
- Fix one condition that was passing only for React podspec, now we need to apply these build settings changes to all dependencies whose names start with `React`
Tested by ejecting to SDK36 ExpoKit project. `pod install` passes and project builds fine in Xcode.

feat(xdl): Adjust iOS podfile generation for SDK36

---

packages/expo-cli/src/exp.ts

This allows us to generate documentation for expo-cli directly from the cli itself rather than copy and paste and format things manually.

[expo-cli] introspect command to output command info as json and markdown

---

packages/expo-cli/src/commands/upgrade.ts

Ask to upgrade simulator and android clients when upgrading

---

packages/babel-preset-cli/ts-declarations/brotli-webpack-plugin/index.d.ts
packages/babel-preset-cli/ts-declarations/compression-webpack-plugin/index.d.ts
packages/babel-preset-cli/ts-declarations/mini-css-extract-plugin/index.d.ts
packages/babel-preset-cli/ts-declarations/pnp-webpack-plugin/index.d.ts
packages/babel-preset-cli/ts-declarations/postcss-safe-parser/index.d.ts
packages/babel-preset-cli/ts-declarations/react-dev-utils/index.d.ts
packages/babel-preset-cli/ts-declarations/webpack-deep-scope-plugin/index.d.ts
packages/webpack-config/src/addons/withCompression.ts
packages/webpack-config/src/addons/withOptimizations.ts
packages/webpack-config/src/webpack.config.ts

add ts-declarations for webpack plugins

[webpack-config] remove most `ts-ignore`s

---

packages/expo-cli/src/commands/upload/AndroidUploader.ts

Fixes https://github.com/expo/expo-cli/issues/1179

[expo-cli] make fastlane command output readable

---

packages/expo-cli/src/commands/upload/BaseUploader.ts
packages/expo-cli/src/commands/upload/IOSUploader.ts

Fixes #1286. 
The bug has been introduced in https://github.com/expo/expo-cli/commit/2abd81b14bd056f82bbca6fcb3be35c4a152cbc9

[expo-cli] fix prompting for apple id and password

---

packages/webpack-config/package.json
yarn.lock

- `find-yarn-workspace-root`
- `webpack-merge`

[webpack-config] remove unused dependencies

---

packages/xdl/CHANGELOG.md
packages/xdl/src/detach/AndroidShellApp.js

Prerequisite for https://github.com/expo/expo/pull/6475.
This change won't affect other SDKs since there will be no such pattern in the `AndroidManifest` there.

[xdl] Replace pattern with Facebook scheme

---

.eslintignore
packages/webpack-config/.eslintignore
packages/webpack-config/.eslintrc.js
packages/webpack-config/jest-puppeteer.config.js
packages/webpack-config/package.json
packages/webpack-config/src/addons/__tests__/withCompression-test.js
packages/webpack-config/src/addons/__tests__/withEntry-test.js
packages/webpack-config/src/addons/__tests__/withOptimizations-test.js
packages/webpack-config/src/addons/__tests__/withReporting-test.js
packages/webpack-config/src/env/__tests__/getConfig-test.js
packages/webpack-config/src/env/__tests__/getMode-test.js
packages/webpack-config/src/env/__tests__/paths-test.js
packages/webpack-config/src/env/__tests__/validate-test.js
packages/webpack-config/src/env/paths.ts
packages/webpack-config/src/loaders/__tests__/createAllLoaders-test.js
packages/webpack-config/src/loaders/__tests__/createBabelLoader-test.js
packages/webpack-config/src/utils/__tests__/search-test.js
packages/webpack-config/src/webpack.config.ts

[webpack-config] fix linting

---

packages/expo-cli/src/commands/build-native/Builder.ts
packages/expo-cli/src/commands/build-native/utils.ts

related PR: https://github.com/expo/turtle-v2/pull/102/files

[expo-cli][turtle-v2] use new endpoints

---

packages/expo-cli/src/commands/publish-info.js

same as `publish:history` but for `publish:details`
To test locally, checkout this universe PR: https://github.com/expo/universe/pull/3963
(Also, probably should wait for the above branch to be finished before merging this one)

add apiv2 publish:details option

---

packages/dev-tools/server/graphql/GraphQLSchema.js
packages/expo-cli/src/commands/start/TerminalUI.js
packages/xdl/src/Exp.ts

To test use universe branch: @jkhales/make-apiv2-endpoint-send 
To use set: `EXPO_NEXT_API=true`

add apiV2 option for send

---

packages/xdl/src/Project.ts

Pair with PR:
Change line 1357 to 
`const missing = Object.keys(paths).filter(key => metas[key].exists);`
to force an upload

@jkhales/add apiv2 option assets

---

packages/android-manifest/package.json
packages/android-manifest/src/Manifest.ts
packages/android-manifest/src/__tests__/Manifest-test.js
packages/android-manifest/src/__tests__/__snapshots__/Manifest-test.js.snap
yarn.lock

https://github.com/expo/expo-cli/pull/1247

Replace native libxmljs with xml2js

---

packages/expo-cli/src/commands/eject/Eject.ts
packages/xdl/package.json
packages/xdl/src/detach/IosSetBundleIdentifier.ts
packages/xdl/src/detach/IosWorkspace.js
yarn.lock

Set bundle identifier on an ejected bare project

---

packages/expo-cli/src/commands/init.ts

Seems like if a user runs `expo init <name>`, they probably would expect not to see a name prompt. This only skips the prompt for managed projects as bare projects could be harder to rename.
Also skip the red `undefined` log when a user cancels out of the name prompt.

Skip the project name/slug prompt when a user runs `expo init name`

---

packages/expo-cli/src/commands/build-native/Builder.ts
packages/expo-cli/src/commands/build-native/utils.ts

[expo-cli] turtle-v2: print logs url

---

packages/xdl/src/createWebpackCompiler.ts

https://github.com/expo/expo/issues/6782

[web] update beta warning

---

packages/expo-cli/src/appleApi/provisioningProfileAdhoc.ts
packages/expo-cli/src/credentials/api.ts
packages/expo-cli/src/credentials/views/IosProvisioningProfileAdhoc.ts

The adhoc provisioning profile version of https://github.com/expo/expo-cli/pull/1381

refactor(cli) create adhoc profile selector

---

packages/xdl/src/Exp.ts

Start roll out apiv2 switch with send.

make apiv2 default behavior with send

---

packages/next-adapter/src/customize/manifest.ts

Move `@expo/next-adapter` to dev deps

---

packages/webpack-config/src/Diagnosis.ts
packages/webpack-config/src/addons/withAlias.ts
packages/webpack-config/src/addons/withCompression.ts
packages/webpack-config/src/addons/withDevServer.ts
packages/webpack-config/src/addons/withEntry.ts
packages/webpack-config/src/addons/withNodeMocks.ts
packages/webpack-config/src/addons/withOptimizations.ts
packages/webpack-config/src/addons/withReporting.ts
packages/webpack-config/src/addons/withTypeScriptAsync.ts
packages/webpack-config/src/addons/withUnimodules.ts
packages/webpack-config/src/addons/withWorkbox.ts
packages/webpack-config/src/env/alias.ts
packages/webpack-config/src/env/extensions.ts
packages/webpack-config/src/env/getConfig.ts
packages/webpack-config/src/env/getMode.ts
packages/webpack-config/src/env/paths.ts
packages/webpack-config/src/env/validate.ts
packages/webpack-config/src/index.ts
packages/webpack-config/src/loaders/createAllLoaders.ts
packages/webpack-config/src/loaders/createBabelLoader.ts
packages/webpack-config/src/loaders/createFontLoader.ts
packages/webpack-config/src/plugins/ExpoDefinePlugin.ts
packages/webpack-config/src/plugins/ExpoHtmlWebpackPlugin.ts
packages/webpack-config/src/plugins/ExpoInterpolateHtmlPlugin.ts
packages/webpack-config/src/plugins/ExpoProgressBarPlugin.ts
packages/webpack-config/src/utils/config.ts
packages/webpack-config/src/utils/normalizePaths.ts
packages/webpack-config/src/utils/search.ts
packages/webpack-config/src/webpack.config.ts

Added doc blocks to webpack-config

---

packages/webpack-config/src/loaders/createBabelLoader.ts

fix https://github.com/styled-components/styled-components/issues/2624

Add support for styled-components in next.js expo

---

.circleci/config.yml
packages/dev-tools/package.json
packages/webpack-config/package.json
packages/webpack-config/src/loaders/__tests__/createBabelLoader-test.js
packages/webpack-config/src/loaders/createBabelLoader.ts
yarn.lock

- remove dependency on `babel-preset-expo`
- log when no babel config can be found

[webpack-config] Warn when the babel config is missing

---

packages/xdl/src/Exp.ts

- Update error messages to not reference `exp.json`
- Update error messages to be more helpful
- Remove unused sdk version check in favor of expo/config sdk version validation
- Not sure how this method is tested

[xdl] Add `app.config.js` support to `getPublishInfoAsync`.

---

packages/expo-cli/src/commands/init.ts

Fixes https://github.com/expo/expo-cli/issues/1536

[expo-cli] Fix regression in `expo init --template bare-minimum`

---

packages/expo-cli/package.json
packages/traveling-fastlane/Rakefile
packages/traveling-fastlane/actions/resolve_itc_team_id.rb
packages/traveling-fastlane/publishing/darwin/package.json
packages/traveling-fastlane/publishing/linux/package.json
yarn.lock

This should help us debug https://github.com/expo/expo-cli/issues/1535 issue.
This PR makes error handling in resolve_itc_team_id.rb better.

[traveling-fastlane][expo-cli] improve error handling in resolve_itc_team_id.rb script

---

packages/expo-cli/src/commands/eject/Eject.ts
packages/xdl/src/detach/Detach.js

- Ideally this changes nothing except except how the config file is read
- ?? Not sure if there are tests for this module

[xdl] add app.config.js support to detach

---

packages/xdl/src/Project.ts

Continuing with the gradual migration.

[xdl] Make Project.ts default to apiv2

---

packages/traveling-fastlane/actions/manage_provisioning_profiles.rb

- This is the fastlane portion of a previous approved PR https://github.com/expo/expo-cli/pull/1482
- need to bump at least minor version of fastlane, then change expo-cli deps

breaking,feat(fastlane) list(), use-existing() to prov profile script

---

packages/webpack-pwa-manifest-plugin/src/icons.ts

Fix 
```
(node:62589) UnhandledPromiseRejectionWarning: Error: Invalid mimeType for image with source: https://github.com/expo/expo/blob/master/templates/expo-template-blank/assets/icon.png?raw=true
```

[expo build:web] Fix remote image downloading

---

packages/webpack-config/package.json
yarn.lock

Added progress plugin, removed progress-bar-webpack-plugin

---

packages/xdl/src/Android.ts

fix(xdl): clean install with android clients

---

packages/webpack-config/package.json
yarn.lock

fix https://github.com/expo/expo/issues/7419
- `expo start:web` should open without errors

[webpack-config] Bump babel

---

packages/dev-tools/common/state.js
packages/expo-cli/src/commands/start/TerminalUI.ts

fix: broken login prompt after trying to send a link from Dev Tools

---

packages/expo-cli/src/commands/export.ts

Followup to #1734 -- add the same option to `expo export` so it's available to self-hosted apps. This has the same breaking change as well; `expo export` will no longer use `.expo.*` files by default in bare workflow projects.
Tested by logging the output of `sourceExts` in `Project.ts` and ensuring it has the correct extensions when running `expo export`, `expo export --target managed`, and `expo export --target bare` in both a bare and managed workflow project.

[expo-cli] add --target managed|bare option to export

---

packages/expo-cli/src/commands/send.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/url.ts
packages/expo-cli/src/urlOpts.ts

fix https://github.com/expo/expo-cli/issues/1729

[expo-cli] Fix platform parameters for the start command

---

packages/image-utils/package.json
packages/pwa/src/cli.ts
yarn.lock

fix #1748 by setting tempy to a lower version

Fix node warning in expo-pwa

---

packages/pwa/src/Manifest.ts
packages/pwa/src/cli.ts
packages/webpack-config/src/plugins/ApplePwaWebpackPlugin.ts
packages/webpack-config/src/webpack.config.ts

- fix expo-pwa icon --platform
- fix adding multiple meta in head
- fix using too many `manifest.json` values

Fix PWA Webpack bugs

---

packages/xdl/src/EmbeddedAssets.ts
packages/xdl/src/Project.ts
packages/xdl/src/detach/Detach.js

re-opening PR of https://github.com/expo/expo-cli/pull/1745 with correct base branch

[xdl] add default paths for saving embedded assets to disk

---

packages/expo-codemod/package.json
packages/expo-codemod/src/cli.ts

feat(expo-codemod): make codemods install new packages with expo install

---

packages/config/src/__tests__/ConfigParsing-test.js
packages/config/src/__tests__/fixtures/behavior/custom-location-json/app.json
packages/config/src/__tests__/fixtures/behavior/custom-location-json/src/app.staging.json
packages/dev-tools/package.json
packages/expo-cli/package.json

Fix xdl versions

---

packages/xdl/src/credentials/Credentials.ts

https://github.com/expo/expo-cli/issues/1774

[credentials][apiv2] revert updateCredentialsForPlatform

---

packages/expo-cli/src/PackageManager.ts
packages/expo-cli/src/commands/eject/Eject.ts
packages/expo-cli/src/commands/init.ts
packages/expo-cli/src/commands/upgrade.ts
packages/package-manager/src/CocoaPodsPackageManager.ts
packages/xdl/src/Exp.ts

Also went ahead and ran the project with `yarn ios` to show that pods were indeed installed.

Install CocoaPods automatically on init and eject

---

packages/next-adapter/src/customize/index.ts
packages/next-adapter/src/customize/manifest.ts

fix https://github.com/expo/expo-cli/issues/1811

[next-adapter] Fix adding the build script

---

packages/pod-install/package.json

For correct access via npm page

Fix package.json repository & add homepage

---

packages/xdl/src/Project.ts
packages/xdl/src/project/ProjectUtils.ts

Fixes https://github.com/expo/expo-cli/issues/1742.

feat: handle device logs with format strings (e.g. %s)

---

packages/config/src/Config.ts

fix https://github.com/expo/expo-cli/issues/1848

Default to using folder name for projects

---

packages/config/src/Config.ts

fix https://github.com/expo/expo-cli/issues/1849

Use a default version for configs

---

packages/expo-cli/src/commands/__tests__/publish-info-test.ts
packages/expo-cli/src/commands/__tests__/publish-modify-test.ts

tests 4 https://github.com/expo/expo-cli/pull/1707

[cli] tests for release channels

---

packages/expo-cli/src/credentials/test-fixtures/mocks.ts
packages/expo-cli/src/credentials/views/IosDistCert.ts
packages/expo-cli/src/credentials/views/IosProvisioningProfile.ts
packages/expo-cli/src/credentials/views/IosPushCredentials.ts
packages/expo-cli/src/credentials/views/__tests__/IosDistCert-test.ts
packages/expo-cli/src/credentials/views/__tests__/IosProvisioningProfile-test.ts
packages/expo-cli/src/credentials/views/__tests__/IosPushCredentials-test.ts
packages/expo-cli/src/credentials/views/__tests__/SetupIosDist-test.ts
packages/expo-cli/src/credentials/views/__tests__/SetupIosPush-test.ts
packages/expo-cli/src/credentials/views/__tests__/SetupProvisioningProfile-test.ts

tests for https://github.com/expo/expo-cli/pull/1881

[cli] credential tests

---

packages/config/src/Config.ts
packages/config/src/__tests__/Config-test.js
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/exp.ts

Logs out the configs a project is using when expo start is run fix https://github.com/expo/expo-cli/issues/1851

Created a method for describing the project configs

---

packages/uri-scheme/src/Android.ts
packages/uri-scheme/src/CLI.ts
packages/uri-scheme/src/Ios.ts
packages/uri-scheme/src/Options.ts
packages/uri-scheme/src/URIScheme.ts

fix https://github.com/expo/expo-cli/issues/1895
Now you can point to arbitrary info.plist or android manifests

[uri-scheme] Added custom path options

---

packages/expo-cli/src/commands/init.ts
packages/xdl/src/Exp.ts

fix https://github.com/expo/expo-cli/issues/1917

Create init commit for projects

---

packages/expo-cli/src/commands/init.ts

fix https://github.com/expo/expo-cli/issues/1919

added default name for projects

---

packages/webpack-config/src/addons/withDevServer.ts

fix https://github.com/expo/expo-cli/issues/1939
fix https://github.com/expo/expo-cli/issues/1936
fix https://github.com/expo/expo-cli/issues/1935
When SSL fails, fallback on insecure https and warn the user about how to disable https, and clear the SSL cache.

Fallback on insecure HTTPS

---

.circleci/config.yml
.github/workflows/test.yml
codecov.yml
package.json

This introduces flags so in theory each report would be linked to a package

Add codecov action

---

.github/workflows/test.yml
packages/babel-preset-cli/__tests__/__snapshots__/index-test.js.snap
packages/babel-preset-cli/__tests__/index-test.js
packages/babel-preset-cli/index.js
packages/babel-preset-cli/package.json
yarn.lock

Ensure our core babel functionality works as expected. This will help in the future when we want to upgrade the babel packages.

[babel preset cli] add tests

---

packages/electron-adapter/tsconfig.json
packages/expo-codemod/tsconfig.json
packages/expo-optimize/tsconfig.json
packages/image-utils/tsconfig.json
packages/json-file/tsconfig.json
packages/metro-config/tsconfig.json
packages/next-adapter/tsconfig.json
packages/osascript/tsconfig.json
packages/plist/tsconfig.json
packages/pod-install/tsconfig.json
packages/schemer/tsconfig.json
packages/uri-scheme/tsconfig.json
packages/webpack-config/tsconfig.json

- We're shipping tests and mocks in packages with TS tests, this fixes that

Ignore mocks and tests in TypeScript builds

---

packages/uri-scheme/src/Android.ts
packages/uri-scheme/src/CLI.ts
packages/uri-scheme/src/URIScheme.ts

Moved from https://github.com/expo/expo-cli/pull/1884

Configure uri-scheme to open from anywhere

---

CHANGELOG.md
packages/expo-cli/src/commands/android.ts
packages/expo-cli/src/commands/ios.ts

resolve https://github.com/expo/expo-cli/issues/1986

Deprecate ios and android commands

---

packages/expo-cli/src/commands/build/__tests__/build-ios-test.ts
packages/expo-cli/src/credentials/test-fixtures/mocks.ts

add more `expo build:ios` tests

[cli] add more build tests

---

packages/expo-cli/package.json
packages/expo-cli/src/exp.ts

feat: suggest closest match to an unknown command

---

packages/webpack-config/package.json
packages/webpack-config/src/addons/withWorkbox.ts
yarn.lock

https://github.com/expo/expo-cli/pull/1942 found a regression where websites don't upgrade unless force refreshed.

Revert workbox upgrade

---

packages/uri-scheme/README.md

resolve https://github.com/expo/expo-cli/issues/1918

Added docs for uri-scheme

---

.github/ISSUE_TEMPLATE.md

People keep forgetting to delete the help, this will make it only show up when editing.

Use comments in the issue template

---

packages/next-adapter/document.d.ts
packages/next-adapter/package.json

[next-adapter] Create typings for Document

---

packages/xdl/src/createWebpackCompiler.ts

Print a note Press w to open the project in the browser on start command in expo-cli

 <improvement>: <Add a note about Press w to open the project in the browser>

---

CONTRIBUTING.md
README.md
packages/config/src/Config.types.ts
packages/electron-adapter/README.md
packages/expo-cli/README.md
packages/expo-cli/src/appleApi/authenticate.ts
packages/expo-cli/src/commands/client/index.ts
packages/expo-cli/src/commands/eject/LegacyEject.ts
packages/expo-cli/src/commands/publish.ts
packages/expo-cli/src/commands/upgrade.ts
packages/expo-cli/src/commands/upload/BaseUploader.ts
packages/expo-cli/src/credentials/views/IosDistCert.ts
packages/expo-cli/src/credentials/views/IosPushCredentials.ts
packages/expo-optimize/README.md
packages/next-adapter/README.md
packages/pwa/README.md
packages/webpack-config/README.md
packages/xdl/README.md
packages/xdl/src/Android.ts
packages/xdl/src/detach/Detach.js
packages/xdl/src/logs/PackagerLogsStream.ts

docs: update old versioned links to unversioned links

---

packages/dev-tools/server/graphql/GraphQLSchema.ts
packages/xdl/src/Project.ts

[xdl]  Start Ngrok only when running expo start --tunnel

---

packages/expo-cli/src/commands/whoami.ts

Fixes https://github.com/expo/expo-cli/issues/2057

fix: always print whoami output to stdout

---

packages/xdl/src/User.ts

Fixes https://github.com/expo/expo-cli/issues/2052

fix: whoami treating all errors as "not logged in"

---

packages/expo-cli/src/commands/eject/Eject.ts

Metro config with the `hashAssetFiles` plugin is now needed for expo-updates in the bare workflow, so we need to add this to projects when ejecting.
We now check all three places metro config may exist (metro.config.js, metro.config.json, and package.json['metro']), and we copy metro.config.js from the template projects if there's no existing config. If there is existing config, we log a warning instead, linking to the instructions/example in the expo-updates README.

[expo-cli] copy metro config in eject

---

packages/webpack-config/src/addons/index.ts
packages/webpack-config/src/addons/withSourceMaps.ts
packages/webpack-config/src/webpack.config.ts

Added platform based source maps

[webpack-config] with platform source maps

---

packages/webpack-config/src/__tests__/__snapshots__/webpack.config-test.js.snap
packages/webpack-config/src/__tests__/webpack.config-test.js
packages/webpack-config/src/addons/withDevServer.ts
packages/webpack-config/src/addons/withUnimodules.ts
packages/webpack-config/src/addons/withWorkbox.ts
packages/webpack-config/src/env/__tests__/paths-test.js
packages/webpack-config/src/env/paths.ts
packages/webpack-config/src/env/validate.ts
packages/webpack-config/src/index.ts
packages/webpack-config/src/loaders/createAllLoaders.ts
packages/webpack-config/src/loaders/createBabelLoader.ts
packages/webpack-config/src/plugins/ExpoHtmlWebpackPlugin.ts
packages/webpack-config/src/utils/normalizePaths.ts
packages/webpack-config/src/webpack.config.ts

- only use mocks on web
- only use aliases on web
- use project root for context on native
- use target webworker on native

[webpack-config] Added full snapshot tests

---

packages/xdl/src/detach/IosPodsTools.js
packages/xdl/src/modules/config.ts

We want it to be shipped in standalone apps as it's now integrated into Expo client and ExpoKit.

[xdl] Add expo-notifications to modules config

---

packages/uri-scheme/src/URIScheme.ts

Added warnings when nothing happens in URI scheme

---

packages/dev-server/README.md
packages/dev-server/src/MetroDevServer.ts
packages/dev-tools/README.md
packages/dev-tools/TESTING.md
packages/electron-adapter/src/Webpack.ts
packages/expo-cli/src/commands/publish.ts
packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/upgrade.ts
packages/expo-optimize/README.md
packages/metro-config/src/ExpoMetroConfig.ts
packages/pod-install/README.md
packages/webpack-config/README.md
packages/webpack-config/src/addons/withAlias.ts
packages/xdl/src/Project.ts
packages/xdl/src/detach/Detach.js
packages/xdl/src/logs/PackagerLogsStream.ts
packages/xdl/src/project/Doctor.ts

react-native packager -> Metro bundler

---

packages/webpack-config/src/addons/__tests__/withUnimodules-test.js
packages/webpack-config/src/addons/withUnimodules.ts

- Created unit tests for the core Next.js feature https://github.com/expo/expo-cli/pull/2174

[webpack-config] test externals

---

packages/expo-cli/e2e/__tests__/eject-test.ts
packages/expo-cli/jest.config.js
packages/expo-cli/src/commands/eject/Eject.ts

We need to make changes to this command but it's really fragile.
- Create a basic e2e test to ensure the default case is handled

Creaetd e2e test for eject command

---

jest/unit-test-config.js
package.json
yarn.lock

These plugins are awesome and make life better 👏  ty @simenb

Added jest watch plugins

---

.circleci/config.yml
.github/workflows/test.yml
packages/webpack-config/jest-puppeteer.config.js

Move puppeteer from Circle CI to GH Actions

Created puppeteer GH action

---

packages/expo-cli/src/commands/build/ios/IOSBuilder.ts

fix the `skip-credentials-check` flag so it doesnt prompt for apple credentials

[cli] fix skip creds flag

---

packages/expo-cli/src/askUser.ts
packages/expo-cli/src/commands/send.ts

[expo-cli] Updated syntax for send command

---

packages/expo-cli/e2e/__tests__/install-test.ts
packages/expo-cli/src/commands/install.ts

- clean up error messages 
- add e2e tests for install command

[expo-cli][install] format error messages

---

packages/package-manager/package.json
packages/webpack-config/package.json
yarn.lock

- https://github.com/square/find-yarn-workspace-root/pull/25
- still one usage which comes from expo-yarn-workspaces https://github.com/expo/expo/pull/8779

Upgrade find-yarn-workspace-root

---

packages/expo-cli/src/commands/build-native/Builder.ts
packages/expo-cli/src/commands/build-native/index.ts
packages/expo-cli/src/commands/build-native/utils.ts
packages/expo-cli/src/commands/upload/submission-service/utils/files.ts
packages/expo-cli/src/commands/utils/progress.ts

For Turtle v2 builds, we want to create an app on Expo Servers before scheduling the build.

[expo-cli] turtle v2: create app before running build

---

packages/xdl/package.json
packages/xdl/src/Project.ts
packages/xdl/src/UrlUtils.ts
yarn.lock

[xdl] Fix deprecated joi types and methods

---

packages/expo-cli/src/commands/init.ts

Should land and release this prior to SDK 38 release

[init] Make the tabs template use TypeScript

---

packages/expo-cli/src/commands/upgrade.ts

[cli] Fail upgrade when expo install throws

---

packages/webpack-config/package.json
packages/webpack-config/src/addons/withWorkbox.ts
packages/webpack-config/src/webpack.config.ts
yarn.lock

- Tests will continue to pass
- Built and deployed a project
- Added files to `web/` and ensured they were copied to `web-build`

Upgraded copy-webpack-plugin

---

packages/expo-cli/src/commands/publish-info.ts

Make the channel column a 'big cell' to show longer channel names

[expo-cli] Show longer release channel names

---

packages/expo-cli/src/commands/build-native/build.ts
packages/expo-cli/src/commands/build-native/index.ts
packages/expo-cli/src/commands/build-native/utils.ts

We want to have a command to show the list of recent builds for turtle v2.
Example usage:
```js
expo build-status
```

[expo-cli] Add a build-status command

---

packages/expo-cli/src/commands/build/ios/utils/image.ts

Adds a link to FYI (https://github.com/expo/fyi/pull/11) to give developers more context.
Addresses: https://github.com/expo/expo-cli/issues/2225

[expo-cli] Adds link to FYI

---

packages/xdl/package.json
packages/xdl/src/project/Doctor.ts
yarn.lock

This should help in detecting network or computer/dns specific issues. It pings some of our domains and checks if it's reachable. Right now, I simply used `is-reachable` ([bundlephobia](https://bundlephobia.com/result?p=is-reachable@4.0.0)) but we can also implement our own logic for that.
Fixes #2157

[xdl] Add network ping to doctor

---

packages/expo-cli/src/commands/upload/utils.ts

Fixes #2493
It uses the [same implementation as in the newer submission service](https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/upload/submission-service/utils/files.ts#L12), with protection for undefined or empty `progress.total` values.

[cli] Fix progress bar when uploading ios

---

packages/config/src/android/AllowBackup.ts
packages/config/src/android/__tests__/AllowBackup-test.ts
packages/config/src/android/__tests__/__snapshots__/Permissions-test.js.snap
packages/config/src/android/__tests__/fixtures/react-native-AndroidManifest.xml
packages/config/src/android/index.ts
packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts

[eject] Added support for allowBackup

---

packages/expo-cli/src/commands/init.ts

- also fixed the git init order so lock files get added to the initial commit.

[cli] Added no-install option to expo init

---

packages/expo-cli/src/commands/eas-build/index.ts
packages/expo-cli/src/exp.ts

Added eas help group and normalized descriptions

---

packages/expo-cli/src/credentials/views/SetupIosPush.ts

- handles non interactive
- smaller package
- we're migrating to prompts

Migrate SetupIosPush to prompts

---

packages/xdl/src/Android.ts
packages/xdl/src/Simulator.ts

@byCedric raised a point that if a user is on an older SDK version they may not want to use the latest client, this will help prevent annoying interactions.
The prompt to upgrade will only be run once per `expo start` instance, per device.

Only prompt to upgrade once in a single run per device

---

packages/expo-cli/src/commands/diagnostics.ts

- fix #2390
- added Managers
- added SDKs

[cli] Added workflow info

---

packages/xdl/package.json
packages/xdl/src/detach/IosPodsTools.js
yarn.lock

[xdl] sdk-39 tweaks

---

packages/expo-cli/src/commands/upgrade.ts
packages/expo-cli/src/prompts.ts

Prompts is a smaller package that fits our needs, we are moving to consolidate all prompting packages across the repo.

Migrate upgrade command to prompts

---

packages/expo-cli/src/commands/eject/Eject.ts

[eject] Skip warnings notice when no warnings are thrown

---

packages/expo-cli/src/commands/eas-build/build/builders/__tests__/iOSBuilder-test.ts
packages/expo-cli/src/credentials/provider/__tests__/AndroidCredentialsProvider-test.ts
packages/expo-cli/src/credentials/provider/__tests__/iOSCredentialsProvider-test.ts

- failed here https://app.circleci.com/pipelines/github/expo/expo-cli/4366/workflows/c1ccfa9d-7314-4378-8a4d-4702d71f825c/jobs/53269

Added extra time to failing tests

---

packages/expo-cli/src/commands/eject/ConfigValidation.ts
packages/expo-cli/src/commands/utils/url.ts

warn the user when the bundle ID or package name is already in use

---

packages/config/src/android/Facebook.ts
packages/config/src/android/Manifest.ts

I'll migrate the Facebook helper after https://github.com/expo/expo-cli/pull/2587 lands

[config] Unify metadata manifest helpers

---

packages/config/src/evalConfig.ts

fixes https://github.com/expo/expo-cli/pull/2648#discussion_r489468422

Disable using the project's babel.config.js for transpiling app.config.js

---

packages/expo-cli/src/credentials/views/Select.ts
packages/expo-cli/src/prompts.ts

The current implementation of prompts helpers does not work with list of questions, but types suggest that

[expo-cli] fix prompt helpers

---

CHANGELOG.md
packages/expo-cli/src/commands/utils/PublishUtils.ts
packages/xdl/src/Project.ts

- Remove deprecated methods
- Delete seemingly unused functions and types from `Project` module.

[xdl] Remove unused methods from Project module

---

packages/config/src/android/AllowBackup.ts
packages/config/src/android/Colors.ts
packages/config/src/android/Facebook.ts
packages/config/src/android/Icon.ts
packages/config/src/android/Name.ts
packages/config/src/android/Package.ts
packages/config/src/android/UserInterfaceStyle.ts
packages/config/src/android/Version.ts
packages/config/src/android/__tests__/Colors-test.ts
packages/config/src/ios/CustomInfoPlistEntries.ts
packages/config/src/ios/Entitlements.ts
packages/config/src/ios/Facebook.ts
packages/config/src/ios/Google.ts
packages/config/src/ios/IosConfig.types.ts
packages/config/src/ios/Name.ts
packages/config/src/ios/Orientation.ts
packages/config/src/ios/Resources.ts
packages/config/src/ios/Scheme.ts
packages/config/src/ios/Updates.ts
packages/config/src/ios/UserInterfaceStyle.ts
packages/config/src/ios/UsesNonExemptEncryption.ts
packages/config/src/ios/Version.ts
packages/config/src/ios/__tests__/Updates-test.ts
packages/xdl/src/detach/IosPlist.ts

- various improvements and updates from https://github.com/expo/expo-cli/pull/2669
- unify and simplify getters
- attempt to delete more values when they aren't defined in the config
- plist extracts values and doesn't add them back if they're missing
- manifest deletes values from XML files
- use helpers in allows backups
- test Colors module
- improve plist types

[config] improve modules

---

packages/xdl/src/Android.ts
packages/xdl/src/logs/TerminalLink.ts

- resolve https://github.com/expo/expo-cli/issues/2677
- converted error to a controlled warning about authorizing the device
- added FYI for resolving issue https://github.com/expo/fyi/pull/13

Support unauthorized devices

---

packages/config-types/package.json
packages/config-types/src/index.ts

@expo/config-types@39.0.1

---

packages/config/src/ios/Locales.ts
packages/config/src/ios/__tests__/Locales-test.ts

- Our schema allows `string | object (<string, string>)` but we only support `string` values (json files). We should support inlining the locales JSON so the types match up as expected:
```js
{
locales: { 
// Currently supporting
fr: "./french.json", 
// Proposed addition
es: { CFBundleDisplayName: 'spanish-value' } }
}
```
- Related confusion: https://github.com/expo/universe/pull/5860
- test that invalid json produces a useful warning
- test that inlined json is allowed

[config] Resolve inline locales

---

packages/config/src/android/Colors.ts
packages/config/src/android/Icon.ts
packages/config/src/android/Manifest.ts
packages/config/src/android/NavigationBar.ts
packages/config/src/android/Paths.ts
packages/config/src/android/PrimaryColor.ts
packages/config/src/android/RootViewBackgroundColor.ts
packages/config/src/android/StatusBar.ts
packages/config/src/android/Strings.ts
packages/config/src/android/Styles.ts
packages/config/src/android/__tests__/Colors-test.ts
packages/config/src/android/__tests__/NavigationBar-test.js
packages/config/src/android/__tests__/Paths-test.ts
packages/config/src/android/__tests__/PrimaryColor-test.js
packages/config/src/android/__tests__/RootViewBackgroundColor-test.js
packages/config/src/android/__tests__/StatusBar-test.js
packages/config/src/android/index.ts
packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
packages/expo-cli/src/commands/init.ts

- Unify path resolution for android files 
- Support Kotlin MainActivities by failing gracefully

[config] Created Paths module

---

packages/expo-cli/src/CommandError.ts
packages/expo-cli/src/exp.ts
packages/expo-cli/src/prompts.ts

Disable error message when aborting

---

packages/dev-tools/components/ProjectManagerPublishingSection.js
packages/expo-cli/src/commands/utils/url.ts

Updates a few URLs based on the website's new URL scheme.

[CLI] Update CLI urls

---

packages/xdl/src/Android.ts

Update Android uninstalling copy

---

packages/config/src/Errors.ts
packages/config/src/Modules.ts
packages/config/src/android/Paths.ts
packages/config/src/android/__tests__/Resources-test.ts
packages/config/src/ios/BundleIdentifier.ts
packages/config/src/ios/DeviceFamily.ts
packages/config/src/ios/Entitlements.ts
packages/config/src/ios/Google.ts
packages/config/src/ios/Paths.ts
packages/config/src/ios/Scheme.ts
packages/config/src/ios/__tests__/BundleIdentifier-test.ts
packages/config/src/ios/__tests__/DeviceFamily-test.ts
packages/config/src/ios/__tests__/Paths-test.ts
packages/config/src/ios/index.ts
packages/config/src/ios/utils/Xcodeproj.ts
packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts

- #2753 seems to be an issue people keep encountering, ~~but we cannot repro it~~.
- fix #2753
- We have a unified paths module for Android already.
- Unify the error messages and warnings.
- Unify the code for resolving project files.

[config] Created paths module for ios

---

packages/config/src/android/StatusBar.ts
packages/config/src/android/__tests__/Icon-test.ts
packages/config/src/ios/DeviceFamily.ts
packages/config/src/ios/Entitlements.ts
packages/config/src/ios/__tests__/DeviceFamily-test.ts
packages/config/src/ios/__tests__/Icons-test.ts
packages/config/src/ios/__tests__/Locales-test.ts
packages/config/src/ios/__tests__/Paths-test.ts
packages/config/src/ios/__tests__/utils/getDirFromFS.ts
packages/config/src/ios/utils/Xcodeproj.ts
packages/config/src/plugins/__tests__/fixtures/react-native-project.ts
ts-declarations/xcode/index.d.ts

- Moved from https://github.com/expo/expo-cli/pull/2789
- Bring over big fixture file
- Warn about conflicting config settings in device family
- Warn about deprecated android status bar config setting
- Improve entitlements product name resolution (preventing it from being `$(TARGET_NAME)`)
- Unify test utility

[config] disjointed features from plugins ios

---

packages/xdl/src/UrlUtils.ts
packages/xdl/src/__tests__/UrlUtils-test.ts
packages/xdl/src/project/ManifestHandler.ts
packages/xdl/src/project/__tests__/ManifestHandler-test.ts

I want to add the custom client support but it's hard cuz this code is unruly and untested.

[xdl] Clean up UrlUtils

---

packages/config/src/ios/Branch.ts
packages/config/src/ios/CustomInfoPlistEntries.ts
packages/config/src/ios/DeviceFamily.ts
packages/config/src/ios/Facebook.ts
packages/config/src/ios/Google.ts
packages/config/src/ios/Icons.ts
packages/config/src/ios/IosConfig.types.ts
packages/config/src/ios/Locales.ts
packages/config/src/ios/Name.ts
packages/config/src/ios/Orientation.ts
packages/config/src/ios/RequiresFullScreen.ts
packages/config/src/ios/Scheme.ts
packages/config/src/ios/SplashScreen.ts
packages/config/src/ios/Updates.ts
packages/config/src/ios/UserInterfaceStyle.ts
packages/config/src/ios/UsesNonExemptEncryption.ts
packages/config/src/ios/Version.ts
packages/config/src/ios/__tests__/DeviceFamily-test.ts
packages/config/src/ios/__tests__/Icons-test.ts
packages/config/src/ios/__tests__/Locales-test.ts
packages/config/src/ios/__tests__/Name-test.ts
packages/config/src/ios/__tests__/Paths-test.ts
packages/config/src/ios/__tests__/ProvisioningProfile-test.ts
packages/config/src/ios/__tests__/Scheme-test.ts
packages/config/src/ios/__tests__/Updates-test.ts
packages/config/src/ios/__tests__/UserInterfaceStyle-test.ts
packages/config/src/plugins/__tests__/core-plugins-test.ts
packages/config/src/plugins/compiler-plugins.ts

- fix types in tests
- add more specific types for functions
- fix typos 
- unify property names
- related https://github.com/expo/expo-cli/pull/2851

[config] iOS fix types

---

packages/expo-optimize/src/assets.ts
packages/xdl/src/ProjectSettings.ts

Resolves https://github.com/expo/expo-cli/issues/2200

[xdl][expo-cli] <feat>: Add READMEs to the .expo & .expo-shared folders

---

packages/config/src/ios/Paths.ts
packages/config/src/ios/__tests__/Paths-test.ts
packages/uri-scheme/src/Ios.ts

fix https://github.com/expo/expo-cli/issues/2235

sort Info.plist files by length

---

packages/expo-cli/src/commands/eject/Eject.ts

- not certain about splash-screen or updates, I'm pretty sure we setup updates automatically, we currently do not configure splash screen automatically however.

[eject] Added more packages with extra setup

---

.github/workflows/test.yml

cache keeps [failing unexpectedly](https://github.com/expo/expo-cli/runs/1381688006#step:2:5), maybe upgrading will fix it

[actions] Upgrade cache to v2

---

packages/xdl/src/SimControl.ts

- Encountered a few errors due to automatic Simulator upgrades, eventually the simulator closed itself and rerunning `expo start` worked as expected.
- Not sure how I could reproduce the errors without uninstalling parts of Xcode.
- Recorded error info in the comments and improved error handling in case this happens again.

[xdl] Record simctl error

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/log.ts
packages/xdl/src/webpack-utils/createWebpackCompiler.ts

unify clear logs

---

packages/xdl/package.json
packages/xdl/src/detach/Detach.js

- part of https://github.com/expo/expo-cli/issues/1983
- TBD

[xdl] Replace inquirer with prompts

---

packages/xdl/src/Webpack.ts
packages/xdl/src/webpack-utils/createWebpackCompiler.ts

- dim warning and promote to "late beta".

promote web warning to late beta

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/project/ProjectUtils.ts
packages/xdl/src/webpack-utils/createWebpackCompiler.ts

- Use same format as the `?` help prompt
- Remove library tags `[Metro]` `[React]` `[Expo]` since these didn't do much to help the user.
- Combine warning with `expo build:web` tip.

[xdl] Update web terminal UI

---

packages/expo-cli/src/commands/customize.ts
packages/expo-cli/src/commands/eject/LegacyEject.ts
packages/expo-cli/src/commands/install.ts
packages/expo-cli/src/commands/upgrade.ts
packages/expo-cli/src/commands/utils/ClientUpgradeUtils.ts
packages/expo-cli/src/exp.ts
packages/xdl/src/Webpack.ts

- extract ConfigUtils into singular imports

Refactor ConfigUtils imports

---

packages/expo-cli/src/commands/build/BaseBuilder.ts

- related https://github.com/expo/expo-cli/issues/2909

Handle undefined build job more gracefully

---

packages/expo-cli/package.json
packages/expo-cli/src/exp.ts
yarn.lock

wrap links correctly in the help prompt

---

packages/expo-cli/scripts/introspect.ts
packages/expo-cli/src/exp.ts

- results: https://github.com/expo/expo/pull/11094 / https://github.com/expo/expo/blob/@evanbacon/docs/update-cli-docs/docs/pages/workflow/expo-cli.md

Support grouping and hiding in the introspect script

---

packages/expo-cli/src/commands/apply/configureAndroidProjectAsync.ts
packages/expo-cli/src/commands/apply/configureIOSProjectAsync.ts
packages/expo-cli/src/commands/eject.ts
packages/expo-cli/src/commands/eject/Eject.ts
packages/expo-cli/src/log.ts

- added `log.debug` which only prints with `EXPO_DEBUG`
- log evaluated ios and android configs in `expo eject`
- log eject mode

[cli] debug logging

---

packages/config/src/android/AllowBackup.ts
packages/config/src/android/Branch.ts
packages/config/src/android/Facebook.ts
packages/config/src/android/GoogleMapsApiKey.ts
packages/config/src/android/GoogleMobileAds.ts
packages/config/src/android/IntentFilters.ts
packages/config/src/android/Name.ts
packages/config/src/android/Orientation.ts
packages/config/src/android/Package.ts
packages/config/src/android/Scheme.ts
packages/config/src/android/UserInterfaceStyle.ts
packages/config/src/ios/Branch.ts
packages/config/src/ios/Entitlements.ts
packages/config/src/ios/Facebook.ts
packages/config/src/ios/Google.ts
packages/config/src/ios/Name.ts
packages/config/src/ios/Orientation.ts
packages/config/src/ios/RequiresFullScreen.ts
packages/config/src/ios/Scheme.ts
packages/config/src/ios/UserInterfaceStyle.ts
packages/config/src/ios/UsesNonExemptEncryption.ts
packages/config/src/ios/Version.ts
packages/config/src/plugins/android-plugins.ts
packages/config/src/plugins/core-plugins.ts
packages/config/src/plugins/ios-plugins.ts

improve error handling by adding a name to the stack trace

name all config plugins

---

packages/config-plugins/src/plugins/expo-plugins.ts

- this seems to make configure-splash-screen work ¯\_(ツ)_/¯

[config] run splash first

---

packages/expo-cli/src/prompts.ts

- fix https://github.com/expo/expo-cli/issues/2964

fix prompt selection

---

packages/expo-cli/src/accounts.ts

Fixes https://github.com/expo/expo-cli/issues/2970 and improves the wording in the register prompt.. a lot.
h/t & s/o to @byCedric for raising this issue and discussing solution and wording with me

Fix register command and some cleanup

---

packages/config/src/Config.ts
packages/config/src/Config.types.ts
packages/config/src/plugins/withInternal.ts

- Move all config _internal logic to a plugin.
- Moved from https://github.com/expo/expo-cli/pull/2943

withInternal plugin

---

packages/expo-cli/src/commands/upgrade.ts

Rather than just using the `versions.iosUrl` or `versions.androidUrl` values, we should upgrade the client app to the version that is compatible with the SDK version that is provided.
This fixes an issue that @sjchmiela pointed out where `expo upgrade` for SDK 40 beta didn't install the correct client version.
Also, in the future, we should remove the `iosUrl` and `androidUrl` fields entirely.

[cli] Fix installing client for selected target SDK version in upgrade

---

packages/xdl/src/Android.ts
packages/xdl/src/Simulator.ts

When we run `expo client:install:ios` or `expo client:install:android` inside a project we get different results from `expo start` and then pressing `i` or `a`. This resolves that.

[xdl] Install the client version for the project's SDK when opening project

---

packages/config-plugins/src/android/Paths.ts
packages/config-plugins/src/android/Resources.ts
packages/config-plugins/src/android/Styles.ts
packages/config-plugins/src/android/XML.ts
packages/config-plugins/src/android/__tests__/Styles-test.ts

- moved from https://github.com/expo/expo-cli/pull/2992

[config plugins] added styles helper methods

---

packages/config-plugins/src/ios/utils/Xcodeproj.ts
ts-declarations/xcode/index.d.ts

added method for adding frameworks

---

packages/expo-optimize/package.json
packages/pod-install/package.json
packages/pwa/package.json
packages/schemer/package.json
packages/uri-scheme/package.json
packages/webpack-config/package.json
yarn.lock

minor version bump of types/node

---

packages/xdl/src/Project.ts

[english] effect -> affect

---

packages/config-types/package.json
packages/config-types/src/ExpoConfig.ts
yarn.lock

X https://github.com/expo/universe/pull/6692

added plugins to config-types

---

packages/config-plugins/README.md
packages/config-plugins/src/Plugin.types.ts
packages/config-plugins/src/index.ts
packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/plugins/compiler-plugins.ts
packages/config-plugins/src/plugins/ios-plugins.ts

moved from https://github.com/expo/expo-cli/pull/3057

Added AppDelegate mod

---

packages/expo-cli/src/commands/eject/Eject.ts
packages/expo-cli/src/commands/utils/CreateApp.ts

- Use yellow instead of red since these are expected warnings and not errors:
- Use a better bullet
- New line + indent the URL

clean up eject logging

---

packages/config-plugins/src/Plugin.types.ts

required for external plugins in expo/expo

export more types from config-plugins

---

packages/expo-cli/src/commands/eject/Eject.ts

- to better support disabling various features in CI

[eject] split up functionality into more methods

---

packages/expo-cli/src/appleApi/authenticate.ts

[expo-cli] improvement: Handle keychain save error

---

packages/expo-cli/src/commands/eject/Eject.ts

- extra steps are not actually required

[prebuild] remove lottie extra step warning

---

packages/dev-tools/package.json
packages/expo-cli/package.json
packages/json-file/package.json
packages/schemer/package.json
packages/xdl/package.json
yarn.lock

This reduces the amount of lodash copies in the install size from 3 to 1.

bump lodash

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/init.ts
packages/expo-cli/src/commands/start/TerminalUI.ts
yarn.lock

Similar change was made in EAS CLI

remove wordwrap

---

CHANGELOG.md

Forgot to add this when running publish, luckily it reminded me.

Update changelog to include axios bugfix

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/build/BaseBuilder.ts
packages/expo-cli/src/credentials/route.ts
packages/xdl/package.json
packages/xdl/src/Project.ts
packages/xdl/src/Simulator.ts
packages/xdl/src/__integration_tests__/Simulator-test.ts
packages/xdl/src/project/ngrok.ts
packages/xdl/src/project/resolveNgrok.ts
packages/xdl/src/utils/delayAsync.ts
yarn.lock

Small package removal to cut down on the download + indexing time.

Remove delay-async package

---

packages/pwa/package.json
packages/pwa/src/cli.ts

- json-file unused
- fs-extra not needed
- dev deps in repo already

[expo-pwa] Remove extra deps

---

packages/xdl/src/project/Doctor.ts

- Remove unused Doctor exports (checked expo-cli and turtle v1)
```diff
- Doctor.EXPO_SDK_INSTALLED_AND_IMPORTED
- Doctor.EXPO_SDK_NOT_INSTALLED
- Doctor.EXPO_SDK_NOT_IMPORTED
- Doctor.getExpoSdkStatus()
- Doctor.validateWithSchema()
```

Drop unused Doctor code

---

packages/expo-cli/src/commands/start/TerminalUI.ts

- Prompts.pauseInteractions is designed for pausing and resuming TerminalUI. 
- Prompts has a bit more expected behavior for our users.
- `expo start`, press e
- try exiting -- esc

[expo-cli] refactor email prompt to use prompts

---

packages/expo-cli/bin/expo.js
packages/expo-cli/src/exp.ts
packages/expo-cli/src/urlOpts.ts
packages/expo-codemod/bin/expo-codemod.js
packages/json-file/__tests__/JsonFile-test.ts
packages/traveling-fastlane/publishing/linux/platform.js
packages/xdl/src/Api.ts
packages/xdl/src/Session.ts
packages/xdl/src/UserSettings.ts

It's good form, var is not safe for scopes.

remove vars from the repo

---

packages/config-plugins/src/android/Package.ts
packages/config-plugins/src/android/__tests__/Package-test.ts
packages/config-plugins/src/android/__tests__/fixtures/android/app/build.gradle
packages/expo-cli/src/commands/start/TerminalUI.ts
packages/xdl/src/Android.ts

Similar to https://github.com/expo/expo-cli/pull/3182, but for Android.

[xdl] Add Dev Client simulator flow v0 for Android devices

---

packages/metro-config/package.json

- resolve https://github.com/expo/expo-cli/issues/3213

update babel transformer

---

packages/config-plugins/src/ios/Entitlements.ts
packages/config-plugins/src/plugins/__tests__/__snapshots__/expo-plugins-test.ts.snap
packages/config-plugins/src/plugins/expo-plugins.ts
packages/config-plugins/src/plugins/unversioned/expo-apple-authentication.ts

- expo/expo#11979
- this will get disabled when someone uses the versioned copy

Added unversioned apple-auth plugin

---

packages/metro-config/src/ExpoMetroConfig.ts

When the error or warning is global, the first frame is useless, something like:
```
* somn.js:2:0 in <global>
* App.js:3:0 in <global>
* index.js:3:0 in <global>
* http://192.168.1.35:19000/index.bundle?platform=android&dev=true&hot=false&minify=false:111014:3 in global code
```
This PR identifies the first frame if it's a URL requiring the initial module, and collapses it:
```
* somn.js:2:0 in <global>
* App.js:3:0 in <global>
* index.js:3:0 in <global>
```

Collapse first frame if it's useless

---

packages/expo-cli/src/commands/start/TerminalUI.ts

- This command is pretty useless nowadays. We don't need to automate the sending of an email from the same script used to start the metro bundler. 
- Terminal UI should be reserved for more important commands.
- Delete the "e" option from terminal UI. The `--send-to` option can still be passed to the command for now.

[expo-cli] Delete e (send to) command from terminal ui

---

packages/config-plugins/src/ios/Google.ts
packages/config-plugins/src/ios/Locales.ts
packages/config-plugins/src/ios/SwiftBridgingHeader.ts
packages/config-plugins/src/ios/XcodeProjectFile.ts
packages/config-plugins/src/ios/__tests__/SwiftBridgingHeader-test.ts
packages/config-plugins/src/ios/__tests__/XcodeProjectFile-test.ts
packages/config-plugins/src/ios/__tests__/fixtures/project-swift.pbxproj
packages/config-plugins/src/ios/index.ts
packages/config-plugins/src/ios/utils/Xcodeproj.ts
packages/config-plugins/src/plugins/__tests__/expo-plugins-test.ts
packages/config-plugins/src/plugins/expo-plugins.ts

- A growing number of packages use swift so creating the header seems reasonable.
- created a new default plugin (maybe it should be a base mod).
- expo eject -- bridging header should be created and linked, building the project will work as expected.

Created withSwiftBridgingHeader

---

packages/expo-cli/src/urlOpts.ts
packages/xdl/src/Simulator.ts

- ensure logs are streamed before opening the dev client app

Added devClient option to mobile options

---

packages/expo-cli/src/commands/run/ios/IOSDeploy.ts
packages/expo-cli/src/commands/run/ios/XcodeBuild.ts
packages/expo-cli/src/commands/run/ios/resolveOptionsAsync.ts
packages/expo-cli/src/commands/run/ios/runIos.ts
packages/xdl/src/SimControl.ts
packages/xdl/src/SimControlLogs.ts
packages/xdl/src/__tests__/SimControlLogs-test.ts

- fix wifi deployment stalling
- fix pausing on bundler startup
- improve install times

improved device deployment

---

packages/expo-cli/src/commands/run/ios/IOSDeploy.ts

auto install ios package

---

packages/config-plugins/src/plugins/expo-plugins.ts

Bug #3316
Currently, it is impossible to setup linking/deep linking in a managed expo project on Android, because https schemes are always removed by the scheme plugin.
I was trying to add linking to my Android app, but the generated AndroidManifest was incorrect. The bug is that the `Scheme` plugin removes all intent filters with a scheme before adding it's own custom schemes. The solution to this is to run the intentFilters plugin after the scheme plugin.
1. Clone the test project https://github.com/fallaciousreasoning/expo-broken-schemes
2. `npm install`
3. Run `expo prebuild --no-install` and inspect the generated `AndroidManifest.xml` in `android/app/src/main`.
If using a current version of `expo-cli` the generated output will be missing a `<data android:scheme="https"/>` element. If …

fix: Fixes a bug where an IntentFilter would be removed by the Scheme plugin

---

packages/config-plugins/src/android/Scheme.ts

- Related PR https://github.com/expo/expo-cli/pull/3319
This plugin used to remove the unused schemes but this is unpredictable because other plugins could add schemes.
The only way to reliably remove schemes from the project is to nuke the file and regenerate the code (`expo prebuild --clean`).
Regardless, having extra schemes isn't a fatal issue and therefore a tolerable compromise is to just add new schemes that aren't currently present.
- `expo prebuild -p android --no-install` in a project with a scheme defined.
- Remove the scheme and rerun `expo prebuild -p android --no-install` the scheme will no longer be removed.
- Manually add a new scheme to the `AndroidManifest.xml` (emulates an unknown plugin), rerun `expo prebuild -p android --no-install` the scheme will not have the …

Prevent removing existing schemes from AndroidManifest.xml

---

packages/expo-cli/src/commands/eject/clearNativeFolder.ts
packages/expo-cli/src/schemes.ts

Improves the ability to start metro in projects with a single platform.

Improve single platform dev client

---

packages/expo-cli/src/commands/run/android/runAndroid.ts
packages/expo-cli/src/commands/run/android/spawnGradleAsync.ts

`EXPO_PROFILE=1 expo run:android` to generate build profile.

profile android build time

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/run/ios/ExpoLogFormatter.ts
packages/expo-cli/src/commands/run/ios/Podfile.ts
packages/expo-cli/src/commands/run/ios/XcodeBuild.ts
yarn.lock

- added npm package name to each line in the logger

Improved package logging

---

packages/expo-cli/src/commands/run/ios/IOSDeploy.ts

- if the device is locked, the prompt will break terminal ui

Fix prompt bug when opening on iOS

---

packages/xdl/binaries/osx/xde/xde

It's not used for anything anymore.

[xdl] Remove unused xde spawn script

---

.github/workflows/test.yml

- node ten ded
- CI should pass

Add node 14 testing and drop node 10

---

packages/expo-codemod/bin/expo-codemod.js
packages/expo-codemod/package.json

[codemod] Removed version gate

---

packages/config-plugins/src/ios/IosConfig.types.ts
packages/uri-scheme/src/Ios.ts

Expand Info.plist type

---

packages/expo-cli/src/commands/build/startBuildAsync.ts

- fix https://github.com/expo/expo-cli/issues/3429
- copied from ConfigValidation.ts

Fix bundle identifier validation

---

packages/config-plugins/src/ios/BuildScheme.ts

reading target does not handle a few cases
- handle the case when reading scheme returns undefined
- add better error message when scheme file does not exist
- ignore capitalization when looking for a scheme file.
run `eas build -p ios` with (correct scheme name, scheme name with different capitalization, missing scheme file)

[config-plugins] ignore case sensitivity when reading scheme

---

packages/config-plugins/src/ios/BuildScheme.ts
packages/config-plugins/src/ios/__tests__/BuildScheme-test.ts

I want to use it to check default value in eas-cli and display warning if Debug build configuration is used
Value specified in ArchiveAction
Added tests

[config-plugins] detect default build configuration for scheme

---

package.json
tsconfig.base.json
yarn.lock

Update tsconfig to support node 12

---

CHANGELOG.md
CONTRIBUTING.md

Update changelog for `expo-cli@4.4.8`.
Follow steps outlined in CONTRIBUTING.md.
Will smoke test the release after landing this PR.

Update changelog and contributing guide for publishing

---

packages/config-plugins/src/plugins/withAndroidBaseMods.ts
packages/config/src/getPrebuildConfig.ts

Use a better default app id

---

packages/config-plugins/src/Plugin.types.ts
packages/config-plugins/src/plugins/unversioned/createLegacyPlugin.ts
packages/config-plugins/src/plugins/unversioned/expo-ads-admob.ts
packages/config-plugins/src/plugins/unversioned/expo-apple-authentication.ts
packages/config-plugins/src/plugins/unversioned/expo-branch.ts
packages/config-plugins/src/plugins/unversioned/expo-contacts.ts
packages/config-plugins/src/plugins/unversioned/expo-document-picker.ts
packages/config-plugins/src/plugins/unversioned/expo-facebook.ts
packages/config-plugins/src/plugins/unversioned/expo-notifications.ts
packages/config-plugins/src/plugins/unversioned/expo-splash-screen.ts
packages/config-plugins/src/plugins/unversioned/expo-updates.ts
packages/config-plugins/src/plugins/unversioned/react-native-maps.ts

unify how legacy plugins are created

Improve legacy plugin creation

---

packages/expo-cli/src/commands/run/index.ts

- along with docs https://github.com/expo/expo/pull/13034

Show run commands in help

---

packages/config-plugins/src/plugins/withIosBaseMods.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap
packages/prebuild-config/src/plugins/__tests__/withDefaultPlugins-test.ts

Object results were not being properly provided in base mods for InfoPlist and entitlements.

Fix object application in iOS base mods

---

packages/prebuild-config/src/plugins/withDefaultPlugins.ts

- Required for https://github.com/expo/expo/pull/13175

Added expo-cellular to the list of default plugins

---

packages/expo-cli/src/commands/install.ts
packages/expo-cli/src/commands/utils/autoAddConfigPluginsAsync.ts
packages/expo-cli/src/commands/utils/modifyConfigAsync.ts
packages/prebuild-config/src/plugins/unversioned/expo-apple-authentication.ts
packages/prebuild-config/src/plugins/unversioned/expo-contacts.ts
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

Add auto install to any plugin that isn't automatically applied internally.

Allow auto plugin adding on install for any version

---

packages/expo-cli/package.json
packages/expo-cli/src/commands/utils/validateDependenciesVersions.ts

we use the built-in assert package in this repo

Remove nullthrows

---

packages/xdl/src/Android.ts

The CLI currently looks for the Android applicationId in the Android native project which crashes the `start --dev-client` command in a managed app.
When encountering a managed project (i.e. no `android/` folder, in this case), look for `expo.android.package` in `app.json`/`app.config.*`.
```
expo init --yes
yarn add expo-dev-client@next
expo run:android  # build & install the app
rm -rf ios android  # go back to managed
expod start --dev-client --android --scheme com.fson.helloandroid  # works!
```

Add support for Android dev client on managed projects

---

packages/prebuild-config/src/plugins/icons/__tests__/withAndroidIcons-test.ts
packages/prebuild-config/src/plugins/icons/withAndroidIcons.ts

- Resolve ENG-1084
- Resolve https://github.com/expo/expo-cli/issues/3035

Add support for legacy android icons

---

packages/config-plugins/package.json
packages/config-plugins/src/android/Package.ts
packages/config-plugins/src/android/__tests__/Package-test.ts
packages/config-plugins/src/plugins/__tests__/fixtures/react-native-project.ts
yarn.lock

- resolve ENG-1273
- Refactor contents of android debug files when the package name changes.
- Added tests

[config plugins] Refactor debug contents on android

---

packages/expo-cli/src/commands/build/ios/IOSBuilder.ts

This is jarring to say the least
Select-backspace baby
N/A

Remove expo upload:ios cmd copy

---

packages/expo-cli/src/commands/build/index.ts
packages/expo-cli/src/commands/bundle-assets.ts
packages/expo-cli/src/commands/client/index.ts
packages/expo-cli/src/commands/config/config.ts
packages/expo-cli/src/commands/customize.ts
packages/expo-cli/src/commands/diagnostics.ts
packages/expo-cli/src/commands/doctor/index.ts
packages/expo-cli/src/commands/eject.ts
packages/expo-cli/src/commands/fetch/index.ts
packages/expo-cli/src/commands/index.ts
packages/expo-cli/src/commands/install.ts
packages/expo-cli/src/commands/login.ts
packages/expo-cli/src/commands/logout.ts
packages/expo-cli/src/commands/prebuild.ts
packages/expo-cli/src/commands/prepare-detached-build.ts
packages/expo-cli/src/commands/publish-modify.ts
packages/expo-cli/src/commands/publish.ts
packages/expo-cli/src/commands/push-creds.ts
packages/expo-cli/src/commands/register.ts
packages/expo-cli/src/commands/run/index.ts
packages/expo-cli/src/commands/send.ts
packages/expo-cli/src/commands/upload.ts
packages/expo-cli/src/commands/url.ts
packages/expo-cli/src/commands/utils/applyAsyncAction.ts
packages/expo-cli/src/commands/webhooks.ts
packages/expo-cli/src/commands/whoami.ts
packages/expo-cli/src/urlOpts.ts

Import Command as type

---

packages/config-plugins/src/android/StatusBar.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap

Parity with turtle v1.
- After https://github.com/expo/expo-cli/pull/3576 lands, ensure the functionality is expected
- Unit tests

Make the status bar translucent by default

---

packages/config-plugins/src/ios/Permissions.ts
packages/config-plugins/src/ios/__tests__/Permissions-test.ts

Reduce permission interface code in expo/expo

Added createPermissionsPlugin

---

packages/dev-server/src/middleware/__tests__/createJsInspectorMiddleware-test.ts
packages/dev-server/src/middleware/createJsInspectorMiddleware.ts

For dev-client running on android emulator, user may try to load bundles from http://10.0.2.2:8081/.
This is the [host loopback address](https://developer.android.com/studio/run/emulator-networking)
To query available inspector, we tried to send `/json/list` request to metro server but using HOST address in request headers.
In this case, HOST is 10.0.2.2:8081. For metro server, sending requests to 10.0.2.2:8081 is usually unreachable.
Should use metro's local server address instead of request header HOST address.
1. Use dev-client to load http://10.0.2.2:8081 bundle on android emulator.
2. Open dev-menu and see if there are any timeout errros.

[dev-server] Fix incorrect inspector request from android emulator loopback

---

packages/config-plugins/src/android/EasBuildGradleScript.ts

we set EAS_BUILD=1 in few places instead of true
check if env is set and to a non-empty string
tested code snippet in groovy console

[config-plugins] check if EAS_BUILD env is set

---

packages/expo-cli/src/commands/start.ts
packages/expo-cli/src/commands/start/startAsync.ts

https://github.com/expo/expo-cli/pull/3672

[expo-cli] Lazy load the start command

---

packages/prebuild-config/babel.config.js
packages/prebuild-config/package.json

reduce load time from 252.504ms to 5ms

lazy load prebuild-config modules

---

packages/config-plugins/src/ios/RootViewBackgroundColor.ts
packages/config-plugins/src/ios/__tests__/RootViewBackgroundColor-test.ts
packages/config-plugins/src/ios/index.ts
packages/config-plugins/src/ios/utils/normalizeColor.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

https://linear.app/expo/issue/ENG-1553/support-backgroundcolor-app-config-property-in-prebuild
https://github.com/expo/expo/pull/13607/files

[config-plugins] Added support for iOS rootViewBackgroundColor

---

packages/expo-cli/e2e/__tests__/init-test.ts
packages/expo-cli/src/commands/initAsync.ts

- resolve https://github.com/expo/expo-cli/issues/3663

Remove custom branch setting

---

packages/expo-cli/package.json
yarn.lock

Match what we use in webpack-config and expo.

Bump babel/runtime

---

packages/expo-cli/src/exp.ts
packages/xdl/src/project/createBundlesAsync.ts
ts-declarations/metro/index.d.ts

Import small standalone changes from #3685

[expo cli] various fixes from #3685

---

packages/xdl/src/Simulator.ts

- Split out of #3745 
- Use logger module instead of console logs
- Prevent checking for the latest iOS client more than once

[xdl][simulator] prevent checking for updates more than once per run

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/xdl/src/Webpack.ts
packages/xdl/src/start/startAsync.ts

Fix webpack messages

---

packages/xdl/src/start/ManifestHandler.ts

[xdl] Strip query params before checking path

---

packages/expo-cli/src/commands/publish/publishRollbackAsync.ts

Resolve https://github.com/expo/expo-cli/issues/3783

Fix prop validation in expo publish:rollback

---

packages/dev-server/package.json

chore: missing deps 

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/commands/start/parseStartOptions.ts

Enable sockets in native webpack

---

packages/config-plugins/src/plugins/withIosBaseMods.ts

When we fixed the warnings (#3795), it showed an extraneous warning during managed project introspection:
```
yolo50 𝝠 expo config --type introspect
» ios: mods.ios.infoPlist: Failed to find Info.plist linked to Xcode project.
```
- Check if the Xcode project exists first before checking if an Info.plist is linked to it, warn if it's missing.
Following should show no warning:
```
yolo50 𝝠 expo config --type introspect
```

[config plugins] dodge extraneous Info.plist warning in managed projects

---

packages/expo-cli/package.json
packages/expo-cli/scripts/introspect.ts

remove ascii colors, add generated comments, sanitize descriptions, add version notice -- https://github.com/expo/expo/pull/14414

Update introspection for docs

---

packages/expo-cli/src/commands/start/TerminalUI.ts
packages/expo-cli/src/commands/utils/openInEditorAsync.ts

Revert open in editor to a more stable revision

---

packages/expo-cli/package.json
yarn.lock

Fixes https://github.com/expo/expo-cli/issues/3949

Bump to apple-utils 26

---

packages/expo-cli/e2e/__tests__/eject-test.ts
packages/expo-cli/src/commands/eject/updatePackageJson.ts

- https://blog.expo.io/introducing-expo-run-commands-835ae8da4813
- https://github.com/expo/create-react-native-app/pull/885
- https://github.com/expo/expo/pull/13174

Use expo run commands in native projects

---

packages/expo-cli/src/commands/diagnosticsAsync.ts

[expo-cli] Add more packages to diagnostics

---

packages/config-plugins/src/ios/Paths.ts
packages/config-plugins/src/ios/__tests__/Paths-test.ts

- Fix https://github.com/expo/expo-cli/issues/4000

Support schemes with a dot in the name

---

packages/metro-config/package.json

- fix https://github.com/expo/expo-cli/issues/3997

Fix metro-config missing dependencies

---

packages/config-plugins/src/android/Name.ts
packages/config-plugins/src/android/__tests__/Name-test.ts
packages/config-plugins/src/utils/XML.ts
packages/config-plugins/src/utils/__tests__/XML-test.ts

fix https://github.com/expo/expo-cli/issues/3998

[config plugins] fix android strings xml

---

packages/expo-cli/src/commands/run/ios/XcodeBuild.ts

fixes issues where certain build logs don't format correctly.

[run:ios] chunk build logs

---

packages/webpack-config/src/plugins/NativeAssetsPlugin/loader.ts

Fonts weren't working as expected, images weren't resolving correctly.

[webpack] Fix native asset loading

---

packages/config-plugins/src/index.ts
packages/config-plugins/src/ios/JsEngine.ts
packages/config-plugins/src/plugins/ios-plugins.ts
packages/config-plugins/src/plugins/withIosBaseMods.ts

[config-plugins] Export withPodfileProperties

---

packages/config-plugins/src/android/Version.ts
packages/config-plugins/src/android/__tests__/Version-test.ts

[config-plugins] Added buildscript.ext version plugin

---

packages/xdl/src/User.ts
packages/xdl/src/project/ProjectUtils.ts
packages/xdl/src/project/publishAsync.ts
packages/xdl/src/start/ExpoUpdatesManifestHandler.ts
packages/xdl/src/start/ManifestHandler.ts
packages/xdl/src/start/startAsync.ts

We'd like to remove any personal data from incoming events.
Removed properties such as username and project root from events.
Edit: will make a follow-up PR to handle Project Warning at some point.
fired some events, made sure they did not contain the data.

[xdl] anonymize events

---

packages/config-plugins/src/ios/Name.ts
packages/config-plugins/src/ios/__tests__/Name-test.ts
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

See if this resolves CI issue that can't be reproduced locally.

Revert "Add config plugin to set iOS PRODUCT_NAME (#4041)"

---

packages/prebuild-config/src/plugins/icons/withAndroidIcons.ts

- fix https://github.com/expo/expo/issues/15524

[prebuild-config] Fix Android icons

---

packages/config-plugins/src/android/Manifest.ts
packages/config-plugins/src/android/Permissions.ts
packages/config-plugins/src/android/__tests__/Permissions-test.ts

[config-plugins] Add plugin to restrict android permissions

---

packages/config-plugins/src/ios/Maps.ts
packages/config-plugins/src/ios/__tests__/Maps-test.ts
packages/config-plugins/src/ios/__tests__/__snapshots__/Maps-test.ts.snap
packages/config-plugins/src/ios/__tests__/fixtures/AppDelegate.ts

- fix https://github.com/expo/expo-cli/issues/4060
- Added tests

[config-plugins] Fix react-native-maps regex to account for React AppDelegate

---

packages/config-plugins/src/ios/Name.ts
packages/config-plugins/src/ios/__tests__/Name-test.ts
packages/prebuild-config/src/plugins/withDefaultPlugins.ts

- Retry https://github.com/expo/expo-cli/pull/4041

Set iOS PRODUCT_NAME on prebuild

---

packages/expo-cli/src/commands/eject/configureProjectAsync.ts

prep for moving into versioned expo package.

[expo-cli] Remove instances of xdl

---

packages/expo-cli/src/commands/eject/Github.ts
packages/expo-cli/src/commands/utils/validateApplicationId.ts

Prep to move into `expo` package.

[expo-cli] Remove instance of got

---

packages/xdl/src/start/LoadingPageHandler.ts
packages/xdl/static/loading-page/index.html

Pretty straightforward PR - just adding more information about application to interstitial page.
Added information like:
- app name
- runtime version
- path
Go to `localhost:19000/_expo/loading?platform=<android | ios>` and check if everything is render correctly.

[Interstitial page] Add missing information about project

---

packages/xdl/src/project/publishAsync.ts

The website now supports customizing QR codes via query params (if curious, see attached linear issue for more details).
add appropriate query params
tested in demo project

[expo-cli] add new query params to project URL

---

packages/xdl/src/Webpack.ts

- fix https://github.com/expo/expo-cli/issues/4185
- `devServer.before` isn't defined in production Webpack configs, account for this.
- `expo web --no-dev` should work as expected.

Fix running `expo web --no-dev`

---

packages/expo-cli/e2e/__tests__/__snapshots__/export-test.ts.snap
packages/expo-cli/e2e/__tests__/export-test.ts

- Test appears to be fragile in CI. As a temporary workaround we'll round the file test results to lower the required fidelity. Also dropped localization to potentially help.

[expo-cli] round export file test results

---

packages/config-types/src/ExpoConfig.ts

- https://github.com/expo/universe/pull/9215
- https://github.com/expo/expo-cli/pull/4238

Deprecated reservedClientId

---

packages/config-plugins/src/plugins/withAndroidBaseMods.ts
packages/prebuild-config/src/plugins/__tests__/__snapshots__/withDefaultPlugins-test.ts.snap

Updated for SDK 44: [ref](https://github.com/expo/expo/blob/sdk-44/templates/expo-template-bare-minimum/android/app/src/main/AndroidManifest.xml)

[config-plugins] update AndroidManifest.xml template for introspect

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/enhancement.yml

Moving towards a more standardized issue triaging across repos.
Updated issue template
N/A

chore: update bugreport template label

---

packages/babel-preset-cli/README.md
packages/config-plugins/README.md
packages/config-types/README.md
packages/config/README.md
packages/dev-server/README.md
packages/dev-tools/README.md
packages/expo-optimize/README.md
packages/image-utils/README.md
packages/install-expo-modules/README.md
packages/json-file/README.md
packages/metro-config/README.md
packages/next-adapter/README.md
packages/osascript/README.md
packages/pkcs12/README.md
packages/plist/README.md
packages/prebuild-config/README.md
packages/schemer/README.md
packages/xdl/README.md

Lately I have spotted that not all Readme files includes the correct package names in header, also in some cases, the Readme files looks a bit empty.
This PR updates most of the packages Readme files using the common header template which can be found in few of the packages already.
I have also added missing languages to the few code block and tweaked the main description in few cases to better fit with the header.
I have used the live preview, when editing markdown files and will test this on GitHub, after creating this PR.

[chore] update packages readme files

---

.github/workflows/issue-stale.yml

We have a lot of issues which do not apply anymore and should be closed.

ci: add stale bot from expo/expo

---

packages/expo-cli/package.json
yarn.lock

- resolve https://github.com/expo/expo-cli/issues/4148

Bump @expo/apple-utils@0.0.0-alpha.31

---

.github/workflows/issue-stale.yml

When we recently introduced this on eas-cli, we exempted untriaged and assigned issues. I think it makes sense to use the same configuration here.

ci: sync stale config with eas-cli

---

packages/dev-server/src/HermesBundler.ts
packages/dev-server/src/__tests__/HermesBundler-test.ts

fix https://github.com/expo/expo-cli/issues/4283#issuecomment-1128530470 where `expo publish` on ios sdk 45 with hermes is broken because i changed template from react-native 0.68 upgrade. 
- add `/^\s*:hermes_enabled\s*=>\s*flags\[:hermes_enabled\]\s*\|\|\s*podfile_properties\['expo.jsEngine'\]\s*==\s*'hermes',?/m` regular express for sdk 45 support.
```
PASS   @expo/dev-server  src/__tests__/HermesBundler-test.ts
maybeThrowFromInconsistentEngineAsync - ios
✓ should resolve from default sdk 45 template
✓ should resolve from default sdk 44 template
```
there's too many duplicated code for mock setup. i refactored them to a `addMockedFiles()`.

[dev-server] add sdk 45 support for the sanity check of hermes bundler

---

packages/expo-cli/e2e/__tests__/__snapshots__/export-test.ts.snap

chore: fix tests

---

packages/webpack-config/src/plugins/ExpectedErrors/ExpectedErrorsPlugin.ts
packages/webpack-config/src/plugins/ExpectedErrors/createOriginalStackFrame.ts
packages/webpack-config/src/plugins/ExpectedErrors/getModuleBuildError.ts
packages/webpack-config/src/plugins/ExpectedErrors/parseBabelError.ts
packages/webpack-config/src/plugins/NativeAssetsPlugin/NativeAssetResolver.ts
packages/webpack-config/src/plugins/NativeAssetsPlugin/loader.ts

fix license

---

packages/expo-env-info/src/__tests__/diagnostics-test.ts
packages/expo-env-info/src/diagnosticsAsync.ts

[expo-env-info] don't show workflow type outside of project folder

---

packages/next-adapter/package.json
packages/next-adapter/src/babel.ts
yarn.lock

- Replaces https://github.com/expo/expo-cli/pull/4516 https://github.com/expo/expo-cli/pull/4377

chore(next-adapter): update babel preset

---

packages/next-adapter/package.json

fix(next-adapter): drop next-expo script as it causes npm to fail

---

packages/expo-doctor/src/doctor.ts

With `CI=1`, `ora` output would look like
```
- Validating global prerequisites versions
✔ Validating global prerequisites versions
- Checking for incompatible packages
✔ Checking for incompatible packages
```
We're going to rework this output entirely to be less verbose on success, so didn't want to put too much into it, but at least wanted to quickly make it less redundant.
- Update `ora` text on success/ failure
- Also send issue output to `Log.warn` so they'll show as `[stderr]` on EAS Build.
CI output looks like:
```
keith@andknuckles-2 expo-doctor % CI=1 npx expo-doctor ../../../just-kana
- Validating global prerequisites versions...
✔ Validating global prerequisites versions passed
- Checking for incompatible packages...
✔ Checking for incompatible packages passed
- Checking for …
```

[doctor] More CI-friendly output

---

.eslintignore
packages/install-expo-modules/package.json
packages/install-expo-modules/src/index.ts
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/AppDelegate-rn072-updated.mm
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/AppDelegate-rn072.mm
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/MainApplication-rn072-updated.java
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/MainApplication-rn072.java
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/appBuild-rn072-updated.gradle
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/appBuild-rn072.gradle
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/babel-config-rn072-updated.js
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/babel-config-rn072.js
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/metro-config-rn071.js
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/metro-config-rn072-updated.js
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/metro-config-rn072.js
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/xcodeProject-rn072-updated.pbxproj
packages/install-expo-modules/src/plugins/cli/__tests__/fixtures/xcodeProject-rn072.pbxproj
packages/install-expo-modules/src/plugins/cli/__tests__/withCliIntegration-test.ts
packages/install-expo-modules/src/plugins/cli/withCliIntegration.ts
packages/install-expo-modules/src/utils/expoVersionMappings.ts
packages/install-expo-modules/src/utils/link.ts

add expo-cli integration to install-expo-modules
close ENG-8137
this feature is supported from react-native>=0.72.0 and show a prompt before adding the cli integration
add the `withCliIntegration` config-plugin to update the following items:
- **babel.config.js**: use `babel-preset-expo` rather than `metro-react-native-babel-preset`
- **metro.config.js**:  use the `getDefaultConfig` from `expo/metro-config` rather than `@react-native/metro-config`
- use the `.expo/.virtual-metro-entry` entry in **MainApplication.java** and **AppDelegate.mm**
- use the custom `entryFile` and `export:embed` bundle command in **android/app/build.gradle**
- use the custom `entryFile` and `export:embed` bundle command in **ios/{projectName}.xcodeproj/project.pbxproj**
- use the expo-cli's …

[install-expo-modules] add cli integration support

---

packages/install-expo-modules/src/plugins/ios/withIosDeploymentTarget.ts

react-native 0.72.5 has a breaking change for default ios minimal version: https://github.com/facebook/react-native/commit/a5e110adcf21
support parsing the default ios minimal version from the **scripts/cocoapods/helpers.rb**
tested install-expo-modules on a react-native 0.72.5 project

[install-expo-modules] fix react-native 0.72.5 support

---

packages/expo-cli/src/commands/initAsync.ts

Revised PR from #4678.
- Synced descriptions from https://github.com/expo/expo/blob/main/packages/create-expo/src/legacyTemplates.ts#L6-L29
- String change only

refactor(expo-cli): update template descriptions
